<?php
declare(strict_types=1);
use Chengyu\Core\{EncryptedArchive,SnapshotReader,SnapshotSchema,Database};
use Chengyu\Services\{Backups,Recovery,Media};
function databaseBackup18(): array {
    global $config,$tmp,$owner;$base=$config['database'];
    if($base['driver']==='mysql'){$name='chengyu_test_'.bin2hex(random_bytes(8));$owner->exec('CREATE DATABASE `'.$name.'` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');register_shutdown_function(static function()use($owner,$name):void{$owner->exec('DROP DATABASE IF EXISTS `'.$name.'`');});$base['name']=$name;}
    else{$base['path']=$tmp.'/snapshot-'.bin2hex(random_bytes(8)).'.sqlite';}return $base;
}
function rawBackup18(array $records): string {global $tmp;$p=$tmp.'/record-'.key32().'.cybackup';$h=fopen($p,'xb');try{$w=new EncryptedArchive($h,'Backup test phrase 2026!',1048576);foreach($records as $row){$w->add($row);}}finally{fclose($h);}return $p;}
$backupConfig18=$config;$backupConfig18['database']=databaseBackup18();$backupConfig18['storage']=$tmp.'/snapshot-source';mkdir($backupConfig18['storage'],0700);
Chengyu\Schema::create(new Database($backupConfig18['database']));$backupApp18=new Chengyu\App($backupConfig18);
$backupAdmin18=$backupApp18->db->insert('cy_users',['username'=>'restore_admin','email'=>'recovery@example.test','password_hash'=>password_hash('RecoveryPassword!2026',PASSWORD_DEFAULT),'display_name'=>'Recovery administrator','role'=>'admin','status'=>'active','bio'=>'','balance'=>9000000000001,'created_at'=>time()]);
$backupMember18=$backupApp18->db->insert('cy_users',['username'=>'restore_member','email'=>'member@example.test','password_hash'=>'not-a-real-hash','display_name'=>'Member','role'=>'user','status'=>'active','bio'=>'','created_at'=>time()]);
$backupApp18->settings->savePartial('email',['smtp_password'=>'SMTP-RESTORE-SECRET','email_registration_required'=>0]);
$backupPlain18=$tmp.'/source.txt';file_put_contents($backupPlain18,"Private media recovery fixture.\n");
$backupMedia18=$backupApp18->media->storeLocal($backupApp18->db->one('SELECT * FROM cy_users WHERE id=?',[$backupAdmin18]),$backupPlain18,'notes.txt',true,1048576);
$backupPass18='Backup test phrase 2026!';$backupId18=0;$backupFile18='';$backupReport18=[];
test('018 backup table registry matches all installed application tables',static function()use($backupApp18){SnapshotSchema::check($backupApp18->db);same(count(SnapshotSchema::TABLES),count(SnapshotSchema::present($backupApp18->db)));});
test('018 backup create rejects non-administrators and short passwords',static function()use($backupApp18,$backupMember18,$backupAdmin18){reject(static function()use($backupApp18,$backupMember18){$backupApp18->backups->create($backupMember18,'Backup test phrase 2026!',true);},403);reject(static function()use($backupApp18,$backupAdmin18){$backupApp18->backups->create($backupAdmin18,'short',true);});});
test('018 consistent encrypted database and media backup completes',static function()use($backupApp18,$backupAdmin18,$backupPass18,&$backupId18,&$backupFile18,&$backupReport18){$backupId18=$backupApp18->backups->create($backupAdmin18,$backupPass18,true);$file=$backupApp18->backups->file($backupAdmin18,$backupId18);$backupFile18=$file['path'];$text=file_get_contents($backupFile18);truth(strpos($text,'SMTP-RESTORE-SECRET')===false);truth(strpos($text,'recovery@example.test')===false);truth(strpos($text,$backupApp18->config['secret'])===false);same(Media::GUARD,substr($text,0,strlen(Media::GUARD)));$backupReport18=SnapshotReader::walk($backupFile18,$backupPass18);same(1,$backupReport18['files']);same(2,$backupReport18['rows']['cy_users']);same(false,array_key_exists('cy_backup_archives',$backupReport18['rows']));});
test('018 archive can be inspected after stripping the protected storage envelope',static function()use(&$backupFile18,$tmp,$backupPass18){$p=$tmp.'/download.cybackup';file_put_contents($p,substr(file_get_contents($backupFile18),strlen(Media::GUARD)));$report=SnapshotReader::describe(SnapshotReader::walk($p,$backupPass18));same(1,$report['files']);truth(!isset($report['secret']));truth(strpos(json_encode($report),'recovery@example.test')===false);});
test('018 encrypted archive rejects a wrong password',static function()use(&$backupFile18){reject(static function()use($backupFile18){SnapshotReader::walk($backupFile18,'A different backup phrase!');});});
test('018 encrypted archive rejects a truncated completion marker',static function()use(&$backupFile18,$tmp,$backupPass18){$p=$tmp.'/truncated.cybackup';file_put_contents($p,substr(file_get_contents($backupFile18),0,-100));reject(static function()use($p,$backupPass18){SnapshotReader::walk($p,$backupPass18);});});
test('018 encrypted archive rejects a modified authentication tag',static function()use(&$backupFile18,$tmp,$backupPass18){$raw=file_get_contents($backupFile18);$offset=strpos($raw,"\n",strlen(Media::GUARD)+strlen(EncryptedArchive::MAGIC))+1+4+12;$raw[$offset]=chr(ord($raw[$offset])^1);$p=$tmp.'/tampered.cybackup';file_put_contents($p,$raw);reject(static function()use($p,$backupPass18){SnapshotReader::walk($p,$backupPass18);});});
test('018 encrypted archive rejects data after a valid completion marker',static function()use(&$backupFile18,$tmp,$backupPass18){$p=$tmp.'/trailing.cybackup';file_put_contents($p,file_get_contents($backupFile18).'TRAILER');reject(static function()use($p,$backupPass18){SnapshotReader::walk($p,$backupPass18);});});
test('018 backup file retrieval remains administrator-only',static function()use($backupApp18,$backupMember18,&$backupId18){reject(static function()use($backupApp18,$backupMember18,$backupId18){$backupApp18->backups->file($backupMember18,$backupId18);},403);});
test('018 archive parser rejects a signed but unsupported table identifier',static function()use(&$backupReport18){$p=rawBackup18([$backupReport18['meta'],['type'=>'row','table'=>'cy_users; DROP TABLE cy_orders','data'=>['id'=>1]]]);reject(static function()use($p){SnapshotReader::walk($p,'Backup test phrase 2026!');});});
test('018 archive parser rejects a signed path traversal file',static function()use(&$backupReport18){$p=rawBackup18([$backupReport18['meta'],['type'=>'file','name'=>'../config.php','bytes'=>128]]);reject(static function()use($p){SnapshotReader::walk($p,'Backup test phrase 2026!');});});
test('018 archive writer enforces its byte budget',static function()use($tmp){$h=fopen($tmp.'/capped.cybackup','xb');try{$w=new EncryptedArchive($h,'Backup test phrase 2026!',1024);reject(static function()use($w){$w->add(['type'=>'row','data'=>str_repeat('x',2000)]);},413);}finally{fclose($h);}});
test('018 recovery refuses a nonempty database before changing data',static function()use(&$backupFile18,$backupPass18,$backupConfig18,$tmp,$backupApp18){reject(static function()use($backupFile18,$backupPass18,$backupConfig18,$tmp){Recovery::restore($backupFile18,$backupPass18,$backupConfig18['database'],$tmp.'/rejected-storage',$tmp.'/rejected-config.php');},409);same(2,(int)$backupApp18->db->value('SELECT COUNT(*) FROM cy_users'));truth(!file_exists($tmp.'/rejected-storage'));});
test('018 recovery verifies before creating any tables or storage',static function()use($tmp,$backupPass18){$target=databaseBackup18();reject(static function()use($tmp,$backupPass18,$target){Recovery::restore($tmp.'/truncated.cybackup',$backupPass18,$target,$tmp.'/broken-storage',$tmp.'/broken-config.php');});same([],SnapshotSchema::present(new Database($target)));truth(!file_exists($tmp.'/broken-storage'));});
test('018 complete recovery preserves money, site-key encryption and media; disables remote jobs',static function()use(&$backupFile18,$backupPass18,$tmp,$backupApp18,$backupAdmin18,$backupMedia18){$target=databaseBackup18();$out=Recovery::restore($backupFile18,$backupPass18,$target,$tmp.'/restored-storage',$tmp.'/restored-config.php');same(true,$out['maintenance']);$config=require $tmp.'/restored-config.php';same($backupApp18->config['secret'],$config['secret']);$restored=new Chengyu\App($config);same('9000000000001',(string)$restored->db->value('SELECT balance FROM cy_users WHERE id=?',[$backupAdmin18]));same('SMTP-RESTORE-SECRET',$restored->settings->get('smtp_password'));same(true,$restored->settings->get('maintenance'));same('',$restored->settings->get('jobs_secret'));same(false,$restored->settings->get('smtp_enabled'));same('portable',$restored->settings->get('search_engine'));reject(static function()use($restored){$restored->jobs->run(1);},503);same(2,(int)$restored->db->value('SELECT session_version FROM cy_users WHERE id=?',[$backupAdmin18]));$key=$restored->db->value('SELECT file_key FROM cy_media WHERE id=?',[$backupMedia18]);same(hash_file('sha256',$backupApp18->config['storage'].'/blobs/'.$key),hash_file('sha256',$tmp.'/restored-storage/blobs/'.$key));same(0,(int)$restored->db->value('SELECT COUNT(*) FROM cy_backup_archives'));});
test('018 a missing local file aborts complete media backup without a success record',static function()use($backupApp18,$backupAdmin18,$backupPass18,$backupMedia18){$key=$backupApp18->db->value('SELECT file_key FROM cy_media WHERE id=?',[$backupMedia18]);$path=$backupApp18->config['storage'].'/blobs/'.$key;rename($path,$path.'.hold');$before=count($backupApp18->backups->listing($backupAdmin18));try{reject(static function()use($backupApp18,$backupAdmin18,$backupPass18){$backupApp18->backups->create($backupAdmin18,$backupPass18,true);});same($before,count($backupApp18->backups->listing($backupAdmin18)));}finally{rename($path.'.hold',$path);}});
test('018 database-only archive clearly reports omitted local bytes',static function()use($backupApp18,$backupAdmin18,$backupPass18){$id=$backupApp18->backups->create($backupAdmin18,$backupPass18,false);$p=$backupApp18->backups->file($backupAdmin18,$id)['path'];$report=SnapshotReader::walk($p,$backupPass18);same(false,$report['meta']['local_media']);same(0,$report['files']);same(1,$report['local_media_records']);});
test('018 backup retention keeps the latest successful copy only',static function()use($backupApp18,$backupAdmin18,$backupPass18){$backupApp18->settings->savePartial('security',['backup_retention'=>1]);$id=$backupApp18->backups->create($backupAdmin18,$backupPass18,false);$rows=$backupApp18->backups->listing($backupAdmin18);same(1,count($rows));same($id,(int)$rows[0]['id']);truth(is_file($backupApp18->backups->file($backupAdmin18,$id)['path']));});
test('018 deleting a recovery copy removes file and catalog entry',static function()use($backupApp18,$backupAdmin18){$rows=$backupApp18->backups->listing($backupAdmin18);$id=(int)$rows[0]['id'];$path=$backupApp18->backups->file($backupAdmin18,$id)['path'];$backupApp18->backups->remove($backupAdmin18,$id);same([], $backupApp18->backups->listing($backupAdmin18));truth(!file_exists($path));});
