"""Reusable picker exercised through real UI and real server media records."""
page.set_viewport_size({'width':1440,'height':1000})
go('/admin/index.php?tab=visuals&slot=icon:compass')
picker23=page.locator('#media-picker')
page.set_viewport_size({'width':1254,'height':564})
page.locator('[data-media-open]').click();expect(picker23).to_be_visible()
check('023 short desktop keeps visual editor actions reachable',page.locator('.visual-editor').evaluate('(n)=>getComputedStyle(n).position')=='static')
picker23.locator('[data-close-dialog]').click();expect(picker23).not_to_be_visible()
page.set_viewport_size({'width':1440,'height':1000})
def field23(name):
    return page.locator('.upload-field').filter(has=page.locator('[name="'+name+'"]'))
def search23(name):
    picker23.locator('#media-search-query').fill(name)
    picker23.locator('[data-media-search] button[type=submit]').click()
    expect(picker23.locator('[data-media-items]')).to_have_attribute('aria-busy','false')
def choose23(name,media_id):
    field23(name).locator('[data-media-open]').click()
    expect(picker23).to_be_visible()
    search23('cover-')
    picker23.locator('[data-media-id="'+media_id+'"]').click()
    expect(picker23.locator('[data-media-preview]')).to_be_visible()
    picker23.locator('[data-media-confirm]').click()
    expect(picker23).not_to_be_visible()
    expect(page.locator('[name="'+name+'"]')).to_have_value(media_id)
choose23('media_id',image_ids22[0])
check('023 selection updates visual preview and clears built-in source',page.locator('[name=asset_key]').input_value()=='' and ('id='+image_ids22[0]) in page.locator('[data-visual-preview] img').get_attribute('src'))
submit_native(page.locator('.visual-form button[type=submit]').first)
check('023 chosen image survives actual save and reload',page.locator('[name=media_id]').input_value()==image_ids22[0])
field23('media_id').locator('[data-media-clear]').click()
check('023 clear updates shared field and preview',page.locator('[name=media_id]').input_value()=='0' and page.locator('[data-visual-preview] img').is_hidden())
submit_native(page.locator('[name=operation][value=reset]'))
go('/admin/index.php?tab=edit_content&id='+article_id22)
page.locator('.editor-images > summary').click()
choose23('gallery_image_1',image_ids22[0])
choose23('gallery_image_2',image_ids22[1])
check('023 choosing another field keeps the first selection',page.locator('[name=gallery_image_1]').input_value()==image_ids22[0])
submit_native(page.locator('.editor-settings .form-actions button[type=submit]'))
check('023 gallery selections persist in the real editor',page.locator('[name=gallery_image_1]').input_value()==image_ids22[0] and page.locator('[name=gallery_image_2]').input_value()==image_ids22[1])
go('/admin/index.php?tab=navigation&edit='+menu_ids22[0])
choose23('image_id',image_ids22[0])
submit_native(page.locator('.navigation-editor button[type=submit]'))
go('/admin/index.php?tab=navigation&edit='+menu_ids22[0])
check('023 menu image selection persists',page.locator('[name=image_id]').input_value()==image_ids22[0])
field23('image_id').locator('[data-media-open]').click()
search23('nothing-matches-023')
check('023 empty results keep confirmation disabled',picker23.locator('[data-media-id]').count()==0 and picker23.locator('[data-media-confirm]').is_disabled() and bool(picker23.locator('[data-media-status]').inner_text()))
search23('cover-')
picker23.locator('[data-media-id="'+image_ids22[1]+'"]').click()
for width23 in [320,390,768,1440]:
    page.set_viewport_size({'width':width23,'height':900})
    check('023 picker fits viewport '+str(width23),picker23.evaluate('(n)=>{const r=n.getBoundingClientRect();return r.left>=0 && r.right<=innerWidth && n.scrollWidth<=n.clientWidth+1}'))
page.set_viewport_size({'width':1440,'height':1000});shot('023-media-picker-desktop.png')
page.set_viewport_size({'width':390,'height':844});shot('023-media-picker-mobile.png')
page.keyboard.press('Escape');expect(picker23).not_to_be_visible()
check('023 cancel preserves the original field and restores focus',page.locator('[name=image_id]').input_value()==image_ids22[0] and field23('image_id').locator('[data-media-open]').evaluate('(n)=>n===document.activeElement'))
page.emulate_media(reduced_motion='reduce')
field23('image_id').locator('[data-media-open]').click();expect(picker23).to_be_visible();search23('cover-')
picker23.locator('[data-close-dialog]').click();expect(picker23).not_to_be_visible()
check('023 picker works with reduced motion',page.locator('[name=image_id]').input_value()==image_ids22[0]);page.emulate_media(reduced_motion='no-preference')
nojs23=browser.new_context(java_script_enabled=False,storage_state=context.storage_state(),viewport={'width':390,'height':844})
static23=nojs23.new_page();static23.goto(BASE+'/admin/index.php?tab=navigation&edit='+menu_ids22[0],wait_until='load')
check('023 without JavaScript native image ID and file upload remain available',static23.locator('[name=image_id]').is_visible() and static23.locator('[data-media-open]:visible').count()==0 and static23.locator('input[type=file]').count()>0)
nojs23.close()
page.set_viewport_size({'width':1440,'height':1000})
go('/admin/index.php?tab=visuals&slot=icon:compass')
for image23 in sorted((ROOT/'site/assets/art').glob('icon-*.webp'))+sorted((ROOT/'site/assets/art').glob('cover-*.webp'))[:5]:
    page.locator('[name=media_id]').fill('0')
    field23('media_id').locator('input[type=file]').set_input_files(str(image23))
    expect(page.locator('[name=media_id]')).not_to_have_value('0')
field23('media_id').locator('[data-media-open]').click();search23('')
first_ids23=picker23.locator('[data-media-id]').evaluate_all('(nodes)=>nodes.map(n=>n.dataset.mediaId)')
check('023 browser first page is bounded at twelve images',len(first_ids23)==12)
picker23.locator('[data-media-next]').click();expect(picker23.locator('[data-media-items]')).to_have_attribute('aria-busy','false')
second_ids23=picker23.locator('[data-media-id]').evaluate_all('(nodes)=>nodes.map(n=>n.dataset.mediaId)')
check('023 browser next page has different actual media records',bool(second_ids23) and not set(first_ids23)&set(second_ids23))
picker23.locator('[data-media-previous]').click();expect(picker23.locator('[data-media-items]')).to_have_attribute('aria-busy','false')
check('023 browser previous page restores its media records',first_ids23==picker23.locator('[data-media-id]').evaluate_all('(nodes)=>nodes.map(n=>n.dataset.mediaId)'))
shot('023-media-library-desktop.png')
page.set_viewport_size({'width':390,'height':844});shot('023-media-library-mobile.png')
picker23.locator('[data-close-dialog]').click();expect(picker23).not_to_be_visible()
def fail_catalog23(route):
    if 'media_catalog' in (route.request.post_data or ''):route.abort('failed')
    else:route.continue_()
page.route('**/action.php',fail_catalog23)
field23('media_id').locator('[data-media-open]').click();expect(picker23.locator('[data-media-items]')).to_have_attribute('aria-busy','false')
check('023 network failure keeps dialog usable without selection',bool(picker23.locator('[data-media-status]').inner_text()) and picker23.locator('[data-media-confirm]').is_disabled())
page.unroute('**/action.php',fail_catalog23);search23('cover-')
check('023 a real search recovers after transport failure',picker23.locator('[data-media-id]').count()>0)
picker23.locator('[data-close-dialog]').click();expect(picker23).not_to_be_visible()
