"""Admin menu creation, image upload and public navigation with real browser input."""
from urllib.parse import parse_qs,urlparse
page.set_viewport_size({'width':1440,'height':1000})
menu_ids22=[]
for level22,label22 in enumerate(['随手看看','图文笔记','周末照片']):
    go('/admin/index.php?tab=navigation')
    form22=page.locator('.navigation-editor')
    form22.locator('[name=label]').fill(label22)
    form22.locator('[name=route]').select_option('articles')
    form22.locator('[name=sort_order]').fill('0')
    form22.locator('[name=icon]').select_option('anime-gallery' if level22==0 else 'compass')
    if level22:
        form22.locator('[name=parent_id]').select_option(menu_ids22[-1])
        form22.locator('[name=description]').fill('记录散步时遇见的小事。')
    else:form22.locator('[name=panel_style]').select_option('columns')
    submit_native(form22.locator('button[type=submit]'))
    # The controller returns the list; follow the saved row's edit link.
    record22=page.locator('.navigation-record').filter(has=page.get_by_text(label22,exact=True))
    with page.expect_navigation(wait_until='load'):record22.locator('a').click()
    menu_ids22.append(page.locator('.navigation-editor [name=id]').input_value())
    check('022 menu level saved '+str(level22+1),page.locator('.navigation-editor [name=revision]').input_value()=='1')
no_overflow('022 navigation admin');page.set_viewport_size({'width':1440,'height':1000});shot('022-navigation-admin.png')
go('/')
root22=page.locator('.desktop-nav [data-nav-id="'+menu_ids22[0]+'"]')
root22.locator(':scope > summary').focus();page.keyboard.press('Enter')
expect(root22).to_have_attribute('open','')
child22=root22.locator('[data-nav-id="'+menu_ids22[1]+'"]')
child22.locator(':scope > summary').click()
check('022 third-level link visible after real disclosure clicks',child22.locator('[data-nav-id="'+menu_ids22[2]+'"]').is_visible())
check('022 open menu remains within desktop viewport',root22.locator(':scope > .site-nav-panel').evaluate('(n)=>{const r=n.getBoundingClientRect();return r.left>=0 && r.right<=innerWidth}'))
shot('022-navigation-desktop.png')
child22.locator(':scope > summary').focus();page.keyboard.press('Escape')
check('022 Escape closes nested menu and preserves focus',child22.get_attribute('open') is None and child22.locator(':scope > summary').evaluate('(n)=>n===document.activeElement'))
page.locator('main').click(position={'x':5,'y':5})
check('022 outside click closes desktop navigation',page.locator('.desktop-nav details[open]').count()==0)
more22=page.locator('.desktop-nav > .nav-overflow')
more22.locator(':scope > summary').click()
check('022 More menu exposes remaining links',more22.locator('.site-nav-link').first.is_visible())
page.keyboard.press('Escape')
page.set_viewport_size({'width':390,'height':844})
page.locator('[data-dialog="menu-dialog"]').click();expect(page.locator('#menu-dialog')).to_be_visible()
mobile22=page.locator('#menu-dialog [data-nav-id="'+menu_ids22[0]+'"]')
mobile22.locator(':scope > summary').click();mobile22.locator('[data-nav-id="'+menu_ids22[1]+'"] > summary').click()
check('022 mobile drawer uses all three menu levels',mobile22.locator('[data-nav-id="'+menu_ids22[2]+'"]').is_visible())
shot('022-navigation-mobile.png');page.locator('#menu-dialog [data-close-dialog]').click()
page.set_viewport_size({'width':1440,'height':1000});go('/admin/index.php?tab=edit_content&kind=article')
page.locator('[name=title]').fill('周末散步，留两张照片')
page.locator('[name=body]').fill('## 走到哪里算哪里\n没有特别安排，沿着熟悉的小路慢慢走。\n')
page.locator('[name=excerpt]').fill('街角的光和傍晚的风，偶尔停下来看看。')
page.locator('[name=status]').select_option('published')
page.locator('.editor-images > summary').click()
widget22=page.locator('.upload-field').filter(has=page.locator('[name=inline_image]'))
image_ids22=[]
for asset22,caption22 in [('cover-workshop.webp','街角的小店'),('cover-space.webp','晚一点再回家')]:
    page.locator('[name=inline_image]').fill('0')
    widget22.locator('input[type=file]').set_input_files(str(ROOT/'site/assets/art'/asset22))
    expect(page.locator('[name=inline_image]')).not_to_have_value('0')
    image_ids22.append(page.locator('[name=inline_image]').input_value())
    page.locator('[name=inline_image_alt]').fill(caption22)
    page.locator('[name=body]').focus();page.keyboard.press('Control+End')
    page.locator('[data-insert-image]').click()
    check('022 upload and insert adds media syntax '+asset22,'media:'+image_ids22[-1] in page.locator('[name=body]').input_value())
page.locator('[name=image_layout]').select_option('gallery')
no_overflow('022 image editor');page.set_viewport_size({'width':1440,'height':1000});shot('022-image-editor.png')
submit_native(page.locator('.editor-settings .form-actions button[type=submit]'))
article_id22=page.locator('form.content-editor [name=id]').input_value() if page.locator('form.content-editor [name=id]').count() else parse_qs(urlparse(page.url).query)['id'][0]
go('/index.php?r=article&id='+article_id22)
check('022 saved body has two actual loaded images',page.locator('.inline-picture img').count()==2)
page.locator('.inline-picture img').first.scroll_into_view_if_needed()
expect(page.locator('.inline-picture img').first).to_be_visible()
check('022 saved image decodes in the browser',page.locator('.inline-picture img').first.evaluate('(n)=>n.complete && n.naturalWidth>0'))
page.locator('.inline-picture img').first.click()
check('022 uploaded body image opens existing lightbox',page.locator('dialog.image-lightbox').is_visible())
page.keyboard.press('Escape')
no_overflow('022 image article');page.set_viewport_size({'width':390,'height':844});shot('022-image-article-mobile.png')
go('/index.php?r=articles')
check('022 real list contains two-image gallery',page.locator('.card-gallery').first.locator('img').count()==2)
no_overflow('022 gallery list');page.set_viewport_size({'width':1440,'height':1000});shot('022-gallery-desktop.png')
page.set_viewport_size({'width':390,'height':844});shot('022-gallery-mobile.png')
page.emulate_media(reduced_motion='reduce');check('022 gallery remains visible with reduced motion',page.locator('.card-gallery').first.is_visible())
page.emulate_media(reduced_motion='no-preference')
nojs22=browser.new_context(java_script_enabled=False,viewport={'width':390,'height':844});static22=nojs22.new_page()
static22.goto(BASE,wait_until='load')
native22=static22.locator('.fallback-navigation [data-nav-id="'+menu_ids22[0]+'"]')
native22.locator(':scope > summary').click();native22.locator('[data-nav-id="'+menu_ids22[1]+'"] > summary').click()
check('022 no-JavaScript menus still expand to real links',native22.locator('[data-nav-id="'+menu_ids22[2]+'"]').is_visible())
static22.goto(BASE+'/index.php?r=article&id='+article_id22,wait_until='load')
check('022 no-JavaScript article contains real images and captions',static22.locator('.inline-picture img').count()==2 and static22.locator('.image-caption').count()==2)
nojs22.close()
