"""Runs inside browser_live.py with its real browser and authenticated editor."""
page.set_viewport_size({'width':1440,'height':1000})
go('/admin/index.php?tab=bulletins')
page.locator('[name=title]').fill('Browser bulletin21')
page.locator('[name=body]').fill('A real browser submission.\nThe second paragraph stays readable.')
page.locator('[name=source_name]').fill('Editorial desk21')
page.locator('[name=source_url]').fill('https://example.org/editorial')
page.locator('.bulletin-editor [name=status]').select_option('published')
page.locator('[name=publish_at]').fill('2025-09-12T11:30')
submit_native(page.locator('.bulletin-editor button[type=submit]'))
expect(page.locator('[name=title]')).to_have_value('Browser bulletin21')
check('021 native bulletin form persists with a revision',page.locator('[name=revision]').input_value()=='1')
bulletin_id21=page.locator('.bulletin-editor [name=id]').input_value()
no_overflow('021 bulletin admin');page.set_viewport_size({'width':1440,'height':1000});shot('021-bulletins-admin.png')
go('/index.php?r=bulletins')
check('021 posted bulletin appears on real timeline',page.locator('[data-bulletin-id="'+bulletin_id21+'"]').count()==1)
check('021 original news icon resolves',page.locator('.bulletin-heading h1 img').evaluate('(n)=>n.complete && n.naturalWidth>0'))
no_overflow('021 bulletin timeline');page.set_viewport_size({'width':1440,'height':1000});shot('021-bulletins-desktop.png')
page.set_viewport_size({'width':390,'height':844});shot('021-bulletins-mobile.png')
with page.expect_navigation(wait_until='load'):
    page.locator('[data-bulletin-id="'+bulletin_id21+'"] h3 a').click()
expect(page.locator('.bulletin-detail h1')).to_have_text('Browser bulletin21')
check('021 timeline link opens its own bulletin',page.locator('.bulletin-detail .bulletin-body').inner_text().count('second paragraph')==1)
no_overflow('021 bulletin detail');page.set_viewport_size({'width':390,'height':844})
page.emulate_media(reduced_motion='reduce');check('021 reduced motion keeps timeline readable',page.locator('.bulletin-body').is_visible())
shot('021-bulletin-mobile.png');page.emulate_media(reduced_motion='no-preference')
nojs21=browser.new_context(java_script_enabled=False,viewport={'width':390,'height':844});static21=nojs21.new_page()
static21.goto(BASE+'/index.php?r=bulletins',wait_until='load',timeout=20000)
check('021 no-JavaScript timeline contains real detail links',static21.locator('[data-bulletin-id="'+bulletin_id21+'"] h3 a').is_visible())
static21.goto(BASE+'/index.php?r=bulletin&id='+bulletin_id21,wait_until='load',timeout=20000)
check('021 no-JavaScript bulletin text is visible',static21.locator('.bulletin-body').is_visible());nojs21.close()
page.set_viewport_size({'width':1440,'height':1000});go('/index.php?r=articles')
no_overflow('021 editorial article listing');page.set_viewport_size({'width':1440,'height':1000});shot('021-articles-desktop.png')
