<?php
// New modules use real transactions, not mocked balance or authorization functions.
settings('community',['circles_enabled'=>true,'bounties_enabled'=>true,'bounty_max'=>1000,'comment_visibility'=>'public']);
settings('modules',['questions_enabled'=>true,'polls_enabled'=>true,'forum_enabled'=>true,'submissions_enabled'=>true]);
settings('commerce',['reviews_enabled'=>true,'reviews_review'=>true,'invitation_products_enabled'=>true]);
function fresh012(string $name): int {global $a;$id=$a->db->insert('cy_users',['username'=>$name,'email'=>$name.'@example.test','password_hash'=>password_hash('FreshPassword012!',PASSWORD_DEFAULT),'display_name'=>$name,'bio'=>'','created_at'=>time()]);foreach(['balance','points','tokens'] as $asset){$a->wallet->adjust($id,$asset,10000,'fresh012:'.$id.':'.$asset,'Fixture');}return $id;}
function circle012(array $change=[]): int {global $a,$admin;return $a->categories->save($admin,array_merge(['name'=>'Circle '.key32(),'kind'=>'thread','description'=>'Public circle introduction','access_level'=>'members','post_level'=>'members','is_circle'=>'1','join_open'=>'1','join_currency'=>'points','join_price'=>'40','join_days'=>30],$change));}
function updateCategory012(int $id,array $change): int {global $a,$admin;$c=$a->categories->get($id);$c['join_price']=$c['join_currency']==='balance'?number_format((int)$c['join_amount']/100,2,'.',''):$c['join_amount'];return $a->categories->save($admin,array_merge($c,$change));}
function thread012(int $owner,string $mode='question',array $change=[]): int {global $a,$admin;$id=$a->content->save(account($admin),array_merge(['kind'=>'thread','thread_mode'=>$mode,'title'=>'Community fixture '.key32(),'body'=>'Public question','protected_body'=>'Protected answer material','status'=>'published','access_level'=>'public','comment_enabled'=>'1'],$change),true);$a->db->update('cy_contents',$id,['author_id'=>$owner]);return $id;}
function answer012(int $content,int $user,string $status='approved'): int {global $a;return $a->db->insert('cy_comments',['content_id'=>$content,'user_id'=>$user,'body'=>'A helpful original answer','status'=>$status,'created_at'=>time()]);}
$cu=fresh012('community012');$cv=fresh012('answer012');$cx=fresh012('outsider012');
$circle=circle012();$post=thread012($cu,'discussion',['category_id'=>$circle,'title'=>'UNIQUE-PRIVATE-CIRCLE-012']);
test('circle content is excluded from guest and nonmember feeds',static function()use($a,$cx){same(0,$a->content->feed('all',null,['q'=>'UNIQUE-PRIVATE-CIRCLE-012'])['total']);same(0,$a->content->feed('all',account($cx),['q'=>'UNIQUE-PRIVATE-CIRCLE-012'])['total']);});
test('circle single content blocks even its nonmember author',static function()use($a,$cu,$post){reject(static function()use($a,$cu,$post){$a->content->get($post,account($cu));},403);});
test('circle joining charges once and opens content',static function()use($a,$cu,$circle,$post){$key=key32();$before=funds($cu,'points');$one=$a->commerce->buy($cu,'circle',$circle,$key);$two=$a->commerce->buy($cu,'circle',$circle,$key);same($one['id'],$two['id']);same($before-40,funds($cu,'points'));truth($a->categories->member($circle,$cu));same($post,(int)$a->content->get($post,account($cu))['id']);same(1,$a->content->feed('thread',account($cu),['q'=>'UNIQUE-PRIVATE-CIRCLE-012'])['total']);});
test('active circle membership cannot be charged a second time',static function()use($a,$cu,$circle){$before=funds($cu,'points');reject(static function()use($a,$cu,$circle){$a->commerce->buy($cu,'circle',$circle,key32());},409);same($before,funds($cu,'points'));});
test('circle private file enforces the same category boundary',static function()use($a,$cu,$cx,$admin,$post){$mid=$a->db->insert('cy_media',['owner_id'=>$admin,'name'=>'circle-secret.txt','mime'=>'text/plain','bytes'=>10,'file_key'=>bin2hex(random_bytes(24)).'.php','is_private'=>1,'created_at'=>time()]);$a->db->update('cy_contents',$post,['resource_id'=>$mid]);same($mid,(int)$a->media->readable($mid,account($cu))['id']);reject(static function()use($a,$mid,$cx){$a->media->readable($mid,account($cx));},403);});
test('circle read and post gates are independently enforced',static function()use($a,$cu,$circle){updateCategory012($circle,['post_level'=>'vip','min_vip_tier'=>2]);truth($a->categories->allowed($circle,account($cu)));same(false,$a->categories->allowed($circle,account($cu),'post'));reject(static function()use($a,$cu,$circle){$a->content->save(account($cu),['kind'=>'thread','title'=>'Cannot post','body'=>'Forbidden','category_id'=>$circle,'status'=>'pending'],false);},403);updateCategory012($circle,['post_level'=>'members']);});
test('circle replies also enforce the posting gate',static function()use($a,$cu,$circle,$post){updateCategory012($circle,['post_level'=>'staff']);reject(static function()use($a,$cu,$post){$a->content->comment(account($cu),$post,'Cannot reply');},403);updateCategory012($circle,['post_level'=>'members']);});
test('suspension takes precedence over paid access and forbids repurchase',static function()use($a,$cu,$circle,$admin,$post){$a->categories->manageMember($admin,$circle,$cu,true,0);same(false,$a->categories->member($circle,$cu));reject(static function()use($a,$cu,$post){$a->content->get($post,account($cu));},403);reject(static function()use($a,$cu,$circle){$a->commerce->buy($cu,'circle',$circle,key32());},403);$a->categories->manageMember($admin,$circle,$cu,false,0);truth($a->categories->member($circle,$cu));});
test('manual grant expires without creating a fictitious paid order',static function()use($a,$cv,$circle,$admin){$count=(int)$a->db->value('SELECT COUNT(*) FROM cy_orders');$a->categories->manageMember($admin,$circle,$cv,false,time()+600);truth($a->categories->member($circle,$cv));same($count,(int)$a->db->value('SELECT COUNT(*) FROM cy_orders'));$a->categories->manageMember($admin,$circle,$cv,false,time()-1);same(false,$a->categories->member($circle,$cv));});
test('refund restores circle asset and revokes its exact term',static function()use($a,$cu,$circle,$admin){$order=$a->db->one("SELECT * FROM cy_orders WHERE user_id=? AND kind='circle' AND item_id=?",[$cu,$circle]);$b=funds($cu,'points');$a->commerce->requestRefund($cu,(int)$order['id'],'Circle test refund');$a->commerce->refund($admin,(int)$order['id'],true);same($b+40,funds($cu,'points'));same(false,$a->categories->member($circle,$cu));});
test('expired circle term can be renewed and old refund does not revoke renewal',static function()use($a,$cu,$circle,$admin){$o=$a->commerce->buy($cu,'circle',$circle,key32());$a->db->update('cy_orders',(int)$o['id'],['access_until'=>time()-1]);same(false,$a->categories->member($circle,$cu));$a->commerce->buy($cu,'circle',$circle,key32());$a->commerce->requestRefund($cu,(int)$o['id'],'Old expired term');$a->commerce->refund($admin,(int)$o['id'],true);truth($a->categories->member($circle,$cu));});
test('circle balance price uses integer cents',static function()use($a,$cu){$id=circle012(['join_currency'=>'balance','join_price'=>'2.50']);$b=funds($cu);$a->commerce->buy($cu,'circle',$id,key32());same($b-250,funds($cu));});
test('free circle joins produce no zero-value ledger entry',static function()use($a,$cu){$id=circle012(['join_price'=>'0','join_days'=>0]);$count=(int)$a->db->value('SELECT COUNT(*) FROM cy_ledger');$o=$a->commerce->buy($cu,'circle',$id,key32());same(0,(int)$o['access_until']);same(0,(int)$o['amount']);same($count,(int)$a->db->value('SELECT COUNT(*) FROM cy_ledger'));});
test('unaffordable circle leaves no order or membership',static function()use($a,$cu){$id=circle012(['join_price'=>'9999999']);$count=(int)$a->db->value('SELECT COUNT(*) FROM cy_orders');reject(static function()use($a,$cu,$id){$a->commerce->buy($cu,'circle',$id,key32());});same($count,(int)$a->db->value('SELECT COUNT(*) FROM cy_orders'));same(false,$a->categories->member($id,$cu));});
test('closed circle denies joining while existing membership remains valid',static function()use($a,$cu,$cx,$circle){updateCategory012($circle,['join_open'=>0]);reject(static function()use($a,$cx,$circle){$a->commerce->buy($cx,'circle',$circle,key32());},409);truth($a->categories->member($circle,$cu));updateCategory012($circle,['join_open'=>1]);});
test('a public child cannot weaken a members-only parent',static function()use($a,$circle,$cu,$cx){$child=circle012(['parent_id'=>$circle,'access_level'=>'public','post_level'=>'login','join_price'=>'0']);same(false,$a->categories->allowed($child,account($cx)));truth($a->categories->allowed($child,account($cu)));reject(static function()use($a,$cx,$child){$a->commerce->buy($cx,'circle',$child,key32());},403);});
test('category cycles rejected without modifying the existing tree',static function()use($a,$circle){$child=circle012(['parent_id'=>$circle]);reject(static function()use($circle,$child){updateCategory012($circle,['parent_id'=>$child]);});same(0,(int)$a->categories->get($circle)['parent_id']);});
test('missing category is fail-closed',static function()use($a,$cu){same(false,$a->categories->allowed(999999,account($cu)));});
test('existing category update to nonexisting ID returns 404',static function()use($a,$admin){reject(static function()use($a,$admin){$a->admin->entity($admin,'categories',['id'=>999999,'name'=>'Unknown','kind'=>'thread']);},404);});
test('circle with membership history cannot be silently converted to a public category',static function()use($circle){reject(static function()use($circle){updateCategory012($circle,['is_circle'=>0,'access_level'=>'public','post_level'=>'login']);});});
$multi=thread012($cu,'poll',['poll_question'=>'Choose useful features','poll_options'=>"Access\nMotion\nCommerce",'poll_max_choices'=>2,'poll_results'=>'after_vote']);$opts=array_map('intval',array_column($a->threads->options($multi),'id'));
test('multi-choice results and counts stay absent before authorized result visibility',static function()use($a,$multi,$cu){$r=$a->threads->snapshot($a->content->get($multi,account($cu)),account($cu),true);same(null,$r['total']);same(false,isset($r['options'][0]['votes']));});
test('multi-choice ballot stores two selections but one voter',static function()use($a,$cu,$multi,$opts){$a->threads->voteMany(account($cu),$multi,[$opts[0],$opts[2]],$a->content);$r=$a->threads->snapshot($a->content->get($multi,account($cu)),account($cu),true);same(1,$r['total']);same(2,count($r['choices']));same(1,$r['options'][0]['votes']);same(100.0,(float)$r['options'][0]['percent']);});
test('same multiselect ballot in different order is idempotent',static function()use($a,$cu,$multi,$opts){$a->threads->voteMany(account($cu),$multi,[$opts[2],$opts[0]],$a->content);same(1,(int)$a->db->value('SELECT COUNT(*) FROM cy_poll_votes WHERE content_id=?',[$multi]));});
test('cannot change previously recorded multiselect ballot',static function()use($a,$cu,$multi,$opts){reject(static function()use($a,$cu,$multi,$opts){$a->threads->voteMany(account($cu),$multi,[$opts[1]],$a->content);},409);});
test('too many options and duplicate options leave no ballot',static function()use($a,$cv,$multi,$opts){reject(static function()use($a,$cv,$multi,$opts){$a->threads->voteMany(account($cv),$multi,$opts,$a->content);});reject(static function()use($a,$cv,$multi,$opts){$a->threads->voteMany(account($cv),$multi,[$opts[0],$opts[0]],$a->content);});same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_poll_votes WHERE content_id=? AND user_id=?',[$multi,$cv]));});
test('foreign poll options are rejected transactionally',static function()use($a,$cv,$multi){reject(static function()use($a,$cv,$multi){$a->threads->voteMany(account($cv),$multi,[999999],$a->content);});});
test('maximum choices cannot be changed after voting',static function()use($a,$admin,$multi){reject(static function()use($a,$admin,$multi){$a->threads->save(account($admin),$multi,['thread_mode'=>'poll','poll_max_choices'=>1]);},409);});
test('v3 to v4 ballot backfill is restartable and preserves multiselect choices',static function()use($a,$multi){$count=(int)$a->db->value('SELECT COUNT(*) FROM cy_poll_choices');$a->db->execute('UPDATE cy_settings SET value=? WHERE name=?',['3','_schema_version']);\Chengyu\Core\Migrations::upgrade($a->db,$a->config['storage']);same($count,(int)$a->db->value('SELECT COUNT(*) FROM cy_poll_choices'));same(\Chengyu\Core\Migrations::VERSION,\Chengyu\Core\Migrations::version($a->db));});
$q=thread012($cu);$ans=answer012($q,$cv);
test('funded question holds points once under repeated submission',static function()use($a,$cu,$q){$b=funds($cu,'points');$a->bounties->fund(account($cu),$q,100,7,$a->content);$a->bounties->fund(account($cu),$q,100,7,$a->content);same($b-100,funds($cu,'points'));same('open',$a->bounties->get($q)['status']);});
test('third party cannot fund another authors question',static function()use($a,$cv,$q){reject(static function()use($a,$cv,$q){$a->bounties->fund(account($cv),$q,100,7,$a->content);},403);});
test('unexpired bounty cannot be withdrawn by owner',static function()use($a,$cu,$q){reject(static function()use($a,$cu,$q){$a->bounties->release(account($cu),$q);},403);});
test('self answer cannot claim bounty',static function()use($a,$cu,$q){$id=answer012($q,$cu);reject(static function()use($a,$cu,$q,$id){$a->threads->accept(account($cu),$q,$id,$a->content);},403);same('open',$a->bounties->get($q)['status']);});
test('unapproved answer cannot receive bounty',static function()use($a,$cu,$cv,$q){$id=answer012($q,$cv,'pending');reject(static function()use($a,$cu,$q,$id){$a->threads->accept(account($cu),$q,$id,$a->content);});same('open',$a->bounties->get($q)['status']);});
test('accepting an answer atomically pays held points once',static function()use($a,$cu,$cv,$q,$ans){$b=funds($cv,'points');$a->threads->accept(account($cu),$q,$ans,$a->content);$a->threads->accept(account($cu),$q,$ans,$a->content);same($b+100,funds($cv,'points'));same('awarded',$a->bounties->get($q)['status']);same($ans,(int)$a->threads->definition($q)['accepted_comment_id']);});
test('awarded bounty cannot be reassigned or returned',static function()use($a,$admin,$cu,$cv,$q){$otherAnswer=answer012($q,$cv);reject(static function()use($a,$cu,$q,$otherAnswer){$a->threads->accept(account($cu),$q,$otherAnswer,$a->content);},409);reject(static function()use($a,$admin,$q){$a->bounties->release(account($admin),$q);},409);});
test('moderating an awarded answer does not erase or duplicate financial history',static function()use($a,$admin,$cu,$cv,$q,$ans){$b=funds($cv,'points');$a->admin->moderation($admin,'comments',$ans,'rejected');same(0,(int)$a->threads->definition($q)['accepted_comment_id']);same('awarded',$a->bounties->get($q)['status']);$a->admin->moderation($admin,'comments',$ans,'approved');$a->threads->accept(account($cu),$q,$ans,$a->content);same($b,funds($cv,'points'));});
test('expired unanswered bounty returns once without cron',static function()use($a,$cu){$id=thread012($cu);$b=funds($cu,'points');$row=$a->bounties->fund(account($cu),$id,80,1,$a->content);$a->db->update('cy_bounties',(int)$row['id'],['expires_at'=>time()-1]);$a->bounties->release(account($cu),$id);$a->bounties->release(account($cu),$id);same($b,funds($cu,'points'));same('returned',$a->bounties->get($id)['status']);});
test('bounty return remains available when new bounties are disabled',static function()use($a,$cu){$id=thread012($cu);$row=$a->bounties->fund(account($cu),$id,70,1,$a->content);$a->db->update('cy_bounties',(int)$row['id'],['expires_at'=>time()-1]);settings('community',['bounties_enabled'=>false]);$a->bounties->release(account($cu),$id);same('returned',$a->bounties->get($id)['status']);settings('community',['bounties_enabled'=>true]);});
test('oversized or unaffordable bounty creates no escrow',static function()use($a,$cu){$id=thread012($cu);reject(static function()use($a,$cu,$id){$a->bounties->fund(account($cu),$id,1001,7,$a->content);});same(null,$a->bounties->get($id));});
test('bounty-bearing question cannot be converted into a poll',static function()use($a,$admin,$q){reject(static function()use($a,$admin,$q){$a->threads->save(account($admin),$q,['thread_mode'=>'discussion']);},409);});
$reviewProduct=product('digital');$reviewOrder=$a->commerce->buy($cu,'content',$reviewProduct,key32());$reviewId=0;
test('nonbuyer cannot create a verified review',static function()use($a,$cv,$reviewProduct){reject(static function()use($a,$cv,$reviewProduct){$a->reviews->save(account($cv),$reviewProduct,5,'No purchase',$a->content);},403);});
test('new verified review waits for moderation and is not in public aggregate',static function()use($a,$cu,$reviewProduct,&$reviewId){$reviewId=$a->reviews->save(account($cu),$reviewProduct,4,'Useful after actual purchase',$a->content);same(0,$a->reviews->listing($reviewProduct)['total']);});
test('approved review appears in accurate rating aggregate',static function()use($a,$admin,$reviewProduct,&$reviewId){$a->reviews->moderate($admin,$reviewId,'approved');$rows=$a->reviews->listing($reviewProduct);same(1,$rows['total']);same(4.0,(float)$rows['average']);});
test('editing review re-enters moderation and never creates second review',static function()use($a,$cu,$admin,$reviewProduct,&$reviewId){same($reviewId,$a->reviews->save(account($cu),$reviewProduct,5,'Updated actual experience',$a->content));same(0,$a->reviews->listing($reviewProduct)['total']);same(1,(int)$a->db->value('SELECT COUNT(*) FROM cy_reviews WHERE content_id=? AND user_id=?',[$reviewProduct,$cu]));$a->reviews->moderate($admin,$reviewId,'approved');});
test('refund removes verified review from public score without deleting its audit history',static function()use($a,$cu,$admin,$reviewOrder,$reviewProduct,&$reviewId){$a->commerce->requestRefund($cu,(int)$reviewOrder['id'],'Review refund test');$a->commerce->refund($admin,(int)$reviewOrder['id'],true);same(0,$a->reviews->listing($reviewProduct)['total']);same(null,$a->reviews->listing($reviewProduct)['average']);truth((bool)$a->db->one('SELECT id FROM cy_reviews WHERE id=?',[$reviewId]));reject(static function()use($a,$cu,$reviewProduct){$a->reviews->save(account($cu),$reviewProduct,5,'No longer purchased',$a->content);},403);});
test('invalid review rating cannot reach storage',static function()use($a,$cu,$reviewProduct){reject(static function()use($a,$cu,$reviewProduct){$a->reviews->save(account($cu),$reviewProduct,6,'Bad rating',$a->content);});});
$inviteProduct=product('invitation','balance','1.00',5);
test('automatic invitation product delivers a unique encrypted code exactly once',static function()use($a,$cu,$inviteProduct){$intent=key32();$one=$a->commerce->buy($cu,'content',$inviteProduct,$intent);$two=$a->commerce->buy($cu,'content',$inviteProduct,$intent);same($one['id'],$two['id']);$code=trim($a->commerce->delivery($one));truth((bool)preg_match('/^[A-F0-9]{24}$/D',$code));truth(strpos($one['delivery_cipher'],$code)===false);$more=$a->commerce->buy($cu,'content',$inviteProduct,key32());truth(trim($a->commerce->delivery($more))!==$code);same(3,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$inviteProduct]));});
test('unused invitation refund revokes the generated registration code',static function()use($a,$cu,$admin,$inviteProduct){$o=$a->commerce->buy($cu,'content',$inviteProduct,key32());$code=trim($a->commerce->delivery($o));$a->commerce->requestRefund($cu,(int)$o['id'],'Unused code');$a->commerce->refund($admin,(int)$o['id'],true);reject(static function()use($a,$code){$a->db->transaction(static function()use($a,$code){$a->invitations->consume($code);});});});
test('used invitation cannot be refunded automatically or create a double credit',static function()use($a,$cu,$admin,$inviteProduct){$o=$a->commerce->buy($cu,'content',$inviteProduct,key32());$code=trim($a->commerce->delivery($o));$a->db->transaction(static function()use($a,$code){$a->invitations->consume($code);});$a->commerce->requestRefund($cu,(int)$o['id'],'Used code');$before=funds($cu);reject(static function()use($a,$admin,$o){$a->commerce->refund($admin,(int)$o['id'],true);},409);same($before,funds($cu));same('refund_requested',$a->db->value('SELECT status FROM cy_orders WHERE id=?',[(int)$o['id']]));});
test('failed invitation purchase leaves no usable invitation or spent stock',static function()use($a,$cu){$p=product('invitation','balance','999999.99',1);$count=(int)$a->db->value('SELECT COUNT(*) FROM cy_invitations');reject(static function()use($a,$cu,$p){$a->commerce->buy($cu,'content',$p,key32());});same($count,(int)$a->db->value('SELECT COUNT(*) FROM cy_invitations'));same(1,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$p]));});
test('disabling invitation products cannot silently fulfill them as plain text',static function()use($a,$cu){settings('commerce',['invitation_products_enabled'=>false]);$p=product('invitation');reject(static function()use($a,$cu,$p){$a->commerce->buy($cu,'content',$p,key32());},403);settings('commerce',['invitation_products_enabled'=>true]);});

test('category with children cannot change kind and orphan child policy',static function()use($a,$admin){$p=$a->categories->save($admin,['name'=>'Typed parent','kind'=>'article']);$a->categories->save($admin,['name'=>'Typed child','kind'=>'article','parent_id'=>$p]);reject(static function()use($p){updateCategory012($p,['kind'=>'product']);});same('article',$a->categories->get($p)['kind']);});
