<?php
use Chengyu\Services\{Checkout,Rulebooks,DirectPayments};
use Chengyu\Core\{IntegerMath,Problem};
use Chengyu\Payments\Tools;
function buyer16(): int {global $a;$id=user14('commerce16');$a->wallet->adjust($id,'balance',500000,'f16:'.$id,'fixture');return $id;}
function lines16(int $id,int $qty=1): array{return [['kind'=>'content','item_id'=>$id,'variant_id'=>0,'quantity'=>$qty]];}
function address16(): array{return ['recipient'=>'Fixture Buyer','phone'=>'123456789','address'=>'Fixture Road 1','region'=>'CN-GD'];}
function buy16(int $uid,int $pid,int $qty=1,string $gateway='wallet',string $intent=''): array {global $a;$l=lines16($pid,$qty);$q=$a->checkout->quote(account($uid),$l,address16(),'');return $a->checkout->create($uid,$l,address16(),'',$gateway,$intent?:key32(),$q['total'],$q['currency']);}
function unit16(array $sale): array {global $a;return $a->db->one('SELECT * FROM cy_orders WHERE sale_id=? ORDER BY id',[(int)$sale['id']]);}
settings('checkout',['checkout_enabled'=>1,'guest_checkout_enabled'=>1,'shipping_enabled'=>1,'promotions_enabled'=>1,'upgrades_enabled'=>1]);
settings('direct_payments',['stripe_enabled'=>1,'stripe_secret'=>'sk_test_fixture','stripe_webhook_secret'=>'whsec_fixture']);
$a->db->execute('UPDATE cy_promotions SET active=0');
foreach([[1,1,2,0,1],[999999999,250000000000,253402214400,986573855,986573856],[10,3,2,15,15],[0,999,9,0,0]] as $i=>$v){test('016 integer ratio '.$i,static function()use($v){[$x,$y,$d,$floor,$ceil]=$v;same($floor,IntegerMath::mulDiv($x,$y,$d));same($ceil,IntegerMath::mulDiv($x,$y,$d,true));});}
test('016 exact cent allocation retains all remainders',static function(){same([0=>4,1=>3,2=>3],Rulebooks::allocate(10,[1,1,1]));same([4=>3,8=>2],Rulebooks::allocate(5,[4=>0,8=>0]));reject(static function(){Rulebooks::allocate(-1,[1]);});});
test('016 invalid promotion and delivery documents fail closed',static function(){reject(static function(){Rulebooks::validate('shipping',['default'=>null]);});reject(static function(){Rulebooks::validate('promotion',['type'=>'eval','code'=>'x']);});reject(static function(){Rulebooks::validate('promotion',['type'=>'bundle','item_ids'=>[1],'discount'=>100]);});});
test('016 wallet checkout is atomically paid, fulfilled and idempotent',static function()use($a){$id=buyer16();$p=product('physical','balance','9.99',5);$key=key32();$s=buy16($id,$p,2,'wallet',$key);same('paid',$s['status']);same(1998,(int)$s['amount']);same(3,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$p]));same(498002,funds($id));$s2=buy16($id,$p,2,'wallet',$key);same((int)$s['id'],(int)$s2['id']);same(498002,funds($id));$orders=$a->db->all('SELECT * FROM cy_orders WHERE sale_id=?',[(int)$s['id']]);same(2,count($orders));foreach($orders as $o){same('awaiting_shipment',$o['fulfillment']);truth((int)$o['fulfilled_at']>0);}});
test('016 price ceiling rollback releases all reservations and ledger effects',static function()use($a){$id=buyer16();$p=product('physical','balance','9.99',2);reject(static function()use($a,$id,$p){$a->checkout->create($id,lines16($p),address16(),'','wallet',key32(),998,'CNY');},409);same(500000,funds($id));same(2,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$p]));same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_sales WHERE user_id=?',[$id]));});
test('016 saved shipping uses first and additional units; old checkout cannot skip it',static function()use($a,$admin){$id=buyer16();$p=product('physical','balance','10.00',10);$t=$a->rulebooks->save($admin,'shipping',['name'=>'Piece fixture','active'=>1,'document'=>json_encode(['mode'=>'piece','default'=>['first'=>1,'first_fee'=>600,'step'=>1,'step_fee'=>200]])]);$a->rulebooks->bindShipping($admin,$p,$t,100);$q=$a->checkout->quote(account($id),lines16($p,3),address16(),'');same(1000,$q['shipping']);same(4000,$q['total']);same(1000,array_sum(array_column($q['items'],'shipping')));reject(static function()use($a,$id,$p){$a->commerce->buy($id,'content',$p,key32());},409);$s=buy16($id,$p,3);same(4000,(int)$s['amount']);});
test('016 weight shipping and excluded regions enforce exact server policy',static function()use($a,$admin){$id=buyer16();$p=product('physical','balance','10.00',10);$t=$a->rulebooks->save($admin,'shipping',['name'=>'Weight fixture','active'=>1,'document'=>json_encode(['mode'=>'weight','default'=>null,'zones'=>['CN-GD'=>['first'=>1000,'first_fee'=>500,'step'=>500,'step_fee'=>200]]])]);$a->rulebooks->bindShipping($admin,$p,$t,700);$q=$a->checkout->quote(account($id),lines16($p,3),address16(),'');same(1100,$q['shipping']);$bad=address16();$bad['region']='CN-OTHER';reject(static function()use($a,$id,$p,$bad){$a->checkout->quote(account($id),lines16($p),$bad,'');});});
test('016 best-in-group promotions stack across distinct groups and allocate exactly',static function()use($a,$admin){$id=buyer16();$p=product('physical','balance','10.00',20);$scope=['item_ids'=>[$p],'min_amount'=>0];$ids=[];foreach([['type'=>'percent','group'=>'a','discount_bps'=>1000],['type'=>'threshold_fixed','group'=>'a','discount'=>500],['type'=>'nth','group'=>'b','nth'=>2,'discount_bps'=>5000]] as $r){$ids[]=$a->rulebooks->save($admin,'promotion',['name'=>'Fixture promotion','active'=>1,'document'=>json_encode($scope+$r)]);}try{$q=$a->checkout->quote(account($id),lines16($p,2),address16(),'');same(1125,$q['total']);same(2,count($q['promotions']));same(1125,array_sum(array_column($q['items'],'amount')));}finally{foreach($ids as $rid){$a->db->update('cy_promotions',$rid,['active'=>0]);}}});
test('016 promotions optimistic revision prevents lost edits',static function()use($a,$admin){$r=['name'=>'Edit fixture','active'=>1,'document'=>json_encode(['type'=>'percent','discount_bps'=>1000])];$id=$a->rulebooks->save($admin,'promotion',$r);$a->rulebooks->save($admin,'promotion',$r+['id'=>$id,'revision'=>1]);reject(static function()use($a,$admin,$r,$id){$a->rulebooks->save($admin,'promotion',$r+['id'=>$id,'revision'=>1]);},409);$a->db->update('cy_promotions',$id,['active'=>0]);});
test('016 external orders reserve stock, do not grant access, and cancel only before sending',static function()use($a){$id=buyer16();$p=product('physical','balance','5.00',2);$s=buy16($id,$p,1,'stripe');same('pending',$s['status']);same(1,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$p]));same(500000,funds($id));same(false,$a->content->access($a->content->get($p,account($id)),account($id)));$a->checkout->cancelUnsent((int)$s['id'],$id);same(2,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$p]));$s=buy16($id,$p,1,'stripe');$a->db->update('cy_sales',(int)$s['id'],['attempted_at'=>time()]);reject(static function()use($a,$s,$id){$a->checkout->cancelUnsent((int)$s['id'],$id);},409);same(1,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$p]));});
test('016 verified provider receipt grants access once and never credits wallet',static function()use($a){$id=buyer16();$p=product('digital','balance','4.50');$s=buy16($id,$p,1,'stripe');$r=Tools::receipt($s,'pi_'.key32(),450,'CNY',$s['sale_no']);$a->checkout->settle((int)$s['id'],$r);$a->checkout->settle((int)$s['id'],$r);same(500000,funds($id));same(1,(int)$a->db->value('SELECT sold_count FROM cy_contents WHERE id=?',[$p]));same(true,$a->content->access($a->content->get($p,account($id)),account($id)));$r['trade']='different_trade';reject(static function()use($a,$s,$r){$a->checkout->settle((int)$s['id'],$r);},409);});
test('016 wrong amount or currency cannot settle a reserved order',static function()use($a){$id=buyer16();$p=product();$s=buy16($id,$p,1,'stripe');foreach([['amount'=>99,'currency'=>'CNY'],['amount'=>100,'currency'=>'USD']] as $bad){$r=$bad+['trade'=>'pi_fake','order'=>$s['sale_no'],'state'=>'paid'];reject(static function()use($a,$s,$r){$a->checkout->settle((int)$s['id'],$r);},409);}same('pending',unit16($s)['status']);});
test('016 guest pass is encrypted/hashed and is not login or category membership',static function()use($a,$admin){$g=$a->guests->create('real-contact@example.test');$guest=$a->guests->authorize($g['token']);same(1,(int)$guest['is_guest']);$stored=$a->db->one('SELECT * FROM cy_guest_passes WHERE id=?',[$g['id']]);truth(strpos(json_encode($stored),$g['token'])===false);truth(strpos(json_encode($stored),'real-contact@example.test')===false);$category=$a->categories->save($admin,['kind'=>'article','name'=>'Login only fixture','access_level'=>'login','post_level'=>'login']);same(false,$a->categories->allowed($category,$guest));$post=$a->content->save(account($admin),['kind'=>'article','title'=>'Login fixture','body'=>'Public','protected_body'=>'LOGIN SECRET','status'=>'published','access_level'=>'login'],true);same(false,$a->content->access($a->content->get($post,$guest),$guest));reject(static function()use($a){$a->guests->authorize(str_repeat('f',64));},403);});
test('016 guest paid access is order-scoped and can be explicitly claimed',static function()use($a){$g=$a->guests->create('guest-buy@example.test');$guest=$a->guests->authorize($g['token']);$p=product();$s=buy16((int)$guest['id'],$p,1,'stripe');$target=buyer16();reject(static function()use($a,$target,$g){$a->guests->claim($target,$g['token']);},409);$a->checkout->settle((int)$s['id'],Tools::receipt($s,'pi_'.key32(),100,'CNY',$s['sale_no']));truth($a->content->access($a->content->get($p,$guest),$guest));$other=product();same(false,$a->content->access($a->content->get($other,$guest),$guest));same(1,$a->guests->claim($target,$g['token']));reject(static function()use($a,$g){$a->guests->authorize($g['token']);},403);same($target,(int)unit16($s)['user_id']);truth($a->content->access($a->content->get($p,account($target)),account($target)));});
test('016 full unit wallet refund includes freight and restocks exactly once',static function()use($a,$admin){$id=buyer16();$p=product('physical','balance','10.00',3);$t=$a->rulebooks->save($admin,'shipping',['name'=>'Refund freight','active'=>1,'document'=>json_encode(['mode'=>'fixed','default'=>['first_fee'=>500]])]);$a->rulebooks->bindShipping($admin,$p,$t,1);$s=buy16($id,$p);$o=unit16($s);same(498500,funds($id));$c=$a->aftersales->request($id,(int)$o['id'],'refund','Fixture cancellation');$a->aftersales->review($admin,$c,1,'approve','Approved fixture');$rid=(int)$a->db->value('SELECT id FROM cy_refunds WHERE order_id=?',[$o['id']]);same('succeeded',$a->refunds->run($rid)['status']);$a->refunds->run($rid);same(500000,funds($id));same(3,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$p]));same('refunded',unit16($s)['status']);});
test('016 direct original refund cannot mint wallet credit',static function()use($a,$admin){$id=buyer16();$p=product();$s=buy16($id,$p,1,'stripe');$a->checkout->settle((int)$s['id'],Tools::receipt($s,'pi_'.key32(),100,'CNY',$s['sale_no']));$o=unit16($s);$c=$a->aftersales->request($id,(int)$o['id'],'refund','Original route');$a->aftersales->review($admin,$c,1,'approve','Approved original route');$rid=(int)$a->db->value('SELECT id FROM cy_refunds WHERE order_id=?',[$o['id']]);$original=$a->directPayments;$a->directPayments=new DirectPayments($a->settings,new \Chengyu\Core\HttpClient(static function($method,$url,$headers,$body)use($s,$a,$rid){parse_str($body,$fields);same($s['trade_no']?:$a->db->value('SELECT trade_no FROM cy_sales WHERE id=?',[$s['id']]),$fields['payment_intent']);return response15(['id'=>'re_fixture_'.$rid,'payment_intent'=>$fields['payment_intent'],'amount'=>100,'currency'=>'cny','status'=>'succeeded','metadata'=>$fields['metadata']]);}));try{same('succeeded',$a->refunds->run($rid)['status']);$a->refunds->run($rid);same(500000,funds($id));same(false,$a->content->access($a->content->get($p,account($id)),account($id)));}finally{$a->directPayments=$original;}});
test('016 refund timeout holds assets and retains the original refund reference',static function()use($a,$admin){$id=buyer16();$p=product();$s=buy16($id,$p,1,'stripe');$a->checkout->settle((int)$s['id'],Tools::receipt($s,'pi_'.key32(),100,'CNY',$s['sale_no']));$o=unit16($s);$c=$a->aftersales->request($id,(int)$o['id'],'refund','Network fixture');$a->aftersales->review($admin,$c,1,'approve','Approved');$rid=(int)$a->db->value('SELECT id FROM cy_refunds WHERE order_id=?',[$o['id']]);$original=$a->directPayments;$a->directPayments=new DirectPayments($a->settings,new \Chengyu\Core\HttpClient(static function(){throw new Problem('Fixture timeout',502);}));try{reject(static function()use($a,$rid){$a->refunds->run($rid);},502);$r=$a->db->one('SELECT * FROM cy_refunds WHERE id=?',[$rid]);same('uncertain',$r['status']);same('refund_requested',unit16($s)['status']);same(500000,funds($id));truth((int)$r['attempted_at']>0);}finally{$a->directPayments=$original;}});
test('016 same-SKU exchange requires return transit, inspection and customer receipt',static function()use($a,$admin){$id=buyer16();$p=product('physical','balance','10.00',3);$s=buy16($id,$p);$o=unit16($s);$a->commerce->ship($admin,(int)$o['id'],'Fixture outbound');$c=$a->aftersales->request($id,(int)$o['id'],'exchange','Size fixture');$a->aftersales->review($admin,$c,1,'approve','Return to fixture warehouse');reject(static function()use($a,$admin,$c){$a->aftersales->review($admin,$c,2,'replace','Too early',false,'Fixture replacement');},409);$a->aftersales->customer($id,$c,2,'return','Fixture return carrier 123');$a->aftersales->review($admin,$c,3,'received','Inspected',true);$a->aftersales->review($admin,$c,4,'replace','New goods',false,'Fixture replacement 456');same(2,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$p]));$a->aftersales->customer($id,$c,5,'received');same('paid',unit16($s)['status']);same('received',unit16($s)['fulfillment']);same(499000,funds($id));});
function plan16(int $tier,int $days,int $amount): int {global $a;return $a->db->insert('cy_plans',['name'=>'Upgrade fixture '.$tier,'tier'=>$tier,'days'=>$days,'price_amount'=>$amount,'price_currency'=>'balance','active'=>1,'description'=>'Fixture']);}
test('016 finite upgrade consumes actual paid lots and rolls back cash only',static function()use($a,$admin){$id=buyer16();$old=plan16(1,365,10000);$new=plan16(2,365,20000);$o=$a->commerce->buy($id,'membership',$old,key32());$before=funds($id);$q=$a->upgrades->quote($id,$new);truth($q['credit']<=10000&&$q['credit']>=9999);$up=$a->upgrades->buy($id,$new,$q['mode'],$q['as_of'],$q['token'],key32());same($before-$q['amount'],funds($id));same(2,$a->membership->tier(account($id)));$a->upgrades->refund($admin,(int)$up['id']);$a->upgrades->refund($admin,(int)$up['id']);same($before,funds($id));same(1,$a->membership->tier(account($id)));same('active',$a->db->value('SELECT status FROM cy_membership_lots WHERE order_id=?',[$o['id']]));});
test('016 lifetime-to-lifetime upgrades preserve permanent rights and block finite target',static function()use($a){$id=buyer16();$old=plan16(1,0,10000);$finite=plan16(2,365,20000);$permanent=plan16(3,0,30000);$a->commerce->buy($id,'membership',$old,key32());reject(static function()use($a,$id,$finite){$a->upgrades->quote($id,$finite);});$q=$a->upgrades->quote($id,$permanent);same(20000,$q['amount']);same(\Chengyu\Services\Membership::FOREVER,$q['target_until']);$a->upgrades->buy($id,$permanent,$q['mode'],$q['as_of'],$q['token'],key32());same(3,$a->membership->lifetimeTier($id));});
test('016 upgrade refund refuses to erase a later manual grant',static function()use($a,$admin){$id=buyer16();$old=plan16(1,365,10000);$new=plan16(2,365,20000);$a->commerce->buy($id,'membership',$old,key32());$q=$a->upgrades->quote($id,$new);$up=$a->upgrades->buy($id,$new,$q['mode'],$q['as_of'],$q['token'],key32());$a->membership->grant($id,3,30);$balance=funds($id);reject(static function()use($a,$admin,$up){$a->upgrades->refund($admin,(int)$up['id']);},409);same(3,$a->membership->tier(account($id)));same($balance,funds($id));});
test('016 changed upgrade price invalidates the signed review',static function()use($a){$id=buyer16();$old=plan16(1,365,10000);$new=plan16(2,365,20000);$a->commerce->buy($id,'membership',$old,key32());$q=$a->upgrades->quote($id,$new);$a->db->update('cy_plans',$new,['price_amount'=>30000]);reject(static function()use($a,$id,$new,$q){$a->upgrades->buy($id,$new,$q['mode'],$q['as_of'],$q['token'],key32());},409);same(490000,funds($id));});
test('016 store currency cannot be relabelled after ledger activity',static function(){reject(static function(){settings('checkout',['store_currency'=>'USD']);},409);});
$_SESSION=[];$_SERVER['REMOTE_ADDR']='test-fixture';
