<?php
// Same assertions run under FFI SQLite locally or the native PDO CI matrix.
$writer=$a->db->insert('cy_users',['username'=>'writer013','email'=>'writer013@example.test','password_hash'=>password_hash('WriterPassword123!',PASSWORD_DEFAULT),'display_name'=>'Independent writer','role'=>'user','status'=>'active','bio'=>'','creator_enabled'=>1,'created_at'=>time()]);
$reader=$a->db->insert('cy_users',['username'=>'reader013','email'=>'reader013@example.test','password_hash'=>password_hash('ReaderPassword123!',PASSWORD_DEFAULT),'display_name'=>'Reader','role'=>'user','status'=>'active','bio'=>'','created_at'=>time()]);
$a->wallet->adjust($reader,'balance',100000,'reader013-initial','Test fixture');
settings('commerce',['creator_income_enabled'=>'1','creator_hold_days'=>'7','creator_share_bps'=>'8000','creator_balance_conversion'=>'1']);
$creatorProduct=product('digital','balance','10.00');$a->db->update('cy_contents',$creatorProduct,['author_id'=>$writer]);
$creatorOrder=$a->commerce->buy($reader,'content',$creatorProduct,key32());
$income=$a->db->one('SELECT * FROM cy_creator_earnings WHERE order_id=?',[(int)$creatorOrder['id']]);
test('creator accrual snapshots independent author, net price and share',static function()use($income,$writer){same($writer,(int)$income['author_id']);same(1000,(int)$income['net_amount']);same(800,(int)$income['share_amount']);same('pending',$income['status']);});
test('pending earnings are not spendable or settled before hold expiry',static function()use($a,$writer,$income){same(0,funds($writer,'earnings'));same(false,$a->creator->settleOne($writer,(int)$income['id']));reject(static function()use($a,$writer){$a->creator->convert($writer,1,key32());});});
test('foreign creator cannot settle another author income',static function()use($a,$reader,$income){reject(static function()use($a,$reader,$income){$a->creator->settleOne($reader,(int)$income['id']);},404);});
$a->db->update('cy_creator_earnings',(int)$income['id'],['release_at'=>time()-1]);
test('settlement and replay credit exactly one author ledger entry',static function()use($a,$writer,$income){truth($a->creator->settleOne($writer,(int)$income['id']));same(false,$a->creator->settleOne($writer,(int)$income['id']));same(800,funds($writer,'earnings'));});
test('earnings conversion is atomic, idempotent and input-bound',static function()use($a,$writer){$key=key32();$a->creator->convert($writer,500,$key);$a->creator->convert($writer,500,$key);same(500,funds($writer));same(300,funds($writer,'earnings'));reject(static function()use($a,$writer,$key){$a->creator->convert($writer,501,$key);},409);});
test('creator refund reverses settled earnings even after conversion and module disable',static function()use($a,$reader,$writer,$creatorOrder,$admin){settings('commerce',['creator_income_enabled'=>'0']);$a->commerce->requestRefund($reader,(int)$creatorOrder['id'],'Full refund fixture');$a->commerce->refund($admin,(int)$creatorOrder['id'],true);same(-500,funds($writer,'earnings'));same(500,funds($writer));same('reversed',$a->db->value('SELECT status FROM cy_creator_earnings WHERE order_id=?',[(int)$creatorOrder['id']]));settings('commerce',['creator_income_enabled'=>'1']);});
test('income debt prevents withdrawal rather than creating spendable funds',static function()use($a,$writer){settings('commerce',['withdrawals_enabled'=>'1','withdraw_min'=>'100']);reject(static function()use($a,$writer){$a->commerce->withdraw($writer,1,'fixture recipient',key32(),'earnings');});});
$newProduct=product('digital','balance','10.00');$a->db->update('cy_contents',$newProduct,['author_id'=>$writer]);$second=$a->commerce->buy($reader,'content',$newProduct,key32());$secondIncome=$a->db->one('SELECT * FROM cy_creator_earnings WHERE order_id=?',[(int)$second['id']]);$a->db->update('cy_creator_earnings',(int)$secondIncome['id'],['release_at'=>0]);
test('pending refund freezes creator settlement',static function()use($a,$reader,$writer,$second,$secondIncome){$a->commerce->requestRefund($reader,(int)$second['id'],'Dispute');same(false,$a->creator->settleOne($writer,(int)$secondIncome['id']));});
test('rejected refund releases settlement and new revenue repays income debt',static function()use($a,$admin,$writer,$second,$secondIncome){$a->commerce->refund($admin,(int)$second['id'],false);truth($a->creator->settleOne($writer,(int)$secondIncome['id']));same(300,funds($writer,'earnings'));});
test('earnings withdrawal rejection returns the same asset',static function()use($a,$writer,$admin){$key=key32();$a->commerce->withdraw($writer,100,'fixture recipient',$key,'earnings');$a->commerce->withdraw($writer,100,'fixture recipient',$key,'earnings');same(200,funds($writer,'earnings'));$id=(int)$a->db->value('SELECT id FROM cy_withdrawals WHERE request_key=?',[$writer.':'.$key]);$a->commerce->reviewWithdrawal($admin,$id,false,'Not sent');same(300,funds($writer,'earnings'));same(0,funds($writer,'commission'));reject(static function()use($a,$writer,$key){$a->commerce->withdraw($writer,100,'fixture recipient',$key,'commission');},409);});
test('self purchases never accrue author earnings',static function()use($a,$writer){$p=product('digital','balance','1.00');$a->db->update('cy_contents',$p,['author_id'=>$writer]);$o=$a->commerce->buy($writer,'content',$p,key32());same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_creator_earnings WHERE order_id=?',[(int)$o['id']]));});
test('author share uses net amount after referral not gross twice',static function()use($a,$reader,$writer,$u){settings('commerce',['affiliate_enabled'=>'1','commission_bps'=>'1000']);$a->db->update('cy_users',$reader,['referred_by'=>$u]);$p=product('digital','balance','10.00');$a->db->update('cy_contents',$p,['author_id'=>$writer]);$o=$a->commerce->buy($reader,'content',$p,key32());$e=$a->db->one('SELECT * FROM cy_creator_earnings WHERE order_id=?',[(int)$o['id']]);same(100,(int)$o['commission_amount']);same(900,(int)$e['net_amount']);same(720,(int)$e['share_amount']);$a->db->update('cy_users',$reader,['referred_by'=>0]);});
test('unapproved author and points sales create no monetary author liability',static function()use($a,$reader,$writer){$p=product('digital','balance','1.00');$a->db->update('cy_contents',$p,['author_id'=>$writer]);$a->db->update('cy_users',$writer,['creator_enabled'=>0]);$o=$a->commerce->buy($reader,'content',$p,key32());same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_creator_earnings WHERE order_id=?',[(int)$o['id']]));$a->db->update('cy_users',$writer,['creator_enabled'=>1]);});
settings('modules',['submissions_enabled'=>'1']);
$draft=['kind'=>'article','title'=>'Original paid article','body'=>'Free introduction','protected_body'=>'Private paid content','access_level'=>'paid','price'=>'2.50','comment_enabled'=>1];
$submission=0;
test('approved author can create paid content but cannot self-publish',static function()use($a,$writer,$draft,&$submission){$submission=$a->content->save(account($writer),array_merge($draft,['status'=>'published','featured'=>1]),false);$r=$a->db->one('SELECT * FROM cy_contents WHERE id=?',[$submission]);same('pending',$r['status']);same('paid',$r['access_level']);same(250,(int)$r['price_amount']);same(0,(int)$r['featured']);same(1,(int)$r['creator_pricing']);});
test('approved author retains editor constraints while adjusting own permitted price',static function()use($a,$writer,$submission,$draft){$a->content->save(account($writer),array_merge($draft,['id'=>$submission,'price'=>'3.00','pinned'=>1,'access_days'=>100]),false);$r=$a->db->one('SELECT * FROM cy_contents WHERE id=?',[$submission]);same(300,(int)$r['price_amount']);same(0,(int)$r['pinned']);same(0,(int)$r['access_days']);});
test('revoked author cannot newly add a paid gate',static function()use($a,$writer,$draft){$a->db->update('cy_users',$writer,['creator_enabled'=>0]);try{reject(static function()use($a,$writer,$draft){$a->content->save(account($writer),$draft,false);});}finally{$a->db->update('cy_users',$writer,['creator_enabled'=>1]);}});
test('creator approval does not unlock administrator-owned pricing controls',static function()use($a,$writer,$draft){$p=$a->content->save(account($writer),array_merge($draft,['access_level'=>'public']),false);$a->db->update('cy_contents',$p,['creator_pricing'=>0,'access_level'=>'paid','price_amount'=>975]);$a->content->save(account($writer),array_merge($draft,['id'=>$p,'price'=>'0','access_level'=>'public']),false);$r=$a->db->one('SELECT * FROM cy_contents WHERE id=?',[$p]);same(975,(int)$r['price_amount']);same('paid',$r['access_level']);});
$historyItem=$a->content->save(account($admin),['kind'=>'article','title'=>'History permission fixture','body'=>'Visible body','status'=>'published','access_level'=>'public'],true);
test('history progress is private, monotonic and replay safe',static function()use($a,$reader,$historyItem){$a->discovery->record(account($reader),$historyItem,40);$a->discovery->record(account($reader),$historyItem,20);same(40,(int)$a->db->value('SELECT progress FROM cy_reading_history WHERE user_id=? AND content_id=?',[$reader,$historyItem]));same(1,$a->content->feed('all',account($reader),['history'=>true])['total']);});
test('another user cannot see private reading history',static function()use($a,$writer,$historyItem){same(0,$a->content->feed('all',account($writer),['history'=>true])['total']);$a->discovery->forget($writer,$historyItem);});
test('disabling reading history clears records and prevents new writes',static function()use($a,$reader,$historyItem){$a->discovery->preference($reader,false);$a->discovery->record(account($reader),$historyItem,99);same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_reading_history WHERE user_id=?',[$reader]));$a->discovery->preference($reader,true);});
test('history rejects denied content and never indexes protected body',static function()use($a,$reader,$submission){$a->db->update('cy_contents',$submission,['status'=>'published']);reject(static function()use($a,$reader,$submission){$a->discovery->record(account($reader),$submission,5);},403);same([],$a->discovery->suggestions('Private paid content',account($reader)));});
test('search suggestions escape SQL wildcards and expose only safe fields',static function()use($a){same([],$a->discovery->suggestions('%_not_a_title',null));$rows=$a->discovery->suggestions('History permission',null);truth(count($rows)>0);same(['id','title','kind'],array_keys($rows[0]));});
test('following feed contains only followed authors',static function()use($a,$reader,$writer){$a->content->follow($reader,$writer);$feed=$a->content->feed('all',account($reader),['following'=>true]);truth($feed['total']>0);foreach($feed['items'] as $item){same($writer,(int)$item['author_id']);}});
test('pinning a missing comment returns not found',static function()use($a,$admin){reject(static function()use($a,$admin){$a->admin->pinComment($admin,2147483647,true);},404);});
test('points sales never generate money-denominated author earnings',static function()use($a,$reader,$writer){$a->wallet->adjust($reader,'points',100,'reader013-points','fixture');$p=product('digital','points','10');$a->db->update('cy_contents',$p,['author_id'=>$writer]);$o=$a->commerce->buy($reader,'content',$p,key32());same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_creator_earnings WHERE order_id=?',[(int)$o['id']]));});
test('refund while earnings withdrawal is held blocks manual paid confirmation',static function()use($a,$reader,$writer,$admin){
 $p=product('digital','balance','10.00');$a->db->update('cy_contents',$p,['author_id'=>$writer]);$o=$a->commerce->buy($reader,'content',$p,key32());$e=$a->db->one('SELECT * FROM cy_creator_earnings WHERE order_id=?',[(int)$o['id']]);$a->db->update('cy_creator_earnings',(int)$e['id'],['release_at'=>0]);$a->creator->settleOne($writer,(int)$e['id']);
 $amount=funds($writer,'earnings');$key=key32();$a->commerce->withdraw($writer,$amount,'fixture only',$key,'earnings');$w=(int)$a->db->value('SELECT id FROM cy_withdrawals WHERE request_key=?',[$writer.':'.$key]);
 $a->commerce->requestRefund($reader,(int)$o['id'],'Refund while held');$a->commerce->refund($admin,(int)$o['id'],true);
 reject(static function()use($a,$admin,$w){$a->commerce->reviewWithdrawal($admin,$w,true,'must not mark paid');},409);
 $a->commerce->reviewWithdrawal($admin,$w,false,'Cancel held withdrawal');same($amount-800,funds($writer,'earnings'));
});
test('history retention is bounded by configured count',static function()use($a,$reader,$admin){
 settings('users',['reading_history_limit'=>'20']);for($i=0;$i<24;$i++){$id=$a->content->save(account($admin),['kind'=>'article','title'=>'Retention '.$i,'body'=>'Original','status'=>'published'],true);$a->discovery->record(account($reader),$id,10);}
 same(20,(int)$a->db->value('SELECT COUNT(*) FROM cy_reading_history WHERE user_id=?',[$reader]));settings('users',['reading_history_limit'=>'200']);
});
test('restarting additive v5 preserves author ledger and history',static function()use($a){$count=(int)$a->db->value('SELECT COUNT(*) FROM cy_creator_earnings');$history=(int)$a->db->value('SELECT COUNT(*) FROM cy_reading_history');$a->db->execute('UPDATE cy_settings SET value=? WHERE name=?',['4','_schema_version']);\Chengyu\Core\Migrations::upgrade($a->db,$a->config['storage']);same(\Chengyu\Core\Migrations::VERSION,\Chengyu\Core\Migrations::version($a->db));same($count,(int)$a->db->value('SELECT COUNT(*) FROM cy_creator_earnings'));same($history,(int)$a->db->value('SELECT COUNT(*) FROM cy_reading_history'));});

test('physical creator revenue requires confirmed receipt even after hold expiry',static function()use($a,$reader,$writer,$admin){
 $p=product('physical','balance','10.00',1);$a->db->update('cy_contents',$p,['author_id'=>$writer]);
 $address=$a->db->insert('cy_addresses',['user_id'=>$reader,'recipient'=>'Test reader','phone'=>'000','address'=>'Isolated test address','created_at'=>time()]);
 $o=$a->commerce->buy($reader,'content',$p,key32(),'',$address);$e=$a->db->one('SELECT * FROM cy_creator_earnings WHERE order_id=?',[(int)$o['id']]);
 $a->db->update('cy_creator_earnings',(int)$e['id'],['release_at'=>0]);same(false,$a->creator->settleOne($writer,(int)$e['id']));
 $a->commerce->ship($admin,(int)$o['id'],'FIXTURE-NOT-A-REAL-SHIPMENT');same(false,$a->creator->settleOne($writer,(int)$e['id']));
 $a->commerce->receive($reader,(int)$o['id']);truth($a->creator->settleOne($writer,(int)$e['id']));
});
test('old revenue retains its rate and hold after author and global terms change',static function()use($a,$reader,$writer){
 $p=product('digital','balance','10.00');$a->db->update('cy_contents',$p,['author_id'=>$writer]);$o=$a->commerce->buy($reader,'content',$p,key32());
 $before=$a->db->one('SELECT * FROM cy_creator_earnings WHERE order_id=?',[(int)$o['id']]);
 settings('commerce',['creator_share_bps'=>'3000','creator_hold_days'=>'0']);$a->db->update('cy_users',$writer,['creator_bps'=>5000]);
 try{$after=$a->db->one('SELECT * FROM cy_creator_earnings WHERE order_id=?',[(int)$o['id']]);same($before,$after);same(800,(int)$after['share_amount']);}
 finally{settings('commerce',['creator_share_bps'=>'8000','creator_hold_days'=>'7']);$a->db->update('cy_users',$writer,['creator_bps'=>-1]);}
});
test('pending author income refund cancels liability without crediting earnings',static function()use($a,$reader,$writer,$admin){
 $p=product('digital','balance','10.00');$a->db->update('cy_contents',$p,['author_id'=>$writer]);$o=$a->commerce->buy($reader,'content',$p,key32());$balance=funds($writer,'earnings');
 $a->commerce->requestRefund($reader,(int)$o['id'],'Pending refund test');$a->commerce->refund($admin,(int)$o['id'],true);
 same($balance,funds($writer,'earnings'));same('reversed',$a->db->value('SELECT status FROM cy_creator_earnings WHERE order_id=?',[(int)$o['id']]));
});
test('free content orders create no creator income',static function()use($a,$reader,$writer){
 $p=product('digital','balance','0.00');$a->db->update('cy_contents',$p,['author_id'=>$writer]);$o=$a->commerce->buy($reader,'content',$p,key32());same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_creator_earnings WHERE order_id=?',[(int)$o['id']]));
});
