<?php
declare(strict_types=1);
// Included by run.php; every fixture lives in its disposable database.
use Chengyu\Core\{Input,Problem,Migrations,Markdown};
use Chengyu\Services\{Commerce,Media};
function fixtureUser(string $prefix='new'):int {global $a;$name=$prefix.substr(key32(),0,8);return $a->db->insert('cy_users',['username'=>$name,'email'=>$name.'@example.test','password_hash'=>'test-fixture','display_name'=>$name,'role'=>'user','status'=>'active','bio'=>'','created_at'=>time()]);}
function contentInput(int $id,array $changes=[]):array {global $a;$row=$a->db->one('SELECT * FROM cy_contents WHERE id=?',[$id]);$row['price']=$row['price_currency']==='balance'?\Chengyu\Services\Payment::decimal((int)$row['price_amount']):(int)$row['price_amount'];$row['publish_at']=$row['publish_at']?date('Y-m-d H:i:s',(int)$row['publish_at']):'';return array_merge($row,$changes);}
function fixtureVariant(int $product,string $name='Blue',int $stock=3,string $price='2.00'):int {global $a,$admin;return $a->inventory->save($admin,['content_id'=>$product,'sku'=>'SKU-'.key32(),'name'=>$name,'price'=>$price,'inventory'=>$stock,'active'=>'1']);}
$guestBuyer=fixtureUser('buyer');$a->wallet->adjust($guestBuyer,'balance',100000,'ext-funds:'.$guestBuyer,'Extension fixtures');
test('migration is additive, repeatable and versioned',static function()use($a,$config){$before=(int)$a->db->value('SELECT COUNT(*) FROM cy_orders');Migrations::upgrade($a->db,$config['storage']);Migrations::upgrade($a->db,$config['storage']);same(Migrations::VERSION,Migrations::version($a->db));same($before,(int)$a->db->value('SELECT COUNT(*) FROM cy_orders'));truth((bool)$a->db->one('SELECT name FROM cy_settings WHERE name=?',['_schema_version']));});
foreach(['public','login','reply','vip','password'] as $accessMode){test('direct zero-price purchase cannot unlock '.$accessMode,static function()use($a,$admin,$guestBuyer,$accessMode){$id=$a->content->save(account($admin),['kind'=>'article','title'=>'Gate test '.$accessMode,'body'=>'public','protected_body'=>'GATED','status'=>'published','access_level'=>$accessMode,'content_password'=>'secret-password'],true);$before=(int)$a->db->value('SELECT COUNT(*) FROM cy_orders');reject(static function()use($a,$guestBuyer,$id){$a->commerce->buy($guestBuyer,'content',$id,key32());},403);same($before,(int)$a->db->value('SELECT COUNT(*) FROM cy_orders'));});}
test('legacy zero-price order does not bypass VIP policy',static function()use($a,$admin,$guestBuyer){$id=$a->content->save(account($admin),['kind'=>'article','title'=>'Legacy zero order','body'=>'public','protected_body'=>'VIP','status'=>'published','access_level'=>'vip'],true);$row=Commerce::row($guestBuyer,'content',$id,'legacy',0,'balance',key32());$row['status']='paid';$a->db->insert('cy_orders',$row);same(false,$a->content->access($a->content->get($id),account($guestBuyer)));});
foreach([['bad'],"bad\0password"] as $bad){test('malformed password input is a controlled rejection '.gettype($bad),static function()use($bad){reject(static function()use($bad){Input::password($bad);});reject(static function()use($bad){Input::passwordValue($bad);});});}
test('password whitespace is preserved',static function(){same(' password1234 ',Input::passwordValue(' password1234 '));});
$pw=$a->content->save(account($admin),['kind'=>'article','title'=>'Password gate','body'=>'public','protected_body'=>'PW-PRIVATE','access_level'=>'password','content_password'=>' secret1234 ','status'=>'published'],true);
test('guest password access uses exact password',static function()use($a,$pw){same(false,$a->content->access($a->content->get($pw),null));reject(static function()use($a,$pw){$a->content->unlock($pw,'secret1234',null);},403);$a->content->unlock($pw,' secret1234 ',null);truth($a->content->access($a->content->get($pw),null));});
test('changing password revokes previous browser grant',static function()use($a,$admin,$pw){$a->content->save(account($admin),contentInput($pw,['content_password'=>'changed-secret']),true);same(false,$a->content->access($a->content->get($pw),null));});
test('bounded password sessions preserve content ID keys',static function()use($a,$pw){$_SESSION['content_unlock']=array_fill_keys(range(5000,5099),'grant');$a->content->unlock($pw,'changed-secret',null);same(100,count($_SESSION['content_unlock']));truth(isset($_SESSION['content_unlock'][5099]));truth(!isset($_SESSION['content_unlock'][0]));});
$exp=product('digital','balance','1.00');$a->content->save(account($admin),contentInput($exp,['access_days'=>1]),true);$expOrder=$a->commerce->buy($guestBuyer,'content',$exp,key32());
test('purchased access expiry is captured in the order',static function()use($expOrder){truth((int)$expOrder['access_until']>=time()+86390);});
test('expired purchase no longer authorizes protected body',static function()use($a,$guestBuyer,$exp,$expOrder){$a->db->update('cy_orders',(int)$expOrder['id'],['access_until'=>time()-1]);same(false,$a->content->access($a->content->get($exp),account($guestBuyer)));});
test('expired digital access can be purchased again',static function()use($a,$guestBuyer,$exp,$expOrder){$new=$a->commerce->buy($guestBuyer,'content',$exp,key32());truth((int)$new['id']!==(int)$expOrder['id']);truth($a->content->access($a->content->get($exp),account($guestBuyer)));});
$tierUser=fixtureUser('tier');
test('higher tier and lower tier have separate expiry dates',static function()use($a,$tierUser){$a->membership->grant($tierUser,3,2);$higher=(int)$a->db->value('SELECT until_at FROM cy_memberships WHERE user_id=? AND tier=3',[$tierUser]);$a->membership->grant($tierUser,1,100);same($higher,(int)$a->db->value('SELECT until_at FROM cy_memberships WHERE user_id=? AND tier=3',[$tierUser]));same(3,$a->membership->tier(account($tierUser)));$a->db->execute('UPDATE cy_memberships SET until_at=? WHERE user_id=? AND tier=3',[time()-1,$tierUser]);same(1,$a->membership->tier(account($tierUser)));});
test('tier 1 cannot open tier 2 content',static function()use($a,$admin,$tierUser){$id=$a->content->save(account($admin),['kind'=>'article','title'=>'Tier two','body'=>'public','protected_body'=>'private','status'=>'published','access_level'=>'vip','min_vip_tier'=>2],true);same(false,$a->content->access($a->content->get($id),account($tierUser)));$a->membership->grant($tierUser,2,1);truth($a->content->access($a->content->get($id),account($tierUser)));});
test('ordinary admin profile edit preserves all tier grants',static function()use($a,$admin,$tierUser){$before=$a->db->all('SELECT tier,until_at FROM cy_memberships WHERE user_id=? ORDER BY tier',[$tierUser]);$user=account($tierUser);$a->admin->user($admin,$tierUser,array_merge($user,['vip_tier'=>3,'vip_until'=>date('Y-m-d H:i',time()+300*86400)]));same($before,$a->db->all('SELECT tier,until_at FROM cy_memberships WHERE user_id=? ORDER BY tier',[$tierUser]));});
test('explicit administrator replacement can revoke memberships',static function()use($a,$admin,$tierUser){$a->admin->user($admin,$tierUser,array_merge(account($tierUser),['replace_membership'=>1,'vip_until'=>'','vip_tier'=>1]));same(0,$a->membership->tier(account($tierUser)));});
$skup=product('physical','balance','1.00',20);$sku=fixtureVariant($skup);$sku2=fixtureVariant($skup,'Red',2,'3.00');$skuAddress=$a->db->insert('cy_addresses',['user_id'=>$guestBuyer,'recipient'=>'Fixture','phone'=>'000','address'=>'Test shipping address','created_at'=>time()]);
test('variant stock aggregation replaces base inventory',static function()use($a,$skup){same(5,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$skup]));});
test('variant selection is required for direct purchase',static function()use($a,$guestBuyer,$skup,$skuAddress){reject(static function()use($a,$guestBuyer,$skup,$skuAddress){$a->commerce->buy($guestBuyer,'content',$skup,key32(),'',$skuAddress);});});
$skuOrder=$a->commerce->buy($guestBuyer,'content',$skup,key32(),'',$skuAddress,$sku);
test('variant price, allocation and metadata use server values',static function()use($a,$skuOrder,$sku,$skup){same(200,(int)$skuOrder['amount']);same($sku,(int)$skuOrder['variant_id']);same(2,(int)$a->db->value('SELECT inventory FROM cy_variants WHERE id=?',[$sku]));same(4,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$skup]));truth(strpos($skuOrder['title'],'Blue')!==false);});
test('unshipped variant refund restores only its own stock',static function()use($a,$admin,$guestBuyer,$skuOrder,$sku,$sku2){$other=(int)$a->db->value('SELECT inventory FROM cy_variants WHERE id=?',[$sku2]);$a->commerce->requestRefund($guestBuyer,(int)$skuOrder['id'],'return');$a->commerce->refund($admin,(int)$skuOrder['id'],true);same(3,(int)$a->db->value('SELECT inventory FROM cy_variants WHERE id=?',[$sku]));same($other,(int)$a->db->value('SELECT inventory FROM cy_variants WHERE id=?',[$sku2]));});
test('variant cannot be moved to a different product',static function()use($a,$admin,$sku){$new=product('physical');reject(static function()use($a,$admin,$new,$sku){$a->inventory->save($admin,['id'=>$sku,'content_id'=>$new,'sku'=>'moved','name'=>'moved','price'=>'2.00','active'=>1]);},404);});
test('foreign product variant rejected',static function()use($a,$guestBuyer,$sku,$skuAddress){$other=product('physical');reject(static function()use($a,$guestBuyer,$sku,$skuAddress,$other){$a->commerce->buy($guestBuyer,'content',$other,key32(),'',$skuAddress,$sku);});});
test('variant pricing asset cannot silently change',static function()use($a,$admin,$skup){reject(static function()use($a,$admin,$skup){$a->content->save(account($admin),contentInput($skup,['price_currency'=>'points','price'=>10]),true);});});
$codeSkuProduct=product('code');$codeSku=fixtureVariant($codeSkuProduct,'License',999,'1.00');
test('code variants ignore forged inventory quantities',static function()use($a,$codeSku){same(0,(int)$a->db->value('SELECT inventory FROM cy_variants WHERE id=?',[$codeSku]));});
test('code variant import synchronizes stock and preserves zero code',static function()use($a,$admin,$codeSkuProduct,$codeSku){same(2,$a->commerce->importStock($admin,$codeSkuProduct,"0\nVARIANT-SECRET",$codeSku));same(2,(int)$a->db->value('SELECT inventory FROM cy_contents WHERE id=?',[$codeSkuProduct]));});
test('code variant purchase consumes one matching secret',static function()use($a,$guestBuyer,$codeSkuProduct,$codeSku){$order=$a->commerce->buy($guestBuyer,'content',$codeSkuProduct,key32(),'',0,$codeSku);truth(strpos($a->commerce->delivery($order),'0')===0);same(1,(int)$a->db->value('SELECT inventory FROM cy_variants WHERE id=?',[$codeSku]));});
test('unassigned base codes prevent ambiguous variant conversion',static function()use($a,$admin){$id=product('code');$a->commerce->importStock($admin,$id,'BASE-CODE');reject(static function()use($id){fixtureVariant($id);});});
$checkoutIntent=key32();$checkoutLines=[['item_id'=>$skup,'variant_id'=>$sku,'quantity'=>2],['item_id'=>$skup,'variant_id'=>$sku2,'quantity'=>1]];
$checkoutOrders=$a->commerce->checkout($guestBuyer,$checkoutLines,$checkoutIntent,$skuAddress);
test('multi-variant checkout consumes exact per-unit quantities',static function()use($a,$checkoutOrders,$sku,$sku2){same(3,count($checkoutOrders));same(1,(int)$a->db->value('SELECT inventory FROM cy_variants WHERE id=?',[$sku]));same(1,(int)$a->db->value('SELECT inventory FROM cy_variants WHERE id=?',[$sku2]));});
test('checkout replay returns the same order IDs without debit',static function()use($a,$guestBuyer,$checkoutLines,$checkoutIntent,$skuAddress,$checkoutOrders){$balance=funds($guestBuyer);same($checkoutOrders,$a->commerce->checkout($guestBuyer,$checkoutLines,$checkoutIntent,$skuAddress));same($balance,funds($guestBuyer));});
test('checkout intent cannot be reused with changed quantity',static function()use($a,$guestBuyer,$checkoutLines,$checkoutIntent,$skuAddress){$lines=$checkoutLines;$lines[0]['quantity']=1;reject(static function()use($a,$guestBuyer,$lines,$checkoutIntent,$skuAddress){$a->commerce->checkout($guestBuyer,$lines,$checkoutIntent,$skuAddress);},409);});
test('checkout stock failure rolls back orders ledger and earlier unit',static function()use($a,$guestBuyer,$skup,$sku,$skuAddress){$before=funds($guestBuyer);$orders=(int)$a->db->value('SELECT COUNT(*) FROM cy_orders');reject(static function()use($a,$guestBuyer,$skup,$sku,$skuAddress){$a->commerce->checkout($guestBuyer,[['item_id'=>$skup,'variant_id'=>$sku,'quantity'=>2]],key32(),$skuAddress);});same($before,funds($guestBuyer));same($orders,(int)$a->db->value('SELECT COUNT(*) FROM cy_orders'));same(1,(int)$a->db->value('SELECT inventory FROM cy_variants WHERE id=?',[$sku]));});
test('digital access quantity cannot cause duplicate charges',static function()use($a,$guestBuyer){$id=product();reject(static function()use($a,$guestBuyer,$id){$a->commerce->checkout($guestBuyer,[['item_id'=>$id,'quantity'=>2]],key32());});});
test('shipment can be corrected and owner can confirm receipt',static function()use($a,$admin,$guestBuyer,$checkoutOrders){$id=$checkoutOrders[0];reject(static function()use($a,$guestBuyer,$id){$a->commerce->receive($guestBuyer,$id);});$a->commerce->ship($admin,$id,'TRACK-OLD');$a->commerce->ship($admin,$id,'TRACK-CORRECTED');$a->commerce->receive($guestBuyer,$id);$a->commerce->receive($guestBuyer,$id);same('received',$a->db->value('SELECT fulfillment FROM cy_orders WHERE id=?',[$id]));});
test('withdrawn referral commission does not block buyer refund',static function()use($a,$admin){$ref=fixtureUser('ref');$buyer=fixtureUser('refbuy');$a->db->update('cy_users',$buyer,['referred_by'=>$ref]);$a->wallet->adjust($buyer,'balance',10000,'refund-funds:'.$buyer,'fixture');$product=product('digital','balance','50.00');$order=$a->commerce->buy($buyer,'content',$product,key32());$earned=funds($ref,'commission');truth($earned>0);$a->wallet->adjust($ref,'commission',-$earned,'payout-simulated:'.$ref,'Simulated reserved payout');$a->commerce->requestRefund($buyer,(int)$order['id'],'refund');$a->commerce->refund($admin,(int)$order['id'],true);same(10000,funds($buyer));same(-$earned,funds($ref,'commission'));$a->wallet->adjust($ref,'commission',1,'debt-repayment:'.$ref,'Offset commission debt');same(1-$earned,funds($ref,'commission'));});
test('revision saves old text and rejects stale editor version',static function()use($a,$admin,$pw){$before=contentInput($pw);$a->content->save(account($admin),array_merge($before,['body'=>'CHANGED BODY']),true);reject(static function()use($a,$admin,$before){$a->content->save(account($admin),$before,true);},409);$snapshot=json_decode($a->db->value('SELECT snapshot FROM cy_revisions WHERE content_id=? ORDER BY id DESC LIMIT 1',[$pw]),true);same($before['body'],$snapshot['body']);});
test('revision restore does not roll back current pricing',static function()use($a,$admin,$pw){$revision=(int)$a->db->value('SELECT id FROM cy_revisions WHERE content_id=? ORDER BY id DESC LIMIT 1',[$pw]);$a->content->save(account($admin),contentInput($pw,['price'=>'7.50']),true);$a->content->restore(account($admin),$pw,$revision);same(750,(int)$a->db->value('SELECT price_amount FROM cy_contents WHERE id=?',[$pw]));same('public',$a->db->value('SELECT body FROM cy_contents WHERE id=?',[$pw]));});
test('revision cannot be restored to another content item',static function()use($a,$admin,$pw,$exp){$revision=(int)$a->db->value('SELECT id FROM cy_revisions WHERE content_id=? ORDER BY id DESC LIMIT 1',[$pw]);reject(static function()use($a,$admin,$exp,$revision){$a->content->restore(account($admin),$exp,$revision);},404);});
$layout=['format'=>'chengyu-layout','version'=>1,'blocks'=>[['id'=>'intro','type'=>'heading','title'=>'<script>evil()</script>','text'=>'[bad](javascript:alert(1))','unknown_secret'=>'not-retained']]];
test('layout validation strips unknown fields and uses safe choices',static function()use($a,$layout){$valid=$a->layout->validate(json_encode($layout));same(false,isset($valid['blocks'][0]['unknown_secret']));same(false,strpos(Markdown::render($valid['blocks'][0]['text']),'href="javascript:')!==false);});
test('layout saves with revision check and exports no unrelated settings',static function()use($a,$admin,$layout){same(1,$a->layout->save($admin,'home',json_encode($layout),0));$out=$a->layout->get('home');same(1,$out['revision']);truth(!isset($out['document']['epay_secret']));reject(static function()use($a,$admin,$layout){$a->layout->save($admin,'home',json_encode($layout),0);},409);});
foreach(['php','javascript','<script>'] as $badType){test('layout rejects executable/unknown block '.$badType,static function()use($a,$layout,$badType){$layout['blocks'][0]['type']=$badType;reject(static function()use($a,$layout){$a->layout->validate(json_encode($layout));});});}
test('layout rejects duplicate IDs and oversized block lists',static function()use($a,$layout){$layout['blocks'][]=$layout['blocks'][0];reject(static function()use($a,$layout){$a->layout->validate(json_encode($layout));});$layout['blocks']=array_fill(0,25,['id'=>'a','type'=>'text']);reject(static function()use($a,$layout){$a->layout->validate(json_encode($layout));});});
test('layout rejects external/script destinations',static function()use($a,$layout){$layout['blocks'][0]['route']='javascript:alert(1)';reject(static function()use($a,$layout){$a->layout->validate(json_encode($layout));});});
$collectionId=$a->catalog->save($admin,'collections',['name'=>'Curated fixtures','description'=>'safe','content_ids'=>'1,2,1','active'=>1]);
test('collection deduplicates IDs and preserves editorial order',static function()use($a,$collectionId){same(2,(int)$a->db->value('SELECT COUNT(*) FROM cy_collection_items WHERE collection_id=?',[$collectionId]));$feed=$a->content->feed('all',null,['collection'=>$collectionId]);same([1,2],array_map('intval',array_column($feed['items'],'id')));});
test('invalid collection update rolls back previous membership',static function()use($a,$admin,$collectionId){reject(static function()use($a,$admin,$collectionId){$a->catalog->save($admin,'collections',['id'=>$collectionId,'name'=>'bad','content_ids'=>'1,999999','active'=>1]);});same(2,(int)$a->db->value('SELECT COUNT(*) FROM cy_collection_items WHERE collection_id=?',[$collectionId]));});
test('link directory blocks script and credential URLs',static function()use($a,$admin){foreach(['javascript:alert(1)','https://user:pass@example.test/'] as $url){reject(static function()use($a,$admin,$url){$a->catalog->save($admin,'links',['name'=>'bad','url'=>$url,'active'=>1]);});}});
test('announcements honor audience and scheduled start',static function()use($a,$admin,$guestBuyer){$a->catalog->save($admin,'announcements',['name'=>'VIP NOTICE','audience'=>'vip','active'=>1]);$a->catalog->save($admin,'announcements',['name'=>'FUTURE NOTICE','starts_at'=>date('Y-m-d H:i',time()+86400),'active'=>1]);$names=array_column($a->catalog->visibleAnnouncements(account($guestBuyer)),'name');truth(!in_array('VIP NOTICE',$names,true));truth(!in_array('FUTURE NOTICE',$names,true));});
$taskId=$a->tasks->save($admin,['name'=>'Profile task','metric'=>'profile','period'=>'once','target_count'=>1,'reward_points'=>13,'reward_xp'=>7,'active'=>1]);
test('task requires server-verified progress',static function()use($a,$guestBuyer,$taskId){reject(static function()use($a,$guestBuyer,$taskId){$a->tasks->claim($guestBuyer,$taskId);});});
test('task claim is idempotent and credits points plus experience',static function()use($a,$guestBuyer,$taskId){$a->db->update('cy_users',$guestBuyer,['bio'=>'A complete profile']);$before=funds($guestBuyer,'points');$xp=(int)account($guestBuyer)['experience'];$a->tasks->claim($guestBuyer,$taskId);$a->tasks->claim($guestBuyer,$taskId);same($before+13,funds($guestBuyer,'points'));same($xp+7,(int)account($guestBuyer)['experience']);});
test('claimed task reward rules cannot be silently changed',static function()use($a,$admin,$taskId){$task=$a->db->one('SELECT * FROM cy_tasks WHERE id=?',[$taskId]);$task['reward_points']=999;reject(static function()use($a,$admin,$task){$a->tasks->save($admin,$task);});});
test('daily profile reward farming is rejected',static function()use($a,$admin){reject(static function()use($a,$admin){$a->tasks->save($admin,['name'=>'bad','metric'=>'profile','period'=>'daily','active'=>1]);});});
test('pending comments do not qualify for task rewards',static function()use($a,$admin,$guestBuyer){$id=$a->tasks->save($admin,['name'=>'Comments','metric'=>'comments','period'=>'daily','target_count'=>1,'reward_points'=>5,'active'=>1]);$comment=$a->db->insert('cy_comments',['content_id'=>1,'user_id'=>$guestBuyer,'parent_id'=>0,'body'=>'pending','status'=>'pending','created_at'=>time()]);reject(static function()use($a,$guestBuyer,$id){$a->tasks->claim($guestBuyer,$id);});$a->db->update('cy_comments',$comment,['status'=>'approved']);$a->tasks->claim($guestBuyer,$id);truth((bool)$a->db->one('SELECT id FROM cy_task_claims WHERE task_id=? AND user_id=?',[$id,$guestBuyer]));});
test('task module disable blocks claim endpoint',static function()use($a,$guestBuyer,$taskId){settings('modules',['tasks_enabled'=>'0']);reject(static function()use($a,$guestBuyer,$taskId){$a->tasks->claim($guestBuyer,$taskId);},403);settings('modules',['tasks_enabled'=>'1']);});
settings('security',['register_limit'=>20]);settings('users',['registration_mode'=>'invite']);
$invite=$a->invitations->issue($admin,1,1,time()+86400,'test invite')[0];
test('invitation plaintext is never stored',static function()use($a,$invite){$row=$a->db->one('SELECT * FROM cy_invitations ORDER BY id DESC LIMIT 1');truth(strpos(json_encode($row),$invite)===false);});
test('registration requires a valid invitation when configured',static function()use($a){$before=(int)$a->db->value('SELECT COUNT(*) FROM cy_users');reject(static function()use($a){$a->auth->register(['username'=>'invitebad','email'=>'invitebad@example.test','password'=>'PasswordTest123']);});same($before,(int)$a->db->value('SELECT COUNT(*) FROM cy_users'));});
test('invitation is consumed once with new account transaction',static function()use($a,$invite){$id=$a->auth->register(['username'=>'invitedok','email'=>'invitedok@example.test','password'=>'PasswordTest123','invitation'=>$invite]);truth($id>0);same(1,(int)$a->db->value('SELECT uses FROM cy_invitations ORDER BY id DESC LIMIT 1'));reject(static function()use($a,$invite){$a->auth->register(['username'=>'invitedagain','email'=>'invitedagain@example.test','password'=>'PasswordTest123','invitation'=>$invite]);});});
test('failed registration never spends invitation allowance',static function()use($a,$admin){$code=$a->invitations->issue($admin,1,2,time()+86400,'rollback invite')[0];reject(static function()use($a,$code){$a->auth->register(['username'=>'invitedok','email'=>'duplicate@example.test','password'=>'PasswordTest123','invitation'=>$code]);});same(0,(int)$a->db->value('SELECT uses FROM cy_invitations ORDER BY id DESC LIMIT 1'));});
test('disabled invitation is rejected',static function()use($a,$admin){$code=$a->invitations->issue($admin,1,1,time()+86400,'disabled')[0];$id=(int)$a->db->value('SELECT id FROM cy_invitations ORDER BY id DESC LIMIT 1');$a->invitations->disable($admin,$id);reject(static function()use($a,$code){$a->invitations->consume($code);});});
settings('users',['registration_mode'=>'open']);
function fixtureMedia(int $owner):int {global $a;return $a->db->insert('cy_media',['owner_id'=>$owner,'name'=>'file.txt','mime'=>'text/plain','bytes'=>20,'file_key'=>bin2hex(random_bytes(24)).'.php','is_private'=>1,'created_at'=>time()]);}
$dm1=fixtureMedia($admin);$dm2=fixtureMedia($admin);
foreach([$dm1,$dm2] as $id){$a->content->save(account($admin),['kind'=>'article','title'=>'Download fixture '.$id,'body'=>'public','status'=>'published','access_level'=>'login','resource_id'=>$id],true);}
test('download counts authorized unique files rather than range retries',static function()use($a,$guestBuyer,$dm1){settings('security',['download_daily_limit'=>1]);$a->media->recordDownload($dm1,account($guestBuyer));$a->media->recordDownload($dm1,account($guestBuyer));same(1,(int)$a->db->value('SELECT COUNT(*) FROM cy_downloads WHERE user_id=?',[$guestBuyer]));});
test('daily download quota rejects another file without recording it',static function()use($a,$guestBuyer,$dm2){reject(static function()use($a,$guestBuyer,$dm2){$a->media->recordDownload($dm2,account($guestBuyer));},429);same(1,(int)$a->db->value('SELECT COUNT(*) FROM cy_downloads WHERE user_id=?',[$guestBuyer]));});
test('unauthorized file access is not recorded',static function()use($a,$admin,$guestBuyer){$id=fixtureMedia($admin);reject(static function()use($a,$id,$guestBuyer){$a->media->recordDownload($id,account($guestBuyer));},403);same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_downloads WHERE media_id=?',[$id]));});
test('byte-range parser supports whole suffix and open-ended ranges',static function(){same([0,19,false],Media::range('',20));same([15,19,true],Media::range('bytes=-5',20));same([10,19,true],Media::range('bytes=10-',20));same([0,3,true],Media::range('bytes=0-3',20));});
foreach(['bytes=20-','bytes=9-2','bytes=0-1,3-4','bytes=-0'] as $range){test('invalid range rejected '.$range,static function()use($range){reject(static function()use($range){Media::range($range,20);},416);});}
settings('security',['download_daily_limit'=>0]);
test('comment visibility rejects unauthorized readers and writers',static function()use($a,$guestBuyer){settings('community',['comment_visibility'=>'verified']);same(false,$a->content->commentsVisible(account($guestBuyer)));same(false,$a->content->commentsVisible(null));reject(static function()use($a,$guestBuyer){$a->content->comment(account($guestBuyer),1,'blocked');},403);settings('community',['comment_visibility'=>'public']);});

test('long SKU order labels fit the MySQL title column',static function()use($a,$admin,$guestBuyer,$skuAddress){$id=product('physical');$a->content->save(account($admin),contentInput($id,['title'=>str_repeat('A',255)]),true);$variant=fixtureVariant($id,str_repeat('B',100),1,'1.00');$o=$a->commerce->buy($guestBuyer,'content',$id,key32(),'',$skuAddress,$variant);truth(strlen($o['title'])<=255);});
test('catalog shows actual minimum available variant price',static function()use($a,$skup){$item=$a->content->get($skup);same(2,(int)$item['variant_count']);same(200,(int)$item['variant_min_price']);});
test('UTF-8 body and revision can exceed 64 KB without being shortened',static function()use($a,$admin){$body=str_repeat("\xe4\xb8\xad",30000);$id=$a->content->save(account($admin),['kind'=>'article','title'=>'Long UTF-8 body','body'=>$body,'status'=>'draft'],true);$a->content->save(account($admin),contentInput($id,['body'=>$body.' revised']),true);$revision=$a->db->one('SELECT snapshot FROM cy_revisions WHERE content_id=?',[$id]);same($body,json_decode($revision['snapshot'],true)['body']);});
// Separate processes contend for the same SKU; each customer has its own wallet and address.
test('eight concurrent SKU purchases settle exactly one unit',static function()use($a,$config,$tmp){
    $pid=product('physical');$variant=fixtureVariant($pid,'One item',1,'1.00');$jobs=[];
    file_put_contents($tmp.'/config.json',json_encode($config));
    for($i=0;$i<8;$i++){$buyer=fixtureUser('sku_race');$a->wallet->adjust($buyer,'balance',1000,'sku-race:'.$buyer,'Concurrency fixture');$address=$a->db->insert('cy_addresses',['user_id'=>$buyer,'recipient'=>'Fixture','phone'=>'000','address'=>'Fixture','created_at'=>time()]);$p=proc_open([PHP_BINARY,'-d','ffi.enable=1',__DIR__.'/sku_worker.php',$tmp.'/config.json',(string)$buyer,(string)$pid,(string)$variant,(string)$address],[1=>['pipe','w'],2=>['pipe','w']],$pipes);$jobs[]=[$p,$pipes,$buyer];}
    $paid=0;$declined=0;foreach($jobs as [$process,$pipes,$buyer]){$output=trim(stream_get_contents($pipes[1]));$error=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);if(proc_close($process)!==0){throw new RuntimeException($error);}if($output==='paid'){$paid++;same(900,funds($buyer));}elseif($output==='declined'){$declined++;same(1000,funds($buyer));}else{throw new RuntimeException($output);}}
    same(1,$paid);same(7,$declined);same(0,(int)$a->db->value('SELECT inventory FROM cy_variants WHERE id=?',[$variant]));same(1,(int)$a->db->value('SELECT COUNT(*) FROM cy_orders WHERE item_id=?',[$pid]));
});
