"""0.13 real local HTTP: author approval, accounting, reading privacy and search."""
for tab in ['creators']:
    response=admin.get(base+'/admin/index.php',params={'tab':tab});check('0.13 admin '+tab,response.status_code==200,response.text[-300:])
    check('creator finance screen denies normal users',user.get(base+'/admin/index.php?tab='+tab).status_code==403)
for asset in ['discovery.css','discovery.js','feedback.js']:
    r=guest.get(base+'/assets/'+asset);check('0.13 asset '+asset,r.status_code==200 and len(r.content)>500)
for route in ['history','following']:
    check('0.13 authenticated '+route,user.get(base+'/index.php?r='+route).status_code==200)
    check('0.13 anonymous '+route+' requires login','r=login' in guest.get(base+'/index.php?r='+route).url)
check('creator route starts disabled',user.get(base+'/index.php?r=creator').status_code==403)
save_group('commerce',creator_income_enabled='1',creator_share_bps='8000',creator_hold_days='0',creator_balance_conversion='1',withdrawals_enabled='1',withdraw_min='100')
# Approve the author through the real admin form and retain the verified current email.
person=db_one('SELECT * FROM cy_users WHERE id=?',(uid,))
expect_post(admin,'admin_user',id=uid,email=person['email'],display_name=person['display_name'],role=person['role'],status='active',creator_enabled='1',creator_bps='-1')
check('author approval persisted',db_one('SELECT creator_enabled FROM cy_users WHERE id=?',(uid,))['creator_enabled']==1)
check('creator dashboard completes with HTTP 200',user.get(base+'/index.php?r=creator').status_code==200)
creator=html(user,'/index.php?r=creator');check('creator center renders settlement and conversion controls',bool(creator.select('input[name=action][value=creator_settle]')) and bool(creator.select('input[name=action][value=creator_convert]')))
editor=html(user,'/index.php?r=write');check('approved author sees paid visibility and price input',bool(editor.select('select[name=access_level] option[value=paid]')) and bool(editor.select('input[name=price]')))
r=expect_post(user,'content_save',kind='article',title='HTTP original creator article',body='CREATOR-PUBLIC-INTRO',protected_body='CREATOR-PAID-BODY',status='published',access_level='paid',price='10.00',price_currency='balance',comment_enabled='1')
created=int(parse_qs(urlparse(r.json()['redirect']).query)['id'][0]);entry=db_one('SELECT * FROM cy_contents WHERE id=?',(created,))
check('paid author submission awaits moderation',entry['status']=='pending' and entry['price_amount']==1000)
expect_post(admin,'admin_content',id=created,kind='article',title=entry['title'],body=entry['body'],protected_body=entry['protected_body'],status='published',access_level='paid',price='10.00',price_currency='balance',creator_pricing='1')
buyer=db_one("SELECT id FROM cy_users WHERE username='bob'")['id']
expect_post(admin,'admin_wallet',user_id=buyer,currency='balance',delta='100',reason='Isolated author purchase fixture',intent=os.urandom(16).hex(),current_password='TestPassword!2026')
check('unpaid buyer never receives creator protected body','CREATOR-PAID-BODY' not in other.get(base+f'/index.php?r=article&id={created}').text)
intent=os.urandom(16).hex();expect_post(other,'buy',kind='content',item_id=created,intent=intent);expect_post(other,'buy',kind='content',item_id=created,intent=intent)
order=db_one("SELECT * FROM cy_orders WHERE user_id=? AND item_id=? AND kind='content' ORDER BY id DESC",(buyer,created));income=db_one('SELECT * FROM cy_creator_earnings WHERE order_id=?',(order['id'],))
check('creator HTTP purchase makes exactly one income record',bool(income) and db_one('SELECT COUNT(*) n FROM cy_creator_earnings WHERE order_id=?',(order['id'],))['n']==1)
check('paid creator body visible only after entitlement','CREATOR-PAID-BODY' in other.get(base+f'/index.php?r=article&id={created}').text)
expect_post(user,'creator_settle');expect_post(user,'creator_settle')
check('real HTTP settlement credits once',db_one('SELECT earnings FROM cy_users WHERE id=?',(uid,))['earnings']==income['share_amount'])
key=os.urandom(16).hex();expect_post(user,'creator_convert',amount='2.00',intent=key,current_password='TestPassword!2026');expect_post(user,'creator_convert',amount='2.00',intent=key,current_password='TestPassword!2026')
check('conversion credits and debits exactly once',db_one('SELECT earnings FROM cy_users WHERE id=?',(uid,))['earnings']==income['share_amount']-200)
expect_post(user,'creator_convert',403,amount='1.00',intent=os.urandom(16).hex(),current_password='WrongPassword!2026')
expect_post(user,'withdraw',amount='1.00',currency='earnings',account='HTTP payout recipient',intent=os.urandom(16).hex(),current_password='TestPassword!2026')
withdrawal=db_one("SELECT id FROM cy_withdrawals WHERE user_id=? AND currency='earnings' ORDER BY id DESC",(uid,))['id']
expect_post(admin,'admin_withdrawal',id=withdrawal,decision='reject',note='Not transferred',current_password='TestPassword!2026')
expect_post(other,'refund',order_id=order['id'],reason='Creator HTTP refund')
expect_post(admin,'admin_refund',id=order['id'],decision='approve',current_password='TestPassword!2026')
check('HTTP refund reverses earnings after conversion',db_one('SELECT earnings FROM cy_users WHERE id=?',(uid,))['earnings']==-200)
expect_post(user,'withdraw',400,amount='1.00',currency='earnings',account='Should not pay',intent=os.urandom(16).hex(),current_password='TestPassword!2026')
# No GET writes and no private text in the suggestions endpoint.
expect_post(user,'history_record',content_id=1,progress=41);expect_post(user,'history_record',content_id=1,progress=10)
check('history progress never moves backwards',db_one('SELECT progress FROM cy_reading_history WHERE user_id=? AND content_id=1',(uid,))['progress']==41)
history=html(user,'/index.php?r=history');check('history page displays real persisted progress',bool(history.select('progress[value="41"]')))
check('another reader does not inherit history',not html(other,'/index.php?r=history').select('progress[value="41"]'))
expect_post(other,'history_record',403,content_id=created,progress=1)
expect_post(user,'history_preference',enabled='0');expect_post(user,'history_record',content_id=1,progress=100)
check('history opt-out removes and blocks records',db_one('SELECT COUNT(*) n FROM cy_reading_history WHERE user_id=?',(uid,))['n']==0)
expect_post(user,'history_preference',enabled='1')
expect_post(user,'history_record',400,content_id=1,progress=101)
expect_post(guest,'history_record',401,content_id=1,progress=10)
r=guest.get(base+'/index.php?r=suggest',params={'q':'HTTP original creator'});payload=r.json();check('real suggestion API returns title not paid body',r.status_code==200 and payload['items'] and 'CREATOR-PAID-BODY' not in r.text and all(set(x)=={'id','kind','title','url'} for x in payload['items']))
check('suggestions use private no-store caching','no-store' in r.headers.get('Cache-Control',''))
check('protected text is not indexed',guest.get(base+'/index.php?r=suggest',params={'q':'CREATOR-PAID-BODY'}).json()['items']==[])
check('restricted category absent from suggestions',guest.get(base+'/index.php?r=suggest',params={'q':'PRIVATE-CIRCLE-TITLE'}).json()['items']==[])
save_group('modules',search_suggestions_enabled='0')
check('disabled suggestions reject direct endpoint',guest.get(base+'/index.php?r=suggest&q=HTTP').status_code==403)
check('standard search works with suggestions disabled',guest.get(base+'/index.php?r=search&q=HTTP').status_code==200)
save_group('modules',search_suggestions_enabled='1')
save_group('appearance',motion_navigation='0',motion_feedback='1',motion_images='0')
config=json.loads(html(guest).html['data-motion-settings']);check('new motion switches persist and reach runtime',config['motion_navigation'] is False and config['motion_feedback'] is True and config['motion_images'] is False)
expect_post(admin,'admin_comment_pin',404,id=2147483647,pinned='1')
