"""0.12 real local HTTP contract, permission, transaction and form regressions."""
for tab in ['circles','bounties','reviews']:
    response=admin.get(base+'/admin/index.php',params={'tab':tab});check('0.12 admin '+tab,response.status_code==200,response.text[-200:])
    response=user.get(base+'/admin/index.php',params={'tab':tab});check('0.12 admin denies ordinary user '+tab,response.status_code==403)
for asset in ['spring.js','interactions.js','interactions.css','community.css']:
    response=guest.get(base+'/assets/'+asset);check('0.12 asset '+asset,response.status_code==200 and len(response.content)>500)
save_group('community',circles_enabled='1',bounties_enabled='1',bounty_max='1000')
save_group('commerce',reviews_enabled='1',reviews_review='1',invitation_products_enabled='1')
for target in [uid,1]:expect_post(admin,'admin_wallet',user_id=target,currency='points',delta='500',reason='Isolated 0.12 HTTP fixture',intent=os.urandom(16).hex(),current_password='TestPassword!2026')
expect_post(admin,'admin_entity',entity='categories',name='HTTP restricted circle',kind='thread',is_circle='1',access_level='members',post_level='members',join_currency='points',join_price='40',join_days='7',join_open='1')
circle=db_one('SELECT id FROM cy_categories WHERE name=?',('HTTP restricted circle',))['id']
private_post=create_content(kind='thread',category_id=circle,title='PRIVATE-CIRCLE-TITLE',body='PRIVATE-CIRCLE-BODY')
check('circle directory is available',guest.get(base+'/index.php?r=circles').status_code==200)
check('circle public introduction excludes restricted posts','PRIVATE-CIRCLE-TITLE' not in guest.get(base+f'/index.php?r=circle&id={circle}').text)
check('private circle direct URL denied',guest.get(base+f'/index.php?r=article&id={private_post}').status_code==403)
check('private circle search excludes title','PRIVATE-CIRCLE-TITLE' not in guest.get(base+'/index.php?r=search&q=PRIVATE-CIRCLE').text)
intent=os.urandom(16).hex();before=db_one('SELECT points FROM cy_users WHERE id=?',(uid,))['points']
expect_post(user,'buy',kind='circle',item_id=circle,intent=intent);expect_post(user,'buy',kind='circle',item_id=circle,intent=intent)
order=db_one("SELECT * FROM cy_orders WHERE user_id=? AND item_id=? AND kind='circle'",(uid,circle))
check('circle HTTP retries debit exactly once',db_one('SELECT points FROM cy_users WHERE id=?',(uid,))['points']==before-40)
check('joined circle exposes authorized body','PRIVATE-CIRCLE-BODY' in user.get(base+f'/index.php?r=article&id={private_post}').text)
expect_post(admin,'admin_circle_member',category_id=circle,user_id=uid,blocked='1')
check('manual suspension revokes direct access',user.get(base+f'/index.php?r=article&id={private_post}').status_code==403)
expect_post(admin,'admin_circle_member',category_id=circle,user_id=uid,blocked='0')
check('removing suspension restores paid term',user.get(base+f'/index.php?r=article&id={private_post}').status_code==200)
expect_post(user,'refund',order_id=order['id'],reason='HTTP circle refund')
expect_post(admin,'admin_refund',id=order['id'],decision='approve',current_password='TestPassword!2026')
check('refunded circle loses access',user.get(base+f'/index.php?r=article&id={private_post}').status_code==403)
check('circle refund returns original points',db_one('SELECT points FROM cy_users WHERE id=?',(uid,))['points']==before)
expect_post(admin,'admin_entity',404,entity='categories',id=999999,name='No phantom category',kind='thread')
multi=create_content(kind='thread',thread_mode='poll',title='HTTP multi choice',poll_question='Pick two',poll_options='First\nSecond\nThird',poll_max_choices='2',poll_results='after_vote')
choices=[r['id'] for r in conn.execute('SELECT id FROM cy_poll_options WHERE content_id=? ORDER BY id',(multi,))]
form=html(user,f'/index.php?r=article&id={multi}').select_one('.poll-form')
check('multiple selection uses real native checkboxes',len(form.select('input[type=checkbox][name="option_ids[]"]'))==3)
r=user.post(base+'/action.php',data={'csrf':csrf(user),'action':'poll_vote','content_id':multi,'option_ids[]':choices[:2]},headers={'Accept':'application/json'});check('PHP array ballot accepted through real HTTP',r.status_code==200,r.text)
r=user.post(base+'/action.php',data={'csrf':csrf(user),'action':'poll_vote','content_id':multi,'option_ids[]':list(reversed(choices[:2]))},headers={'Accept':'application/json'});check('reordered ballot retry remains idempotent',r.status_code==200,r.text)
check('one ballot and two choices stored',db_one('SELECT COUNT(*) n FROM cy_poll_votes WHERE content_id=?',(multi,))['n']==1 and db_one('SELECT COUNT(*) n FROM cy_poll_choices c JOIN cy_poll_votes v ON v.id=c.vote_id WHERE v.content_id=?',(multi,))['n']==2)
r=user.post(base+'/action.php',data={'csrf':csrf(user),'action':'poll_vote','content_id':multi,'option_ids[bad][nested]':'1'},headers={'Accept':'application/json'});check('nested ballot values rejected',r.status_code==400,r.text)
question=create_content(kind='thread',thread_mode='question',title='HTTP funded question')
expect_post(admin,'bounty_fund',content_id=question,amount='60',days='7');expect_post(admin,'bounty_fund',content_id=question,amount='60',days='7')
expect_post(user,'comment',content_id=question,body='A useful verified answer')
answer=db_one('SELECT id FROM cy_comments WHERE content_id=? ORDER BY id DESC',(question,))['id']
expect_post(admin,'answer_accept',400,content_id=question,comment_id=answer)
expect_post(admin,'admin_moderate',entity='comments',id=answer,status='approved')
old=db_one('SELECT points FROM cy_users WHERE id=?',(uid,))['points']
expect_post(admin,'answer_accept',content_id=question,comment_id=answer);expect_post(admin,'answer_accept',content_id=question,comment_id=answer)
check('accepted bounty pays answerer only once',db_one('SELECT points FROM cy_users WHERE id=?',(uid,))['points']==old+60)
check('awarded bounty rendered',db_one('SELECT status FROM cy_bounties WHERE content_id=?',(question,))['status']=='awarded' and bool(html(user,f'/index.php?r=article&id={question}').select('.bounty-panel')))
expect_post(admin,'admin_bounty_release',409,content_id=question)
review_product=create_content(kind='product',product_type='digital',title='HTTP verified review',price='0')
expect_post(other,'review_save',403,content_id=review_product,rating='5',body='I did not purchase')
expect_post(user,'buy',kind='content',item_id=review_product,intent=os.urandom(16).hex())
expect_post(user,'review_save',content_id=review_product,rating='5',body='REVIEW-VISIBLE-ONLY-AFTER-APPROVAL')
review=db_one('SELECT id FROM cy_reviews WHERE content_id=?',(review_product,))['id']
check('pending purchase review hidden from public','REVIEW-VISIBLE-ONLY-AFTER-APPROVAL' not in guest.get(base+f'/index.php?r=product&id={review_product}').text)
expect_post(user,'admin_review',403,id=review,status='approved')
expect_post(admin,'admin_review',id=review,status='approved')
check('approved purchase review published','REVIEW-VISIBLE-ONLY-AFTER-APPROVAL' in guest.get(base+f'/index.php?r=product&id={review_product}').text)
review_order=db_one("SELECT id FROM cy_orders WHERE item_id=? AND user_id=? AND kind='content'",(review_product,uid))['id']
expect_post(user,'refund',order_id=review_order,reason='HTTP rating removal');expect_post(admin,'admin_refund',id=review_order,decision='approve',current_password='TestPassword!2026')
check('refunded review disappears from public','REVIEW-VISIBLE-ONLY-AFTER-APPROVAL' not in guest.get(base+f'/index.php?r=product&id={review_product}').text)
invite_product=create_content(kind='product',product_type='invitation',title='HTTP invitation delivery',price='0',inventory='2',invite_uses='1',invite_days='7')
expect_post(user,'buy',kind='content',item_id=invite_product,intent=os.urandom(16).hex())
invite_order=db_one("SELECT * FROM cy_orders WHERE item_id=? AND user_id=? AND kind='content'",(invite_product,uid));metadata=json.loads(invite_order['metadata'])
check('invitation product stores generated code metadata',bool(metadata['invitation_id']) and bool(invite_order['delivery_cipher']))
check('invitation code appears only in owners order history',bool(re.search(r'\b[A-F0-9]{24}\b',user.get(base+'/index.php?r=orders').text)))
expect_post(user,'refund',order_id=invite_order['id'],reason='Unused generated invite');expect_post(admin,'admin_refund',id=invite_order['id'],decision='approve',current_password='TestPassword!2026')
check('refunded invitation is revoked in storage',db_one('SELECT active FROM cy_invitations WHERE id=?',(metadata['invitation_id'],))['active']==0)
save_group('appearance',motion_response='spring',spring_stiffness='230',spring_damping='27',spring_mass='110',motion_disclosures='1')
rendered=json.loads(html(guest).html['data-motion-settings'])
check('spring controls render validated same frontend configuration',rendered['motion_response']=='spring' and rendered['spring_stiffness']==230 and rendered['spring_damping']==27 and rendered['spring_mass']==110)
check('native cross-document transition opt-in present','@view-transition{navigation:auto;}' in guest.get(base+'/').text)

# Isolated SQL fixtures exercise pagination beyond the first page; no real users are created.
fixture_hash=db_one('SELECT password_hash FROM cy_users WHERE id=1')['password_hash']
for number in range(50):
    username='pager012_'+str(number)
    cursor=conn.execute('INSERT INTO cy_users(username,email,password_hash,display_name,bio,created_at) VALUES (?,?,?,?,?,?)',(username,username+'@example.test',fixture_hash,username,'',int(time.time())))
    conn.execute('INSERT INTO cy_circle_members(category_id,user_id,granted_until,blocked,updated_at) VALUES (?,?,?,?,?)',(circle,cursor.lastrowid,int(time.time())+86400,0,int(time.time())+100+number))
conn.commit()
page1=html(admin,f'/admin/index.php?tab=circles&category_id={circle}')
link=page1.select_one('a[href*="member_page=2"]')
check('manual member listing exposes next page after fifty rows',bool(link))
check('manual member pagination preserves selected circle',bool(link) and f'category_id={circle}' in link['href'])
page2=html(admin,f'/admin/index.php?tab=circles&category_id={circle}&member_page=2')
check('second manual member page contains remaining row',len(page2.select('section.panel.section tbody tr'))==1)
