"""New editorial routes exercised through the production action controller and real forms."""
save_group('modules',bulletins_enabled='1')
for url21 in ['/index.php?r=bulletins','/admin/index.php?tab=bulletins','/admin/index.php?tab=settings&group=editorial']:
    response21=admin.get(base+url21)
    check('021 editorial route '+url21,response21.status_code==200,response21.text[:180])
def bulletin_input21(title='HTTP-BULLETIN-021'):
    return dict(title=title,body='Public bulletin <script>alert(1)</script>',publish_at='2025-03-01T10:00',status='published',request_key=secrets.token_hex(16),source_name='Source <b>21</b>',source_url='https://example.org/news')
in21=bulletin_input21()
expect_post(user,'bulletin_save',403,**in21)
created21=expect_post(admin,'bulletin_save',**in21)
bid21=int(parse_qs(urlparse(created21.json()['redirect']).query)['edit'][0])
again21=expect_post(admin,'bulletin_save',**in21)
check('021 bulletin retry returns same item',created21.json()['redirect']==again21.json()['redirect'])
expect_post(admin,'bulletin_save',409,**dict(in21,title='Conflicting bulletin'))
detail21=html(guest,'/index.php?r=bulletin&id='+str(bid21))
check('021 public bulletin title and plain text are rendered',detail21.h1.get_text()=='HTTP-BULLETIN-021' and '<script>alert(1)</script>' in detail21.get_text() and not detail21.select('.bulletin-body script'))
check('021 source is escaped and external link isolated',not detail21.select('.article-source b') and 'noopener' in detail21.select_one('.article-source a').get('rel',[]))
check('021 bulletin canonical has exact item ID','id='+str(bid21) in detail21.select_one('link[rel=canonical]')['href'])
check('021 bulletin page uses its actual title','HTTP-BULLETIN-021' in detail21.title.get_text())
check('021 feed contains new sidebar update','HTTP-BULLETIN-021' in html(guest,'/').get_text())
check('021 public markup has no private request token',in21['request_key'] not in str(detail21))
edit21=dict(in21,id=bid21,revision=1,title='Updated bulletin21')
expect_post(admin,'bulletin_save',**edit21)
expect_post(admin,'bulletin_save',409,**edit21)
for title21,status21,date21 in [('HIDDEN-DRAFT21','draft','2025-03-01T10:00'),('HIDDEN-FUTURE21','published','2100-01-01T10:00')]:
    result21=expect_post(admin,'bulletin_save',**dict(bulletin_input21(title21),status=status21,publish_at=date21))
    hidden_id21=int(parse_qs(urlparse(result21.json()['redirect']).query)['edit'][0])
    check('021 hidden bulletin details denied '+status21,guest.get(base+'/index.php?r=bulletin&id='+str(hidden_id21)).status_code==404)
    check('021 hidden bulletin search has no leak '+status21,title21 not in html(guest,'/index.php?r=bulletins').get_text())
expect_post(admin,'bulletin_save',400,**dict(bulletin_input21(),publish_at='2101-01-01T00:00'))
expect_post(admin,'bulletin_save',400,**dict(bulletin_input21(),publish_at='2026-02-30T12:00'))
expect_post(admin,'bulletin_save',400,**dict(bulletin_input21(),source_url='javascript:alert(1)'))
for i21 in range(22):
    row21=dict(bulletin_input21('PAGE21-'+str(i21)),body='Timeline paging fixture')
    # One HTTP submission plus service-level pagination tests cover validation; direct fixture insertion keeps this suite bounded.
    conn.execute('INSERT INTO cy_bulletins(title,body,source_name,source_url,cover_id,status,publish_at,revision,actor_id,request_key,fingerprint,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)',(row21['title'],row21['body'],'','',0,'published',1740794400,1,admin_id20,'http21:'+row21['request_key'],'f'*64,1740794400,1740794400))
conn.commit()
page21=html(guest,'/index.php?r=bulletins&period=2025-03&q=PAGE21')
page221=html(guest,'/index.php?r=bulletins&period=2025-03&q=PAGE21&page=2')
check('021 native bulletin pages contain 20 then 2 items',len(page21.select('[data-bulletin-id]'))==20 and len(page221.select('[data-bulletin-id]'))==2)
check('021 date and query survive native pagination',all('period=2025-03' in a['href'] and 'q=PAGE21' in a['href'] for a in page21.select('.pagination a')))
check('021 month canonical retains period','period=2025-03' in page21.select_one('link[rel=canonical]')['href'])
for endpoint21 in ['/feed.php?kind=bulletins','/sitemap.php?kind=bulletins&page=1']:
    r21=guest.get(base+endpoint21)
    try: ET.fromstring(r21.content);valid21=True
    except ET.ParseError:valid21=False
    check('021 valid public bulletin XML '+endpoint21,valid21 and r21.status_code==200 and 'HIDDEN-FUTURE21' not in r21.text and 'HIDDEN-DRAFT21' not in r21.text)
check('021 main sitemap indexes bulletin pages','kind=bulletins' in guest.get(base+'/sitemap.php').text)
save_group('editorial',article_neighbors='1',article_related='1',article_author_card='1',article_summary='1',article_cover='1',article_thumbnail='right',copyright_original='{author} - {title} - {site} <script>bad</script>')
aid21=create_content(title='Editorial HTTP21',excerpt='A concrete summary21',source_name='Original desk21',source_url='https://example.org/story',copyright_mode='original',cover_art='cover-space')
article21=html(guest,'/index.php?r=article&id='+str(aid21))
check('021 attribution summary copyright and author card are real UI',all(article21.select_one(x) is not None for x in ['.article-source','.article-summary','.article-copyright','.article-author-card']))
check('021 template substitutes title and escapes raw HTML','Editorial HTTP21' in article21.select_one('.article-copyright').get_text() and not article21.select('.article-copyright script'))
check('021 custom editor fields exist',all(html(admin,'/admin/index.php?tab=edit_content&id='+str(aid21)).select_one('[name='+x+']') is not None for x in ['source_name','source_url','copyright_mode']))
home21=html(guest,'/')
check('021 configurable right thumbnail is attached to article rows',home21.select_one('.article-row.thumbnail-right') is not None)
save_group('editorial',article_thumbnail='text',article_cover='0')
check('021 text-only article list removes thumbnails',not html(guest,'/index.php?r=articles').select('[data-catalog-results] .card-cover'))
check('021 cover switch works on article details',not html(guest,'/index.php?r=article&id='+str(aid21)).select('.article-cover'))
product21=create_content(kind='product',title='Independent product cover21',cover_art='cover-workshop')
check('021 article cover switch does not hide product images',html(guest,'/index.php?r=product&id='+str(product21)).select_one('.article-cover') is not None)
save_group('editorial',article_thumbnail='left',article_cover='1')
save_group('modules',bulletins_enabled='0')
check('021 disabled bulletins cannot be browsed',guest.get(base+'/index.php?r=bulletins').status_code==403)
check('021 disabled bulletins cannot be fetched through RSS',guest.get(base+'/feed.php?kind=bulletins').status_code==404)
check('021 staff can manage disabled module',admin.get(base+'/admin/index.php?tab=bulletins').status_code==200)
save_group('modules',bulletins_enabled='1')
