"""Menu trees and local article images through real authenticated HTTP actions."""
def menu22(label, **changes):
    return dict(label=label, route='articles', active='1', request_key=secrets.token_hex(16), **changes)
def save_menu22(data):
    response=expect_post(admin,'admin_entity',entity='navigation',**data)
    return db_one('SELECT id FROM cy_navigation WHERE request_key=?',(str(admin_id20)+':'+data['request_key'],))['id']
root_in22=menu22('HTTP-MENU-ROOT22',panel_style='columns',sort_order='0')
root22=save_menu22(root_in22)
child_in22=menu22('HTTP-MENU-CHILD22',parent_id=root22,description='A useful <script>description</script>')
child22=save_menu22(child_in22)
leaf22=save_menu22(menu22('HTTP-MENU-LEAF22',parent_id=child22))
check('022 retry of menu create returns original row',save_menu22(root_in22)==root22)
expect_post(admin,'admin_entity',409,entity='navigation',**dict(root_in22,label='Conflicting tree22'))
expect_post(user,'admin_entity',403,entity='navigation',**menu22('UNAUTHORIZED22'))
expect_post(admin,'admin_entity',400,entity='navigation',**menu22('FOURTH22',parent_id=leaf22))
expect_post(admin,'admin_entity',400,entity='navigation',**dict(root_in22,id=root22,revision=1,parent_id=child22))
page22=html(guest,'/')
check('022 all three menu levels render with native disclosures',page22.select_one('.desktop-nav [data-nav-id="%s"] [data-nav-id="%s"] [data-nav-id="%s"]'%(root22,child22,leaf22)) is not None)
check('022 menu descriptions are escaped',not page22.select('.site-nav-panel script') and '<script>description</script>' in page22.get_text())
check('022 mobile menu uses the same complete tree',page22.select_one('#menu-dialog [data-nav-id="%s"]'%leaf22) is not None)
check('022 excess top-level links remain reachable',page22.select_one('.desktop-nav .nav-overflow') is not None)
expect_post(admin,'admin_entity',entity='navigation',**dict(root_in22,id=root22,revision=1,visibility='login'))
expect_post(admin,'admin_entity',409,entity='navigation',**dict(root_in22,id=root22,revision=1))
check('022 guest cannot see descendants of a member-only menu',html(guest,'/').select_one('[data-nav-id="%s"]'%leaf22) is None)
check('022 member can see descendants of member-only menu',html(user,'/').select_one('[data-nav-id="%s"]'%leaf22) is not None)
expect_post(admin,'admin_entity',entity='navigation',**dict(root_in22,id=root22,revision=2))
editor22=html(admin,'/admin/index.php?tab=navigation&edit='+str(child22))
check('022 actual admin form contains parent image and edit revision',all(editor22.select_one('.navigation-editor [name='+n+']') for n in ['parent_id','image_id','description','panel_style','revision','request_key']))

images22=[]
for icon22 in ['gallery','community']:
    with (ROOT/'site/assets/art'/('icon-'+icon22+'.webp')).open('rb') as file22:
        upload22=admin.post(base+'/action.php',data={'action':'upload','csrf':csrf(admin),'private':'0'},files={'file':(icon22+'.webp',file22,'image/webp')},headers={'Accept':'application/json'})
    check('022 public WebP upload '+icon22,upload22.status_code==200,upload22.text[:200]);images22.append(upload22.json()['media_id'])
save_group('editorial',article_multimage='1',article_image_captions='1',article_thumbnail='left')
body22='First photo\n![Camera <b>caption</b>](media:%s)\nSecond photo\n![Community](media:%s)\n`![code](media:%s)`'%(*images22,images22[0])
article_id22=create_content(title='HTTP-GALLERY22',body=body22,protected_body='PROTECTED-GALLERY22',access_level='login',image_layout='default')
article22=html(guest,'/index.php?r=article&id='+str(article_id22))
check('022 actual article embeds two uploaded photos with escaped captions',len(article22.select('.inline-picture img'))==2 and len(article22.select('.image-caption'))==2 and not article22.select('.image-caption b'))
check('022 inline code remains text and protected prose stays private',not article22.select('code img') and 'PROTECTED-GALLERY22' not in str(article22))
listing22=html(guest,'/index.php?r=articles&q=HTTP-GALLERY22')
check('022 article list uses real body images as a gallery',len(listing22.select('.card-gallery img'))==2)
edit22=html(admin,'/admin/index.php?tab=edit_content&id='+str(article_id22))
check('022 real editor includes insertion button and all gallery fields',edit22.select_one('[data-insert-image]') is not None and all(edit22.select_one('[name=gallery_image_'+str(n)+']') for n in range(1,5)))
save_group('editorial',article_image_captions='0',article_multimage='0')
check('022 captions can be disabled in the actual settings form',not html(guest,'/index.php?r=article&id='+str(article_id22)).select('.image-caption'))
check('022 site default can disable automatic multi-image cards',not html(guest,'/index.php?r=articles&q=HTTP-GALLERY22').select('.card-gallery'))
save_group('editorial',article_image_captions='1',article_multimage='1')
conn.execute('UPDATE cy_media SET is_private=1 WHERE id=?',(images22[0],));conn.commit()
revoked22=html(guest,'/index.php?r=article&id='+str(article_id22))
check('022 revoked media leaves no public image URL',len(revoked22.select('.inline-picture img'))==1 and not revoked22.select('img[src$="id='+str(images22[0])+'"]'))
check('022 single remaining image falls back from gallery',not html(guest,'/index.php?r=articles&q=HTTP-GALLERY22').select('.card-gallery'))
conn.execute('UPDATE cy_media SET is_private=0 WHERE id=?',(images22[0],));conn.commit()
