"""Content menus through authenticated forms, actual HTML and permission changes."""
builder24=html(admin,'/admin/index.php?tab=builder&slot=page10')
source24=builder24.select_one('textarea[data-layout-document]')
check('024 visual builder boot attributes are actually emitted',source24 is not None and json.loads(source24['data-layout-entry-types'])==['features','tabs','gallery','timeline','slider','buttons','faq'])
check('024 visual builder receives the route and symbol registries',source24 is not None and 'articles' in json.loads(source24['data-layout-routes']) and 'anime-reading' in json.loads(source24['data-layout-symbols']))
check('024 textarea respects its configured row count',source24 is not None and source24['rows']=='16')
expect_post(admin,'admin_entity',entity='categories',name='HTTP-CATEGORY24',kind='article',access_level='public')
cat24=db_one("SELECT id FROM cy_categories WHERE name='HTTP-CATEGORY24'")['id']
article24=create_content(title='HTTP-CONTENT24 <script>title</script>',category_id=cat24,body='BODY-NOT-IN-MENU24',protected_body='SECRET-NOT-IN-MENU24',access_level='login')
draft24=create_content(title='HTTP-DRAFT24',category_id=cat24,status='draft')
future24=create_content(title='HTTP-FUTURE24',category_id=cat24)
conn.execute('UPDATE cy_contents SET publish_at=? WHERE id=?',(int(time.time())+3600,future24));conn.commit()
input24=menu22('HTTP-NAV24',category_id=cat24,preview_count=3,preview_sort='latest',sort_order=0,icon='anime-reading')
nav24=save_menu22(input24)
home24=html(guest,'/')
panel24=home24.select_one('.desktop-nav [data-nav-id="%s"]'%nav24)
check('024 desktop content menu renders only the published source',panel24 is not None and len(panel24.select('[data-preview-id]'))==1 and panel24.select_one('[data-preview-id="%s"]'%article24) is not None)
check('024 menu metadata escapes HTML and never contains content bodies',not panel24.select('script') and 'BODY-NOT-IN-MENU24' not in str(panel24) and 'SECRET-NOT-IN-MENU24' not in str(panel24))
check('024 parent menu link preserves the category filter','category='+str(cat24) in panel24.select_one('.nav-parent-link')['href'])
check('024 preview link opens the actual article','id='+str(article24) in panel24.select_one('[data-preview-id]')['href'])
check('024 mobile and no-script menus retain the same content',home24.select_one('#menu-dialog [data-preview-id="%s"]'%article24) is not None and home24.select_one('noscript [data-preview-id="%s"]'%article24) is not None)
active24=html(guest,'/index.php?r=articles&category='+str(cat24))
check('024 current category has an accessible active link',active24.select_one('.desktop-nav [data-nav-id="%s"] .nav-parent-link[aria-current=page]'%nav24) is not None)
edit24=html(admin,'/admin/index.php?tab=navigation&edit='+str(nav24))
check('024 backend exposes all content-menu settings',all(edit24.select_one('.navigation-editor [name='+name+']') for name in ['category_id','preview_count','preview_sort']))
check('024 menu save follows the new fields in form order',str(edit24).index('name="preview_sort"')<str(edit24).index('class="btn full"'))
expect_post(user,'admin_entity',403,entity='navigation',**dict(input24,id=nav24,revision=1,preview_count=4))
expect_post(admin,'admin_entity',400,entity='navigation',**dict(input24,id=nav24,revision=1,preview_count=7))
conn.execute('UPDATE cy_categories SET access_level=? WHERE id=?',('login',cat24));conn.commit()
check('024 changed category permission hides the entire guest menu',html(guest,'/').select_one('[data-nav-id="%s"]'%nav24) is None)
check('024 signed-in reader keeps access to the category preview',html(user,'/').select_one('[data-nav-id="%s"] [data-preview-id="%s"]'%(nav24,article24)) is not None)
conn.execute('UPDATE cy_categories SET access_level=? WHERE id=?',('public',cat24));conn.commit()
expect_post(admin,'admin_entity',entity='navigation',**dict(input24,id=nav24,revision=1,preview_count=0))
check('024 disabling previews leaves a functioning category link',html(guest,'/').select_one('.desktop-nav a.site-nav-link[data-nav-id="%s"]'%nav24) is not None)
save_group('site',brand_caption='一起读点好东西 <b>')
brand24=html(guest,'/').select_one('.brand-caption')
check('024 custom header subtitle is escaped',brand24 is not None and '<b>' in brand24.get_text() and brand24.select_one('b') is None)
save_group('site',brand_caption='')
check('024 empty header subtitle is hidden',html(guest,'/').select_one('.brand-caption') is None)
for name24 in ['reading','support']:
    result24=guest.get(base+'/assets/art/icon-'+name24+'.webp')
    check('024 original '+name24+' icon is served locally',result24.status_code==200 and result24.headers.get('Content-Type')=='image/webp')
layout24=db_one('SELECT revision FROM cy_layouts WHERE slot=?',('page11',))
faq24={'format':'chengyu-layout','version':1,'blocks':[{'id':'faq24','type':'faq','title':'HTTP-FAQ24','text':'Legacy question24|Legacy answer24','items':[{'title':'Question <script>24</script> | A','text':'Answer **bold** | separator\n\nSecond paragraph. [safe](https://example.org)'},{'title':'Another question24','text':'<script>never_execute24()</script>'}]}]}
expect_post(admin,'admin_layout',slot='page11',revision=layout24['revision'] if layout24 else 0,document=json.dumps(faq24))
faq_page24=html(guest,'/index.php?r=landing&slot=page11')
faq_list24=faq_page24.select('.composed-faq details')
check('024 FAQ renders old and structured questions as native disclosures',len(faq_list24)==3 and faq_list24[0].select_one('summary').get_text()=='Legacy question24')
check('024 FAQ preserves multiline Markdown and literal separators',faq_list24[1].select_one('strong').get_text()=='bold' and len(faq_list24[1].select('.prose p'))==2 and '| separator' in faq_list24[1].get_text())
check('024 FAQ escapes question and answer HTML',not faq_page24.select('.composed-faq script') and '<script>24</script>' in faq_list24[1].get_text())
expect_post(user,'admin_layout',403,slot='page11',revision=1,document=json.dumps(faq24))
faq24['blocks'][0]['items'][0]['text']=''
expect_post(admin,'admin_layout',400,slot='page11',revision=(layout24['revision'] if layout24 else 0)+1,document=json.dumps(faq24))
