"""Real local HTTP security/pricing/diagnostics tests. No external service is contacted."""
import hmac, hashlib, struct, re
for asset in ['refinement.css','refinement.js']:
    r=guest.get(base+'/assets/'+asset);check('014 production asset '+asset,r.status_code==200 and len(r.content)>1000)
for tab in ['pricing','system']:
    check('014 management '+tab,admin.get(base+'/admin/index.php?tab='+tab).status_code==200)
    check('014 management rejects normal user '+tab,user.get(base+'/admin/index.php?tab='+tab).status_code==403)
check('014 security center requires login','r=login' in guest.get(base+'/index.php?r=security').url)
check('014 security center is a real authenticated route',user.get(base+'/index.php?r=security').status_code==200)
expect_post(user,'admin_diagnostics',403)
r=post(admin,'admin_diagnostics',download='1');report=r.json()
check('014 exported capability report has private attachment headers',r.status_code==200 and 'attachment' in r.headers.get('Content-Disposition','') and 'no-store' in r.headers.get('Cache-Control',''))
check('014 capability report has no config secret/path',str(work) not in r.text and 'secret_cipher' not in r.text and 'password_hash' not in r.text)
check('014 actual rollback probe is reported as passing',any(c['check']=='Real database rollback' and c['state']=='pass' for c in report['checks']))
expect_post(admin,'admin_diagnostics');check('014 diagnostics results rendered in backend',bool(html(admin,'/admin/index.php?tab=system').select('.capability-row')))
# The existing isolated mail fixture is not used by TOTP. Register a dedicated account.
save_group('users',two_factor_enabled='1',email_registration_required='0',registration_mode='open')
secure=requests.Session();expect_post(secure,'register',username='secure14',email='secure14@example.test',display_name='Security fixture',password='TestPassword!2026',agree='1')
secure2=requests.Session();expect_post(secure2,'login',identifier='secure14',password='TestPassword!2026')
expect_post(secure,'factor_begin',403,current_password='WrongPassword!2026')
expect_post(secure,'factor_begin',current_password='TestPassword!2026')
setup=html(secure,'/index.php?r=security');secret=setup.select_one('.setup-key code').get_text(strip=True)
check('014 enrollment key exists only in owner session',secret not in user.get(base+'/index.php?r=security').text)
def totp14(secret):
    counter=int(time.time())//30;raw=base64.b32decode(secret);digest=hmac.new(raw,struct.pack('>Q',counter),hashlib.sha1).digest();off=digest[-1]&15
    return str((struct.unpack('>I',digest[off:off+4])[0]&0x7fffffff)%1000000).zfill(6)
expect_post(secure,'factor_activate',403,current_password='WrongPassword!2026',factor_code=totp14(secret))
activated_code=totp14(secret)
expect_post(secure,'factor_activate',current_password='TestPassword!2026',factor_code=activated_code)
page=html(secure,'/index.php?r=security');codes=[x.get_text(strip=True) for x in page.select('.recovery-grid code')]
check('014 eight recovery codes shown once',len(codes)==8 and not html(secure,'/index.php?r=security').select('.recovery-grid code'))
check('014 enrollment revokes prior session','r=login' in secure2.get(base+'/index.php?r=security').url)
factor_uid=db_one("SELECT id FROM cy_users WHERE username='secure14'")['id'];dbfactor=dict(db_one('SELECT * FROM cy_second_factors WHERE user_id=?',(factor_uid,)))
check('014 database encrypts secret and stores no plain recovery codes',secret not in str(dbfactor) and all(c.replace('-','') not in str(dbfactor) for c in codes))
expect_post(secure2,'login',401,identifier='secure14',password='TestPassword!2026')
expect_post(secure2,'login',403,identifier='secure14',password='TestPassword!2026',factor_code=activated_code)
expect_post(secure2,'login',identifier='secure14',password='TestPassword!2026',factor_code=codes[0])
expect_post(secure2,'logout');expect_post(secure2,'login',403,identifier='secure14',password='TestPassword!2026',factor_code=codes[0])
save_group('users',two_factor_enabled='0')
expect_post(secure2,'login',401,identifier='secure14',password='TestPassword!2026')
check('014 enrollment off preserves active factor',db_one('SELECT id FROM cy_second_factors WHERE user_id=?',(factor_uid,)) is not None)
save_group('users',two_factor_enabled='1')
expect_post(secure,'factor_rotate',current_password='TestPassword!2026',factor_code=codes[1]);rotated=[x.get_text(strip=True) for x in html(secure,'/index.php?r=security').select('.recovery-grid code')]
check('014 recovery rotation issues eight different codes',len(rotated)==8 and not set(rotated)&set(codes))
expect_post(secure2,'login',403,identifier='secure14',password='TestPassword!2026',factor_code=codes[2])
expect_post(secure2,'login',identifier='secure14',password='TestPassword!2026',factor_code=rotated[0])
expect_post(secure,'session_revoke',current_password='TestPassword!2026',factor_code=rotated[1])
check('014 explicit session revoke logs out other browser','r=login' in secure2.get(base+'/index.php?r=security').url)
expect_post(secure,'factor_disable',current_password='TestPassword!2026',factor_code=rotated[2]);check('014 verified disable removes factor',db_one('SELECT id FROM cy_second_factors WHERE user_id=?',(factor_uid,)) is None)
expect_post(secure2,'login',identifier='secure14',password='TestPassword!2026')
# Pricing: scope, integer totals, variant display and saved order breakdown.
save_group('commerce',pricing_enabled='1',pricing_coupon_stack='0')
priced=create_content(kind='product',product_type='digital',price_currency='balance',price='10.00',title='014 priced download',access_level='paid')
expect_post(user,'admin_pricing',403,content_id=priced,revision='0')
from datetime import timezone
start=datetime.now(timezone(timedelta(hours=8)))-timedelta(minutes=5);end=start+timedelta(days=1)
fields=dict(content_id=priced,revision='0',active='1',vip1_bps='8000',vip2_bps='7000',vip3_bps='6000',promo_bps='5000',starts_at=start.strftime('%Y-%m-%dT%H:%M'),ends_at=end.strftime('%Y-%m-%dT%H:%M'))
expect_post(admin,'admin_pricing',**fields);expect_post(admin,'admin_pricing',409,**fields)
quote=other.get(base+'/index.php?r=price_quote',params={'id':priced},headers={'Accept':'application/json'}).json()['quote']
check('014 live quote applies current timed promotion',quote['amount']==500 and quote['source']=='promotion')
check('014 pricing view shows server quote without JavaScript','500'==html(other,f'/index.php?r=product&id={priced}').select_one('[name=price_ceiling]')['value'])
expect_post(other,'cart_add',item_id=priced,quantity='1');check('014 cart renders actual discount',bool(html(other,'/index.php?r=cart').select('.cart-row')) and '\u00a5 5.00' in html(other,'/index.php?r=cart').get_text())
code='PRICE14HTTP';expect_post(admin,'admin_entity',entity='coupons',code=code,mode='flat',value='1.00',minimum='0',max_uses='10',expires_at=end.strftime('%Y-%m-%dT%H:%M'),active='1',scope_kind='content',content_id=priced,min_vip_tier='0')
quote_url=base+'/index.php?r=price_quote';r=other.get(quote_url,params={'id':priced,'coupon':code},headers={'Accept':'application/json'});check('014 coupon stacking disabled at preview boundary',r.status_code==400 and r.json()['ok'] is False)
save_group('commerce',pricing_coupon_stack='1');quote=other.get(quote_url,params={'id':priced,'coupon':code}).json()['quote'];check('014 enabled stacking has correct quote',quote['amount']==400 and quote['coupon_discount']==100)
expect_post(other,'buy',409,kind='content',item_id=priced,intent=os.urandom(16).hex(),coupon=code,price_ceiling='399')
check('014 stale quote rejection leaves coupon quota untouched',db_one('SELECT uses FROM cy_coupons WHERE code=?',(code,))['uses']==0)
key=os.urandom(16).hex();expect_post(other,'buy',kind='content',item_id=priced,intent=key,coupon=code,price_ceiling='400')
order14=db_one('SELECT * FROM cy_orders WHERE user_id=? AND item_id=? ORDER BY id DESC',(buyer,priced));check('014 order persisted exact quoted price',order14['amount']==400)
check('014 order page shows historical pricing breakdown',bool(html(other,'/index.php?r=orders&id='+str(order14['id'])).select('.order-pricing')))
fields['revision']='1';fields['promo_bps']='10000';expect_post(admin,'admin_pricing',**fields)
expect_post(other,'refund',order_id=order14['id'],reason='014 quote refund');before14=db_one('SELECT balance FROM cy_users WHERE id=?',(buyer,))['balance'];expect_post(admin,'admin_refund',id=order14['id'],decision='approve',current_password='TestPassword!2026')
check('014 refund returns old paid amount not current list price',db_one('SELECT balance FROM cy_users WHERE id=?',(buyer,))['balance']==before14+400)
check('014 ordinary public article cannot be quoted',guest.get(quote_url,params={'id':1},headers={'Accept':'application/json'}).status_code==403)
save_group('appearance',motion_layout='1',reading_focus='1')
check('014 new visual options reach frontend',html(guest).html['data-reading-focus']=='1' and json.loads(html(guest).html['data-motion-settings'])['motion_layout'] is True)

save_group('appearance',motion_duration='0')
check('014 zero duration persists through real HTTP settings',json.loads(html(guest).html['data-motion-settings'])['motion_duration']==0)
save_group('appearance',motion_duration='420')
