<?php
use Chengyu\Core\HttpClient;
use Chengyu\Services\{OAuth,Auth,Membership,Payment,Wallet};
function response15(array $body): string {$json=json_encode($body,JSON_THROW_ON_ERROR);return "HTTP/1.1 200 OK\r\nContent-Length: ".strlen($json)."\r\n\r\n".$json;}
function oauth15(string $subject='test-identity',string $provider='google'): array {
    global $a;$_SESSION=[];$_SERVER['REMOTE_ADDR']='oauth-fixture-'.key32();
    settings('connections',['social_enabled'=>'1','oauth_'.$provider.'_enabled'=>'1','oauth_'.$provider.'_id'=>'local-test-app','oauth_'.$provider.'_secret'=>'fixture-client-secret']);
    $auth=new Auth($a->db,$a->settings,$a->crypto,$a->activity,$a->wallet,$a->secondFactor);
    $calls=new ArrayObject();
    $http=new HttpClient(static function($method,$url,$headers,$body)use($subject,$provider,$calls){
        $calls[]=['method'=>$method,'url'=>$url,'headers'=>$headers,'body'=>$body];
        if($method==='POST'){parse_str($body,$fields);truth(isset($fields['code_verifier']));truth(strlen($fields['code_verifier'])>=43);if($provider==='microsoft'){same('https://graph.microsoft.com/User.Read',$fields['scope']);}return response15(['token_type'=>'Bearer','access_token'=>'fixture-access-token']);}
        same('Bearer fixture-access-token',$headers['Authorization']);
        return response15(['sub'=>$subject,'id'=>$subject,'name'=>'Fixture Person','login'=>'FixtureGit','displayName'=>'Fixture Office','email'=>'never-used@example.test']);
    });
    return [new OAuth($a->db,$a->settings,$a->crypto,$a->activity,$a->wallet,$auth,$a->secondFactor,$a->config['url'],$http),$auth,$calls];
}
function callback15(OAuth $oauth,string $provider='google',string $purpose='login',string $password='',string $factor=''): array {
    $url=$oauth->begin($provider,$purpose,$password,$factor);parse_str(parse_url($url,PHP_URL_QUERY),$query);
    $target=$oauth->callback($provider,['state'=>$query['state'],'code'=>'fixture-authorization-code']);return [$query,$target];
}
foreach(['127.0.0.1','10.1.1.1','172.16.0.1','192.168.1.1','169.254.169.254','100.64.0.1','198.18.0.1','192.0.2.1','198.51.100.1','203.0.113.1','0.0.0.0','224.0.0.1','::1','fc00::1','fe80::1','::ffff:8.8.8.8','2001:db8::1','2002:0808:0808::1'] as $ip){test('015: HTTPS transport rejects non-global address '.$ip,static function()use($ip){same(false,HttpClient::publicIp($ip));});}
foreach(['http://example.test','https://name:secret@example.test','https://example.test:8443','https://example.test/#private','https://127.0.0.1/api','https://localhost/api','https://name.localhost/api',"https://example.test/a\r\nInjected: yes"] as $url){test('015: rejects unsafe endpoint '.str_replace("\r\n",'CRLF',$url),static function()use($url){reject(static function()use($url){HttpClient::endpoint($url);});});}
test('015: integration framing accepts exact JSON and chunked body',static function(){same('{"ok":true}',HttpClient::decode(response15(['ok'=>true])));same('{"ok":true}',HttpClient::decode("HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\nb\r\n{\"ok\":true}\r\n0\r\n\r\n"));});
foreach(["HTTP/1.1 302 Found\r\nLocation: https://other.test\r\n\r\n","HTTP/1.1 200 OK\r\nContent-Length: 10\r\n\r\n{}","HTTP/1.1 200 OK\r\nContent-Length: 2\r\nContent-Length: 2\r\n\r\n{}","HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\nContent-Length: 2\r\n\r\n{}","HTTP/1.1 200 OK\r\nContent-Encoding: gzip\r\n\r\n{}","HTTP/1.1 200 OK\r\nTransfer-Encoding: chunked\r\n\r\n99\r\nx\r\n0\r\n\r\n"] as $n=>$raw){test('015: malformed or redirected HTTPS response '.$n,static function()use($raw){reject(static function()use($raw){HttpClient::decode($raw);},502);});}
test('015: bounded integration body rejects oversize',static function(){reject(static function(){HttpClient::decode(response15(['long'=>str_repeat('x',200)]),64);},502);});
test('015: private transport rejects nonobject invalid JSON',static function(){foreach(['null','"text"','{'] as $body){$http=new HttpClient(static function()use($body){return "HTTP/1.1 200 OK\r\n\r\n".$body;});reject(static function()use($http){$http->json('GET','https://example.test');},502);}});
foreach(['google','github','microsoft'] as $provider){test('015: '.$provider.' code exchange binds stable subject with PKCE and no token storage',static function()use($a,$provider){[$oauth,$auth,$calls]=oauth15(key32(),$provider);$id=user14('provider');$auth->login(account($id)['username'],'TestPassword!2026');[$q,$target]=callback15($oauth,$provider,'link','TestPassword!2026');same('security',$target);same('S256',$q['code_challenge_method']);same($oauth->callbackUrl($provider),$q['redirect_uri']);same(2,count($calls));same(1,count($oauth->links($id)));$json=json_encode($a->db->one('SELECT * FROM cy_identities WHERE user_id=?',[$id]));truth(strpos($json,'fixture-access-token')===false);truth(strpos($json,'never-used@example.test')===false);$auth->logout();callback15($oauth,$provider);$pending=$oauth->pending();same('login',$pending['kind']);$oauth->login($pending['nonce'],'');same($id,(int)$auth->user()['id']);reject(static function()use($oauth,$pending){$oauth->login($pending['nonce'],'');},403);$auth->logout();});}
test('015: callback state is session-bound and consumed once',static function(){[$oauth]=oauth15();$url=$oauth->begin('google','login');parse_str(parse_url($url,PHP_URL_QUERY),$q);reject(static function()use($oauth){$oauth->callback('google',['state'=>str_repeat('a',64),'code'=>'x']);},403);$oauth->callback('google',['state'=>$q['state'],'code'=>'x']);reject(static function()use($oauth,$q){$oauth->callback('google',['state'=>$q['state'],'code'=>'x']);},403);});
test('015: expired OAuth state never calls provider',static function(){[$oauth,$auth,$calls]=oauth15();$url=$oauth->begin('google','login');parse_str(parse_url($url,PHP_URL_QUERY),$q);$_SESSION['oauth_flows'][$q['state']]['expires_at']=time()-1;reject(static function()use($oauth,$q){$oauth->callback('google',['state'=>$q['state'],'code'=>'x']);},403);same(0,count($calls));});
test('015: provider mismatch consumes but does not exchange state',static function(){[$oauth,$auth,$calls]=oauth15();$url=$oauth->begin('google','login');parse_str(parse_url($url,PHP_URL_QUERY),$q);reject(static function()use($oauth,$q){$oauth->callback('github',['state'=>$q['state'],'code'=>'x']);},403);same(0,count($calls));});
test('015: provider client rotation invalidates in-flight proof',static function(){[$oauth]=oauth15();$url=$oauth->begin('google','login');parse_str(parse_url($url,PHP_URL_QUERY),$q);settings('connections',['oauth_google_secret'=>'new-secret']);reject(static function()use($oauth,$q){$oauth->callback('google',['state'=>$q['state'],'code'=>'x']);},409);});
test('015: email equality never attaches unknown provider to local account',static function()use($a){$id=user14('local');$a->db->update('cy_users',$id,['email'=>'never-used@example.test']);[$oauth]=oauth15(key32());callback15($oauth);same('register',$oauth->pending()['kind']);same([], $oauth->links($id));});
test('015: linking requires current password and cannot steal another subject',static function(){[$oauth,$auth]=oauth15(key32());$one=user14();$two=user14();$auth->login(account($one)['username'],'TestPassword!2026');reject(static function()use($oauth){$oauth->begin('google','link','wrong-password');},403);callback15($oauth,'google','link','TestPassword!2026');$auth->logout();$auth->login(account($two)['username'],'TestPassword!2026');reject(static function()use($oauth){callback15($oauth,'google','link','TestPassword!2026');},409);same([], $oauth->links($two));$auth->logout();});
test('015: OAuth login preserves enrolled second factor and recovery replay protection',static function()use($a){[$oauth,$auth]=oauth15(key32());[$id,$secret,$codes]=factor14();$auth->login(account($id)['username'],'TestPassword!2026',$codes['codes'][0]);callback15($oauth,'google','link','TestPassword!2026',$codes['codes'][1]);$auth->logout();callback15($oauth);$p=$oauth->pending();reject(static function()use($oauth,$p){$oauth->login($p['nonce'],'');},401);$oauth->login($p['nonce'],$codes['codes'][2]);same($id,(int)$auth->user()['id']);same(5,$a->secondFactor->status($id)['recovery_remaining']);$auth->logout();});
test('015: account revocation after provider callback blocks login',static function()use($a){[$oauth,$auth]=oauth15(key32());$id=user14();$auth->login(account($id)['username'],'TestPassword!2026');callback15($oauth,'google','link','TestPassword!2026');$auth->logout();callback15($oauth);$p=$oauth->pending();$a->db->execute('UPDATE cy_users SET session_version=session_version+1 WHERE id=?',[$id]);reject(static function()use($oauth,$p){$oauth->login($p['nonce'],'');},401);});
test('015: unlink only owns identity, remains possible after enrollment disabled',static function(){[$oauth,$auth]=oauth15(key32());$id=user14();$auth->login(account($id)['username'],'TestPassword!2026');callback15($oauth,'google','link','TestPassword!2026');$link=$oauth->links($id)[0];$before=(int)account($id)['session_version'];settings('connections',['social_enabled'=>'0']);$oauth->unlink((int)$link['id'],'TestPassword!2026','');same([],$oauth->links($id));same($before+1,(int)account($id)['session_version']);same($id,(int)$auth->user()['id']);$auth->logout();});
test('015: external registration follows invitation and local password rules',static function()use($a,$admin){[$oauth,$auth]=oauth15(key32());callback15($oauth);$p=$oauth->pending();settings('users',['registration_mode'=>'invite']);try{$name='conn'.substr(key32(),0,8);$input=['username'=>$name,'email'=>$name.'@example.test','password'=>'TestPassword!2026','display_name'=>'Connected member','agree'=>'1'];reject(static function()use($oauth,$p,$input){$oauth->register($p['nonce'],$input);});same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_users WHERE username=?',[$name]));$codes=$a->invitations->issue($admin,1,1,time()+3600,'external test');$input['invitation']=$codes[0];$id=$oauth->register($p['nonce'],$input);same(1,count($oauth->links($id)));truth(password_verify('TestPassword!2026',account($id)['password_hash']));same($id,(int)$auth->user()['id']);$auth->logout();}finally{settings('users',['registration_mode'=>'open']);}});
function payment15(array $changes=[],?callable $during=null): array {
 global $a;$_SERVER['REMOTE_ADDR']='payment-fixture-'.key32();settings('epay',['epay_enabled'=>'1','epay_endpoint'=>'https://merchant.example.test/submit.php','epay_merchant'=>'10015','epay_secret'=>'old-query-secret','epay_query_enabled'=>'1','epay_query_endpoint'=>'https://merchant.example.test/api.php','epay_alipay'=>'1']);
 $id=user14('reconcile');$order=$a->payment->create($id,100,'epay','alipay',key32());$calls=new ArrayObject();
 $http=new HttpClient(static function($method,$url,$headers,$body)use($order,$changes,$calls,$during){parse_str(parse_url($url,PHP_URL_QUERY),$q);$calls[]=$q;same('10015',$q['pid']);same('old-query-secret',$q['key']);if($during){$during($order);}return response15(array_merge(['code'=>1,'pid'=>'10015','out_trade_no'=>$order['order_no'],'trade_no'=>'RECEIPT-'.$order['id'],'money'=>'1.00','status'=>1,'type'=>'alipay'],$changes));});
 return [new Payment($a->db,$a->settings,$a->crypto,$a->wallet,$a->activity,$a->config['url'],$http),$id,$order,$calls];
}
test('015: active payment query credits once and uses original credential snapshot',static function()use($a){[$payment,$id,$order,$calls]=payment15();settings('epay',['epay_merchant'=>'20015','epay_secret'=>'rotated-key']);$result=$payment->reconcile($id,(int)$order['id']);same('paid',$result['status']);same(100,funds($id));same(false,$payment->reconcile($id,(int)$order['id'])['changed']);same(1,count($calls));same(1,(int)$a->db->value("SELECT COUNT(*) FROM cy_ledger WHERE user_id=? AND reason LIKE 'Top-up%'",[$id]));});
foreach(['pid'=>'wrong','out_trade_no'=>'wrong','money'=>'2.00','type'=>'wxpay','status'=>9,'code'=>0] as $field=>$value){test('015: reconciliation rejects mismatched '.$field,static function()use($field,$value,$a){[$payment,$id,$order]=payment15([$field=>$value]);reject(static function()use($payment,$id,$order){$payment->reconcile($id,(int)$order['id']);},502);same(0,funds($id));same('pending',$a->db->value('SELECT status FROM cy_orders WHERE id=?',[(int)$order['id']]));});}
test('015: pending query never credits and foreign user never queries',static function(){[$payment,$id,$order,$calls]=payment15(['status'=>0]);$other=user14();reject(static function()use($payment,$other,$order){$payment->reconcile($other,(int)$order['id']);},404);same(0,count($calls));same('pending',$payment->reconcile($id,(int)$order['id'])['status']);same(0,funds($id));});
test('015: valid callback during payment query still credits once',static function()use($a){[$payment,$id,$order]=payment15([],static function($order)use($a){$fields=['pid'=>'10015','type'=>'alipay','out_trade_no'=>$order['order_no'],'trade_no'=>'RECEIPT-'.$order['id'],'trade_status'=>'TRADE_SUCCESS','money'=>'1.00'];$fields['sign']=Payment::sign($fields,'old-query-secret');$a->payment->settle('epay',$fields);});same('paid',$payment->reconcile($id,(int)$order['id'])['status']);same(100,funds($id));});
test('015: disabled reconciliation does not contact remote',static function(){[$payment,$id,$order,$calls]=payment15();settings('epay',['epay_query_enabled'=>'0']);try{reject(static function()use($payment,$id,$order){$payment->reconcile($id,(int)$order['id']);},403);same(0,count($calls));}finally{settings('epay',['epay_query_enabled'=>'1']);}});
test('015: expired topup can be recovered by exact merchant proof',static function()use($a){[$payment,$id,$order]=payment15();$a->db->update('cy_orders',(int)$order['id'],['status'=>'expired']);same('paid',$payment->reconcile($id,(int)$order['id'])['status']);same(100,funds($id));});
test('015: lifetime grant is explicit and cannot be shortened by timed grant',static function()use($a){$id=user14();$a->membership->grant($id,2,0);same(2,$a->membership->lifetimeTier($id));$a->membership->grant($id,2,30);same(Membership::FOREVER,(int)$a->db->value('SELECT until_at FROM cy_memberships WHERE user_id=? AND tier=2',[$id]));});
test('015: lifetime plan purchase rejects redundant equal or lower-tier purchase',static function()use($a,$admin){$plan=$a->admin->entity($admin,'plans',['name'=>'Lifetime test','tier'=>2,'days'=>0,'price_currency'=>'balance','price'=>'1.00','description'=>'Lifetime','active'=>1]);if(!$plan){$plan=(int)$a->db->value('SELECT MAX(id) FROM cy_plans');}$id=user14();$a->wallet->adjust($id,'balance',1000,'lifetime:'.$id,'fixture');$intent=key32();$order=$a->commerce->buy($id,'membership',$plan,$intent);same(2,$a->membership->lifetimeTier($id));same((int)$order['id'],(int)$a->commerce->buy($id,'membership',$plan,$intent)['id']);reject(static function()use($a,$id,$plan){$a->commerce->buy($id,'membership',$plan,key32());},409);same(900,funds($id));});
test('015: whole cart ceiling mismatch rolls back every order and debit',static function()use($a){$id=user14();$a->wallet->adjust($id,'balance',2000,'bag:'.$id,'fixture');$one=product('digital','balance','2.00');$two=product('digital','balance','3.00');$lines=[['item_id'=>$one,'variant_id'=>0,'quantity'=>1],['item_id'=>$two,'variant_id'=>0,'quantity'=>1]];reject(static function()use($a,$id,$lines){$a->commerce->checkout($id,$lines,key32(),0,'',['balance'=>499,'points'=>0,'tokens'=>0]);},409);same(2000,funds($id));same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_orders WHERE user_id=?',[$id]));$orders=$a->commerce->checkout($id,$lines,key32(),0,'',['balance'=>500,'points'=>0,'tokens'=>0]);same(2,count($orders));same(1500,funds($id));});
test('015: single purchase currency changes are rejected before any debit',static function()use($a){$id=user14();$a->wallet->adjust($id,'points',1000,'currency:'.$id,'fixture');$item=product('digital','points','10');reject(static function()use($a,$id,$item){$a->commerce->buy($id,'content',$item,key32(),'',0,0,1000,'balance');},409);same(1000,funds($id,'points'));});
test('015: settings snapshot encrypts secrets and rejects cross-site archives',static function()use($a,$admin){$id=$a->configuration->capture($admin,'Test encrypted archive');$archive=$a->configuration->export($admin,$id);truth(strpos($archive,'old-query-secret')===false);truth(strpos($archive,'site_name')===false);$other=new \Chengyu\Core\Crypto(bin2hex(random_bytes(32)));$foreign=$other->seal('{"format":"chengyu.settings.v1","settings":{}}');reject(static function()use($a,$admin,$foreign){$a->configuration->import($admin,$foreign,'Foreign');});same(0,count($a->configuration->preview($admin,$id)['changes']));});
test('015: preview masks changed credentials and rejects stale restore',static function()use($a,$admin){$id=$a->configuration->capture($admin,'Before rotation');settings('epay',['epay_secret'=>'secret-v2']);$p=$a->configuration->preview($admin,$id);$json=json_encode($p);truth(strpos($json,'secret-v2')===false);truth(strpos($json,'old-query-secret')===false);settings('site',['site_name'=>'Changed after preview']);reject(static function()use($a,$admin,$id,$p){$a->configuration->restore($admin,$id,$p['revision']);},409);same('Changed after preview',$a->settings->get('site_name'));});
test('015: valid restore refreshes cache and retains pre-restore snapshot',static function()use($a,$admin){$id=$a->configuration->capture($admin,'Stable name');settings('site',['site_name'=>'Temporary name']);$p=$a->configuration->preview($admin,$id);$before=(int)$a->db->value('SELECT COUNT(*) FROM cy_setting_snapshots');$a->configuration->restore($admin,$id,$p['revision']);same('Changed after preview',$a->settings->get('site_name'));same($before+1,(int)$a->db->value('SELECT COUNT(*) FROM cy_setting_snapshots'));});
test('015: snapshots restore email and SMTP dependency as one atomic configuration',static function()use($a,$admin){settings('email',['smtp_enabled'=>'1','smtp_host'=>'smtp.example.test','smtp_from'=>'site@example.test']);settings('email',['email_registration_required'=>'1']);$id=$a->configuration->capture($admin,'Email verified registration');settings('email',['email_registration_required'=>'0']);settings('email',['smtp_enabled'=>'0']);$p=$a->configuration->preview($admin,$id);try{$a->configuration->restore($admin,$id,$p['revision']);same(true,$a->settings->get('smtp_enabled'));same(true,$a->settings->get('email_registration_required'));}finally{settings('email',['email_registration_required'=>'0']);settings('email',['smtp_enabled'=>'0']);}});
test('015: nonadmin cannot read or change configuration archives',static function()use($a){$id=user14();reject(static function()use($a,$id){$a->configuration->capture($id,'Not allowed');},403);reject(static function()use($a,$id){$a->configuration->listing($id);},403);});
test('015: recognition is idempotent and cannot grant account or financial privileges',static function()use($a,$admin){$id=user14();$before=account($id);$badge=$a->badges->save($admin,['name'=>'Helpful voice','description'=>'A real contribution','active'=>1,'symbol'=>'heart','tone'=>'dusk']);$a->badges->grant($admin,$id,$badge);$a->badges->grant($admin,$id,$badge);same(1,count($a->badges->forUser($id)));same($before['role'],account($id)['role']);foreach(Wallet::CURRENCIES as $currency){same((int)$before[$currency],funds($id,$currency));}$a->badges->revoke($admin,$id,$badge);same([],$a->badges->forUser($id));});
test('015: expired or disabled badges disappear without deleting audit records',static function()use($a,$admin){$id=user14();$badge=$a->badges->save($admin,['name'=>'Timebound badge','active'=>1]);$a->badges->grant($admin,$id,$badge,time()+3600);$a->db->execute('UPDATE cy_user_badges SET expires_at=? WHERE user_id=?',[time()-1,$id]);same([],$a->badges->forUser($id));$a->badges->grant($admin,$id,$badge);$a->db->update('cy_badges',$badge,['active'=>0]);same([],$a->badges->forUser($id));truth((int)$a->db->value("SELECT COUNT(*) FROM cy_audit WHERE action='badge.granted' AND target=?",[$id.':'.$badge])>0);});
test('015: badge editing never accepts unsupported symbols or nonadmin actor',static function()use($a,$admin){reject(static function()use($a,$admin){$a->badges->save($admin,['name'=>'Invalid','symbol'=>'<script>','active'=>1]);});$id=user14();reject(static function()use($a,$id){$a->badges->save($id,['name'=>'Forged','active'=>1]);},403);});
// Leave a clean session before shared concurrency and accounting assertions.
$_SESSION=[];$_SERVER['REMOTE_ADDR']='test-fixture';settings('connections',['social_enabled'=>'0']);

test('015: handoff preserves complete signed URL without exposing it as a form action',static function(){
    $url='https://merchant.example.test/checkout?state=abc&sign=def';
    $data=\Chengyu\Core\ExternalNavigation::target($url);same($url,$data['target']);same('merchant.example.test',$data['host']);
    ob_start();partial('external_handoff',$data+['title'=>'Continue securely']);$html=ob_get_clean();
    truth(strpos($html,'data-external-handoff')!==false);truth(strpos($html,'rel="noreferrer noopener"')!==false);
    truth(strpos($html,'<form')===false);truth(strpos($html,'state=abc&amp;sign=def')!==false);
});
foreach(['http://merchant.example.test/','//merchant.example.test/','javascript:alert(1)','https://user:secret@merchant.example.test/','https://merchant.example.test/#fragment',"https://merchant.example.test/\r\nLocation: bad",'https://merchant.example.test/'.str_repeat('a',16384)] as $i=>$target){
    test('015: handoff rejects invalid destination '.$i,static function()use($target){reject(static function()use($target){\Chengyu\Core\ExternalNavigation::target($target);},400);});
}
test('015: handoff is not a public URL forwarding endpoint',static function(){
    $controller=file_get_contents(dirname(__DIR__).'/site/app/Http/SiteController.php');
    truth(strpos($controller,"$"."route==='external_handoff'")===false);
    truth(strpos(file_get_contents(dirname(__DIR__).'/site/app/Core/Support.php'),"form-action 'self'")!==false);
});
