<?php
declare(strict_types=1);
// Version 0.11 regression fixtures. Included only by the CLI test runner.
use Chengyu\Core\{Motion,Security};
function threadFixture(array $changes=[]):int { global $a,$admin;return $a->content->save(account($admin),array_merge(['kind'=>'thread','title'=>'Thread '.key32(),'body'=>'Public question','protected_body'=>'PRIVATE THREAD','status'=>'published','access_level'=>'public','comment_enabled'=>1,'thread_mode'=>'poll','poll_question'=>'Choose a direction','poll_options'=>"North\nSouth",'poll_results'=>'after_vote'],$changes),true); }
function answerFixture(int $content,int $user,string $status='approved',int $parent=0):int{global $a;return $a->db->insert('cy_comments',['content_id'=>$content,'user_id'=>$user,'body'=>'Answer fixture','status'=>$status,'parent_id'=>$parent,'created_at'=>time()]);}
function emailFixture(string $purpose='register',int $user=0):array {
    global $a;$_SERVER['REMOTE_ADDR']='mail-'.key32();$email='mail'.key32().'@example.test';$code='';
    $a->verification->request($email,$purpose,$user,static function($to,$subject,$body)use(&$code):void{preg_match('/\b[0-9]{6}\b/',$body,$m);$code=$m[0]??'';});
    return [$email,$code,(int)$a->db->value('SELECT MAX(id) FROM cy_email_challenges')];
}
function resetFixture(int $user):string {global $a;$token=bin2hex(random_bytes(32));$a->db->insert('cy_resets',['user_id'=>$user,'token_hash'=>$a->crypto->digest($token),'expires_at'=>time()+1800,'created_at'=>time()]);return $token;}
settings('modules',['polls_enabled'=>'1','questions_enabled'=>'1']);settings('users',['registration_mode'=>'open']);settings('community',['comment_visibility'=>'public']);
test('nested exception cannot be swallowed into a partial commit',static function()use($a,$u){$before=funds($u);$thrown=false;try{$a->db->transaction(static function()use($a,$u){try{$a->db->transaction(static function()use($a,$u){$a->wallet->adjust($u,'balance',21,'nested-abort','fixture');throw new RuntimeException('inner abort');});}catch(RuntimeException $e){}$a->wallet->adjust($u,'balance',22,'after-abort','fixture');});}catch(RuntimeException $e){$thrown=true;}truth($thrown);same($before,funds($u));same(0,(int)$a->db->value("SELECT COUNT(*) FROM cy_ledger WHERE idempotency_key IN ('nested-abort','after-abort')"));});
test('transaction remains reusable after rollback-only failure',static function()use($a){$a->db->transaction(static function()use($a){same(1,(int)$a->db->value('SELECT 1'));});});
test('logout clears all authorization and one-time secret state',static function()use($a){$_SESSION['content_unlock']=[1=>'proof'];$_SESSION['issued_invitations']=['SECRET'];$_SESSION['issued_codes']=['SECRET'];$_SESSION['verification_nonce']='SECRET';$_SESSION['cart']=[1];$old=Security::csrf();$a->auth->logout();same(['csrf'],array_keys($_SESSION));truth($old!==Security::csrf());same(null,$a->auth->user());});
$pwdUser=fixtureUser('pwd');$a->db->update('cy_users',$pwdUser,['password_hash'=>password_hash('Original!12345',PASSWORD_DEFAULT)]);
test('password change invalidates recovery links and rotates session version',static function()use($a,$pwdUser){$a->auth->login(account($pwdUser)['username'],'Original!12345');$token=resetFixture($pwdUser);$version=(int)account($pwdUser)['session_version'];$csrf=Security::csrf();$a->auth->changePassword('Original!12345','Updated!12345');same($version+1,(int)account($pwdUser)['session_version']);truth($csrf!==Security::csrf());reject(static function()use($a,$token){$a->auth->reset($token,'Stolen!12345');});});
test('incorrect password change cannot consume recovery links',static function()use($a,$pwdUser){$token=resetFixture($pwdUser);reject(static function()use($a){$a->auth->changePassword('wrong','Another!12345');},403);same(0,(int)$a->db->value('SELECT used_at FROM cy_resets WHERE token_hash=?',[$a->crypto->digest($token)]));});
test('admin credential or email change invalidates all outstanding recovery links',static function()use($a,$admin){
    $id=fixtureUser('adminreset');$token=resetFixture($id);$old=account($id);
    $a->admin->user($admin,$id,['role'=>'user','status'=>'active','email'=>$old['email'],'display_name'=>$old['display_name'],'new_password'=>'AdminReset!12345']);
    same((int)$old['session_version']+1,(int)account($id)['session_version']);
    reject(static function()use($a,$token){$a->auth->reset($token,'Recovered!12345');});
    $a->db->update('cy_users',$id,['email_verified_at'=>time()]);$token=resetFixture($id);
    $a->admin->user($admin,$id,['role'=>'user','status'=>'active','email'=>'changed'.key32().'@example.test','display_name'=>$old['display_name']]);
    same(0,(int)account($id)['email_verified_at']);reject(static function()use($a,$token){$a->auth->reset($token,'Recovered!12345');});
});
test('admin display-only change preserves valid recovery proof',static function()use($a,$admin){$id=fixtureUser('rename');$old=account($id);$token=resetFixture($id);$a->admin->user($admin,$id,['role'=>'user','status'=>'active','email'=>$old['email'],'display_name'=>'Renamed']);same(0,(int)$a->db->value('SELECT used_at FROM cy_resets WHERE token_hash=?',[$a->crypto->digest($token)]));same((int)$old['session_version'],(int)account($id)['session_version']);});
$poll=threadFixture();$opts=$a->threads->options($poll);
test('poll requires 2-10 distinct options and rolls back entire post',static function()use($a){$before=(int)$a->db->value('SELECT COUNT(*) FROM cy_contents');foreach(["Only","Same\nsame",implode("\n",range(1,11))] as $options){reject(static function()use($options){threadFixture(['poll_options'=>$options]);});}same($before,(int)$a->db->value('SELECT COUNT(*) FROM cy_contents'));});
test('unvoted poll snapshot never contains counts for after-vote privacy',static function()use($a,$poll){$snapshot=$a->threads->snapshot($a->content->get($poll),null,true);same(null,$snapshot['total']);same(false,$snapshot['can_see_results']);truth(!isset($snapshot['options'][0]['votes']));});
test('first vote recorded exactly once despite duplicate submit',static function()use($a,$poll,$opts,$u){$a->threads->vote(account($u),$poll,(int)$opts[0]['id'],$a->content);$a->threads->vote(account($u),$poll,(int)$opts[0]['id'],$a->content);same(1,(int)$a->db->value('SELECT COUNT(*) FROM cy_poll_votes WHERE content_id=?',[$poll]));$snap=$a->threads->snapshot($a->content->get($poll),account($u),true);same(1,$snap['total']);same(100.0,$snap['options'][0]['percent']);});
test('second choice after voting is rejected without changing result',static function()use($a,$poll,$opts,$u){reject(static function()use($a,$poll,$opts,$u){$a->threads->vote(account($u),$poll,(int)$opts[1]['id'],$a->content);},409);same((int)$opts[0]['id'],(int)$a->db->value('SELECT option_id FROM cy_poll_votes WHERE content_id=? AND user_id=?',[$poll,$u]));});
test('another reader cannot see private poll counts after someone else votes',static function()use($a,$poll,$v){$snap=$a->threads->snapshot($a->content->get($poll),account($v),true);same(false,$snap['can_see_results']);truth(!isset($snap['options'][0]['votes']));});
test('foreign option cannot be used in a vote',static function()use($a,$poll,$v){$otherPoll=threadFixture();$option=$a->threads->options($otherPoll)[0];reject(static function()use($a,$poll,$v,$option){$a->threads->vote(account($v),$poll,(int)$option['id'],$a->content);});});
foreach(['poll_question'=>'Changed','poll_options'=>"West\nEast",'poll_results'=>'always','poll_closes_at'=>date('Y-m-d H:i:s',time()+3600),'thread_mode'=>'discussion'] as $field=>$value){test('poll freezes '.$field.' after first vote',static function()use($a,$poll,$admin,$field,$value){reject(static function()use($a,$poll,$admin,$field,$value){$a->content->save(account($admin),contentInput($poll,['thread_mode'=>'poll',$field=>$value]),true);},409);});}
test('failed poll edit leaves content revision unchanged',static function()use($a,$poll,$admin){$before=contentInput($poll);reject(static function()use($a,$poll,$admin){$a->content->save(account($admin),contentInput($poll,['title'=>'BAD CHANGE','thread_mode'=>'poll','poll_options'=>'invalid']),true);});same($before['title'],$a->content->get($poll)['title']);same((int)$before['edit_version'],(int)$a->content->get($poll)['edit_version']);});
test('content authorization protects poll metadata and voting',static function()use($a,$v){$id=threadFixture(['access_level'=>'vip','min_vip_tier'=>3]);$item=$a->content->get($id,account($v));same(null,$a->threads->snapshot($item,account($v),false));$option=$a->threads->options($id)[0];reject(static function()use($a,$v,$id,$option){$a->threads->vote(account($v),$id,(int)$option['id'],$a->content);},403);});
test('unvoted poll deadline can be cleared explicitly',static function()use($a,$admin){$id=threadFixture(['poll_closes_at'=>date('Y-m-d H:i:s',time()+600)]);$a->content->save(account($admin),contentInput($id,['thread_mode'=>'poll','poll_closes_at'=>'']),true);same(0,(int)$a->threads->definition($id)['closes_at']);});
test('closed-only poll requires an actual closing time',static function(){reject(static function(){threadFixture(['poll_results'=>'closed']);});});
test('closed poll rejects votes and releases closed-only results',static function()use($a,$u){$id=threadFixture(['poll_results'=>'closed','poll_closes_at'=>date('Y-m-d H:i:s',time()-30)]);$option=$a->threads->options($id)[0];reject(static function()use($a,$u,$id,$option){$a->threads->vote(account($u),$id,(int)$option['id'],$a->content);});$snapshot=$a->threads->snapshot($a->content->get($id),null,true);same(true,$snapshot['closed']);same(true,$snapshot['can_see_results']);same(0,$snapshot['total']);});
test('closed-only results remain private even to a voter before deadline',static function()use($a,$u){$id=threadFixture(['poll_results'=>'closed','poll_closes_at'=>date('Y-m-d H:i:s',time()+600)]);$option=$a->threads->options($id)[0];$a->threads->vote(account($u),$id,(int)$option['id'],$a->content);same(false,$a->threads->snapshot($a->content->get($id),account($u),true)['can_see_results']);});
test('future scheduled poll cannot accept votes even from its author',static function()use($a,$admin){$id=threadFixture(['publish_at'=>date('Y-m-d H:i:s',time()+3600)]);$option=$a->threads->options($id)[0];reject(static function()use($a,$admin,$id,$option){$a->threads->vote(account($admin),$id,(int)$option['id'],$a->content);},403);});
test('suspended user cannot vote with a stale account snapshot',static function()use($a){$id=fixtureUser('suspended');$user=account($id);$poll=threadFixture();$option=$a->threads->options($poll)[0];$a->db->update('cy_users',$id,['status'=>'suspended']);reject(static function()use($a,$user,$poll,$option){$a->threads->vote($user,$poll,(int)$option['id'],$a->content);},403);});
test('disabled poll module blocks write endpoint and snapshot',static function()use($a,$poll,$opts,$v){settings('modules',['polls_enabled'=>'0']);reject(static function()use($a,$poll,$opts,$v){$a->threads->vote(account($v),$poll,(int)$opts[0]['id'],$a->content);},403);same(null,$a->threads->snapshot($a->content->get($poll),account($v),true));settings('modules',['polls_enabled'=>'1']);});
$question=threadFixture(['thread_mode'=>'question']);$answer=answerFixture($question,$u);
test('only question author or editor can accept an answer',static function()use($a,$question,$answer,$v){reject(static function()use($a,$question,$answer,$v){$a->threads->accept(account($v),$question,$answer,$a->content);},403);});
test('pending, nested and foreign answers cannot be accepted',static function()use($a,$question,$admin,$u,$answer){$bad=[answerFixture($question,$u,'pending'),answerFixture($question,$u,'approved',$answer),answerFixture(threadFixture(['thread_mode'=>'question']),$u)];foreach($bad as $id){reject(static function()use($a,$question,$admin,$id){$a->threads->accept(account($admin),$question,$id,$a->content);});}});
test('accepting an answer is idempotent and notifies once',static function()use($a,$question,$answer,$admin){$before=(int)$a->db->value('SELECT COUNT(*) FROM cy_notifications');$a->threads->accept(account($admin),$question,$answer,$a->content);$a->threads->accept(account($admin),$question,$answer,$a->content);same($answer,(int)$a->threads->definition($question)['accepted_comment_id']);same($before+1,(int)$a->db->value('SELECT COUNT(*) FROM cy_notifications'));});
test('moderation revokes rejected accepted answer atomically',static function()use($a,$question,$answer,$admin){$a->admin->moderation($admin,'comments',$answer,'rejected');same(0,(int)$a->threads->definition($question)['accepted_comment_id']);same(0,(int)$a->threads->snapshot($a->content->get($question),null,true)['accepted_comment_id']);});
test('question feature switch blocks answer acceptance',static function()use($a,$question,$admin,$u){settings('modules',['questions_enabled'=>'0']);$answer=answerFixture($question,$u);reject(static function()use($a,$question,$admin,$answer){$a->threads->accept(account($admin),$question,$answer,$a->content);},403);settings('modules',['questions_enabled'=>'1']);});
test('motion presets reference only shared validated fields',static function()use($a){foreach(Motion::presets() as $preset){foreach($preset as $key=>$value){truth(in_array($key,Motion::KEYS,true));truth(isset($a->settings->schema()[$key]));}}});
test('partial motion save preserves theme and unrelated appearance settings',static function()use($a){$theme=$a->settings->get('theme');$radius=$a->settings->get('radius');$a->settings->savePartial('appearance',['motion_curve'=>'custom','curve_x1'=>15,'curve_y1'=>145,'curve_x2'=>75,'curve_y2'=>100]);same($theme,$a->settings->get('theme'));same($radius,$a->settings->get('radius'));same([.15,1.45,.75,1.0],Motion::curve($a->settings));});
test('custom curve cannot inject CSS or invalid x coordinates',static function()use($a){reject(static function()use($a){$a->settings->savePartial('appearance',['curve_x1'=>'999']);});reject(static function()use($a){$a->settings->savePartial('appearance',['motion_curve'=>'x);color:red']);});reject(static function()use($a){$a->settings->savePartial('appearance',['smtp_enabled'=>1]);});});
test('mandatory email verification cannot be enabled without SMTP',static function()use($a){reject(static function()use($a){$a->settings->savePartial('email',['email_registration_required'=>true,'smtp_enabled'=>false]);});});
settings('email',['smtp_enabled'=>1,'smtp_host'=>'smtp.example.test','smtp_from'=>'no-reply@example.test','smtp_port'=>587]);
[$mail,$code,$challenge]=emailFixture();
test('verification stores no plaintext email or code',static function()use($a,$mail,$code,$challenge){truth(strlen($code)===6);$row=$a->db->one('SELECT * FROM cy_email_challenges WHERE id=?',[$challenge]);same(64,strlen($row['code_hash']));truth(strpos(json_encode($row),$mail)===false);same('sent',$row['state']);});
test('wrong code attempt persists despite the validation exception',static function()use($a,$mail,$code,$challenge){reject(static function()use($a,$mail,$code){$a->verification->validate($mail,'register',$code==='000000'?'111111':'000000',0);},403);same(1,(int)$a->db->value('SELECT attempts FROM cy_email_challenges WHERE id=?',[$challenge]));});
test('correct code produces a proof consumed exactly once',static function()use($a,$mail,$code,$challenge){same($challenge,$a->verification->validate($mail,'register',$code,0));$a->db->transaction(static function()use($a,$challenge){$a->verification->consume($challenge);});reject(static function()use($a,$mail,$code){$a->verification->validate($mail,'register',$code,0);},403);reject(static function()use($a,$challenge){$a->verification->consume($challenge);},409);});
test('code proof rolls back with a failed account transaction',static function()use($a){[$mail,$code,$id]=emailFixture();try{$a->db->transaction(static function()use($a,$id){$a->verification->consume($id);throw new RuntimeException('cancel');});}catch(RuntimeException $e){}same($id,$a->verification->validate($mail,'register',$code,0));});
test('code is bound to browser session and original purpose',static function()use($a){[$mail,$code,$id]=emailFixture();$nonce=$_SESSION['verification_nonce'];$_SESSION['verification_nonce']=key32();reject(static function()use($a,$mail,$code){$a->verification->validate($mail,'register',$code,0);},403);$_SESSION['verification_nonce']=$nonce;reject(static function()use($a,$mail,$code){$a->verification->validate($mail,'email',$code,1);},403);same($id,$a->verification->validate($mail,'register',$code,0));});
test('five wrong codes exhaust the challenge even when next code is correct',static function()use($a){[$mail,$code,$id]=emailFixture();for($i=0;$i<5;$i++){reject(static function()use($a,$mail){$a->verification->validate($mail,'register','bad',0);},403);}same(5,(int)$a->db->value('SELECT attempts FROM cy_email_challenges WHERE id=?',[$id]));reject(static function()use($a,$mail,$code){$a->verification->validate($mail,'register',$code,0);},403);});
test('expired code cannot validate',static function()use($a){[$mail,$code,$id]=emailFixture();$a->db->update('cy_email_challenges',$id,['expires_at'=>time()-1]);reject(static function()use($a,$mail,$code){$a->verification->validate($mail,'register',$code,0);},403);});
test('failed delivery never leaves a usable challenge',static function()use($a){$_SERVER['REMOTE_ADDR']='mail-'.key32();$mail='failed'.key32().'@example.test';$code='';reject(static function()use($a,$mail,&$code){$a->verification->request($mail,'register',0,static function($to,$s,$body)use(&$code){preg_match('/\b[0-9]{6}\b/',$body,$m);$code=$m[0];throw new RuntimeException('SMTP fixture failure');});},503);same('failed',$a->db->value('SELECT state FROM cy_email_challenges ORDER BY id DESC LIMIT 1'));reject(static function()use($a,$mail,$code){$a->verification->validate($mail,'register',$code,0);},403);});
test('mail rate limiter is shared across purposes and password recovery',static function()use($a){[$mail,$code,$id]=emailFixture();reject(static function()use($a,$mail){$a->verification->rateDelivery($mail);},429);});
settings('email',['email_registration_required'=>1]);
test('verified registration records proof and reward in one transaction',static function()use($a){[$mail,$code,$id]=emailFixture();$name='verified'.substr(key32(),0,12);$user=$a->auth->register(['username'=>$name,'email'=>$mail,'password'=>'Verified!12345','email_code'=>$code]);truth((int)account($user)['email_verified_at']>0);same('used',$a->db->value('SELECT state FROM cy_email_challenges WHERE id=?',[$id]));same((int)$a->settings->get('register_points'),funds($user,'points'));});
test('registration without required proof creates neither account nor reward',static function()use($a){$_SERVER['REMOTE_ADDR']='register-'.key32();$before=(int)$a->db->value('SELECT COUNT(*) FROM cy_users');reject(static function()use($a){$a->auth->register(['username'=>'noprof'.substr(key32(),0,10),'email'=>'missing@example.test','password'=>'Verified!12345']);},403);same($before,(int)$a->db->value('SELECT COUNT(*) FROM cy_users'));});
test('duplicate username does not spend a correct email proof',static function()use($a){[$mail,$code,$id]=emailFixture();reject(static function()use($a,$mail,$code){$a->auth->register(['username'=>'alice','email'=>$mail,'password'=>'Verified!12345','email_code'=>$code]);});same($id,$a->verification->validate($mail,'register',$code,0));});
test('email change requires current password and binds proof to current user',static function()use($a,$pwdUser){$a->auth->logout();$a->auth->login(account($pwdUser)['username'],'Updated!12345');[$mail,$code,$id]=emailFixture('email',$pwdUser);reject(static function()use($a,$mail,$code){$a->auth->changeEmail($mail,$code,'Wrong!12345');},403);same('sent',$a->db->value('SELECT state FROM cy_email_challenges WHERE id=?',[$id]));$old=resetFixture($pwdUser);$version=(int)account($pwdUser)['session_version'];$a->auth->changeEmail($mail,$code,'Updated!12345');same($mail,account($pwdUser)['email']);truth((int)account($pwdUser)['email_verified_at']>0);same($version+1,(int)account($pwdUser)['session_version']);reject(static function()use($a,$old){$a->auth->reset($old,'Wrong!12345');});});
settings('email',['email_registration_required'=>0,'smtp_enabled'=>0]);$_SERVER['REMOTE_ADDR']='test-fixture';
