<?php
/** 0.17 regressions use the same real database adapter as the rest of the suite. */
use Chengyu\Services\{SearchIndex,Learning,Tracking,Reconciliation};
function content17(array $extra=[]): int {global $a,$admin;return $a->content->save(account($admin),array_merge(['kind'=>'article','title'=>'Index fixture '.key32(),'excerpt'=>'Public metadata','body'=>'BODY-NEVER-INDEX-017','protected_body'=>'SECRET-NEVER-INDEX-017','status'=>'published','access_level'=>'public'],$extra),true);}
function layout17(string $title): string{return json_encode(['format'=>'chengyu-layout','version'=>1,'blocks'=>[['id'=>'intro','type'=>'heading','title'=>$title]]]);}
function course17(string $access='public',int $media=0): array {global $a,$admin;$content=content17(['access_level'=>$access,'price'=>'1.00','price_currency'=>'balance']);$course=$a->learning->saveCourse(account($admin),['content_id'=>$content,'title'=>'Course fixture','description'=>'Safe public introduction','active'=>1]);$lesson=$a->learning->saveLesson(account($admin),['course_id'=>$course,'title'=>'Private lesson','body'=>'LESSON-SECRET-017','duration_seconds'=>120,'media_id'=>$media,'active'=>1]);return [$content,$course,$lesson];}
function shipment17(string $carrier='shunfeng',string $number='SF12345678'): array {global $a,$admin;$u=buyer16();$sale=buy16($u,product('physical','balance','10.00',3));$order=unit16($sale);$shipment=$a->tracking->attach($admin,['order_id'=>$order['id'],'revision'=>0,'carrier'=>$carrier,'tracking_number'=>$number]);return [$u,$sale,$order,$shipment];}
function statement17(array $rows): string {$s=fopen('php://temp','w+');fputcsv($s,Reconciliation::HEADER,',','"','');foreach($rows as $r){fputcsv($s,$r,',','"','');}rewind($s);$text=stream_get_contents($s);fclose($s);return $text;}
settings('modules',['courses_enabled'=>1,'support_enabled'=>1]);settings('commerce',['tracking_enabled'=>1]);settings('discovery',['search_engine'=>'portable']);
test('017 migration is repeatable and retains existing data',static function()use($a){$n=(int)$a->db->value('SELECT COUNT(*) FROM cy_contents');\Chengyu\Core\Migration017::up($a->db);\Chengyu\Core\Migration017::up($a->db);same($n,(int)$a->db->value('SELECT COUNT(*) FROM cy_contents'));same(1,(int)$a->db->value('SELECT COUNT(*) FROM cy_search_state'));same(\Chengyu\Core\Migrations::VERSION,\Chengyu\Core\Migrations::version($a->db));});
test('017 active member count excludes guest checkout shadow identities',static function()use($a){$n=$a->memberCount();$id=buyer16();same($n+1,$a->memberCount());$a->db->update('cy_users',$id,['is_guest'=>1]);same($n,$a->memberCount());$a->db->update('cy_users',$id,['is_guest'=>0]);});
test('017 base and translated metadata do not overfetch public or paid bodies',static function()use($a,$admin){$id=content17();$item=$a->db->one('SELECT id,edit_version,title,excerpt FROM cy_contents WHERE id=?',[$id]);$a->translations->save($admin,['content_id'=>$id,'locale'=>'en-US','title'=>'Metadata only','excerpt'=>'summary','body'=>'PUBLIC BODY','source_version'=>$item['edit_version'],'revision'=>0,'status'=>'published']);$r=\Chengyu\Services\Translations::apply($a->db,[$item],'en-US')[0];same('Metadata only',$r['title']);same(false,array_key_exists('body',$r));same(false,array_key_exists('protected_body',$r));});
test('017 canonical URL preserves custom page identity without checkout secrets',static function()use($a){$r=$a->canonical('landing',['slot'=>'page4','claim'=>'SECRET','page'=>2]);truth(strpos($r,'slot=page4')!==false);truth(strpos($r,'SECRET')===false);truth(strpos($a->canonical('course',['id'=>4]),'id=4')!==false);});
test('017 independent site/admin locale selection survives context changes',static function(){$_SESSION=[];$_COOKIE=[];\Chengyu\Core\Locale::context('site');\Chengyu\Core\Locale::select('en-US','/',false,'site');\Chengyu\Core\Locale::select('zh-CN','/',false,'admin');same('en-US',\Chengyu\Core\Locale::current());\Chengyu\Core\Locale::context('admin');same('zh-CN',\Chengyu\Core\Locale::current());\Chengyu\Core\Locale::context('site');same('en-US',\Chengyu\Core\Locale::current());});
test('017 CJK bigrams and English normalization share a deterministic index',static function(){$word=json_decode('"\u6d4b\u8bd5\u8bfe\u7a0b"');$t=SearchIndex::tokens($word,true);same(3,count($t));same(['w:hello','w:world'],SearchIndex::tokens('HELLO world world',true));reject(static function(){SearchIndex::tokens("\xFF",true);});});
test('017 resumable rebuild finishes without indexing protected or public bodies',static function()use($a){$indexed=content17(['title'=>'indexunique public title']);$state=$a->search->rebuild(25,true);$guard=0;while(!$state['completed'] && $guard++<100){$state=$a->search->rebuild(25);}truth((bool)$state['completed']);truth($a->search->ready());same(0,$a->content->feed('all',null,['q'=>'SECRET NEVER INDEX 017'])['total']);same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_search_terms WHERE content_id=? AND token_hash=?',[$indexed,hash('sha256','w:body')]));});
test('017 indexed multi-token search ranks title, includes CJK and excludes false positives',static function()use($a){$a1=content17(['title'=>'orchidlunar maplelunar','excerpt'=>'']);$a2=content17(['title'=>'maplelunar','excerpt'=>'orchidlunar']);content17(['title'=>'orchidlunar only','excerpt'=>'']);$r=$a->content->feed('article',null,['q'=>'orchidlunar maplelunar']);same(2,$r['total']);same($a1,(int)$r['items'][0]['id']);$title=json_decode('"\u7d22\u5f15\u68c0\u7d22\u8bfe\u7a0b"');$id=content17(['title'=>$title]);truth(in_array($id,array_map('intval',array_column($a->content->feed('all',null,['q'=>$title])['items'],'id')),true));});
test('017 content edits update index and stale revisions fail closed',static function()use($a,$admin){$id=content17(['title'=>'oldpluto seventeen']);$row=$a->db->one('SELECT * FROM cy_contents WHERE id=?',[$id]);$a->content->save(account($admin),array_merge($row,['id'=>$id,'title'=>'newpluto seventeen','price'=>'0']),true);same(0,$a->content->feed('all',null,['q'=>'oldpluto'])['total']);same(1,$a->content->feed('all',null,['q'=>'newpluto'])['total']);$a->db->update('cy_contents',$id,['edit_version'=>999]);same(0,$a->content->feed('all',null,['q'=>'newpluto'])['total']);});
test('017 draft and future content are hidden by live permissions even if indexed',static function()use($a){$id=content17(['title'=>'visibilitycomet seventeen']);$a->db->update('cy_contents',$id,['status'=>'draft']);same(0,$a->content->feed('all',null,['q'=>'visibilitycomet'])['total']);$a->db->update('cy_contents',$id,['status'=>'published','publish_at'=>time()+86400]);same(0,$a->content->feed('all',null,['q'=>'visibilitycomet'])['total']);});
test('017 published translations are indexed but stale translation tokens disappear',static function()use($a,$admin){$id=content17();$row=$a->db->one('SELECT * FROM cy_contents WHERE id=?',[$id]);$a->translations->save($admin,['content_id'=>$id,'locale'=>'en-US','title'=>'translatedcomet seventeen','excerpt'=>'','body'=>'SECRET-NOT-INDEXED','source_version'=>$row['edit_version'],'revision'=>0,'status'=>'published']);same(1,$a->content->feed('all',null,['q'=>'translatedcomet'])['total']);$a->db->update('cy_contents',$id,['edit_version'=>(int)$row['edit_version']+1]);$a->search->sync($id);same(0,$a->content->feed('all',null,['q'=>'translatedcomet'])['total']);});
test('017 legacy search remains available while rebuilding',static function()use($a){$a->search->rebuild(1,true);same(false,$a->search->ready());$id=content17(['title'=>'fallbackcomet']);same(1,$a->content->feed('all',null,['q'=>'fallbackcomet'])['total']);$s=$a->search->rebuild(25);while(!$s['completed']){$s=$a->search->rebuild(25);}});
test('017 layout drafts never change published output',static function()use($a,$admin){$slot='page10';$live=$a->layout->get($slot);$rev=$a->layout->draft($admin,$slot,layout17('Draft seventeen'),$live['revision'],0);same(1,$rev);same($live,$a->layout->get($slot));same('Draft seventeen',$a->layout->editor($slot)['document']['blocks'][0]['title']);reject(static function()use($a,$admin,$slot,$live){$a->layout->draft($admin,$slot,layout17('Lost edit'),$live['revision'],0);},409);$a->layout->discard($admin,$slot,1);same(0,$a->layout->editor($slot)['draft_revision']);});
test('017 layout publish restores history using a new revision, not stale overwrite',static function()use($a,$admin){$slot='page9';$live=$a->layout->get($slot);$r=$a->layout->publish($admin,$slot,layout17('First publication'),$live['revision'],0);$a->layout->draft($admin,$slot,layout17('Second publication'),$r,0);$next=$a->layout->publish($admin,$slot,layout17('Second publication'),$r,1);same($r+1,$next);same(0,$a->layout->editor($slot)['draft_revision']);$back=$a->layout->restore($admin,$slot,$r,$next);same($next+1,$back);same('First publication',$a->layout->get($slot)['document']['blocks'][0]['title']);reject(static function()use($a,$admin,$slot,$r,$next){$a->layout->restore($admin,$slot,$r,$next);},409);});
test('017 restored layout marks an existing draft stale',static function()use($a,$admin){$slot='page9';$r=$a->layout->get($slot)['revision'];$a->layout->draft($admin,$slot,layout17('Unpublished'),$r,0);$a->layout->restore($admin,$slot,$r,$r);truth($a->layout->editor($slot)['stale']);reject(static function()use($a,$admin,$slot,$r){$a->layout->publish($admin,$slot,layout17('Unpublished'),$r,1);},409);$a->layout->discard($admin,$slot,1);});
test('017 layout history retains only the latest twenty snapshots',static function()use($a,$admin){$slot='page8';$rev=$a->layout->get($slot)['revision'];for($i=0;$i<22;$i++){$rev=$a->layout->save($admin,$slot,layout17('Revision '.$i),$rev);}same(20,count($a->layout->history($slot)));same(20,(int)$a->db->value('SELECT COUNT(*) FROM cy_layout_history WHERE slot=?',[$slot]));});
test('017 course permissions block members from creating lessons',static function()use($a){reject(static function()use($a){$a->learning->saveCourse(account(buyer16()),['content_id'=>1,'title'=>'bad']);},403);});
test('017 paid course previews do not expose other lesson bodies',static function()use($a,$admin){[$content,$course,$lesson]=course17('paid');same(false,$a->learning->course($course,null)['allowed']);reject(static function()use($a,$lesson){$a->learning->lesson($lesson,null);},403);$preview=$a->learning->saveLesson(account($admin),['course_id'=>$course,'title'=>'Preview','body'=>'PREVIEW-017','active'=>1,'preview'=>1]);same('PREVIEW-017',$a->learning->lesson($preview,null)['body']);same(false,array_key_exists('body',$a->learning->course($course,null)['lessons'][0]));});
test('017 paid lesson permission is rechecked after a completed refund',static function()use($a,$admin){[$content,$course,$lesson]=course17('paid');$u=buyer16();$sale=buy16($u,$content);same('LESSON-SECRET-017',$a->learning->lesson($lesson,account($u))['body']);$o=unit16($sale);$case=$a->aftersales->request($u,(int)$o['id'],'refund','Course fixture');$a->aftersales->review($admin,$case,1,'approve','Approved');$rid=(int)$a->db->value('SELECT id FROM cy_refunds WHERE order_id=?',[$o['id']]);$a->refunds->run($rid);reject(static function()use($a,$lesson,$u){$a->learning->lesson($lesson,account($u));},403);});
test('017 archived course and source publication immediately withdraw access',static function()use($a){[$content,$course,$lesson]=course17();same('LESSON-SECRET-017',$a->learning->lesson($lesson,null)['body']);$a->db->update('cy_courses',$course,['active'=>0]);reject(static function()use($a,$lesson){$a->learning->lesson($lesson,null);},404);$a->db->update('cy_courses',$course,['active'=>1]);$a->db->update('cy_contents',$content,['status'=>'draft']);reject(static function()use($a,$lesson){$a->learning->lesson($lesson,null);},404);});
test('017 progress is private, clamped, revision-checked and self-reported',static function()use($a){[$content,$course,$lesson]=course17();$u=buyer16();$v=buyer16();$r=$a->learning->saveProgress(account($u),['lesson_id'=>$lesson,'revision'=>0,'position_seconds'=>999,'note'=>'private student note','completed'=>1]);same(120,$r['position_seconds']);same(1,$r['revision']);same('',$a->learning->progress(account($v),$lesson)['note']);same('private student note',$a->learning->progress(account($u),$lesson)['note']);reject(static function()use($a,$u,$lesson){$a->learning->saveProgress(account($u),['lesson_id'=>$lesson,'revision'=>0]);},409);});
test('017 lesson source and course source cannot be reassigned by stale forms',static function()use($a,$admin){[$content,$course,$lesson]=course17();$other=content17();reject(static function()use($a,$admin,$course,$other){$a->learning->saveCourse(account($admin),['id'=>$course,'revision'=>1,'content_id'=>$other,'title'=>'Move','active'=>1]);});reject(static function()use($a,$admin,$course,$lesson){$a->learning->saveLesson(account($admin),['id'=>$lesson,'revision'=>0,'course_id'=>$course,'title'=>'Stale','active'=>1]);},409);});
test('017 private media inherits the course entitlement and disappears after archive',static function()use($a,$admin,$tmp){$body='RESOURCE 017';$r=$a->uploads->start(account($admin),'lesson-resource.txt',strlen($body));$path=$tmp.'/resource017';file_put_contents($path,$body);$a->uploads->put(account($admin),$r['upload_key'],0,$path);$media=$a->uploads->finish(account($admin),$r['upload_key']);[$content,$course,$lesson]=course17('paid',$media);$u=buyer16();reject(static function()use($a,$media,$u){$a->media->readable($media,account($u));},403);buy16($u,$content);same($media,(int)$a->media->readable($media,account($u))['id']);$a->db->update('cy_courses',$course,['active'=>0]);reject(static function()use($a,$media,$u){$a->media->readable($media,account($u));},403);});
test('017 shipment state is encrypted, owner-scoped and revision-checked',static function()use($a,$admin){[$u,$sale,$order,$shipment]=shipment17();$row=$a->db->one('SELECT * FROM cy_shipments WHERE id=?',[$shipment]);truth(strpos($row['tracking_cipher'],'SF12345678')===false);same('SF12345678',$a->tracking->view((int)$order['id'],account($u))['tracking_number']);reject(static function()use($a,$order){$a->tracking->view((int)$order['id'],account(buyer16()));},404);reject(static function()use($a,$admin,$order){$a->tracking->attach($admin,['order_id'=>$order['id'],'revision'=>0,'carrier'=>'shunfeng','tracking_number'=>'SF12345678']);},409);});
test('017 manual shipment events never automatically confirm receipt',static function()use($a,$admin){[$u,$sale,$order,$shipment]=shipment17();$a->tracking->addEvent($admin,$shipment,1,time(),'Customer reports delivery');$r=$a->tracking->view((int)$order['id'],account($u));same(1,count($r['events']));same('Customer reports delivery',$r['events'][0]['text']);same('shipped',$a->db->value('SELECT fulfillment FROM cy_orders WHERE id=?',[$order['id']]));truth(strpos((string)$a->db->value('SELECT description FROM cy_tracking_events WHERE shipment_id=?',[$shipment]),'Customer reports')===false);});
test('017 missing carrier phone does not consume the query interval',static function()use($a,$admin){settings('commerce',['tracking_provider'=>'kuaidi100','tracking_customer'=>'fixture-customer','tracking_key'=>'fixture-key']);[$u,$sale,$order,$shipment]=shipment17();reject(static function()use($a,$admin,$shipment){$a->tracking->refresh($admin,$shipment);});same(0,(int)$a->db->value('SELECT queried_at FROM cy_shipments WHERE id=?',[$shipment]));});
test('017 carrier query signs exact parameters and caches matching results without financial side effects',static function()use($a,$admin){[$u,$sale,$order,$shipment]=shipment17();$calls=0;$client=new \Chengyu\Core\HttpClient(static function($method,$url,$headers,$body)use(&$calls){$calls++;parse_str($body,$f);same('POST',$method);same('https://poll.kuaidi100.com/poll/query.do',$url);same(strtoupper(md5($f['param'].'fixture-key'.'fixture-customer')),$f['sign']);$p=json_decode($f['param'],true);same('123456789',$p['phone']);return response15(['status'=>'200','com'=>'shunfeng','nu'=>'SF12345678','state'=>'3','data'=>[['ftime'=>'2026-09-01 12:00:00','context'=>'Delivered by carrier']]]);});$service=new Tracking($a,$client);$before=funds($u);$service->refresh($admin,$shipment,'123456789');same(1,$calls);same('3',$service->view((int)$order['id'],account($u))['state']);same($before,funds($u));same('shipped',$a->db->value('SELECT fulfillment FROM cy_orders WHERE id=?',[$order['id']]));reject(static function()use($service,$admin,$shipment){$service->refresh($admin,$shipment,'123456789');},429);same(1,$calls);});
test('017 mismatched carrier identity is rejected instead of replacing a timeline',static function()use($a,$admin){[$u,$sale,$order,$shipment]=shipment17('yunda','YD12345678');$service=new Tracking($a,new \Chengyu\Core\HttpClient(static function(){return response15(['status'=>'200','com'=>'yunda','nu'=>'OTHER','state'=>'3','data'=>[]]);}));reject(static function()use($service,$admin,$shipment){$service->refresh($admin,$shipment);},502);same(0,count($service->view((int)$order['id'],account($u))['events']));});
test('017 shipment edits while querying discard stale carrier responses',static function()use($a,$admin){[$u,$sale,$order,$shipment]=shipment17('yunda','YD12345678');$service=new Tracking($a,new \Chengyu\Core\HttpClient(static function()use($a,$shipment){$a->db->update('cy_shipments',$shipment,['revision'=>2]);return response15(['status'=>'200','com'=>'yunda','nu'=>'YD12345678','state'=>'3','data'=>[]]);}));reject(static function()use($service,$admin,$shipment){$service->refresh($admin,$shipment);},409);same('pending',$service->view((int)$order['id'],account($u))['state']);});
test('017 statement date requires explicit timezone and a real calendar date',static function(){same(1788220800,Reconciliation::timestamp('2026-09-01T00:00:00Z'));foreach(['2026-09-01','2026-02-30T00:00:00Z','2026-09-01T00:00:00'] as $x){reject(static function()use($x){Reconciliation::timestamp($x);});}});
test('017 statement parser rejects formulas, decimal minor units and duplicate references atomically',static function()use($a,$admin){$date=gmdate('Y-m-d\TH:i:s\Z');$row=['payment','CYFixture','pi_fixture','CNY','100','succeeded',$date];$start=time()-3600;$end=time()+3600;$n=(int)$a->db->value('SELECT COUNT(*) FROM cy_recon_batches');foreach(['formula','decimal','duplicate','currency','header'] as $case){$rows=[$row];if($case==='formula'){$rows[0][1]='=1+1';}if($case==='decimal'){$rows[0][4]='1.00';}if($case==='duplicate'){$rows[]=$row;}if($case==='currency'){$rows[0][3]='JPY';}$csv=statement17($rows);if($case==='header'){$csv='wrong,header' . "\n".$csv;}reject(static function()use($a,$admin,$csv,$start,$end){$a->reconciliation->import($admin,'stripe',$csv,$start,$end);});}same($n,(int)$a->db->value('SELECT COUNT(*) FROM cy_recon_batches'));});
test('017 statement import is idempotent and report-only with bidirectional differences',static function()use($a,$admin){$u=buyer16();$s=buy16($u,product(),1,'stripe');$trade='pi_'.key32();$a->checkout->settle((int)$s['id'],\Chengyu\Payments\Tools::receipt($s,$trade,100,'CNY',$s['sale_no']));$date=gmdate('Y-m-d\TH:i:s\Z');$csv=statement17([['payment',$s['sale_no'],$trade,'CNY','100','succeeded',$date],['payment','EXTERNAL'.key32(),'pi_external','CNY','900','succeeded',$date]]);$start=time()-3600;$end=time()+3600;$balance=funds($u);$ledger=(int)$a->db->value('SELECT COUNT(*) FROM cy_ledger');$batch=$a->reconciliation->import($admin,'stripe',$csv,$start,$end);same($batch,$a->reconciliation->import($admin,'stripe',$csv,$start,$end));same('matched',$a->db->value('SELECT outcome FROM cy_recon_rows WHERE batch_id=? AND reference=?',[$batch,$s['sale_no']]));same(1,(int)$a->db->value("SELECT COUNT(*) FROM cy_recon_rows WHERE batch_id=? AND outcome='external_only'",[$batch]));truth((int)$a->db->value("SELECT COUNT(*) FROM cy_recon_rows WHERE batch_id=? AND outcome='local_only'",[$batch])>0);$a->reconciliation->check($admin,$batch);same($balance,funds($u));same($ledger,(int)$a->db->value('SELECT COUNT(*) FROM cy_ledger'));});
test('017 statement amount mismatch cannot mutate a verified sale',static function()use($a,$admin){$u=buyer16();$s=buy16($u,product(),1,'stripe');$trade='pi_'.key32();$a->checkout->settle((int)$s['id'],\Chengyu\Payments\Tools::receipt($s,$trade,100,'CNY',$s['sale_no']));$csv=statement17([['payment',$s['sale_no'],$trade,'CNY','1','succeeded',gmdate('Y-m-d\TH:i:s\Z')]]);$batch=$a->reconciliation->import($admin,'stripe',$csv,time()-3600,time()+3600);same('amount_mismatch',$a->db->value('SELECT outcome FROM cy_recon_rows WHERE batch_id=? AND reference=?',[$batch,$s['sale_no']]));same(100,(int)$a->db->value('SELECT amount FROM cy_sales WHERE id=?',[$s['id']]));});
test('017 ticket creation is owner-bound and repeat submission idempotent',static function()use($a){$u=buyer16();$v=buyer16();$in=['subject'=>'Support fixture','body'=>'Private support contents','request_key'=>key32()];$id=$a->support->create(account($u),$in);same($id,$a->support->create(account($u),$in));same(1,count($a->support->replies(account($u),$id)));reject(static function()use($a,$v,$id){$a->support->ticket(account($v),$id);},404);$in['body']='Different payload';reject(static function()use($a,$u,$in){$a->support->create(account($u),$in);},409);});
test('017 tickets cannot attach another buyers order',static function()use($a){$u=buyer16();$v=buyer16();$order=unit16(buy16($u,product()));reject(static function()use($a,$v,$order){$a->support->create(account($v),['subject'=>'bad','body'=>'bad','order_id'=>$order['id'],'request_key'=>key32()]);},404);});
test('017 support replies use revision conflicts, deduplication and owner notifications',static function()use($a,$admin){$u=buyer16();$id=$a->support->create(account($u),['subject'=>'Question','body'=>'details','request_key'=>key32()]);$in=['ticket_id'=>$id,'revision'=>1,'body'=>'Human approved reply','request_key'=>key32()];same(2,$a->support->reply(account($admin),$in));same(2,$a->support->reply(account($admin),$in));same('waiting',$a->support->ticket(account($u),$id)['status']);same(2,count($a->support->replies(account($u),$id)));$in['request_key']=key32();reject(static function()use($a,$admin,$in){$a->support->reply(account($admin),$in);},409);truth((int)$a->db->value('SELECT COUNT(*) FROM cy_notifications WHERE user_id=?',[$u])>0);});
test('017 members cannot set urgent priority or staff-only support states',static function()use($a,$admin){$u=buyer16();$id=$a->support->create(account($u),['subject'=>'Question','body'=>'details','request_key'=>key32()]);reject(static function()use($a,$u,$id){$a->support->status(account($u),$id,1,'resolved','urgent');});$a->support->status(account($u),$id,1,'closed','urgent');same('normal',$a->support->ticket(account($u),$id)['priority']);reject(static function()use($a,$u,$id){$a->support->reply(account($u),['ticket_id'=>$id,'revision'=>2,'body'=>'blocked','request_key'=>key32()]);},409);$a->support->status(account($u),$id,2,'open');same('open',$a->support->ticket(account($u),$id)['status']);});
test('017 support templates require staff and prevent lost updates',static function()use($a,$admin){$in=['title'=>'Refund policy','body'=>'We will check your request.','active'=>1];$id=$a->support->template(account($admin),$in);reject(static function()use($a,$in){$a->support->template(account(buyer16()),$in);},403);$a->support->template(account($admin),$in+['id'=>$id,'revision'=>1]);reject(static function()use($a,$admin,$in,$id){$a->support->template(account($admin),$in+['id'=>$id,'revision'=>1]);},409);});
test('017 module switches deny new private and public feature entrypoints',static function()use($a){[$content,$course,$lesson]=course17();$u=buyer16();settings('modules',['courses_enabled'=>0,'support_enabled'=>0]);try{reject(static function()use($a,$course){$a->learning->course($course,null);},403);reject(static function()use($a,$u){$a->support->listing(account($u));},403);}finally{settings('modules',['courses_enabled'=>1,'support_enabled'=>1]);}});
test('017 Alipay desktop page-pay preserves the RSA2 signature and exact amount',static function()use($private16,$public16){$sale=gatewaySale16();$c=['alipay_direct_mode'=>'page','alipay_direct_appid'=>'fixtureapp','alipay_direct_private'=>$private16,'alipay_direct_public'=>$public16];$driver=new \Chengyu\Payments\Alipay($c,new \Chengyu\Core\HttpClient());$r=$driver->create($sale);parse_str(parse_url($r['url'],PHP_URL_QUERY),$fields);same('alipay.trade.page.pay',$fields['method']);$biz=json_decode($fields['biz_content'],true);same('FAST_INSTANT_TRADE_PAY',$biz['product_code']);same('12.00',$biz['total_amount']);$sig=$fields['sign'];unset($fields['sign']);ksort($fields);$pairs=[];foreach($fields as $k=>$v){$pairs[]=$k.'='.$v;}\Chengyu\Payments\Tools::rsaVerify(implode('&',$pairs),$sig,$public16);});
test('017 dynamic headings, empty states and reconciliation messages have Chinese translations',static function(){\Chengyu\Core\Locale::context('site');$_SESSION=['locale_site'=>'zh-CN'];$_COOKIE=[];foreach(['Small chapters. Useful knowledge. A journey you can return to.','Turn an article or digital product into a structured learning journey.','Indexed documents','No support tickets yet.','Amount, currency, trade and state agree.','Your support ticket has a reply','Carrier update'] as $key){truth(\Chengyu\Core\Locale::translate($key)!==$key);}});
\Chengyu\Core\Locale::context('site');$_SESSION=[];$_COOKIE=[];
