<?php
use Chengyu\Core\HttpClient;
use Chengyu\Services\{S3,Translations,Uploads};
function raw16(string $body,array $headers=[],int $status=200): string {$out='HTTP/1.1 '.$status." OK\r\n";foreach($headers as $k=>$v){$out.=$k.': '.$v."\r\n";}if(!isset($headers['Content-Length'])){$out.='Content-Length: '.strlen($body)."\r\n";}return $out."\r\n".$body;}
function s3config16(): array {return ['endpoint'=>'https://bucket.example.com','bucket'=>'fixture-bucket','prefix'=>'chengyu','region'=>'us-east-1','access'=>'AKIAIOSFODNN7EXAMPLE','secret'=>'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY','token'=>''];}
test('016 local resumable chunks reject cross-owner writes and missing pieces',static function()use($a,$admin,$tmp){$u=account($admin);$r=$a->uploads->start($u,'notes.txt',Uploads::CHUNK+3);$f=$tmp.'/piece';file_put_contents($f,str_repeat('A',Uploads::CHUNK));$a->uploads->put($u,$r['upload_key'],0,$f);$a->uploads->put($u,$r['upload_key'],0,$f);same([0],$a->uploads->status($u,$r['upload_key'])['parts']);reject(static function()use($a,$u,$r){$a->uploads->finish($u,$r['upload_key']);},409);$v=account(buyer16());$v['role']='admin';reject(static function()use($a,$v,$r){$a->uploads->status($v,$r['upload_key']);},404);file_put_contents($f,str_repeat('B',Uploads::CHUNK));reject(static function()use($a,$u,$r,$f){$a->uploads->put($u,$r['upload_key'],0,$f);},409);$a->uploads->cancel($u,$r['upload_key']);});
test('016 chunk completion checks hashes and streams into a protected media envelope once',static function()use($a,$admin,$tmp){$u=account($admin);$body=str_repeat('chunk fixture ',24000);$r=$a->uploads->start($u,'large.txt',strlen($body),hash('sha256',$body));foreach(str_split($body,Uploads::CHUNK) as $i=>$part){$f=$tmp.'/part';file_put_contents($f,$part);$a->uploads->put($u,$r['upload_key'],$i,$f);}$id=$a->uploads->finish($u,$r['upload_key']);same($id,$a->uploads->finish($u,$r['upload_key']));$media=$a->media->readable($id,$u);same('text/plain',$media['mime']);same(strlen($body),(int)$media['bytes']);same(\Chengyu\Services\Media::GUARD.$body,file_get_contents($a->config['storage'].'/blobs/'.$media['file_key']));reject(static function()use($a,$u,$r){$a->uploads->cancel($u,$r['upload_key']);},409);});
test('016 corrupted chunks and wrong whole-file hashes never register media',static function()use($a,$admin,$tmp){$u=account($admin);$r=$a->uploads->start($u,'wrong.txt',4,str_repeat('0',64));$f=$tmp.'/wrong';file_put_contents($f,'TEXT');$a->uploads->put($u,$r['upload_key'],0,$f);reject(static function()use($a,$u,$r){$a->uploads->finish($u,$r['upload_key']);},409);$a->uploads->cancel($u,$r['upload_key']);});
test('016 executable and SVG chunks cannot bypass the shared MIME policy',static function()use($a,$admin,$tmp){$u=account($admin);foreach(['evil.php'=>'<?php echo "evil";','evil.svg'=>'<svg xmlns="http://www.w3.org/2000/svg"><script>evil</script></svg>'] as $name=>$text){$r=$a->uploads->start($u,$name,strlen($text));$f=$tmp.'/unsafe';file_put_contents($f,$text);$a->uploads->put($u,$r['upload_key'],0,$f);reject(static function()use($a,$u,$r){$a->uploads->finish($u,$r['upload_key']);});$a->uploads->cancel($u,$r['upload_key']);}});
test('016 S3 presigned signature matches an independent fixed-time implementation',static function(){$s3=new S3(s3config16());$r=$s3->presign('GET','chengyu/test.txt',120,[],[],1369353600);parse_str(parse_url($r['url'],PHP_URL_QUERY),$q);same('8af90e8b804c1d983aee3d97f548d4da8316fa21ee214a4a9e76b5f5dd5a9576',$q['X-Amz-Signature']);same('20130524T000000Z',$q['X-Amz-Date']);same('host',$q['X-Amz-SignedHeaders']);});
test('016 S3 limits signatures to a safe namespace and brief link lifetime',static function(){$s3=new S3(s3config16());reject(static function()use($s3){$s3->presign('GET','../secret');});reject(static function()use($s3){$s3->presign('GET','file',901);});reject(static function()use($s3){$s3->presign('GET','file',60,[],['X-Amz-Credential'=>'evil']);});$c=s3config16();$c['endpoint']='https://127.0.0.1/bucket';reject(static function()use($c){new S3($c);});});
test('016 S3 CopyObject rejects embedded error despite HTTP 200',static function(){$s3=new S3(s3config16(),new HttpClient(static function(){return raw16('<Error><Code>SlowDown</Code></Error>');}));reject(static function()use($s3){$s3->copy('chengyu/staging/x','chengyu/media/x','"abcdef"',[]);},502);});
test('016 S3 conditional copy binds the inspected source entity tag',static function(){$s3=new S3(s3config16(),new HttpClient(static function($method,$url,$headers,$body){same('PUT',$method);same('"abcdef"',$headers['x-amz-copy-source-if-match']);same('/fixture-bucket/chengyu/staging/x',$headers['x-amz-copy-source']);truth(strpos($headers['authorization'],'AWS4-HMAC-SHA256 Credential=')===0);return raw16('<CopyObjectResult><ETag>&quot;abcdef&quot;</ETag></CopyObjectResult>');}));$s3->copy('chengyu/staging/x','chengyu/media/x','"abcdef"',[]);});
test('016 published translations are source-version-bound and never alter protected body',static function()use($a,$admin){$id=$a->content->save(account($admin),['kind'=>'article','title'=>'Source translation fixture','body'=>'PUBLIC ORIGIN','protected_body'=>'NEVER TRANSLATE SECRET','status'=>'published','access_level'=>'paid'],true);$item=$a->db->one('SELECT * FROM cy_contents WHERE id=?',[$id]);$in=['content_id'=>$id,'locale'=>'en-US','title'=>'Translated title','excerpt'=>'Translated summary','body'=>'Translated public body','source_version'=>$item['edit_version'],'revision'=>0,'status'=>'published'];$a->translations->save($admin,$in);$translated=Translations::apply($a->db,[$item],'en-US')[0];same('Translated title',$translated['title']);same('NEVER TRANSLATE SECRET',$translated['protected_body']);reject(static function()use($a,$admin,$in){$a->translations->save($admin,$in);},409);$a->db->update('cy_contents',$id,['edit_version'=>(int)$item['edit_version']+1]);$changed=$a->db->one('SELECT * FROM cy_contents WHERE id=?',[$id]);same($changed['title'],Translations::apply($a->db,[$changed],'en-US')[0]['title']);});
test('016 automatic translation sends only public fields and stores drafts',static function()use($a,$admin){settings('international',['translation_endpoint'=>'https://translate.example.com/translate']);$id=$a->content->save(account($admin),['kind'=>'article','title'=>'Machine fixture','body'=>'PUBLIC ORIGIN','protected_body'=>'DO NOT SEND SECRET','status'=>'draft','access_level'=>'paid'],true);$calls=0;$service=new Translations($a,new HttpClient(static function($method,$url,$headers,$body)use(&$calls){$calls++;truth(strpos($body,'SECRET')===false);return response15(['translatedText'=>'Machine suggestion '.$calls]);}));$tid=$service->generate($admin,$id,'zh','en-US',0);$t=$a->db->one('SELECT * FROM cy_translations WHERE id=?',[$tid]);same('draft',$t['status']);truth($calls>=2);same('Machine fixture',Translations::apply($a->db,[$a->db->one('SELECT * FROM cy_contents WHERE id=?',[$id])],'en-US')[0]['title']);});
test('016 token search requires every term, ranks titles and never searches paid secrets',static function()use($a,$admin){$ids=[];foreach([['alphaomega betazeta','plain'],['betazeta only','alphaomega summary'],['alphaomega only','plain']] as $v){$ids[]=$a->content->save(account($admin),['kind'=>'article','title'=>$v[0],'excerpt'=>$v[1],'body'=>'PUBLIC','protected_body'=>'DO_NOT_SEARCH_HIDDEN_016','status'=>'published','access_level'=>'paid'],true);}$feed=$a->content->feed('article',null,['q'=>'alphaomega betazeta']);same(2,$feed['total']);same($ids[0],(int)$feed['items'][0]['id']);same(0,$a->content->feed('all',null,['q'=>'DO_NOT_SEARCH_HIDDEN_016'])['total']);});
test('016 site compositions validate audience, custom pages and media IDs',static function()use($a,$admin){$doc=['format'=>'chengyu-layout','version'=>1,'blocks'=>[['id'=>'hero1','type'=>'hero','title'=>'HELLO','audience'=>'vip','min_vip_tier'=>2],['id'=>'media1','type'=>'media','media_id'=>123],['id'=>'faq1','type'=>'faq','text'=>'Question|Answer']]];$a->layout->save($admin,'global_before',json_encode($doc),0);same(3,count($a->layout->get('global_before')['document']['blocks']));$a->layout->save($admin,'page12',json_encode($doc),0);$doc['blocks'][0]['audience']='execute';reject(static function()use($a,$doc){$a->layout->validate(json_encode($doc));});});
function gatewaySale16(string $currency='CNY'): array {return ['sale_no'=>'CY202600001','remote_id'=>'cs_fixture','trade_no'=>'trade_fixture','amount'=>1200,'currency'=>$currency,'expires_at'=>time()+3600,'return_url'=>'https://island.example.com/index.php?r=receipt','notify_url'=>'https://island.example.com/notify-direct.php','payer_ip'=>'8.8.8.8'];}
test('016 Stripe exact binding, mode, amount and currency verification',static function(){$sale=gatewaySale16();$response=['id'=>'cs_fixture','mode'=>'payment','client_reference_id'=>$sale['sale_no'],'livemode'=>false,'payment_status'=>'paid','payment_intent'=>'pi_fixture','amount_total'=>1200,'currency'=>'cny'];foreach(['valid','mode','currency','amount','live','reference'] as $case){$body=$response;if($case==='mode'){$body['mode']='subscription';}if($case==='currency'){$body['currency']='usd';}if($case==='amount'){$body['amount_total']=1;}if($case==='live'){$body['livemode']=true;}if($case==='reference'){$body['client_reference_id']='other';}$driver=new \Chengyu\Payments\Stripe(['stripe_secret'=>'sk_test_fixture'],new HttpClient(static function()use($body){return response15($body);}));if($case==='valid'){same('paid',$driver->query($sale)['state']);}else{reject(static function()use($driver,$sale){$driver->query($sale);},409);}}});
test('016 Stripe HMAC rejects replay age and modified bytes',static function(){$driver=new \Chengyu\Payments\Stripe(['stripe_webhook_secret'=>'whsec_fixture'],new HttpClient());$raw=json_encode(['type'=>'checkout.session.completed','data'=>['object'=>['id'=>'cs_fixture']]]);$time=time();$sig=hash_hmac('sha256',$time.'.'.$raw,'whsec_fixture');same('cs_fixture',$driver->notification($raw,['stripe-signature'=>'t='.$time.',v1='.$sig]));reject(static function()use($driver,$raw,$time,$sig){$driver->notification($raw.' ',['stripe-signature'=>'t='.$time.',v1='.$sig]);},403);$old=$time-400;reject(static function()use($driver,$raw,$old){$driver->notification($raw,['stripe-signature'=>'t='.$old.',v1='.hash_hmac('sha256',$old.'.'.$raw,'whsec_fixture')]);},403);});
$key16=openssl_pkey_new(['private_key_bits'=>2048,'private_key_type'=>OPENSSL_KEYTYPE_RSA]);openssl_pkey_export($key16,$private16);$public16=openssl_pkey_get_details($key16)['key'];
test('016 Alipay RSA2 signs requests and verifies exact original response bytes',static function()use($private16,$public16){$sale=gatewaySale16();$c=['alipay_direct_sandbox'=>true,'alipay_direct_appid'=>'fixtureapp','alipay_direct_seller'=>'fixtureseller','alipay_direct_private'=>$private16,'alipay_direct_public'=>$public16];$driver=new \Chengyu\Payments\Alipay($c,new HttpClient(static function($method,$url,$headers,$body)use($private16,$public16,$sale){parse_str($body,$fields);$sig=$fields['sign'];unset($fields['sign']);ksort($fields);$pairs=[];foreach($fields as $k=>$v){$pairs[]=$k.'='.$v;}\Chengyu\Payments\Tools::rsaVerify(implode('&',$pairs),$sig,$public16);$r=json_encode(['code'=>'10000','out_trade_no'=>$sale['sale_no'],'trade_no'=>'ali_trade','total_amount'=>'12.00','trade_status'=>'TRADE_SUCCESS']);return raw16('{"alipay_trade_query_response":'.$r.',"sign":'.json_encode(\Chengyu\Payments\Tools::rsaSign($r,$private16)).'}');}));same('ali_trade',$driver->query($sale)['trade']);$notify=['app_id'=>'fixtureapp','seller_id'=>'fixtureseller','out_trade_no'=>$sale['sale_no'],'sign_type'=>'RSA2'];$notify['sign']=\Chengyu\Payments\Tools::rsaSign(\Chengyu\Payments\Alipay::canonical($notify),$private16);same($sale['sale_no'],$driver->notification(http_build_query($notify),[]));$notify['seller_id']='other';reject(static function()use($driver,$notify){$driver->notification(http_build_query($notify),[]);},403);});
test('016 duplicate signed JSON fields are rejected before settlement',static function(){reject(static function(){\Chengyu\Payments\Tools::members('{"x":{},"x":{},"sign":"anything"}');},502);});
test('016 WeChat RSA response binds merchant, app, timestamp and platform serial',static function()use($private16,$public16){$c=['wechat_mchid'=>'merchant1','wechat_appid'=>'app1','wechat_serial'=>'MERCHANTSERIAL','wechat_private'=>$private16,'wechat_platform_serial'=>'PLATFORMSERIAL','wechat_platform_public'=>$public16];$sale=gatewaySale16();$driver=new \Chengyu\Payments\Wechat($c,new HttpClient(static function($method,$url,$headers,$body)use($private16,$sale){truth(strpos($headers['Authorization'],'WECHATPAY2-SHA256-RSA2048')===0);$raw=json_encode(['mchid'=>'merchant1','appid'=>'app1','out_trade_no'=>$sale['sale_no'],'trade_state'=>'SUCCESS','transaction_id'=>'wxtrade','amount'=>['total'=>1200,'currency'=>'CNY']]);$t=(string)time();$nonce='fixture';return raw16($raw,['Wechatpay-Timestamp'=>$t,'Wechatpay-Nonce'=>$nonce,'Wechatpay-Serial'=>'PLATFORMSERIAL','Wechatpay-Signature'=>\Chengyu\Payments\Tools::rsaSign($t."\n".$nonce."\n".$raw."\n",$private16)]);}));same('wxtrade',$driver->query($sale)['trade']);reject(static function()use($driver){$driver->verify('{}',['wechatpay-timestamp'=>(string)time(),'wechatpay-nonce'=>'n','wechatpay-serial'=>'UNKNOWN']);},403);});
test('016 PayPal active capture validates merchant and amount before fulfillment',static function(){$sale=gatewaySale16('USD');$sale['remote_id']='PAYPALORDER';$c=['paypal_sandbox'=>true,'paypal_id'=>'client','paypal_secret'=>'secret','paypal_merchant'=>'merchant'];$driver=new \Chengyu\Payments\PayPal($c,new HttpClient(static function($method,$url,$headers,$body)use($sale){if(strpos($url,'oauth2/token')!==false){return response15(['access_token'=>'token','expires_in'=>300]);}$unit=['reference_id'=>$sale['sale_no'],'payee'=>['merchant_id'=>'merchant'],'amount'=>['currency_code'=>'USD','value'=>'12.00']];if($method==='POST'){same('capture-'.$sale['sale_no'],$headers['PayPal-Request-Id']);$unit['payments']=['captures'=>[['id'=>'CAPTURE','status'=>'COMPLETED','amount'=>['value'=>'12.00','currency_code'=>'USD']]]];}return response15(['id'=>'PAYPALORDER','status'=>$method==='POST'?'COMPLETED':'APPROVED','purchase_units'=>[$unit]]);}));same('CAPTURE',$driver->query($sale)['trade']);});

test('016 object lifecycle uses conditional immutable copy, recovers a lost response and returns one media ID',static function()use($a,$admin){
    $saved=[];foreach(['object_storage_enabled','s3_endpoint','s3_region','s3_access','s3_secret','s3_bucket','s3_prefix'] as $key){$saved[$key]=$a->settings->get($key);}
    $cfg=s3config16();$seed=['object_storage_enabled'=>true];foreach(['endpoint','region','access','secret','bucket','prefix'] as $key){$seed['s3_'.$key]=$cfg[$key];}settings('media_plus',$seed);
    try{
        $data='A private object lifecycle fixture.';$etag='"fixture-etag"';$manifest=null;$copied=false;$copyCount=0;$loseResponse=true;
        $http=new HttpClient(static function($method,$url,$headers,$body)use(&$manifest,$data,$etag,&$copied,&$copyCount,&$loseResponse){
            $isFinal=strpos($url,'/media/')!==false;
            $head=['Content-Type'=>'text/plain','Content-Length'=>(string)strlen($data),'ETag'=>$etag,'x-amz-meta-cy-id'=>$manifest['upload_key']];
            if($isFinal){$head['x-amz-meta-cy-source']=hash('sha256',$etag);}
            if($method==='HEAD'){if($isFinal&&!$copied){return raw16('',[],404);}return raw16('',$head);}
            if($method==='GET'){same($etag,$headers['if-match']);return raw16($data,$head,206);}
            same('PUT',$method);same($etag,$headers['x-amz-copy-source-if-match']);truth(strpos($headers['x-amz-copy-source'],'/staging/'.$manifest['upload_key'])!==false);
            $copied=true;$copyCount++;
            if($loseResponse){$loseResponse=false;throw new \Chengyu\Core\Problem('Fixture: copy response lost.',502);}
            return raw16('<CopyObjectResult><ETag>"copied"</ETag></CopyObjectResult>');
        });
        $objects=new \Chengyu\Services\ObjectStorage($a,$http);$u=account($admin);$manifest=$objects->prepare($u,'private.txt',strlen($data));
        truth(strpos($manifest['url'],'/staging/')!==false);truth(strpos($manifest['url'],'content-length')!==false);truth(!isset($manifest['headers']['content-length']));
        reject(static function()use($objects,$u,$manifest){$objects->finish($u,$manifest['upload_key']);},502);
        $id=$objects->finish($u,$manifest['upload_key']);same($id,$objects->finish($u,$manifest['upload_key']));same(1,$copyCount);
        $media=$a->db->one('SELECT * FROM cy_media WHERE id=?',[$id]);same('s3',$media['backend']);same(1,(int)$media['is_private']);
        $url=$objects->download($media);truth(strpos($url,'/media/')!==false);truth(strpos($url,'/staging/')===false);truth(strpos($url,'X-Amz-Expires=120')!==false);
        reject(static function()use($a,$id){$a->media->readable($id,null);},403);
    }finally{foreach($saved as $key=>$value){if($value===''&&($a->settings->schema()[$key][2]??'')==='secret'){$saved['clear_'.$key]='1';}}settings('media_plus',$saved);}
});
test('016 future schema version is rejected before older code can write data',static function()use($a){
    $a->db->execute('UPDATE cy_settings SET value=? WHERE name=?',[(string)(\Chengyu\Core\Migrations::VERSION+1),'_schema_version']);
    try{reject(static function()use($a){\Chengyu\Core\Migrations::upgrade($a->db,$a->config['storage']);},503);}finally{$a->db->execute('UPDATE cy_settings SET value=? WHERE name=?',[(string)\Chengyu\Core\Migrations::VERSION,'_schema_version']);}
});
