<?php
use Chengyu\Core\{Totp,Diagnostics,Migrations};
use Chengyu\Services\Pricing;
foreach ([59=>'94287082',1111111109=>'07081804',1111111111=>'14050471',1234567890=>'89005924',2000000000=>'69279037',20000000000=>'65353130'] as $when=>$code) {
    test('014: RFC 6238 SHA1 vector '.$when,static function()use($when,$code){same($code,Totp::code(Totp::encode('12345678901234567890'),$when,8));});
}
test('014: base32 round trip canonical random secrets',static function(){for($n=10;$n<=60;$n++){ $bytes=random_bytes($n);same($bytes,Totp::decode(Totp::encode($bytes))); }});
test('014: authenticator drift window and replay rejection',static function(){ $secret=Totp::encode(random_bytes(20));$now=1234567890;$step=intdiv($now,30);for($d=-1;$d<=1;$d++){same($step+$d,Totp::match($secret,Totp::code($secret,$now+$d*30),$now));}same(null,Totp::match($secret,Totp::code($secret,$now),$now,$step));same(null,Totp::match($secret,'12345',$now)); });
function factor14(): array {
    global $a;$user=user14('factor');$v=(int)account($user)['session_version'];$a->secondFactor->begin($user,$v,'TestPassword!2026');$secret=$a->secondFactor->pending($user,$v)['secret'];$codes=$a->secondFactor->activate($user,$v,'TestPassword!2026',Totp::code($secret,time()));return [$user,$secret,$codes];
}
test('014: factor enrollment encrypts secret and hashes all recovery codes',static function()use($a){[$id,$secret,$result]=factor14();same(8,count($result['codes']));same(8,$a->secondFactor->status($id)['recovery_remaining']);$stored=json_encode($a->db->one('SELECT * FROM cy_second_factors WHERE user_id=?',[$id]));truth(strpos($stored,$secret)===false);foreach($result['codes'] as $code){truth(strpos($stored,$code)===false);}same((int)account($id)['session_version'],$result['version']);same(null,$a->secondFactor->pending($id,$result['version']));});
test('014: pending enrollment requires current password and matching session',static function()use($a){$id=user14();$v=(int)account($id)['session_version'];reject(static function()use($a,$id,$v){$a->secondFactor->begin($id,$v,'wrong-password');},403);$a->secondFactor->begin($id,$v,'TestPassword!2026');same(null,$a->secondFactor->pending($id,$v+1));reject(static function()use($a,$id,$v){$a->secondFactor->activate($id,$v,'TestPassword!2026','000000');},409);});
test('014: factor verification requires transaction',static function()use($a){[$id]=factor14();try{$a->secondFactor->verifyLocked(account($id),'');}catch(LogicException $e){return;}throw new RuntimeException('Unlocked verification accepted');});
test('014: protected login fails without proof; recovery logs in only once',static function()use($a){[$id,$secret,$codes]=factor14();$old=$_SESSION;try{reject(static function()use($a,$id){$a->auth->login(account($id)['username'],'TestPassword!2026');},401);$a->auth->login(account($id)['username'],'TestPassword!2026',$codes['codes'][0]);same($id,(int)$a->auth->user()['id']);same(7,$a->secondFactor->status($id)['recovery_remaining']);$a->auth->logout();reject(static function()use($a,$id,$codes){$a->auth->login(account($id)['username'],'TestPassword!2026',$codes['codes'][0]);},403);}finally{$a->auth->logout();$_SESSION=$old;}});
test('014: enrollment switch does not disable existing second factors',static function()use($a){[$id]=factor14();settings('users',['two_factor_enabled'=>'0']);try{reject(static function()use($a,$id){$a->db->transaction(static function()use($a,$id){$a->secondFactor->verifyLocked($a->wallet->lockActive($id),'');});},401);$new=user14();reject(static function()use($a,$new){$a->secondFactor->begin($new,(int)account($new)['session_version'],'TestPassword!2026');});}finally{settings('users',['two_factor_enabled'=>'1']);}});
test('014: failed outer transaction restores recovery code',static function()use($a){[$id,$s,$r]=factor14();try{$a->db->transaction(static function()use($a,$id,$r){$a->secondFactor->verifyLocked($a->wallet->lockActive($id),$r['codes'][0]);throw new RuntimeException('rollback');});}catch(RuntimeException $e){}same(8,$a->secondFactor->status($id)['recovery_remaining']);});
test('014: recovery rotation invalidates old codes and prior sessions',static function()use($a){[$id,$secret,$r]=factor14();$next=$a->secondFactor->manage($id,$r['version'],'TestPassword!2026',$r['codes'][0],'rotate');same($r['version']+1,$next['version']);same(8,$a->secondFactor->status($id)['recovery_remaining']);reject(static function()use($a,$id,$r){$a->db->transaction(static function()use($a,$id,$r){$a->secondFactor->verifyLocked($a->wallet->lockActive($id),$r['codes'][1]);});},403);reject(static function()use($a,$id,$r){$a->secondFactor->manage($id,$r['version'],'TestPassword!2026',$r['codes'][2],'disable');},401);$a->secondFactor->manage($id,$next['version'],'TestPassword!2026',$next['codes'][0],'disable');same(false,$a->secondFactor->status($id)['enabled']);});
test('014: bad password does not burn a recovery code',static function()use($a){[$id,$s,$r]=factor14();reject(static function()use($a,$id,$r){$a->secondFactor->manage($id,$r['version'],'wrong-password',$r['codes'][0],'disable');},403);same(8,$a->secondFactor->status($id)['recovery_remaining']);});
test('014: session revocation also works for accounts without second factor',static function()use($a){$id=user14();$v=(int)account($id)['session_version'];$r=$a->secondFactor->manage($id,$v,'TestPassword!2026','','revoke');same($v+1,$r['version']);});
test('014: CLI recovery removes factor and revokes sessions',static function()use($a){[$id,$s,$r]=factor14();$a->secondFactor->recoverOffline($id);same(false,$a->secondFactor->status($id)['enabled']);same($r['version']+1,(int)account($id)['session_version']);});
function priceRule14(int $id,array $overrides=[]): int {global $a,$admin;return $a->pricing->save($admin,$id,array_merge(['active'=>'1','revision'=>$a->pricing->rule($id)['revision']??0,'vip1_bps'=>8000,'vip2_bps'=>7000,'vip3_bps'=>6000,'promo_bps'=>10000],$overrides));}
function coupon14(array $overrides=[]): string {global $a;$code='C14'.strtoupper(substr(key32(),0,12));$a->db->insert('cy_coupons',array_merge(['code'=>$code,'mode'=>'flat','value_amount'=>50,'min_amount'=>1,'max_uses'=>10,'uses'=>0,'expires_at'=>time()+86400,'active'=>1],$overrides));return $code;}
settings('commerce',['pricing_enabled'=>'1','pricing_coupon_stack'=>'0']);
test('014: guest list price, membership inheritance and integer rounding',static function()use($a){$id=product('digital','balance','9.99');priceRule14($id,['vip2_bps'=>9000]);$item=$a->content->get($id);same(999,$a->pricing->price($item,null,999)['amount']);$user=user14();$a->membership->grant($user,2,30);$q=$a->pricing->price($item,account($user),999);same(799,$q['amount']);same('member',$q['source']);same(2,$q['member_tier']);});
test('014: promotion active interval and best price rather than multiplication',static function()use($a){$id=product();priceRule14($id,['promo_bps'=>5000,'starts_at'=>date('Y-m-d\TH:i',time()-60),'ends_at'=>date('Y-m-d\TH:i',time()+600)]);$q=$a->pricing->price($a->content->get($id),null,1001);same(500,$q['amount']);same('promotion',$q['source']);truth($q['ends_at']>time());$user=user14();$a->membership->grant($user,3,30);same(500,$a->pricing->price($a->content->get($id),account($user),1001)['amount']);$a->db->execute('UPDATE cy_price_rules SET ends_at=? WHERE content_id=?',[time(),$id]);same(1001,$a->pricing->price($a->content->get($id),null,1001)['amount']);});
test('014: stale rule editor rejected without overwriting',static function()use($a,$admin){$id=product();priceRule14($id);reject(static function()use($a,$admin,$id){$a->pricing->save($admin,$id,['revision'=>0]);},409);same(1,(int)$a->pricing->rule($id)['revision']);});
test('014: impossible promotion dates rejected',static function()use($a,$admin){$id=product();reject(static function()use($id){priceRule14($id,['promo_bps'=>5000,'starts_at'=>'2026-02-30T12:00','ends_at'=>'2026-03-01T12:00']);});reject(static function()use($id){priceRule14($id,['promo_bps'=>5000]);});});
test('014: checkout snapshot and refund use paid amount after rules change',static function()use($a,$admin){$user=user14();$a->wallet->adjust($user,'balance',10000,'price-fixture:'.$user,'fixture');$a->membership->grant($user,1,30);$id=product('digital','balance','10.00');priceRule14($id);$before=funds($user);$o=$a->commerce->buy($user,'content',$id,key32());same(800,(int)$o['amount']);same(1,json_decode($o['metadata'],true)['pricing']['rule_revision']);same($before-800,funds($user));priceRule14($id,['vip1_bps'=>1000]);$a->commerce->requestRefund($user,(int)$o['id'],'pricing fixture');$a->commerce->refund($admin,(int)$o['id'],true);same($before,funds($user));});
test('014: default coupon stacking rejection does not consume quota',static function()use($a){$id=product();priceRule14($id);$user=user14();$a->membership->grant($user,1,30);$code=coupon14();$q=$a->pricing->price($a->content->get($id),account($user),100);reject(static function()use($a,$id,$user,$q,$code){$a->pricing->coupon(account($user),$a->content->get($id),'content',$q,$code);});same(0,(int)$a->db->value('SELECT uses FROM cy_coupons WHERE code=?',[$code]));});
test('014: scoped coupons enforce item, kind, schedule and membership',static function()use($a){$user=user14();$id=product();$item=$a->content->get($id);$q=Pricing::base(1000);foreach([['scope_kind'=>'membership'],['scope_kind'=>'content','content_id'=>$id+99999],['starts_at'=>time()+1000],['min_vip_tier'=>3]] as $spec){$code=coupon14($spec);reject(static function()use($a,$user,$item,$q,$code){$a->pricing->coupon(account($user),$item,'content',$q,$code);});}$code=coupon14(['scope_kind'=>'content','content_id'=>$id]);same(950,$a->pricing->coupon(account($user),$item,'content',$q,$code)['amount']);same(0,(int)$a->db->value('SELECT uses FROM cy_coupons WHERE code=?',[$code]));});
test('014: enabled stacking reserves once and snapshot explains both discounts',static function()use($a){settings('commerce',['pricing_coupon_stack'=>'1']);try{$user=user14();$a->wallet->adjust($user,'balance',10000,'coupon-funding:'.$user,'fixture');$a->membership->grant($user,1,30);$id=product('digital','balance','10.00');priceRule14($id);$code=coupon14();$key=key32();$o=$a->commerce->buy($user,'content',$id,$key,$code);$again=$a->commerce->buy($user,'content',$id,$key,$code);same((int)$o['id'],(int)$again['id']);same(750,(int)$o['amount']);$q=json_decode($o['metadata'],true)['pricing'];same(1000,$q['base_amount']);same(50,$q['coupon_discount']);same(1,(int)$a->db->value('SELECT uses FROM cy_coupons WHERE code=?',[$code]));}finally{settings('commerce',['pricing_coupon_stack'=>'0']);}});
test('014: disabling pricing restores list price without deleting rules',static function()use($a){$id=product();priceRule14($id);$user=user14();$a->membership->grant($user,3,30);settings('commerce',['pricing_enabled'=>'0']);try{same(100,$a->pricing->price($a->content->get($id),account($user),100)['amount']);}finally{settings('commerce',['pricing_enabled'=>'1']);}truth($a->pricing->rule($id)!==null);});
test('014: free member access price and maximum integer price are exact',static function()use($a){$id=product();priceRule14($id,['vip1_bps'=>0]);$user=user14();$a->membership->grant($user,1,30);same(0,$a->pricing->price($a->content->get($id),account($user),1000000000)['amount']);same(1000000000,$a->pricing->price($a->content->get($id),null,1000000000)['amount']);});
test('014: diagnostics verifies rollback and never exposes app secret',static function()use($a){$before=(int)$a->db->value('SELECT COUNT(*) FROM cy_rate_limits');$report=Diagnostics::run($a);same($before,(int)$a->db->value('SELECT COUNT(*) FROM cy_rate_limits'));$json=json_encode($report);truth(strpos($json,$a->config['secret'])===false);truth(strpos($json,$a->config['storage'])===false);foreach($report['checks'] as $check){truth($check['state']!=='fail');}});
test('014: additive v6 restart preserves security and pricing records',static function()use($a){$f=(int)$a->db->value('SELECT COUNT(*) FROM cy_second_factors');$p=(int)$a->db->value('SELECT COUNT(*) FROM cy_price_rules');$a->db->execute('UPDATE cy_settings SET value=? WHERE name=?',['5','_schema_version']);Migrations::upgrade($a->db,$a->config['storage']);same(Migrations::VERSION,Migrations::version($a->db));same($f,(int)$a->db->value('SELECT COUNT(*) FROM cy_second_factors'));same($p,(int)$a->db->value('SELECT COUNT(*) FROM cy_price_rules'));});
test('014: price ceiling rejects increases and rolls back coupon reservations',static function()use($a){$id=product('digital','balance','10.00');$user=user14();$a->wallet->adjust($user,'balance',5000,'ceiling-funding:'.$user,'fixture');$code=coupon14();$before=funds($user);reject(static function()use($a,$id,$user,$code){$a->commerce->buy($user,'content',$id,key32(),$code,0,0,900);},409);same($before,funds($user));same(0,(int)$a->db->value('SELECT uses FROM cy_coupons WHERE code=?',[$code]));same(0,(int)$a->db->value('SELECT COUNT(*) FROM cy_orders WHERE user_id=?',[$user]));$o=$a->commerce->buy($user,'content',$id,key32(),$code,0,0,1000);same(950,(int)$o['amount']);});
test('014: password reset leaves enrolled factor active and invalidates sessions',static function()use($a){[$id,$secret,$r]=factor14();$token=resetFixture($id);$a->auth->reset($token,'FreshPassword123!');truth($a->secondFactor->status($id)['enabled']);truth((int)account($id)['session_version']>$r['version']);reject(static function()use($a,$id){$a->auth->login(account($id)['username'],'FreshPassword123!');},401);});
test('014: coupon use and discounted funds roll back on insufficient balance',static function()use($a){$id=product('digital','balance','10.00');$user=user14();$code=coupon14();reject(static function()use($a,$id,$user,$code){$a->commerce->buy($user,'content',$id,key32(),$code);});same(0,(int)$a->db->value('SELECT uses FROM cy_coupons WHERE code=?',[$code]));same(0,funds($user));});

test('014: zero timed duration can be saved through the common settings validator',static function()use($a){$old=$a->settings->get('motion_duration');try{settings('appearance',['motion_duration'=>'0']);same(0,$a->settings->get('motion_duration'));}finally{settings('appearance',['motion_duration'=>(string)$old]);}});
