"""Offline DOM proof for current security, pricing and keyed motion UI."""
ids14=json.loads(Path(os.environ['CY_TEST_IDS']).read_text())
for route,label in [('/index.php?r=security','security'),('/admin/index.php?tab=pricing&content_id='+str(ids14['pricing_product']),'pricing-studio'),('/index.php?r=product&id='+str(ids14['pricing_product']),'pricing-product')]:
    for width in [320,390,768,1440]:
        page.set_viewport_size({'width':width,'height':1000 if width==1440 else 844});page.set_content(snapshot(route),wait_until='load')
        check('014 '+label+' fits '+str(width),page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
        if width in [390,1440]:capture_revealed(label+('-desktop.png' if width==1440 else '-mobile.png'))
page.set_viewport_size({'width':1440,'height':1000});page.set_content(snapshot('/index.php?r=product&id='+str(ids14['pricing_product'])),wait_until='load')
check('014 server-rendered quote available before any fetch',page.locator('[data-quote-amount]').inner_text().endswith('40.80'))
focus=page.locator('.reading-focus-toggle');focus.click();check('014 focus mode preserves content and hides only sidebar',page.locator('.reading-focused').count()==1 and focus.get_attribute('aria-pressed')=='true')
check('014 focus mode keeps purchase control',page.locator('form.purchase-form button[type=submit]').is_visible())
capture_revealed('reading-focus-desktop.png');focus.click();check('014 focus mode can restore original layout',page.locator('.reading-focused').count()==0 and focus.get_attribute('aria-pressed')=='false')
# The offline page uses a test base only to resolve URLs; all fetch responses below
# are deliberate transport fixtures. The real endpoint is covered by http_014.py.
page.evaluate('()=>{const base=document.createElement("base");base.href="https://snapshot.test/";document.head.append(base);window.__quoteResolvers=[];window.fetch=()=>new Promise(resolve=>__quoteResolvers.push(resolve));}')
page.locator('[data-quote-refresh]').click();check('014 quote preview marks busy without charging',page.locator('[data-price-quote]').get_attribute('aria-busy')=='true')
page.locator('[name=coupon]').fill('SECOND');page.wait_for_timeout(320)
q14={'amount':3500,'base_amount':4800,'formatted':'\u00a5 35.00','base_formatted':'\u00a5 48.00','label':'<img src=x onerror=alert(1)>'}
page.evaluate('(q)=>__quoteResolvers[1]({ok:true,json:async()=>({ok:true,quote:q})})',q14);page.wait_for_timeout(60)
check('014 new quote updates integer ceiling',page.locator('[name=price_ceiling]').input_value()=='3500')
check('014 quote label cannot inject markup',page.locator('[data-quote-label] img').count()==0 and '<img' in page.locator('[data-quote-label]').inner_text())
q14.update(amount=4400,formatted='\u00a5 44.00');page.evaluate('(q)=>__quoteResolvers[0]({ok:true,json:async()=>({ok:true,quote:q})})',q14);page.wait_for_timeout(60)
check('014 stale quote cannot overwrite a newer confirmation',page.locator('[name=price_ceiling]').input_value()=='3500')
page.locator('[data-quote-refresh]').click();page.evaluate('__quoteResolvers[2]({ok:false,json:async()=>({ok:false,message:"Quote unavailable"})})');page.wait_for_timeout(60)
check('014 failed quote does not leave perpetual busy state',page.locator('[data-price-quote]').get_attribute('aria-busy') is None and 'Quote unavailable' in page.locator('[data-quote-status]').inner_text())
# Keyed reordering keeps expanded sections, focus and keyboard semantics.
page.set_content(snapshot('/admin/index.php?tab=builder&slot=articles'),wait_until='load');page.emulate_media(reduced_motion='no-preference')
page.evaluate('CYMotion.configure({motion:true,motion_layout:true,motion_adaptive:false,motion_duration:460});document.documentElement.dataset.economy="0"')
check('014 layout motion helper installed',page.evaluate('typeof CYLayoutMotion.change==="function"'))
cards=page.locator('[data-block-id]');check('014 seeded layout has at least two keyed blocks',cards.count()>=2)
lastid=cards.last.get_attribute('data-block-id');last=page.locator('[data-block-id="'+lastid+'"]');last.locator('details').evaluate('(d)=>{d.open=true}')
up=last.locator('.studio-block-header button').nth(2);up.focus();page.keyboard.press('Alt+ArrowUp');page.wait_for_timeout(80)
check('014 keyboard reorder changes persistent JSON order',json.loads(page.locator('[data-layout-document]').input_value())['blocks'][0]['id']==lastid)
check('014 reorder preserves the expanded editor',page.locator('[data-block-id="'+lastid+'"] details').evaluate('(n)=>n.open'))
check('014 reorder restores keyboard focus to moved block',page.evaluate('(id)=>document.activeElement.closest("[data-block-id]")?.dataset.blockId===id',lastid))
check('014 reorder announces new position',bool(page.locator('[data-block-list] + [role=status]').inner_text()))
page.keyboard.press('Alt+ArrowDown');page.wait_for_timeout(70);page.keyboard.press('Alt+ArrowUp');page.wait_for_timeout(550)
check('014 repeated reorder leaves no running layout animation',page.evaluate('CYLayoutMotion.active()===0'))
check('014 layout transforms are removed after completion',page.locator('[data-block-id]').evaluate_all('(nodes)=>nodes.every(n=>n.style.transform===""&&n.getAnimations().length===0)'))
page.emulate_media(reduced_motion='reduce');page.keyboard.press('Alt+ArrowDown');check('014 reduced motion keeps reorder without animations',page.evaluate('CYLayoutMotion.active()===0'))
page.emulate_media(reduced_motion='no-preference');page.evaluate('CYMotion.configure({motion_layout:false})');page.keyboard.press('Alt+ArrowUp');check('014 motion switch keeps reorder but removes movement',page.evaluate('CYLayoutMotion.active()===0'))
capture_revealed('layout-studio-desktop.png')
page.set_content(snapshot('/admin/index.php?tab=motion'),wait_until='load');check('014 layout animation configurable in motion lab',page.locator('[name=motion_layout]').count()==1)
page.emulate_media(reduced_motion='no-preference');page.evaluate('CYMotion.configure({motion_duration:0,motion_disclosures:true})')
zero=page.evaluate('()=>{const d=document.querySelector(".motion-section");d.querySelector("summary").click();return d.getAnimations().map(a=>a.effect.getComputedTiming().duration)}')
check('014 zero duration also applies to native disclosure animation',all(d==0 for d in zero))
check('014 motion form allows an actual zero value',page.locator('[name=motion_duration]').get_attribute('min')=='0')
check('014 zero duration has no deferred reveal nodes',page.locator('.reveal.cy-wait').count()==0)

page.wait_for_timeout(400)
# Required form paths survive without JavaScript. Offline context has no navigation.
nojs=browser.new_context(java_script_enabled=False,viewport={'width':390,'height':844});plain=nojs.new_page();plain.set_content(snapshot('/index.php?r=product&id='+str(ids14['pricing_product'])))
check('014 no-JS purchase remains a real POST form',plain.locator('form.purchase-form').get_attribute('method')=='post' and plain.locator('form.purchase-form button[type=submit]').count()==1)
check('014 no-JS uses server price ceiling',plain.locator('[name=price_ceiling]').input_value()=='4080')
check('014 no-JS hides nonfunctional preview button',not plain.locator('[data-quote-refresh]').is_visible());nojs.close()
