"""0.11 DOM/animation checks. Server HTML fetched with requests; browser stays offline."""
IDS=json.loads(Path(os.environ['CY_TEST_IDS']).read_text())
def set_range(name,value):
    page.locator('[name="'+name+'"]').evaluate('(n,v)=>{n.value=String(v);n.dispatchEvent(new Event("input",{bubbles:true}))}',value)
def capture_revealed(name):
    page.evaluate('() => {document.querySelectorAll(".reveal").forEach(n=>n.classList.add("visible"));}')
    # Full-page documentation image, not timing evidence; reveal timing is tested separately.
    page.wait_for_timeout(750);capture(path=str(OUT/name),full_page=True)
page.set_viewport_size({'width':1440,'height':1000});page.emulate_media(reduced_motion='no-preference')
page.set_content(snapshot('/'),wait_until='load');check('motion engine parses real server configuration',page.evaluate('!!window.CYMotion && CYMotion.enabled()'))
check('front-end easing reads the shared server curve registry',page.evaluate('JSON.stringify(CYMotion.curve())===JSON.stringify(JSON.parse(document.documentElement.dataset.motionCurves).gentle)'))
card=page.locator('.quick-link').first;card.hover();page.wait_for_timeout(180)
check('pointer spotlight produces active card state',card.evaluate('(n)=>n.classList.contains("pointer-active")'))
check('pointer perspective produces actual computed transform',card.evaluate('(n)=>getComputedStyle(n).transform!=="none"'))
page.evaluate('CYMotion.configure({motion:false})')
check('master off resets pointer transforms immediately',card.evaluate('(n)=>getComputedStyle(n).transform==="none"'))
page.evaluate('CYMotion.configure({motion:true,motion_reveal_style:"blur"})')
check('reveal variant updates root configuration',page.locator('html').get_attribute('data-reveal-style')=='blur')
page.evaluate('CYMotion.configure({motion_reveal_style:"rise"})');capture_revealed('home-desktop.png')
page.set_viewport_size({'width':390,'height':844});capture_revealed('home-mobile.png')
page.locator('[data-dialog="appearance-dialog"]').click();page.wait_for_timeout(450)
check('animated dialog reaches native open state',page.locator('#appearance-dialog').evaluate('(n)=>n.open'))
page.keyboard.press('Escape');page.wait_for_timeout(300)
check('animated Escape dismissal closes native dialog',not page.locator('#appearance-dialog').evaluate('(n)=>n.open'))
# Do not perform browser URL navigation or network-dependent form submissions here.
page.evaluate('() => {const f=document.createElement("form");f.dataset.async="";const b=document.createElement("button");b.disabled=true;b.id="disabled-fixture";f.append(b);document.body.append(f);dispatchEvent(new PageTransitionEvent("pageshow",{persisted:true}));}')
check('history restoration preserves intentionally disabled controls',page.locator('#disabled-fixture').is_disabled());page.locator('#disabled-fixture').evaluate('(n)=>n.parentElement.remove()')
page.set_viewport_size({'width':1440,'height':1000});page.set_content(snapshot('/admin/index.php?tab=motion'),wait_until='load')
check('motion inspector has real parameter controls',page.locator('.motion-studio-form input[type=range]').count()>=8)
for width in [320,390,768,1440]:
    page.set_viewport_size({'width':width,'height':900});check('motion inspector no horizontal overflow '+str(width),page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
capture_revealed('motion-studio-desktop.png')
page.locator('[data-motion-preset=expressive]').click();check('expressive preset updates shared engine and form',page.locator('[name=motion_curve]').input_value()=='elastic' and page.evaluate('CYMotion.config().motion_magnetic===true'))
page.locator('[data-motion-replay]').first.click();page.wait_for_timeout(80)
check('replay creates actual timed Web Animations',page.evaluate('document.getAnimations().filter(a=>a.playState==="running").length>0'))
page.locator('[name=motion_curve]').select_option('custom');page.locator('.motion-section').last.locator('summary').click()
for name,value in [('curve_x1',12),('curve_y1',155),('curve_x2',64),('curve_y2',100),('motion_duration',580)]:set_range(name,value)
check('curve inspector uses exact custom control points',page.locator('[data-curve-code]').inner_text()=='cubic-bezier(0.12, 1.55, 0.64, 1)')
check('curve path renders an overshoot control point',page.locator('[data-curve-line]').get_attribute('d')=='M0 100C12 -55.000000000000014 64 0 100 0' or page.locator('[data-curve-point="1"]').get_attribute('cy').startswith('-55'))
check('duration output and CSS duration stay synchronized',page.locator('[data-curve-duration]').inner_text()=='580 ms' and page.locator('html').evaluate('(n)=>n.style.getPropertyValue("--duration")')=='580ms')
page.set_viewport_size({'width':390,'height':844})
page.evaluate('scrollTo({top:0,left:0,behavior:"instant"})');page.wait_for_timeout(400)
check('expanded custom curve mobile no horizontal overflow',page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
if page.evaluate('document.documentElement.scrollWidth>innerWidth'):
    (OUT/'overflow-debug.json').write_text(json.dumps(page.evaluate('''() => [...document.querySelectorAll('body *')].filter(n=>n.getBoundingClientRect().right>innerWidth+1).map(n=>({tag:n.tagName,class:n.className,x:n.getBoundingClientRect().x,width:n.getBoundingClientRect().width,position:getComputedStyle(n).position})).slice(0,40)'''),indent=2))
capture_revealed('motion-studio-mobile.png')
page.emulate_media(reduced_motion='reduce');page.wait_for_timeout(80)
check('system reduced-motion switches live engine off',page.locator('html').get_attribute('data-motion')=='0')
page.locator('[data-motion-preset=expressive]').click();check('admin preset cannot override reduced-motion preference',not page.evaluate('CYMotion.enabled()'))
check('reduced-motion retains all editable controls',page.locator('[name=motion_curve]').is_enabled())
page.emulate_media(reduced_motion='no-preference');page.wait_for_timeout(80);check('media preference change restores configured engine',page.evaluate('CYMotion.enabled()'))
page.locator('[name=motion]').uncheck();check('master motion off stops continuous illustration',page.locator('.motion-orb').evaluate('(n)=>getComputedStyle(n).animationName')=='none')
page.locator('[name=motion]').check();page.locator('[data-motion-preset=balanced]').click()
page.evaluate('Object.defineProperty(navigator,"hardwareConcurrency",{configurable:true,get:()=>2});CYMotion.configure({motion_adaptive:true})')
check('adaptive low-resource mode suppresses glass effects',page.locator('html').get_attribute('data-economy')=='1' and page.locator('.motion-preview-card').evaluate('(n)=>getComputedStyle(n).backdropFilter')=='none')
page.evaluate('delete navigator.hardwareConcurrency;CYMotion.configure({motion_adaptive:true})')
# Threads: authorization and real POST mutation covered by separate HTTP suite.
page.set_viewport_size({'width':1440,'height':1000});page.set_content(snapshot('/index.php?r=article&id='+str(IDS['poll'])),wait_until='load')
check('article outline generated from rendered Markdown headings',page.locator('.reading-outline a').count()>=2)
check('private poll results absent before voting',page.locator('.poll-results').count()==0)
for width in [320,390,768,1440]:
    page.set_viewport_size({'width':width,'height':900});check('poll no horizontal overflow '+str(width),page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
capture_revealed('poll-desktop.png')
page.locator('.poll-choice input').first.check();check('poll radio control is an actual required form field',page.locator('.poll-choice input').first.is_checked())
form=BeautifulSoup(SESSION.get(BASE+'/index.php?r=article&id='+str(IDS['poll'])).text,'html.parser').select_one('.poll-form')
fields={n['name']:n.get('value','') for n in form.select('input[name]:not([type=radio])')};fields['option_id']=form.select_one('input[type=radio]')['value']
response=SESSION.post(BASE+form['action'],data=fields,headers={'Accept':'application/json'});response.raise_for_status()
page.set_content(snapshot('/index.php?r=article&id='+str(IDS['poll'])),wait_until='load')
check('HTTP-recorded vote renders correct results in browser',page.locator('.poll-results').count()==1 and page.locator('.poll-form').count()==0);capture_revealed('poll-results.png')
page.set_content(snapshot('/index.php?r=article&id='+str(IDS['question'])),wait_until='load');check('accepted answer is rendered with working anchor',page.locator('#comment-'+str(IDS['answer'])).count()==1);capture_revealed('question-desktop.png')
for width in [320,390,768,1440]:
    page.set_viewport_size({'width':width,'height':900});check('question no horizontal overflow '+str(width),page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
page.set_viewport_size({'width':390,'height':844});capture_revealed('question-mobile.png')
page.set_viewport_size({'width':1440,'height':1000});page.set_content(snapshot('/admin/index.php?tab=threads'),wait_until='load');capture_revealed('threads-admin.png')
page.set_content(snapshot('/admin/index.php?tab=edit_content&kind=thread'),wait_until='load')
check('discussion editor disables irrelevant poll controls',not page.locator('[data-poll-fields]').is_visible() and page.locator('[name=poll_question]').is_disabled())
page.locator('[name=thread_mode]').select_option('poll');check('choosing poll enables functional fields',page.locator('[data-poll-fields]').is_visible() and page.locator('[name=poll_question]').is_enabled())
page.locator('[name=poll_results]').select_option('closed');check('closed-only poll makes deadline required in editor',page.locator('[name=poll_closes_at]').evaluate('(n)=>n.required'))
page.locator('[name=poll_results]').select_option('after_vote');check('ordinary poll deadline is optional again',not page.locator('[name=poll_closes_at]').evaluate('(n)=>n.required'))
# Static HTML/CSS with scripts removed: no hidden initial content dependency.
static_html=BeautifulSoup(snapshot('/'),'html.parser')
for script in static_html.select('script'):script.decompose()
page.set_content(str(static_html),wait_until='load');check('no-JavaScript content remains visible',page.locator('.content-card').first.evaluate('(n)=>getComputedStyle(n).opacity')=='1')
