"""0.13 DOM checks. Mocked browser fetch tests only UI; actual API is in HTTP suite."""
page.emulate_media(reduced_motion='no-preference')
for name,route in [('creator-studio','/index.php?r=creator'),('creator-admin','/admin/index.php?tab=creators'),('history','/index.php?r=history'),('following','/index.php?r=following')]:
    page.set_viewport_size({'width':1440,'height':1000});page.set_content(snapshot(route),wait_until='load')
    check(name+' renders actual new view',page.locator('.error-page').count()==0)
    for width in [320,390,768,1440]:
        page.set_viewport_size({'width':width,'height':900});check(name+' no horizontal overflow '+str(width),page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
    capture_revealed(name+'-desktop.png')
    if name in ['history','creator-studio']:
        page.set_viewport_size({'width':390,'height':844});capture_revealed(name+'-mobile.png')
    if name=='creator-studio':
        check('creator metrics are from real isolated transactions',page.locator('.creator-metrics .metric-card').count()==4 and page.locator('.creator-metrics .metric-card strong').first.inner_text()!='0.00')
        check('income detail labels use readable stacked layout',page.locator('.income-table td small').first.evaluate('(n)=>getComputedStyle(n).display==="block"'))
        check('creator orbit uses a defined theme border token',page.locator('.creator-orbit i').first.evaluate('(n)=>parseFloat(getComputedStyle(n).borderTopWidth)>0'))
        check('creator view exposes real settlement and conversion forms',page.locator('input[value="creator_settle"]').count()==1 and page.locator('input[value="creator_convert"]').count()==1)
    if name=='history':
        check('private reading cards have real saved progress',page.locator('.history-card progress').count()==6)
        check('reading opt-out is an actual checked form field',page.locator('[name=enabled]').is_checked())
page.set_viewport_size({'width':1440,'height':1000});page.set_content(snapshot('/admin/index.php?tab=motion'),wait_until='load')
check('new feedback settings are editable from motion lab',all(page.locator('[name='+k+']').count()==1 for k in ['motion_navigation','motion_feedback','motion_images']))
tabs=page.locator('[data-feedback-tabs]');tabs.locator('button').nth(1).click();page.wait_for_timeout(350)
check('navigation indicator follows the selected control',tabs.locator('button').nth(1).get_attribute('aria-pressed')=='true' and tabs.locator('.nav-trace').is_visible())
check('navigation indicator matches the selected width',tabs.evaluate('(n)=>Math.abs(n.querySelector(".nav-trace").getBoundingClientRect().width-n.querySelector("[aria-pressed=true]").getBoundingClientRect().width)<1'))
page.evaluate('CYMotion.configure({motion_navigation:false})');check('navigation animation switch hides decorative indicator',not tabs.locator('.nav-trace').is_visible())
page.evaluate('CYMotion.configure({motion_navigation:true,motion_duration:0})');tabs.locator('button').last.click();page.wait_for_timeout(50)
check('zero global duration applies to feedback animation',page.evaluate('[...document.querySelectorAll(".nav-trace")].every(n=>n.getAnimations().every(a=>a.effect.getComputedTiming().duration===0))'))
page.evaluate('CYMotion.configure({motion_duration:480})');button=page.locator('[data-feedback-demo]');button.focus();button.click();page.wait_for_timeout(280)
check('feedback uses a dismissible accessible notification',page.locator('.toast-stack[aria-live=polite] .toast-dismiss[aria-label]').count()==1)
page.locator('.toast-dismiss').focus();page.keyboard.press('Enter');page.wait_for_timeout(250)
check('dismissing notification restores originating keyboard focus',page.locator('.toast').count()==0 and button.evaluate('(n)=>document.activeElement===n'))
page.evaluate('for(let i=0;i<7;i++)CYUI.toast("Bounded preview "+i)');check('notification queue is bounded at four',page.locator('.toast').count()==4)
page.locator('.toast-stack').evaluate('(n)=>n.remove()');page.emulate_media(reduced_motion='reduce');button.click()
check('reduced-motion keeps notifications without animation',page.locator('.toast').count()==1 and page.locator('.toast').evaluate('(n)=>n.getAnimations().length===0'))
page.locator('.toast-dismiss').click();page.emulate_media(reduced_motion='no-preference')
capture_revealed('motion-studio-desktop.png');page.set_viewport_size({'width':390,'height':844});capture_revealed('motion-studio-mobile.png')
# Simulated transport isolates IME, out-of-order and DOM-safety behavior. Network endpoint
# authorization, CSRF, limits, errors and returned fields are independently HTTP-tested.
page.set_viewport_size({'width':1440,'height':1000});page.set_content(snapshot('/'),wait_until='load');page.keyboard.press('Control+k');page.wait_for_timeout(450)
page.evaluate("() => {window.__searchCalls=[];window.__pendingSearch={};window.fetch=(url)=>{__searchCalls.push(String(url));return new Promise(resolve=>{const q=new URL(String(url),'http://snapshot.test').searchParams.get('q');__pendingSearch[q]=items=>resolve({ok:true,json:async()=>({items})});});};}")
q=page.locator('#search-dialog input[name=q]');q.fill('a');page.wait_for_timeout(250);check('one character waits for a meaningful search query',page.evaluate('__searchCalls.length===0'))
q.evaluate('(n)=>n.dispatchEvent(new CompositionEvent("compositionstart",{bubbles:true}))');q.fill('alpha');page.wait_for_timeout(250)
check('IME composition does not send intermediate searches',page.evaluate('__searchCalls.length===0'))
q.evaluate('(n)=>n.dispatchEvent(new CompositionEvent("compositionend",{bubbles:true}))');page.wait_for_timeout(260)
check('IME completion triggers one debounced query',page.evaluate('__searchCalls.length===1'))
q.fill('beta');page.wait_for_timeout(260)
page.evaluate('__pendingSearch.beta([{url:"/index.php?r=article&id=1",title:"A considered reading space"},{url:"https://outside.invalid",title:"Reject external URL"},{url:"/index.php?r=article&id=2",title:"<img src=x onerror=alert(1)>"}])');page.wait_for_timeout(250)
check('suggestions render only same-site result links',page.locator('.search-result').count()==2)
check('suggestion titles cannot introduce executable markup',page.locator('.search-result img').count()==0 and '<img' in page.locator('.search-result').last.inner_text())
page.evaluate('__pendingSearch.alpha([{url:"/index.php?r=article&id=3",title:"Stale result"}])');page.wait_for_timeout(80)
check('out-of-order search cannot overwrite a newer response','Stale result' not in page.locator('.search-results').inner_text())
page.keyboard.press('ArrowDown');check('combobox keyboard selection updates active descendant',q.get_attribute('aria-activedescendant')=='search-option-0' and page.locator('#search-option-0').get_attribute('aria-selected')=='true')
page.keyboard.press('Escape');check('first Escape clears suggestions but keeps search dialog',page.locator('.search-result').count()==0 and page.locator('#search-dialog').evaluate('(n)=>n.open'))
q.fill('gamma');page.wait_for_timeout(260);page.keyboard.press('Escape');page.wait_for_timeout(350)
page.evaluate('__pendingSearch.gamma([{url:"/index.php?r=article&id=1",title:"Too late"}])');page.wait_for_timeout(80)
check('closing search invalidates an in-flight response',not page.locator('#search-dialog').evaluate('(n)=>n.open') and page.locator('.search-result').count()==0)
page.keyboard.press('Control+k');q.fill('inspiration');page.wait_for_timeout(260)
preview_response=SESSION.get(BASE+'/index.php?r=suggest',params={'q':'\u521b\u4f5c'},timeout=15);preview_response.raise_for_status()
page.evaluate('(items)=>{__pendingSearch.inspiration(items)}',preview_response.json()['items']);q.evaluate('(n)=>{n.value="\u521b\u4f5c"}');page.wait_for_timeout(250)
for width in [320,390,768,1440]:
    page.set_viewport_size({'width':width,'height':900});check('search palette fits viewport '+str(width),page.evaluate('document.documentElement.scrollWidth<=innerWidth'))
capture_revealed('search-palette-desktop.png');page.set_viewport_size({'width':390,'height':844});capture_revealed('search-palette-mobile.png')

page.set_viewport_size({'width':1440,'height':1000});page.set_content(snapshot('/index.php?r=creator'),wait_until='load')
form=page.locator('form').filter(has=page.locator('input[value="creator_settle"]'))
form.evaluate('(n)=>{const b=document.createElement("button");b.type="submit";b.disabled=true;b.id="original-disabled";b.textContent="Disabled fixture";n.append(b);}')
page.evaluate('() => {window.fetch=()=>new Promise(resolve=>window.__resolveForm=resolve);}')
form.locator('button:not([disabled])').first.click();page.wait_for_timeout(230)
check('slow async action shows real pending and busy state',form.get_attribute('aria-busy')=='true' and form.get_attribute('data-busy-visual')=='1')
page.evaluate('__resolveForm({ok:false,text:async()=>JSON.stringify({ok:false,message:"A clear test error"})})');page.wait_for_timeout(250)
check('failed async request restores active buttons and clears busy state',form.get_attribute('aria-busy') is None and form.get_attribute('data-busy-visual') is None and not form.locator('button').first.is_disabled())
check('async failure preserves intentional disabled state',page.locator('#original-disabled').is_disabled())
check('async failure provides a visible text alert',form.locator('.form-error[role=alert]').inner_text()=='A clear test error')

# Separate no-script document. Search and revenue operations still have HTML forms.
nojs=browser.new_page(java_script_enabled=False,viewport={'width':390,'height':844});nojs.set_content(snapshot('/index.php?r=creator'))
check('no-script creator settlement remains a native POST form',nojs.locator('input[value="creator_settle"]').evaluate('(n)=>n.form.method==="post"'))
check('no-script creator page remains readable',nojs.locator('.creator-hero').is_visible());nojs.close()
