<?php
$contentId=\Chengyu\Core\Input::integer($_GET['content_id']??0);$editId=\Chengyu\Core\Input::integer($_GET['edit']??0);$edit=$editId?$a->resources->edit($me,$editId):[];if($edit){$contentId=(int)$edit['content_id'];}
$resourceContent=$contentId?$a->content->get($contentId,$me):null;
$entries=$contentId?$a->resources->entries($contentId,$me):[];
?>
<div class="admin-title"><div><span class="eyebrow">RESOURCE LIBRARY</span><h1><?= t('Resource releases') ?></h1><p><?= t('Manage file editions, private mirrors and reader reports from one place.') ?></p></div><a class="btn secondary small" href="<?= e(au('media')) ?>"><?= icon('upload') ?><?= t('Media library') ?></a></div>
<form class="panel catalog-filter-form row wrap mb" method="get" action="<?= e($a->basePath.'/admin/index.php') ?>"><?= hidden('tab','resources') ?><label for="resource-content-id"><?= t('Content ID') ?></label><input class="input" id="resource-content-id" type="number" name="content_id" value="<?= $contentId?:'' ?>" min="1" required><?php button('Load resources','small','search'); ?><?php if($resourceContent): ?><a class="text-link" href="<?= e(item_url($resourceContent)) ?>"><?= e($resourceContent['title']) ?><?= icon('arrow') ?></a><?php endif ?></form>
<?php if($resourceContent): ?><div class="resource-workbench"><section class="panel"><h2><?= t('Published file editions') ?></h2><?php if(!$entries){empty_state();}foreach($entries as $entry): ?><div class="resource-row"><div class="grow"><strong><?= e($entry['label']) ?></strong><small class="muted"><?= e($entry['release_version']) ?> · v<?= (int)$entry['revision'] ?> · <?= t((int)$entry['active']?'Enabled':'Disabled') ?></small></div><a class="btn secondary small" href="<?= e(au('resources',['content_id'=>$contentId,'edit'=>$entry['id']])) ?>"><?= t('Edit') ?></a></div><?php endforeach ?></section>
<aside class="panel"><h2><?= t($edit?'Edit resource edition':'Add resource edition') ?></h2><p class="hint"><?= t('Use a private media ID or an HTTPS mirror, never both. Disabling an edition revokes new deliveries without changing the original purchase.') ?></p>
<?= form_start('resource_save','','',false).hidden('id',$edit['id']??0).hidden('content_id',$contentId).hidden('revision',$edit['revision']??0) ?>
<?php field('label','Edition title',$edit['label']??'','text',['required'=>'required','maxlength'=>'120']);field('release_version','Release version',$edit['release_version']??'','text',['maxlength'=>'50']);field('notes','Release notes',$edit['notes']??'','textarea',['maxlength'=>'4000']);upload_field('media_id','Private resource ID',(int)($edit['media_id']??0),true);field('mirror_url','HTTPS mirror URL',$edit['mirror_url']??'','url',['maxlength'=>'1800']);field('extraction_code','Extraction code',$edit['extraction_code']??'','text',['maxlength'=>'100']);field('sort_order','Display order',$edit['sort_order']??0,'number',['min'=>'0','max'=>'10000']);check_field('active','Enabled',!$edit || !empty($edit['active']));button('Save resource edition','full','check'); ?></form><?php if($edit): ?><a class="text-link" href="<?= e(au('resources',['content_id'=>$contentId])) ?>"><?= t('Add another edition') ?></a><?php endif ?></aside></div><?php endif ?>
<?php $reportState=\Chengyu\Core\Input::choice($_GET['state']??'open',['open','resolved','dismissed']);$reportPage=\Chengyu\Core\Input::integer($_GET['page']??1,1,100000);$reportTotal=(int)$a->db->value('SELECT COUNT(*) FROM cy_resource_reports WHERE status=?',[$reportState]);$reports=$a->db->all('SELECT r.*,f.label,f.content_id,u.display_name FROM cy_resource_reports r JOIN cy_resource_files f ON f.id=r.resource_id JOIN cy_users u ON u.id=r.user_id WHERE r.status=? ORDER BY r.updated_at DESC,r.id DESC LIMIT 30 OFFSET ?',[$reportState,($reportPage-1)*30]); ?>
<section class="panel commerce-panel section mt"><div class="section-heading"><h2><?= t('Resource reports') ?></h2><div class="filters"><?php foreach(['open','resolved','dismissed'] as $state): ?><a class="filter <?= $reportState===$state?'active':'' ?>" href="<?= e(au('resources',['state'=>$state,'content_id'=>$contentId])) ?>"><?= t($state) ?></a><?php endforeach ?></div></div>
<?php if(!$reports){empty_state();}foreach($reports as $report): ?><article class="resource-release"><div class="row between wrap"><strong><?= e($report['label']) ?></strong><span class="pill"><?= t($report['reason']) ?></span></div><p class="resource-notes"><?= e($report['body']) ?></p><small class="muted"><?= e($report['display_name']) ?> · <?= dt((int)$report['created_at']) ?></small><?php if($report['status']==='open'): ?><?= form_start('resource_resolve','','mt',false).hidden('id',$report['id']).hidden('revision',$report['revision']) ?><?php field('resolution','Resolution note','','text',['required'=>'required','maxlength'=>'1000']);select_field('status','Result',array_map('tr',['resolved'=>'Resolved','dismissed'=>'Dismissed']),'resolved');button('Resolve and notify','small','check'); ?></form><?php else: ?><p><?= e($report['resolution']) ?></p><?php endif ?></article><?php endforeach ?>
<?php partial('pagination',['pagination'=>['page'=>$reportPage,'pages'=>max(1,(int)ceil($reportTotal/30))],'tab'=>'resources']); ?></section>
