<?php $v=$edit??[]; ?>
<div class="admin-title"><div><span class="eyebrow">CURATE / CONNECT / GROW</span><h1><?= e($title) ?></h1><p><?= t('Every module uses the same publishing rules and permissions.') ?></p></div><a class="btn secondary" href="<?= e(au($tab)) ?>"><?= icon('plus') ?><?= t('New record') ?></a></div>
<div class="admin-edit-grid"><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>ID</th><th><?= t('Name') ?></th><th><?= t('Status') ?></th><th><?= t('Manage') ?></th></tr></thead><tbody>
<?php foreach($rows as $row): ?><tr><td>#<?= (int)$row['id'] ?></td><td><strong><?= e($row['name']) ?></strong><small class="table-subtext"><?= e($row['description']) ?></small></td><td><span class="pill <?= $row['active']?'active':'' ?>"><?= t($row['active']?'active':'disabled') ?></span></td><td><a class="btn secondary small" href="<?= e(au($tab,['edit'=>$row['id']])) ?>"><?= t('Edit') ?></a></td></tr><?php endforeach ?>
</tbody></table></div><?php if(!$rows){empty_state();} ?><p class="hint"><?= t('Showing up to 300 records. Disable records to preserve history.') ?></p></section>
<section class="panel"><h2><?= t($edit?'Edit record':'Create record') ?></h2><?= form_start($tab==='tasks'?'admin_task':'admin_catalog') . hidden('entity',$tab) . hidden('id',$v['id']??0) ?>
<?php field('name','Name',$v['name']??'','text',['required'=>'required','maxlength'=>'100']);field('description','Description',$v['description']??'','textarea',['maxlength'=>'3000']);
if($tab==='collections'){$ids=[];if($v){$ids=array_column($a->db->all('SELECT content_id FROM cy_collection_items WHERE collection_id=? ORDER BY sort_order,id',[(int)$v['id']]),'content_id');}field('content_ids','Content IDs (comma separated)',implode(',',$ids),'textarea');echo '<p class="hint">'.t('Drafts and restricted categories are filtered for each visitor. Up to 200 items.').'</p>';}
elseif($tab==='links'){field('url','Website URL',$v['url']??'','url',['required'=>'required']);field('group_name','Directory group',$v['group_name']??'');}
elseif($tab==='announcements'){select_field('route','Destination',options(\Chengyu\Services\Catalog::ROUTES),$v['route']??'home');select_field('audience','Audience',options(['public','login','vip','verified']),$v['audience']??'public');foreach(['starts_at'=>'Start time (empty means now)','ends_at'=>'End time (empty means no expiry)'] as $key=>$label){field($key,$label,!empty($v[$key])?date('Y-m-d\TH:i',(int)$v[$key]):'','datetime-local');}}
elseif($tab==='tasks'){select_field('metric','Completion evidence',options(\Chengyu\Services\Tasks::METRICS),$v['metric']??'checkin');select_field('period','Claim frequency',options(['once','daily']),$v['period']??'daily');field('target_count','Target count',$v['target_count']??1,'number',['min'=>'1','max'=>'1000']);field('reward_points','Points reward',$v['reward_points']??10,'number',['min'=>'0','max'=>'100000']);field('reward_xp','Experience reward',$v['reward_xp']??5,'number',['min'=>'0','max'=>'100000']);echo '<p class="hint">'.t('Approved comments and published posts only. Claimed task rules are immutable; create another task to change rewards.').'</p>';}
field('sort_order','Sort order',$v['sort_order']??0,'number',['min'=>'0','max'=>'10000']);check_field('active','Enabled',!isset($v['active'])||(bool)$v['active']);button('Save changes','full'); ?></form></section></div>
