<?php
$https=strpos($a->config['url'],'https://')===0;$supported=version_compare(PHP_VERSION,'7.4.0','>=') && PHP_INT_SIZE>=8;
$checks=[['PHP runtime',PHP_VERSION,$supported],['Database',$a->db->driver(),true],['OpenSSL',extension_loaded('openssl')?'available':'missing',extension_loaded('openssl')],['MIME detection','Built-in content checks; Fileinfo is not required.',true],['HTTPS site URL',$https?'enabled':'disabled',$https],['Private storage',is_writable($a->config['storage'])?'writable':'not writable',is_writable($a->config['storage'])],['PHP upload limit',(string)ini_get('upload_max_filesize'),true],['PHP POST limit',(string)ini_get('post_max_size'),true],['Memory limit',(string)ini_get('memory_limit'),true],['Site timezone',date_default_timezone_get(),true]];
?>
<div class="admin-title"><div><span class="eyebrow">RELIABILITY STARTS WITH VISIBILITY</span><h1><?= e($title) ?></h1><p><?= t('Environment checks are observations, not a security audit or a guarantee of host compatibility.') ?></p></div></div><div class="health-grid section"><?php foreach($checks as [$label,$value,$ok]): ?><section class="health-card panel"><span class="health-icon <?= $ok?'success':'warning' ?>"><?= icon($ok?'check':'shield') ?></span><div><strong><?= t($label) ?></strong><p><?= t($value) ?></p></div></section><?php endforeach ?></div>
<?php if (!$supported || !$https): ?><div class="alert warning"><?= t('Use 64-bit PHP 7.4 or newer and configure HTTPS before live payments. A maintained runtime is recommended; no application feature is disabled based on the PHP minor version.') ?></div><?php endif ?>
<div class="two-column"><section class="panel"><h2><?= t('HTTPS and certificate automation') ?></h2><div class="prose"><p><?= t('A PHP application cannot install certificates on a server it does not control. On shared hosting, bind your domain and enable HTTPS in the provider panel.') ?></p><p><?= t('On a VPS, the included Caddy configuration can obtain and renew certificates automatically after DNS, ports 80/443 and the PHP service are configured.') ?></p><p><?= t('This dashboard does not store a hosting-panel API key or claim to control your web server. Certificate deployment remains an infrastructure operation.') ?></p><p><code>deploy/Caddyfile.example</code> / <code>deploy/install-vps.sh</code></p></div></section><section class="panel"><h2><?= t('Routine housekeeping') ?></h2><p class="hint"><?= t('Remove expired rate limits and reset tokens, expire old pending top-ups, and rotate old audit entries according to retention settings. Financial ledgers are never deleted by this action.') ?></p><?= form_start('admin_cleanup') ?><?php button('Run housekeeping','secondary','refresh'); ?></form><h3><?= t('Backups that can restore the site') ?></h3><p class="hint"><?= t('Back up the complete database, private storage and app/config.php together. The application secret is needed to decrypt payment snapshots, delivery codes and payout information. Keep backups outside the public web root.') ?></p><h3><?= t('Manual health check') ?></h3><p class="hint"><?= t('Test registration, sign-in, private downloads, the payment callback and an actual restore after changing hosts. There is no automatic cross-host migration or restore tool in this release.') ?></p></section></div><section class="panel section"><h2><?= t('Build information') ?></h2><div class="prose"><p>Chengyu <?= e(\Chengyu\App::VERSION) ?> / PHP + PDO / SQLite or MySQL / no WordPress / no Composer / no Node runtime</p><p><?= t('This release is an independently implemented feature set, not complete compatibility with all historical Zibll versions. See the delivered feature matrix and test report before launch.') ?></p></div></section>

<?php partial('diagnostics'); ?>
