<?php
use Chengyu\Core\Motion;
$motionSections=[
    'Timing and choreography'=>['motion','motion_adaptive','motion_curve','motion_duration','motion_reveal_style','motion_stagger','motion_distance','hover_lift','reveal','page_transition','motion_theme_transition'],
    'Physical spring response'=>['motion_response','spring_stiffness','spring_damping','spring_mass','motion_disclosures'],
    'Light and interaction'=>['motion_spotlight','motion_tilt','motion_tilt_degrees','motion_magnetic','motion_magnetic_distance','motion_sheen','motion_parallax','ripple'],
    'State and navigation'=>['motion_layout','motion_navigation','motion_feedback','motion_images'],
    'Atmosphere'=>['ambient','grain','particles','motion_continuous'],
    'Custom cubic Bezier'=>['curve_x1','curve_y1','curve_x2','curve_y2'],
];
?>
<div class="admin-title"><div><span class="eyebrow">DESIGN SYSTEM / MOTION LAB</span><h1><?= t('Make every interaction feel considered.') ?></h1><p><?= t('One motion engine. Real controls, instant preview, accessible by default.') ?></p></div><a class="btn secondary" href="<?= e(au('settings',['group'=>'appearance'])) ?>"><?= icon('palette') ?><?= t('Appearance') ?></a></div>
<div class="motion-presets" data-motion-presets="<?= e(json_encode(Motion::presets(),JSON_THROW_ON_ERROR)) ?>">
<?php foreach(['quiet'=>['01','Quiet focus','Small movements. More room to think.'],'balanced'=>['02','Balanced flow','Soft arrivals and thoughtful responses.'],'expressive'=>['03','Expressive light','Depth, light and a little more personality.']] as $key=>$preset): ?><button class="motion-preset panel" type="button" data-motion-preset="<?= e($key) ?>"><span class="motion-preset-number"><?= e($preset[0]) ?></span><span><strong><?= t($preset[1]) ?></strong><small><?= t($preset[2]) ?></small></span><?= icon('arrow') ?></button><?php endforeach ?></div>
<?= form_start('admin_motion','','motion-studio-form') ?>
<div class="motion-studio-grid">
<section class="panel motion-controls"><div class="section-heading"><div><span class="eyebrow">CONTROLS</span><h2><?= t('Your motion language') ?></h2></div><span class="pill soft" data-motion-dirty><?= t('Live preview') ?></span></div>
<?php foreach($motionSections as $section=>$keys): ?><details class="motion-section" <?= $section==='Timing and choreography'?'open':'' ?>><summary><?= t($section) ?></summary><div class="motion-fields"><?php foreach($keys as $key):$definition=$s->schema()[$key];$type=$definition[2];$value=$s->get($key); ?><div class="motion-field <?= $type==='bool'?'motion-field-toggle':'' ?>" data-motion-row="<?= e($key) ?>"><?php if($type==='bool'): ?><label class="toggle-row"><span><?= t($definition[1]) ?></span><span class="toggle"><input type="checkbox" name="<?= e($key) ?>" value="1" <?= $value?'checked':'' ?>><span></span></span></label><?php elseif($type==='select'):select_field($key,$definition[1],options($definition[4]),$value);else: ?><label class="field"><span><?= t($definition[1]) ?><output data-motion-value="<?= e($key) ?>"><?= (int)$value ?></output></span><input type="range" name="<?= e($key) ?>" min="<?= (int)$definition[5] ?>" max="<?= (int)$definition[6] ?>" value="<?= (int)$value ?>" step="1"></label><?php endif ?></div><?php endforeach ?></div></details><?php endforeach ?>
<div class="save-bar"><span class="hint"><?= icon('shield') ?><?= t('Preview is local until you save.') ?></span><?php button('Save motion settings','','check'); ?></div></section>
<aside class="motion-preview-column">
<section class="motion-stage panel glass"><div class="row between"><span class="eyebrow">FEEL THE DIFFERENCE</span><button type="button" class="btn small secondary" data-motion-replay><?= icon('sparkles') ?><?= t('Replay') ?></button></div><div class="motion-scene" aria-hidden="true"><div class="motion-orbit"></div><div class="motion-orb"></div><div class="motion-dot"></div><div class="motion-scene-grid"></div></div><article class="motion-preview-card glass" data-motion-demo><span class="pill soft"><?= icon('leaf') ?><?= t('A place to grow') ?></span><h2><?= t('Good design has a rhythm.') ?></h2><p><?= t('Hover, press, explore. The preview uses the exact same engine as your website.') ?></p><button class="btn" type="button" data-motion-replay><?= t('Feel the curve') ?><?= icon('arrow') ?></button></article><div class="motion-stagger-demo" aria-hidden="true"><i></i><i></i><i></i></div></section>
<section class="panel curve-panel"><div class="section-heading"><h3><?= t('The shape of time') ?></h3><span class="pill soft" data-curve-duration></span></div><div class="curve-inspector"><svg viewBox="-14 -70 128 240" role="img" aria-label="<?= t('Cubic Bezier timing curve') ?>" data-curve-graph><path class="curve-grid" d="M0 0V100H100V0Z M0 50H100 M50 0V100"/><path class="curve-guides" data-curve-guides d=""/><path class="curve-line" data-curve-line d=""/><circle data-curve-point="1" r="3.5"/><circle data-curve-point="2" r="3.5"/><circle class="curve-end" cx="0" cy="100" r="2.5"/><circle class="curve-end" cx="100" cy="0" r="2.5"/></svg><div><span class="eyebrow">CSS / CUBIC-BEZIER</span><code data-curve-code></code><p class="hint"><?= t('Horizontal: elapsed time. Vertical: animation progress. Values above one create a gentle overshoot.') ?></p><div class="curve-runway"><i data-curve-runner></i></div></div></div><p class="motion-device-status hint" data-motion-status role="status"><?= t('Respecting device and accessibility preferences.') ?></p></section>
<section class="panel spring-panel"><div class="section-heading"><div><span class="eyebrow">PHYSICS / CONTINUITY</span><h3><?= t('A response, not a replay.') ?></h3></div><span class="pill soft" data-spring-ratio></span></div><svg viewBox="0 0 320 136" role="img" aria-label="<?= t('Physical spring response') ?>" class="spring-graph"><path class="curve-grid" d="M0 20H320M0 110H320M80 0V136M160 0V136M240 0V136"/><path data-spring-line class="curve-line" d=""/></svg><div class="row between"><span class="hint"><?= t('Settling time') ?></span><strong data-spring-time></strong></div><div class="curve-runway spring-runway"><i data-spring-runner></i></div><p class="hint"><?= t('Stiffness pulls, damping settles, mass carries momentum. The same solver powers pointer motion and this preview.') ?></p><button type="button" class="btn small secondary" data-spring-replay><?= icon('sparkles') ?><?= t('Replay spring') ?></button></section>
<section class="panel"><span class="eyebrow">STATE / MICROINTERACTION</span><h3><?= t('Clear feedback, no waiting games.') ?></h3><div class="feedback-demo-tabs" data-feedback-tabs><button type="button" class="active" aria-pressed="true"><?= t('Discover') ?></button><button type="button" aria-pressed="false"><?= t('Reading history') ?></button><button type="button" aria-pressed="false"><?= t('Creator studio') ?></button></div><button type="button" class="btn secondary" data-feedback-demo="<?= t('A clear response. Your action stays in control.') ?>"><?= icon('check') ?><?= t('Preview feedback') ?></button><p class="hint"><?= t('The indicator follows focus and pointer. Navigation and saving never wait for animation.') ?></p></section>
<section class="motion-note"><span class="quick-icon"><?= icon('shield') ?></span><p><?= t('Motion never controls permissions, payment or content availability. Reduced-motion users keep every feature without decorative movement.') ?></p></section>
</aside></div></form>
