<?php
$id=\Chengyu\Core\Input::integer($_GET['content_id']??0);$item=$id?$a->db->one("SELECT * FROM cy_contents WHERE id=? AND kind<>'page'",[$id]):null;
if($id && !$item){throw new \Chengyu\Core\Problem('Content not found.',404);}
$rule=$item?($a->pricing->rule($id)??[]):[];
$products=$a->db->all("SELECT id,title,kind,price_amount,price_currency FROM cy_contents WHERE kind<>'page' ORDER BY id DESC LIMIT 300");
?>
<div class="admin-title"><div><span class="eyebrow">VALUE / WITHOUT SURPRISES</span><h1><?= t('Pricing studio') ?></h1><p><?= t('One pricing rule for preview, every SKU, checkout and the saved order.') ?></p></div><a class="btn secondary" href="<?= e(au('coupons')) ?>"><?= icon('gift') ?><?= t('Coupons') ?></a></div>
<div class="pricing-intro panel glass section"><div><span class="pill soft"><?= t('Integer-only accounting') ?></span><h2><?= t('The best eligible price wins') ?></h2><p><?= t('Member pricing and a timed promotion do not compound. Higher tiers inherit lower-tier benefits. Coupon stacking is a separate explicit switch.') ?></p></div><div class="pricing-orbit" aria-hidden="true"><span>VIP</span><strong>%</strong><span>TIME</span></div></div>
<div class="admin-edit-grid"><section class="panel"><form method="get" action="<?= e($a->basePath.'/admin/index.php') ?>"><?= hidden('tab','pricing') ?><?php field('content_id','Content ID',$id?:'','number',['min'=>'1','required'=>'required']);button('Load pricing','secondary','arrow'); ?></form><div class="table-wrap"><table class="data-table"><thead><tr><th><?= t('Content') ?></th><th><?= t('List price') ?></th><th><?= t('Manage') ?></th></tr></thead><tbody><?php foreach($products as $p): ?><tr><td>#<?= (int)$p['id'] ?> <?= e($p['title']) ?></td><td><?= e(price((int)$p['price_amount'],$p['price_currency'])) ?></td><td><a class="btn ghost small" href="<?= e(au('pricing',['content_id'=>$p['id']])) ?>"><?= t('Pricing') ?></a></td></tr><?php endforeach ?></tbody></table></div><p class="hint"><?= t('Latest 300 records. Enter a content ID to edit an older record.') ?></p></section>
<section class="panel glass"><?php if($item): ?><span class="eyebrow">#<?= $id ?> / <?= e($item['price_currency']) ?></span><h2><?= e($item['title']) ?></h2><?= form_start('admin_pricing') . hidden('content_id',$id) . hidden('revision',$rule['revision']??0) ?><h3><?= t('Member purchase rates') ?></h3><p class="hint"><?= t('Rate is the amount paid: 8000 means pay 80%, 10000 means full price, 0 means free. Fractions of the smallest asset unit round down.') ?></p><div class="fields-grid"><?php foreach([1,2,3] as $tier){field('vip'.$tier.'_bps','VIP '.$tier,$rule['vip'.$tier.'_bps']??10000,'number',['min'=>'0','max'=>'10000','step'=>'1','required'=>'required']);} ?></div><h3><?= t('Timed promotion') ?></h3><?php field('promo_bps','Promotion purchase rate',$rule['promo_bps']??10000,'number',['min'=>'0','max'=>'10000','step'=>'1']); ?><div class="fields-grid"><?php field('starts_at','Promotion starts',!empty($rule['starts_at'])?date('Y-m-d\TH:i',(int)$rule['starts_at']):'','datetime-local');field('ends_at','Promotion ends',!empty($rule['ends_at'])?date('Y-m-d\TH:i',(int)$rule['ends_at']):'','datetime-local'); ?></div><?php check_field('active','Enable this pricing rule',!isset($rule['active']) || (bool)$rule['active']);button('Save pricing rule','full','check'); ?></form><p class="hint"><?= t('Rules affect future purchases only. Existing order snapshots, refunds and creator shares keep their original transaction amounts.') ?></p><a class="text-link" href="<?= e(au('edit_content',['id'=>$id])) ?>"><?= t('Edit base price and access policy') ?><?= icon('arrow') ?></a><?php else: empty_state('Choose content to configure its member and promotion prices.','gift');endif ?></section></div>
