<?php
$id=\Chengyu\Core\Input::integer($_GET['id']??0);$course=$id?$a->db->one('SELECT * FROM cy_courses WHERE id=?',[$id]):null;
if($id&&!$course){throw new \Chengyu\Core\Problem('Course not found.',404);}
$lessonId=\Chengyu\Core\Input::integer($_GET['lesson']??0);$lesson=$lessonId?$a->db->one('SELECT * FROM cy_lessons WHERE id=? AND course_id=?',[$lessonId,$id]):null;
if($lessonId&&!$lesson){throw new \Chengyu\Core\Problem('Lesson not found.',404);}
partial('platform_header',['title'=>$title,'kicker'=>'TEACH / CREATE','symbol'=>'book','subtitle'=>'Turn an article or digital product into a structured learning journey.']);
?>
<div class="platform-grid section"><aside class="panel commerce-panel"><h2><?= t('Courses') ?></h2><a class="btn secondary small" href="<?= e(au('learning')) ?>"><?= icon('plus') ?><?= t('New course') ?></a>
<?php foreach($a->db->all('SELECT id,title,active FROM cy_courses ORDER BY id DESC LIMIT 100') as $c): ?><a class="platform-list-link <?= $id===(int)$c['id']?'active':'' ?>" href="<?= e(au('learning',['id'=>$c['id']])) ?>"><span><?= e($c['title']) ?></span><small><?= t((int)$c['active']?'Published':'Draft') ?></small></a><?php endforeach ?><p class="hint"><?= t('Newest 100 courses. Open older course IDs directly when needed.') ?></p></aside>
<section class="panel commerce-panel"><h2><?= t($id?'Course settings':'New course') ?></h2><?= form_start('course_save','','',false).hidden('id',$id).hidden('revision',$course['revision']??0) ?>
<?php field('content_id','Access source content ID',$course['content_id']??'','number',array_merge(['min'=>'1','required'=>'required'],$id?['readonly'=>'readonly']:[]));field('title','Course title',$course['title']??'','text',['required'=>'required','maxlength'=>'200']);field('description','Public course description',$course['description']??'','textarea',['maxlength'=>'4000']);check_field('active','Published',!empty($course['active']));button('Save course','','check'); ?></form><p class="hint"><?= t('The source content controls purchase, membership and expiry. Changing access takes effect immediately for lessons and media.') ?></p><?php if($id): ?><a class="btn secondary small" href="<?= e(url('course',['id'=>$id])) ?>"><?= t('View course') ?></a><?php endif ?></section></div>
<?php if($course): ?><div class="platform-grid section"><section class="panel commerce-panel"><div class="row between wrap"><h2><?= t('Lesson outline') ?></h2><a class="btn secondary small" href="<?= e(au('learning',['id'=>$id])) ?>"><?= t('New lesson') ?></a></div><ol class="lesson-outline"><?php foreach($a->db->all('SELECT id,title,sort_order,preview,active FROM cy_lessons WHERE course_id=? ORDER BY sort_order,id',[$id]) as $l): ?><li><a href="<?= e(au('learning',['id'=>$id,'lesson'=>$l['id']])) ?>"><strong><?= e($l['title']) ?></strong><small>#<?= (int)$l['id'] ?> / <?= t($l['active']?'Published':'Draft') ?> <?= $l['preview']?' / '.t('Free preview'):'' ?></small></a></li><?php endforeach ?></ol></section>
<section class="panel commerce-panel"><h2><?= t($lesson?'Edit lesson':'New lesson') ?></h2><?= form_start('lesson_save','','',false).hidden('id',$lessonId).hidden('course_id',$id).hidden('revision',$lesson['revision']??0) ?>
<?php field('title','Lesson title',$lesson['title']??'','text',['required'=>'required','maxlength'=>'200']);field('body','Lesson body (Markdown)',$lesson['body']??'','textarea',['maxlength'=>'50000']);field('media_id','Private resource ID',$lesson['media_id']??0,'number',['min'=>'0']);field('duration_seconds','Duration in seconds (0 = unknown)',$lesson['duration_seconds']??0,'number',['min'=>'0','max'=>'604800']);field('sort_order','Sort order',$lesson['sort_order']??0,'number',['min'=>'0','max'=>'10000']);check_field('preview','Free preview',!empty($lesson['preview']));check_field('active','Published',$lesson?(bool)$lesson['active']:true);button('Save lesson','','check'); ?></form><p class="hint"><?= t('A free preview deliberately grants access to its resource. Do not reuse that file in a private lesson unless public access is intended.') ?></p><a href="<?= e(au('media_lab')) ?>" class="text-link"><?= t('Open media workbench') ?></a></section></div><?php endif ?>
