<?php $id=\Chengyu\Core\Input::integer($_GET['id']??0);$page=\Chengyu\Core\Input::integer($_GET['page']??1,1,100000);partial('platform_header',['title'=>$title,'kicker'=>'VERIFY / NEVER ASSUME','symbol'=>'chart','subtitle'=>'Compare normalized provider statements with local transactions. Imports never move money.']); ?>
<div class="platform-grid section"><section class="panel commerce-panel"><h2><?= t('Import normalized statement') ?></h2><p class="hint"><?= t('Use gross amounts in integer minor units. UTF-8 CSV, at most 2 MiB and 2000 rows. Fees and exchange conversion are not inferred.') ?></p>
<?= str_replace('<form ','<form enctype="multipart/form-data" ',form_start('statement_import','','',false)) ?>
<?php select_field('gateway','Gateway',\Chengyu\Services\DirectPayments::NAMES,'stripe');field('starts_at','Window start (inclusive, with timezone)',gmdate('Y-m-d\T00:00:00\Z'),'text',['required'=>'required']);field('ends_at','Window end (exclusive, with timezone)',gmdate('Y-m-d\T00:00:00\Z',time()+86400),'text',['required'=>'required']);field('statement','CSV file','','file',['accept'=>'.csv,text/csv']);field('csv','Or paste normalized CSV','','textarea',['rows'=>'5','spellcheck'=>'false']);button('Import and compare','','upload'); ?></form>
<details class="commerce-details"><summary><?= t('CSV schema and example') ?></summary><pre class="platform-code">event_type,reference,trade_id,currency,amount_minor,state,event_at
payment,LOCAL_SALE_NO,PROVIDER_TRADE_ID,CNY,100,succeeded,2026-09-01T12:00:00+08:00</pre><p><?= t('For refunds, reference is the local refund number and trade_id is the provider refund ID. Use one final status per reference. Convert provider-specific columns before importing.') ?></p><p><?= t('A statement mismatch requires investigation. Uploads are not trusted payment notifications.') ?></p></details></section>
<aside class="panel commerce-panel"><h2><?= t('Imported statements') ?></h2><?php foreach($a->db->all('SELECT * FROM cy_recon_batches ORDER BY id DESC LIMIT 30') as $b): ?><a class="platform-list-link" href="<?= e(au('reconciliation',['id'=>$b['id']])) ?>"><span>#<?= (int)$b['id'] ?> <?= e($b['gateway']) ?></span><small><?= dt((int)$b['starts_at']) ?> / <?= dt((int)$b['ends_at']) ?></small></a><?php endforeach ?></aside></div>
<?php if($id): $batch=$a->reconciliation->summary($id);$count=(int)$a->db->value('SELECT COUNT(*) FROM cy_recon_rows WHERE batch_id=?',[$id]); ?><section class="section"><div class="row between wrap"><h2><?= t('Comparison results') ?> #<?= $id ?></h2><?= form_start('statement_check','','',false).hidden('batch_id',$id) ?><?php button('Recheck current local state','secondary small','refresh'); ?></form></div><div class="platform-stats"><?php foreach($batch['counts'] as $c): ?><div class="panel platform-stat"><span><?= t($c['outcome']) ?></span><strong><?= (int)$c['count'] ?></strong></div><?php endforeach ?></div><p class="hint"><?= t('Last checked') ?>: <?= dt((int)$batch['checked_at'],'Y-m-d H:i:s') ?> &middot; <?= t('Report-only: no balances, orders or refunds are changed.') ?></p>
<div class="table-wrap panel"><table class="data-table"><thead><tr><?php foreach(['Reference','Event','Gross amount','Outcome','Explanation'] as $h): ?><th><?= t($h) ?></th><?php endforeach ?></tr></thead><tbody><?php foreach($a->reconciliation->rows($id,$page) as $row): ?><tr><td><code><?= e($row['reference']) ?></code><br><small><?= e($row['trade_id']) ?></small></td><td><?= t($row['event_type']) ?></td><td><?= e($row['currency'].' '.money((int)$row['amount_minor'])) ?></td><td><span class="pill"><?= t($row['outcome']) ?></span></td><td><?= t($row['message']) ?></td></tr><?php endforeach ?></tbody></table></div><?php partial('pagination',['pagination'=>['page'=>$page,'pages'=>max(1,(int)ceil($count/50))],'tab'=>'reconciliation']); ?></section><?php endif ?>
