<?php
$orderId=\Chengyu\Core\Input::integer($_GET['order_id']??0);$parcelId=\Chengyu\Core\Input::integer($_GET['parcel']??0);$new=!empty($_GET['new']);
$parcels=$orderId?$a->tracking->parcels($orderId,$me):[];
$shipment=$orderId && $parcels && !$new?$a->tracking->view($orderId,$me,$parcelId):null;
$packageKey=$shipment?$shipment['package_key']:($parcels?bin2hex(random_bytes(16)):'primary');
partial('platform_header',['title'=>$title,'kicker'=>'DELIVER / WITH CLARITY','symbol'=>'box','subtitle'=>'Every parcel has its own waybill, timeline and revision. Order payment stays separate.']);
?>
<?php if($parcels): ?><nav class="parcel-deck section" aria-label="<?= t('Order parcels') ?>"><?php foreach($parcels as $n=>$p): ?><a class="panel parcel-card <?= $shipment && (int)$shipment['id']===(int)$p['id']?'is-selected':'' ?>" href="<?= e(au('logistics',['order_id'=>$orderId,'parcel'=>$p['id']])) ?>" <?= $shipment && (int)$shipment['id']===(int)$p['id']?'aria-current="page"':'' ?>><span class="parcel-index"><?= sprintf('%02d',$n+1) ?></span><strong><?= e($p['package_label']?:tr('Parcel').' '.($n+1)) ?></strong><small><?= e($p['carrier'].' / '.$p['tracking_number']) ?></small></a><?php endforeach ?><a class="panel parcel-card parcel-add" href="<?= e(au('logistics',['order_id'=>$orderId,'new'=>1])) ?>"><?= icon('plus') ?><strong><?= t('Add another parcel') ?></strong></a></nav><?php endif ?>
<div class="platform-grid section"><section class="panel commerce-panel"><h2><?= t($shipment?'Edit this parcel':'Attach a parcel') ?></h2><?= form_start('tracking_attach','','',false).hidden('revision',$shipment['revision']??0).hidden('package_key',$packageKey) ?>
<?php field('order_id','Order ID',$orderId?:'','number',['min'=>'1','required'=>'required']);field('package_label','Parcel label',$shipment['package_label']??'','text',['maxlength'=>'100','placeholder'=>tr('Main item / accessories')]);field('carrier','Carrier code',$shipment['carrier']??'','text',['required'=>'required','maxlength'=>'40','placeholder'=>'shunfeng / yuantong / manual']);field('tracking_number','Tracking number',$shipment['tracking_number']??'','text',['required'=>'required','maxlength'=>'32']);button('Save shipment','','check'); ?></form><p class="hint"><?= t('Changing a waybill clears only that parcel timeline. Existing parcel IDs are preserved after upgrade.') ?></p></section>
<aside class="panel commerce-panel"><h2><?= t('Recent shipments') ?></h2><?php foreach($a->db->all('SELECT s.id,s.order_id,s.carrier,s.package_label,o.order_no FROM cy_shipments s JOIN cy_orders o ON o.id=s.order_id ORDER BY s.id DESC LIMIT 30') as $row): ?><a class="platform-list-link" href="<?= e(au('logistics',['order_id'=>$row['order_id'],'parcel'=>$row['id']])) ?>"><span><?= e($row['order_no']) ?><small><?= e($row['package_label']) ?></small></span><small><?= e($row['carrier']) ?></small></a><?php endforeach ?><a class="text-link" href="<?= e(au('settings',['group'=>'commerce'])) ?>"><?= t('Tracking settings') ?></a></aside></div>
<?php if($shipment): ?><div class="platform-grid section"><section class="panel commerce-panel"><h2><?= t('Merchant timeline update') ?></h2><?= form_start('tracking_event','','',false).hidden('shipment_id',$shipment['id']).hidden('revision',$shipment['revision']) ?>
<?php field('event_at','Event time with timezone',date(DATE_ATOM),'text',['required'=>'required']);field('description','Timeline description','','textarea',['required'=>'required','maxlength'=>'1000']);button('Add timeline event','','plus'); ?></form></section><section class="panel commerce-panel"><h2><?= t('Query carrier') ?></h2><p><?= t('Carrier events are cached. A carrier delivery event does not automatically mark the order as received.') ?></p><?= form_start('tracking_refresh','','',false).hidden('shipment_id',$shipment['id']) ?>
<?php field('phone','Recipient or sender phone (only when required)','','text',['maxlength'=>'24','autocomplete'=>'off']);check_field('consent','Share the waybill and optional phone with the configured carrier service.');button('Refresh carrier timeline','secondary','refresh'); ?></form><p class="hint"><?= t('Last carrier query') ?>: <?= dt((int)$shipment['queried_at'],'Y-m-d H:i:s') ?></p></section></div>
<?php partial('tracking_timeline',['shipment'=>$shipment]);endif ?>
