<?php $pending=$a->db->all("SELECT * FROM cy_upload_sessions WHERE user_id=? AND state='open' ORDER BY id DESC LIMIT 8",[(int)$me['id']]); ?>
<section class="page-hero commerce-hero"><div><span class="eyebrow">MEDIA / WITHOUT THE FRICTION</span><h1><?= e($title) ?></h1><p><?= t('Upload in small verified chunks, or send files directly to your private S3-compatible bucket.') ?></p></div><?= icon('upload') ?></section>
<div class="commerce-grid section"><section class="panel glass commerce-panel" data-media-workbench data-endpoint="<?= e($a->basePath.'/action.php') ?>" data-owner="<?= (int)$me['id'] ?>">
<h2><?= t('New upload') ?></h2><p class="hint"><?= t('Local uploads resume after reselecting the same file. Keep the upload key until completion. Object uploads require bucket CORS and a private staging lifecycle rule.') ?></p>
<?php field('media_file','Choose a file','','file',['data-media-file'=>'1']);select_field('media_mode','Storage destination',['local'=>'Local resumable storage','s3'=>'Private S3-compatible bucket'],'local',['data-media-mode'=>'1']);check_field('media_private','Private attachment',true); ?>
<div class="row wrap"><button class="btn" type="button" data-media-start><?= icon('upload') ?><?= t('Upload / resume') ?></button><button class="btn secondary" type="button" data-media-pause disabled><?= t('Pause') ?></button></div><progress class="media-progress" max="100" value="0" data-media-progress aria-label="<?= t('Upload progress') ?>"></progress><output data-media-status role="status" aria-live="polite"></output><p class="hint" data-media-key></p><noscript><p><?= t('Chunk uploads need JavaScript. Standard file uploads remain available in the media library.') ?></p></noscript>
</section><aside class="panel glass commerce-panel"><h2><?= t('Operational limits') ?></h2><p><?= t('Maximum file size') ?>: <?= (int)$s->get('large_upload_max_mb') ?> MB</p><p><?= t('Local chunk size') ?>: 256 KB</p><p><?= t('Unfinished local quota') ?>: <?= (int)$s->get('large_upload_quota_mb') ?> MB</p><p class="hint"><?= t('This is file delivery, not transcoding, DRM or live streaming. A small free host cannot store unlimited video.') ?></p><a class="btn secondary" href="<?= e(au('settings',['group'=>'media_plus'])) ?>"><?= t('Storage settings') ?></a><a class="btn ghost" href="<?= e(au('media')) ?>"><?= t('Media library') ?></a></aside></div>
<section class="panel commerce-panel"><h2><?= t('Unfinished local uploads') ?></h2><?php foreach($pending as $up): ?><div class="commerce-line"><div><strong><?= e($up['name']) ?></strong><code><?= e($up['upload_key']) ?></code><small><?= dt((int)$up['expires_at']) ?></small></div><?= form_start('upload_cancel','','',false).hidden('upload_key',$up['upload_key']) ?><?php button('Cancel','secondary small','close'); ?></form></div><?php endforeach ?></section>
<section class="panel commerce-panel section"><h2><?= t('Finish an already uploaded object') ?></h2><?= form_start('object_finish','','',false) ?><?php field('upload_key','Upload key','','text',['required'=>'required','pattern'=>'[a-f0-9]{48}']);button('Verify and register','secondary','check'); ?></form><p class="hint"><?= t('After registration, find the resulting file in the media library. Staging objects are never used as published download links.') ?></p></section>
<script type="application/json" id="media-i18n"><?= json_encode(array_combine(['choose','uploading','paused','done','failed','verifying','key'],array_map('tr',['Choose a file first.','Uploading','Paused. Select the same file to resume.','Media registered','Upload failed. Review the error and retry.','Verifying and registering','Upload key'])),JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE) ?></script>
