<?php
$contentId=\Chengyu\Core\Input::integer($_GET['content_id']??0);$variantId=\Chengyu\Core\Input::integer($_GET['edit']??0);$v=$variantId?$a->db->one('SELECT * FROM cy_variants WHERE id=?',[$variantId]):null;
if($v){$contentId=(int)$v['content_id'];}
$products=$a->db->all("SELECT id,title,product_type,price_currency FROM cy_contents WHERE kind='product' AND product_type IN ('physical','code') ORDER BY id DESC LIMIT 500");$opts=[];$chosen=null;foreach($products as $p){$opts[$p['id']]='#'.$p['id'].' '.$p['title'];if((int)$p['id']===$contentId){$chosen=$p;}}
$rows=$a->db->all('SELECT v.*,c.title,c.price_currency,c.product_type FROM cy_variants v JOIN cy_contents c ON c.id=v.content_id'.($contentId?' WHERE v.content_id=?':'').' ORDER BY v.content_id,v.sort_order,v.id LIMIT 500',$contentId?[$contentId]:[]);
?>
<div class="admin-title"><div><span class="eyebrow">ONE PRODUCT / MANY POSSIBILITIES</span><h1><?= e($title) ?></h1><p><?= t('Variant price and stock are checked under the product lock. Digital reading access has no variants.') ?></p></div><a class="btn secondary" href="<?= e(au('variants',['content_id'=>$contentId])) ?>"><?= t('New variant') ?></a></div>
<div class="admin-edit-grid"><section class="panel"><form method="get" action="<?= e($a->basePath.'/admin/index.php') ?>" class="filter-bar"><?= hidden('tab','variants') ?><?php select_field('content_id','Product',[0=>tr('All products')]+$opts,$contentId);button('Filter','secondary small','search'); ?></form><div class="table-wrap"><table class="data-table"><thead><tr><th>SKU</th><th><?= t('Product') ?></th><th><?= t('Price') ?></th><th><?= t('Stock') ?></th><th><?= t('Manage') ?></th></tr></thead><tbody><?php foreach($rows as $row): ?><tr><td><strong><?= e($row['sku']) ?></strong><small class="table-subtext"><?= e($row['name']) ?></small></td><td><?= e($row['title']) ?><small class="table-subtext"><?= t($row['active']?'active':'disabled') ?></small></td><td><?= e(price((int)$row['price_amount'],$row['price_currency'])) ?></td><td><?= (int)$row['inventory']<0?t('Unlimited'):(int)$row['inventory'] ?></td><td><a class="btn secondary small" href="<?= e(au('variants',['edit'=>$row['id']])) ?>"><?= t('Edit') ?></a></td></tr><?php endforeach ?></tbody></table></div><?php if(!$rows){empty_state();} ?></section>
<section class="panel"><h2><?= t($v?'Edit variant':'New variant') ?></h2><?= form_start('admin_variant') . hidden('id',$v['id']??0) ?><?php select_field('content_id','Product',$opts,$contentId);field('sku','Unique SKU',$v['sku']??'','text',['required'=>'required','maxlength'=>'64','pattern'=>'[A-Za-z0-9_.-]+']);field('name','Variant name',$v['name']??'','text',['required'=>'required','maxlength'=>'100']);field('price','Price (CNY for balance; integer for points or tokens)',$v?($chosen['price_currency']==='balance'?money((int)$v['price_amount']):$v['price_amount']):'0','number',['min'=>'0','step'=>'0.01','required'=>'required']);field('inventory','Stock (-1 means unlimited)',$v['inventory']??0,'number',['min'=>'-1']);field('sort_order','Sort order',$v['sort_order']??0,'number',['min'=>'0']);check_field('active','Enabled',!isset($v['active'])||(bool)$v['active']);button('Save variant','full'); ?><p class="hint"><?= t('Code-delivery inventory is derived from imported unused codes. Import codes after creating each variant. Existing base codes must be consumed before switching to variants.') ?></p></form><a class="text-link" href="<?= e(au('stock')) ?>"><?= t('Import delivery codes') ?><?= icon('arrow') ?></a></section></div>
