<?php $status=$a->search->status();partial('platform_header',['title'=>$title,'kicker'=>'DISCOVERY','symbol'=>'compass','subtitle'=>'Search public metadata with a local bilingual index. Protected content stays out.']); ?>
<div class="platform-stats section"><?php foreach(['documents'=>'Indexed documents','terms'=>'Index entries','total'=>'Source documents'] as $k=>$label): ?><div class="panel platform-stat"><span><?= t($label) ?></span><strong><?= number_format((int)$status[$k]) ?></strong></div><?php endforeach ?></div>
<div class="platform-grid"><section class="panel commerce-panel"><div class="row between wrap"><h2><?= t('Index maintenance') ?></h2><span class="pill"><?= t($status['completed']?'Ready':'Rebuild required') ?></span></div><p><?= t('The index supports English words and CJK character pairs. It is not a spelling corrector or an external search cluster.') ?></p><p class="hint"><?= t('Before the first rebuild completes, search uses the existing metadata query. New content and approved translations update automatically.') ?></p>
<?= form_start('search_rebuild','','platform-job',false) ?><div class="row wrap"><?php button('Process next 10 documents','','refresh'); ?><button class="btn secondary" name="reset" value="1" type="submit"><?= t('Restart index') ?></button><button class="btn secondary" type="button" data-index-run><?= t('Continue until complete') ?></button><button class="btn ghost" type="button" data-index-stop hidden><?= t('Pause') ?></button></div><output class="platform-output" data-index-status role="status"><?= t('Last indexed ID') ?>: <?= (int)$status['cursor_id'] ?></output></form><p class="hint"><?= t('Automatic continuation runs only while this page stays open. Every request is limited to 10 documents.') ?></p></section>
<aside class="panel commerce-panel"><h2><?= t('Search controls') ?></h2><a class="btn secondary full" href="<?= e(au('settings',['group'=>'discovery'])) ?>"><?= t('Search settings') ?></a><a class="btn ghost full" href="<?= e(url('search')) ?>"><?= t('Test public search') ?></a><p class="hint"><?= t('Permissions, publication time and source revision are checked again when results are read.') ?></p></aside></div>
<?php $remote=$a->remoteSearch->status(); ?>
<section class="panel remote-search-panel section" data-workbench-glow>
<div class="row between wrap"><div><span class="eyebrow">MEILISEARCH / OPTIONAL</span><h2><?= t('Professional search connector') ?></h2></div><span class="pill"><?= t($remote['configured']?'Configuration saved':'Not configured') ?></span></div>
<p><?= t('Search queries and public titles, summaries and tags can use Meilisearch. Private bodies, accounts and orders never enter this index.') ?></p>
<div class="platform-stats section"><?php foreach(['queued'=>'Queued documents','waiting'=>'Awaiting remote confirmation','retrying'=>'Scheduled retries'] as $key=>$label): ?><div class="platform-stat"><span><?= t($label) ?></span><strong><?= (int)$remote[$key] ?></strong></div><?php endforeach ?></div>
<div class="platform-grid"><div><h3><?= t('Build the synchronization queue') ?></h3><?= form_start('search_remote_rebuild','','',false) ?><div class="row wrap"><?php button('Queue next 25 documents','secondary','plus'); ?><button class="btn ghost" type="submit" name="reset" value="1"><?= t('Restart queue scan') ?></button></div></form><p class="hint"><?= t('Last queued ID') ?>: <?= (int)$remote['cursor_id'] ?> / <?= t($remote['completed']?'Scan complete':'More documents remain') ?></p></div>
<div><h3><?= t('Confirm remote tasks') ?></h3><?= form_start('search_remote_run','','remote-job',false) ?><div class="row wrap"><?php button('Process one due task','','refresh'); ?><button type="button" class="btn secondary" data-remote-run><?= t('Run a short synchronization session') ?></button><button type="button" class="btn ghost" data-remote-stop hidden><?= t('Pause') ?></button></div><output data-remote-status class="platform-output" role="status"></output></form></div></div>
<p class="hint"><?= t('An accepted task is not yet complete. Progress is confirmed with the remote task API; failures retain the queue and retry later.') ?></p>
<p class="hint"><?= t('Local matching remains available, including restricted categories you are allowed to read. Up to 200 remote candidates enrich each query, with live permissions and revisions checked locally.') ?></p>
<a class="text-link" href="<?= e(au('settings',['group'=>'discovery'])) ?>"><?= t('Configure Meilisearch and consent') ?></a>
</section>
