<?php partial('composed',['slot'=>($item['kind']==='page'?'page_before':'article_before')]); ?>
<?php if(!$access && $item['access_level']==='password'): ?><section class="panel glass unlock-panel"><h2><?= t('Password-protected content') ?></h2><?= form_start('content_unlock') . hidden('content_id',$item['id']) ?><?php field('content_password','Content password','','password',['required'=>'required','autocomplete'=>'off']);button('Unlock protected content','','lock'); ?></form></section><?php endif ?>
<?php use Chengyu\Core\Markdown; ?>
<?php if($me && $access && $s->enabled('reading_history') && !empty($me['history_enabled'])): ?><span hidden data-reading-content="<?= (int)$item['id'] ?>"></span><?php endif ?>
<div class="breadcrumb section"><a href="<?= e(url()) ?>"><?= t('Home') ?></a><?= icon('chevron') ?><a href="<?= e(url(['article'=>'articles','thread'=>'forum','product'=>'shop','page'=>'home'][$item['kind']])) ?>"><?= e($item['category_name'] ?: tr($item['kind'])) ?></a></div>
<div class="main-grid <?= !$s->get('show_sidebar')?'no-sidebar':'' ?>"><div><article class="article-panel panel glass" data-focus-article><div class="article-labels"><span class="pill soft"><?= e($item['category_name'] ?: tr($item['kind'])) ?></span><?php if ($item['status']!=='published' || (int)$item['publish_at']>time()): ?><span class="pill warning"><?= t('Unpublished preview') ?></span><?php endif ?><?php if ($item['access_level']!=='public'): ?><span class="pill"><?= icon('lock') ?><?= t($item['access_level'] === 'paid' ? 'Paid access' : $item['access_level']) ?></span><?php endif ?></div><h1 class="article-title"><?= e($item['title']) ?></h1><div class="article-meta"><?php if ($s->get('show_authors')): ?><a class="row" href="<?= e(url('user',['id'=>$item['author_id']])) ?>"><?= avatar($item,'small') ?><span><?= e($item['display_name']) ?></span></a><?php endif ?><?php if ($s->get('show_dates')): ?><time><?= icon('clock') ?><?= dt((int)$item['created_at']) ?></time><?php endif ?><?php if ($s->get('show_stats')): ?><span><?= icon('eye') ?><?= (int)$item['view_count'] ?></span><?php endif ?></div><?php if ($item['kind']!=='thread'): ?><img class="article-cover" src="<?= e(cover($item)) ?>" alt="" width="1280" height="760"><?php endif ?><div class="prose" data-reading-body><?= Markdown::render($item['body']) ?></div>
<?php if(!empty($thread)) { partial('thread_panel',['thread'=>$thread,'item'=>$item]); } ?>
<?php if ($access): ?><?php if ($item['protected_body']): ?><div class="protected-content prose" data-reading-body><?= Markdown::render($item['protected_body']) ?></div><?php endif ?><?php if ((int)$item['resource_id']): ?><div class="download-card"><span class="quick-icon"><?= icon('file') ?></span><div class="grow"><strong><?= t('Your resource is ready') ?></strong><p><?= t('Downloads are checked against your content access.') ?></p></div><a class="btn" href="<?= e(media_url((int)$item['resource_id'])) ?>"><?= icon('download') ?><?= t('Download') ?></a></div><?php endif ?>
<?php partial('resource_library',['item'=>$item]); ?>
<?php elseif ($item['kind']!=='product'): ?><section class="paywall"><span class="paywall-icon"><?= icon('lock') ?></span><h3><?= t('There is a little more to this story.') ?></h3><p><?= t(['login'=>'Sign in to read the rest.','vip'=>'This story is reserved for active members.','paid'=>'Purchase access using your site wallet.','reply'=>'An approved reply unlocks the rest of this story.'][$item['access_level']] ?? 'Sign in to continue.') ?></p><?php if (!$me): ?><a class="btn" href="<?= e(url('login')) ?>"><?= t('Sign in') ?><?= icon('arrow') ?></a><?php elseif ($item['access_level']==='vip' && $s->enabled('membership')): ?><a class="btn" href="<?= e(url('membership')) ?>"><?= icon('crown') ?><?= t('Explore membership') ?></a><?php endif ?></section><?php endif ?>
<?php if (($item['access_level']==='paid' && !$access) || $item['kind']==='product'): ?><section class="purchase-panel"><?php if($s->enabled('checkout') && $item['price_currency']==='balance'): ?><a class="btn full commerce-entry" href="<?= e(url('checkout',['item_id'=>$item['id']])) ?>"><?= icon('shield') ?><?= t($me?'Checkout with shipping and direct payment':'Guest checkout') ?></a><?php endif ?><?php if((int)$item['access_days']): ?><p class="pill"><?= t('Purchased access days') ?>: <?= (int)$item['access_days'] ?></p><?php endif ?><div class="row between wrap"><div><span class="eyebrow"><?= t($item['product_type']) ?></span><strong class="purchase-price"><?= e(item_price($item)) ?></strong></div><span class="muted"><?= t('Stock') ?>: <?= (int)$item['inventory']<0?t('Available'):(int)$item['inventory'] ?></span></div><?php if ($me): ?><?= form_start('buy','','purchase-form') . intent() . hidden('kind','content') . hidden('item_id',$item['id']) ?><?php partial('price_quote',['item'=>$item]); ?><?php if($item['kind']==='product'){variant_select($item);} ?><?php if ($item['price_currency']==='balance'): field('coupon','Coupon code (optional)'); endif ?><?php if ($item['product_type']==='physical') {address_select((int)$me['id']);} ?><div class="row wrap"><?= button('Buy with site assets','','lock') ?><?php if ($s->enabled('wallet')): ?><a href="<?= e(url('wallet')) ?>" class="text-link"><?= t('Open your wallet') ?><?= icon('arrow') ?></a><?php endif ?></div><p class="hint"><?= t('Payment deducts your selected site asset immediately. Check the order details before confirming.') ?></p></form><?php if ($item['kind']==='product' && $s->enabled('cart')): ?><?= form_start('cart_add') . hidden('item_id',$item['id']) ?><?php variant_select($item); ?><?= button('Add to collection bag','secondary full','box') ?></form><?php endif ?><?php else: ?><a class="btn full" href="<?= e(url('login')) ?>"><?= t('Sign in to purchase') ?><?= icon('arrow') ?></a><?php endif ?></section><?php endif ?>
<?php if ($item['tags']): ?><div class="tag-list"><?php foreach (explode(',',$item['tags']) as $tag): ?><a class="tag" href="<?= e(url('search',['q'=>trim($tag)])) ?>"># <?= e(trim($tag)) ?></a><?php endforeach ?></div><?php endif ?><div class="article-actions"><?php foreach (['like'=>'Likes','favorite'=>'Bookmarks'] as $kind=>$label): if (!$s->enabled($kind==='like'?'likes':'favorites')) {continue;} $count=(int)$a->db->value('SELECT COUNT(*) FROM cy_reactions WHERE content_id=? AND kind=?',[(int)$item['id'],$kind]); ?><?php if ($me): ?><?= form_start('reaction') . hidden('content_id',$item['id']) . hidden('kind',$kind) ?><button class="btn secondary"><?= icon($kind==='like'?'heart':'bookmark') ?><?= t($label) ?> <?= $s->get('show_stats')?$count:'' ?></button></form><?php else: ?><a class="btn secondary" href="<?= e(url('login')) ?>"><?= icon($kind==='like'?'heart':'bookmark') ?><?= t($label) ?></a><?php endif ?><?php endforeach ?><?php if($s->get('native_share')): ?><button type="button" class="btn secondary" data-native-share="<?= e(substr($a->config['url'],0,strlen($a->config['url'])-strlen($a->basePath)).item_url($item)) ?>"><?= icon('compass') ?><?= t('Share') ?></button><?php else: ?><button class="btn secondary" data-copy="<?= e(substr($a->config['url'],0,strlen($a->config['url'])-strlen($a->basePath)).item_url($item)) ?>"><?= icon('compass') ?><?= t('Copy link') ?></button><?php endif ?><?php if ($me && ((int)$me['id']===(int)$item['author_id'] || $a->auth->can('content'))): ?><a class="btn ghost" href="<?= e($a->auth->can('content')?au('edit_content',['id'=>$item['id']]):url('write',['id'=>$item['id']])) ?>"><?= icon('edit') ?><?= t('Edit') ?></a><?php endif ?></div>
<?php if ($me && $s->enabled('reports')): ?><details class="report-details"><summary><?= t('Report a concern') ?></summary><?= form_start('report') . hidden('content_id',$item['id']) ?><?php field('reason','Reason','','textarea',['required'=>'required','maxlength'=>'1000']); button('Send report','secondary','shield'); ?></form></details><?php endif ?></article>
<?php if($item['kind']==='product' && $s->enabled('reviews')){partial('reviews',['item'=>$item]);} ?>
<?php partial('comments',['item'=>$item,'access'=>$access,'thread'=>$thread,'comments'=>$comments,'commentFeed'=>$commentFeed,'route'=>$route]); ?></div><?php if ($s->get('show_sidebar')) {partial('sidebar');} ?></div>

<?php partial('composed',['slot'=>($item['kind']==='page'?'page_after':'article_after')]); ?>
