<?php use Chengyu\Core\Security; ?>
<section class="page-hero commerce-hero"><div><span class="eyebrow">CHENGYU / CHECKOUT</span><h1><?= e($title) ?></h1><p><?= t('One clear total. Your payment, delivery and access stay together.') ?></p></div><span class="page-hero-art"><?= icon('shield') ?></span></section>
<div class="commerce-grid"><section class="panel glass commerce-panel">
<?= form_start('checkout_review','','commerce-form',false).hidden('lines',json_encode($lines,JSON_THROW_ON_ERROR)) ?>
<h2><?= t('Your selection') ?></h2><?php foreach($items as $i=>$item): ?><div class="commerce-line"><span class="commerce-line-icon"><?= icon($lines[$i]['kind']==='membership'?'crown':'box') ?></span><div class="grow"><strong><?= e($item['title']??$item['name']) ?></strong><p class="muted"><?= e(price((int)$item['price_amount'],$item['price_currency'])) ?> <span>&times; <?= (int)$lines[$i]['quantity'] ?></span></p></div></div><?php endforeach ?>
<?php if(count($lines)===1 && $lines[0]['kind']==='content' && $items[0]['kind']==='product'): ?><?php variant_select($items[0]);if(in_array($items[0]['product_type'],['physical','code'],true)){field('quantity','Quantity',$lines[0]['quantity'],'number',['min'=>'1','max'=>'10','required'=>'required']);} ?><?php endif ?>
<?php if(!$owner): ?><div class="commerce-note"><strong><?= t('No account needed') ?></strong><p><?= t('Save the private guest pass shown after ordering. Email alone cannot recover an order; the pass grants access to its purchases.') ?></p></div><?php field('email','Contact email','','email',['required'=>'required','autocomplete'=>'email','maxlength'=>'191']); ?><?php endif ?>
<?php if($physical): ?><h2><?= t('Delivery address') ?></h2><div class="form-grid"><?php field('recipient','Recipient','','text',['required'=>'required','autocomplete'=>'shipping name','maxlength'=>'100']);field('phone','Phone','','tel',['required'=>'required','autocomplete'=>'shipping tel','maxlength'=>'40']); ?></div><?php field('address','Full delivery address','','textarea',['required'=>'required','autocomplete'=>'shipping street-address','maxlength'=>'1000']);field('region','Shipping region code','','text',['required'=>'required','maxlength'=>'40','placeholder'=>'CN-GD']); ?><p class="hint"><?= t('Use the region code supplied by the merchant, such as CN-GD. Shipping eligibility is checked on the server.') ?></p><?php endif ?>
<?php if($owner && empty($owner['is_guest'])){field('coupon','Coupon code (optional)','','text',['maxlength'=>'64']);} ?>
<?php $channels=$a->directPayments->available();if($owner && empty($owner['is_guest'])){$channels=['wallet'=>tr('Site wallet')]+$channels;}if(!$channels){$channels=['wallet'=>tr('Free orders only')];}select_field('gateway','Payment method',$channels,array_key_first($channels)); ?>
<div class="commerce-note"><p><?= t('A review screen shows current promotions and shipping before any order or charge is created.') ?></p></div><?php button('Review total','','arrow'); ?></form></section>
<aside class="commerce-aside"><div class="panel glass commerce-panel"><span class="commerce-seal"><?= icon('lock') ?></span><h2><?= t('A deliberate checkout') ?></h2><ol class="commerce-steps"><li class="active"><?= t('Choose delivery and payment') ?></li><li><?= t('Review the exact amount') ?></li><li><?= t('Confirm and verify payment') ?></li></ol><p class="hint"><?= t('Returning from a payment page does not prove payment. Access is released only after verified confirmation.') ?></p></div><a class="text-link" href="<?= e(url('guest_orders')) ?>"><?= t('Already ordered as a guest?') ?> <?= icon('arrow') ?></a></aside></div>
