<?php
// Public block data reuses the content visibility service; no draft/private SQL shortcuts.
$blockColumns=(int)($block['columns']??3);$blockItems=$block['items']??[];$blockId='cy-'.$slot.'-'.$block['id'];
?>
<?php if(in_array($block['type'],['slider','buttons'],true)){partial('composed_slider',['block'=>$block,'blockId'=>$blockId]);} ?>
<?php if($block['type']==='features'): ?><div class="block-features-grid" style="--block-columns:<?= $blockColumns ?>"><?php foreach($blockItems as $entry): ?><article class="block-feature-card"><span class="quick-icon"><?= icon($entry['icon']) ?></span><h3><?= e($entry['title']) ?></h3><p><?= e($entry['text']) ?></p><?php if($entry['url']!==''): ?><a class="text-link mt" href="<?= e($entry['url']) ?>" rel="noopener noreferrer" target="_blank"><?= t('Explore') ?><?= icon('arrow') ?></a><?php endif ?></article><?php endforeach ?></div>
<?php elseif($block['type']==='tabs'): ?><div data-content-tabs="<?= e($block['title']?:tr('Explore sections')) ?>"><?php foreach($blockItems as $index=>$entry): ?><section class="block-tab-panel" id="<?= e($blockId.'-'.($index+1)) ?>" data-tab-panel="<?= e($entry['title']) ?>"><h3><?= e($entry['title']) ?></h3><div class="prose"><?= \Chengyu\Core\Markdown::render($entry['text']) ?></div><?php if($entry['url']!==''): ?><a class="text-link" href="<?= e($entry['url']) ?>" rel="noopener noreferrer" target="_blank"><?= t('Explore') ?><?= icon('arrow') ?></a><?php endif ?></section><?php endforeach ?></div>
<?php elseif($block['type']==='gallery'): ?><div class="block-gallery-grid" style="--block-columns:<?= $blockColumns ?>"><?php foreach($blockItems as $entry):$publicImage=public_image_url((int)$entry['media_id']);if(!$publicImage){continue;} ?><figure><img src="<?= e($publicImage) ?>" alt="<?= e($entry['title']) ?>" loading="lazy" width="800" height="600"><figcaption><strong><?= e($entry['title']) ?></strong><?php if($entry['text']!==''): ?><p><?= e($entry['text']) ?></p><?php endif ?></figcaption></figure><?php endforeach ?></div>
<?php elseif($block['type']==='timeline'): ?><div class="block-timeline"><?php foreach($blockItems as $entry): ?><article class="block-timeline-item"><h3><?= e($entry['title']) ?></h3><p><?= nl2br(e($entry['text'])) ?></p></article><?php endforeach ?></div>
<?php elseif($block['type']==='categories'): $categoryKind=$block['kind']==='all'?'article':$block['kind']; ?><div class="block-category-grid" style="--block-columns:<?= $blockColumns ?>"><?php foreach($a->categories->visible($categoryKind,$me,(int)$block['size']) as $category): $categoryRoute=['article'=>'articles','thread'=>'forum','product'=>'shop'][$categoryKind];if(!$s->enabled($categoryRoute)){continue;} ?><a class="block-category-tile" href="<?= e(url($categoryRoute,['category'=>(int)$category['id']])) ?>"><span class="quick-icon"><?= icon($category['icon']) ?></span><span><strong><?= e($category['name']) ?></strong><small><?= e(\Chengyu\Core\Input::clip($category['description'],60)) ?></small></span></a><?php endforeach ?></div>
<?php elseif($block['type']==='plans' && $s->enabled('membership')): ?><div class="block-plan-grid" style="--block-columns:<?= $blockColumns ?>"><?php foreach($a->db->all('SELECT * FROM cy_plans WHERE active=1 ORDER BY sort_order,id LIMIT ?',[(int)$block['size']]) as $plan): ?><article class="block-plan-card"><span class="pill soft">VIP <?= (int)$plan['tier'] ?></span><h3><?= e($plan['name']) ?></h3><p class="muted"><?= (int)$plan['days']===0?t('Lifetime'):(int)$plan['days'].' '.tr('days') ?></p><p class="plan-amount"><?= e(price((int)$plan['price_amount'],$plan['price_currency'])) ?></p><a class="btn secondary full" href="<?= e(url('membership')) ?>"><?= t('Explore membership') ?><?= icon('arrow') ?></a></article><?php endforeach ?></div>
<?php elseif($block['type']==='titles'): $titleItems=$a->content->feed($block['kind'],$me,['category'=>$block['category'],'size'=>$block['size']])['items']; ?><div class="block-title-links"><?php foreach($titleItems as $entry): ?><a href="<?= e(item_url($entry)) ?>"><span><?= e($entry['title']) ?></span><time datetime="<?= e(date('c',(int)$entry['created_at'])) ?>"><?= dt((int)$entry['created_at'],'m.d') ?></time></a><?php endforeach ?></div>
<?php elseif($block['type']==='noticeboard' && $s->enabled('announcements')): ?><div class="block-timeline"><?php foreach($a->catalog->visibleAnnouncements($me,(int)$block['size']) as $announcement): ?><article class="block-timeline-item"><h3><?= e($announcement['name']) ?></h3><p><?= e($announcement['description']) ?></p><a class="text-link" href="<?= e(url($announcement['route'])) ?>"><?= t('Read more') ?><?= icon('arrow') ?></a></article><?php endforeach ?></div>
<?php elseif($block['type']==='creators'): $creators=[];foreach($a->content->feed('all',$me,['size'=>30])['items'] as $entry){$creators[(int)$entry['author_id']]=$entry;if(count($creators)>=(int)$block['size']){break;}} ?><div class="block-category-grid" style="--block-columns:<?= $blockColumns ?>"><?php foreach($creators as $creator): ?><a class="block-category-tile" href="<?= e(url('user',['id'=>(int)$creator['author_id']])) ?>"><?= avatar($creator,'small') ?><span><strong><?= e($creator['display_name']) ?></strong><small><?= t('Meet the creator') ?><?= icon('arrow') ?></small></span></a><?php endforeach ?></div><?php endif ?>
