<?php $composition=$a->layout->get($slot)['document'];foreach($composition['blocks'] as $block):if(!$block['enabled']){continue;}$audience=$block['audience']??'all';if(($audience==='guest'&&$me)||($audience==='member'&&!$me)||($audience==='vip'&&$a->membership->tier($me)<(int)($block['min_vip_tier']??1))){continue;} ?>
<section id="block-<?= e($slot.'-'.$block['id']) ?>" class="composed-block block-<?= e($block['type']) ?> tone-<?= e($block['tone']) ?> align-<?= e($block['align']) ?> device-<?= e($block['device']) ?> <?= $block['animation']!=='none'?'reveal':'' ?>" data-block-animation="<?= e($block['animation']) ?>">
<?php $background=public_image_url((int)($block['background_id']??0));if($background): ?><img class="block-backdrop" src="<?= e($background) ?>" alt="" loading="lazy" aria-hidden="true"><?php endif ?>
<?php if($block['type']==='spacer'): ?><div class="layout-spacer" style="height:<?= (int)$block['size']*8 ?>px" aria-hidden="true"></div><?php else: ?>
<?php if($block['title']!==''): ?><h2 class="composed-title"><?= e($block['title']) ?></h2><?php endif ?><?php if($block['text']!==''&&$block['type']!=='faq'): ?><div class="prose composed-copy"><?= \Chengyu\Core\Markdown::render($block['text']) ?></div><?php endif ?>
<?php if($block['type']==='faq'): ?><div class="composed-faq"><?php foreach(array_slice(preg_split('/\r?\n/',$block['text'])?:[],0,20) as $line):$qa=explode('|',$line,2);if(count($qa)!==2){continue;} ?><details><summary><?= e(trim($qa[0])) ?></summary><div class="prose"><?= \Chengyu\Core\Markdown::render(trim($qa[1])) ?></div></details><?php endforeach ?></div>
<?php elseif($block['type']==='media'):try{$resource=$a->media->readable((int)($block['media_id']??0),$me);}catch(\Chengyu\Core\Problem $ex){$resource=null;}if($resource): ?><?php if(strpos($resource['mime'],'image/')===0): ?><img class="composed-media" loading="lazy" src="<?= e(media_url((int)$resource['id'])) ?>" alt="<?= e($block['title']) ?>"><?php elseif($resource['mime']==='video/mp4'): ?><video class="composed-media" controls playsinline preload="metadata" src="<?= e(media_url((int)$resource['id'])) ?>"></video><?php elseif($resource['mime']==='audio/mpeg'): ?><audio controls preload="none" src="<?= e(media_url((int)$resource['id'])) ?>"></audio><?php else: ?><a class="btn secondary" href="<?= e(media_url((int)$resource['id'])) ?>"><?= t('Download resource') ?></a><?php endif ?><?php endif ?>
<?php elseif(in_array($block['type'],['content','collection'],true)): $filters=['size'=>$block['size'],'category'=>$block['category']];$show=true;
if($block['type']==='collection'){$show=$s->enabled('collections') && (bool)$a->db->one('SELECT id FROM cy_collections WHERE id=? AND active=1',[$block['collection']]);$filters['collection']=$block['collection'];}
$entries=$show?$a->content->feed($block['kind'],$me,$filters)['items']:[]; ?><div class="card-grid"><?php foreach($entries as $entry){partial('card',['entry'=>$entry]);} ?></div><?php if(!$entries){empty_state();} ?>
<?php elseif($block['type']==='stats'): $feedCount=$a->content->feed('all',$me,['size'=>1])['total']; ?><div class="composed-stats"><div><strong><?= (int)$feedCount ?></strong><span><?= t('Shared discoveries') ?></span></div><div><strong><?= $a->memberCount() ?></strong><span><?= t('Curious minds') ?></span></div></div>
<?php elseif($block['type']==='links' && $s->enabled('links')): ?><div class="composed-links"><?php foreach($a->db->all('SELECT name,url FROM cy_links WHERE active=1 ORDER BY sort_order,id LIMIT ?',[$block['size']]) as $link): ?><a class="btn secondary" href="<?= e($link['url']) ?>" rel="noopener noreferrer" target="_blank"><?= e($link['name']) ?><?= icon('arrow') ?></a><?php endforeach ?></div><?php endif ?>
<?php partial('composed_catalog',['block'=>$block,'slot'=>$slot]); ?>
<?php if($block['button']!==''): ?><a class="btn" href="<?= e(url($block['route'],$block['route']==='landing'?['slot'=>$block['page_slot']??'page1']:[])) ?>"><?= e($block['button']) ?><?= icon('arrow') ?></a><?php endif ?><?php endif ?></section><?php endforeach ?>
