<?php partial('account_nav',['route'=>$route]); ?>
<section class="creator-hero panel glass"><div><span class="eyebrow">CREATOR / YOUR INDEPENDENT WORK</span><h1><?= t('Make something worth supporting.') ?></h1><p><?= t('Original work, clear revenue, a place to keep growing.') ?></p><div class="row wrap"><a class="btn" href="<?= e(url('write')) ?>"><?= icon('plus') ?><?= t('Create a story') ?></a><a class="btn secondary" href="<?= e(url('user',['id'=>$me['id']])) ?>"><?= t('View your work') ?><?= icon('arrow') ?></a></div></div><div class="creator-orbit" aria-hidden="true"><i></i><i></i><i></i><span><?= icon('leaf') ?></span></div></section>
<?php if(!(int)$me['creator_enabled']): ?><p class="alert info"><?= t('Revenue sharing requires administrator approval. Existing income records remain visible.') ?></p><?php endif ?>
<div class="metric-grid section creator-metrics">
<?php foreach(['available'=>['Available earnings',(int)$me['earnings'],'wallet'],'pending'=>['Awaiting settlement',$summary['pending'],'clock'],'settled'=>['Settled revenue',$summary['settled'],'chart'],'reversed'=>['Reversed after refund',$summary['reversed'],'refresh']] as $key=>$metric): ?><article class="metric-card panel glass"><span class="metric-label"><?= icon($metric[2]) ?><?= t($metric[0]) ?></span><strong><?= e(money($metric[1])) ?></strong><small><?= t('CNY / site ledger') ?></small></article><?php endforeach ?></div>
<div class="two-column section"><section class="panel glass"><span class="eyebrow">01 / SETTLEMENT</span><h2><?= t('Income with a clear path.') ?></h2><ol class="revenue-steps"><li><?= t('A real order is paid') ?></li><li><?= t('Referral costs are deducted first') ?></li><li><?= t('Your agreed share enters the hold period') ?></li><li><?= t('Eligible earnings become available') ?></li></ol><p class="hint"><?= t('New orders use the current rate and hold period. Existing orders keep their original terms.') ?> <?= t('Default share') ?>: <?= number_format((int)$s->get('creator_share_bps')/100,2) ?>% / <?= (int)$s->get('creator_hold_days') ?> <?= t('days') ?></p><?= form_start('creator_settle') ?><?php button('Settle eligible earnings','','check'); ?><p class="hint"><?= t('Up to 50 eligible records per click. Refund disputes pause settlement; physical deliveries must be received.') ?></p></form></section>
<section class="panel glass"><span class="eyebrow">02 / USE YOUR EARNINGS</span><h2><?= t('Choose the next step.') ?></h2><?php if((int)$me['earnings']<0): ?><p class="alert warning"><?= t('A refund created an earnings debt. Future revenue repays it before further spending or withdrawal.') ?></p><?php endif ?>
<?php if($s->get('creator_balance_conversion') && $s->enabled('wallet')): ?><?= form_start('creator_convert').intent() ?><?php field('amount','Convert earnings to balance (CNY)','','number',['min'=>'0.01','step'=>'0.01','required'=>'required']);field('current_password','Current password','','password',['required'=>'required','autocomplete'=>'current-password']);button('Convert to balance','secondary','refresh'); ?><p class="hint"><?= t('Conversion is one-way and recorded as two matching ledger entries. Site balance is not withdrawable.') ?></p></form><?php else: ?><p><?= t('Earnings conversion is not enabled by this site.') ?></p><?php endif ?>
<?php if($s->enabled('wallet') && $s->enabled('withdrawals')): ?><a class="text-link" href="<?= e(url('wallet')) ?>"><?= t('Request a manual payout') ?> <?= icon('arrow') ?></a><?php endif ?></section></div>
<section class="panel section"><div class="section-heading"><div><span class="eyebrow">LEDGER / EVERY ORDER COUNTS</span><h2><?= t('Your revenue records') ?></h2></div><span class="pill"><?= (int)$income['total'] ?> <?= t('records') ?></span></div><?php partial('income_rows',['income'=>$income,'adminIncome'=>false]); partial('pagination',['feed'=>$income,'route'=>'creator']); ?></section>
