<?php
$editing=$item ?? [];if(empty($editing['category_id']) && !empty($_GET['category'])){$editing['category_id']=(int)$_GET['category'];} $kind=$editing['kind'] ?? (in_array($_GET['kind']??'', $staff?['article','thread','product','page']:['article','thread'],true)?$_GET['kind']:'article');
$creatorEditor=!$staff && !empty($me['creator_enabled']) && $s->enabled('creator_income') && (empty($editing['id']) || !empty($editing['creator_pricing']));
$categories=[0=>tr('Uncategorized')];foreach ($a->categories->visible($kind,$me,0,$staff?'read':'post') as $cat) {$categories[$cat['id']]=$cat['name'];}
?>
<div class="section-heading"><div><span class="eyebrow"><?= t($kind) ?> / <?= t('Editor') ?></span><h1><?= e($title) ?></h1></div><a class="btn secondary small" href="<?= e($isAdmin?au('contents'):url('profile')) ?>"><?= t('Back') ?></a></div>
<?= form_start($isAdmin?'admin_content':'content_save','','editor-grid',false) . hidden('id',$editing['id']??0) . hidden('kind',$kind) . hidden('edit_version',$editing['edit_version']??1) ?>
<section class="panel glass"><?php field('title','Title',$editing['title']??'','text',['required'=>'required','maxlength'=>'255']);field('excerpt','Public summary',$editing['excerpt']??'','textarea',['maxlength'=>'1000']);field('body','Public body (Markdown)',$editing['body']??'','textarea',['required'=>'required','class'=>'editor-body','maxlength'=>'50000']); ?><p class="hint"><?= t('The public body is always visible. Put paid, member-only or login-only material in the protected body below. Raw HTML is escaped.') ?></p><?php field('protected_body','Protected body (Markdown)',$editing['protected_body']??'','textarea',['class'=>'editor-body','maxlength'=>'50000']);field('tags','Tags (comma separated)',$editing['tags']??''); ?></section>
<aside class="editor-settings panel glass"><?php if($kind==='thread') { partial('thread_editor',['editing'=>$editing]); } ?><?php select_field('status','Publication status',options($staff?['draft','pending','published','archived']:['pending','draft']),$editing['status']??($staff?'draft':'pending')); select_field('category_id','Category',$categories,$editing['category_id']??0);if (!$staff && !$creatorEditor && isset($editing['access_level']) && !in_array($editing['access_level'],['public','login','reply'],true)) {echo '<p class="hint">'.t('Access and prices are managed by the site administrator.').'</p>';} else {select_field('access_level','Protected content access',options($staff?['public','login','vip','paid','reply','password']:($creatorEditor?['public','login','reply','paid']:['public','login','reply'])),$editing['access_level']??'public');}field('slug','URL identifier (optional)',$editing['slug']??'');upload_field('cover_id','Cover image ID',(int)($editing['cover_id']??0));partial('cover_picker',['editing'=>$editing]); if ($staff) {field('content_password','Content password (leave blank to retain)','','password',['autocomplete'=>'new-password']);select_field('min_vip_tier','Required membership tier',[1=>'VIP 1',2=>'VIP 2',3=>'VIP 3'],$editing['min_vip_tier']??1);field('access_days','Purchased access days (0 permanent)',$editing['access_days']??0,'number',['min'=>'0','max'=>'3650']);upload_field('resource_id','Private resource ID',(int)($editing['resource_id']??0),true);} else {echo hidden('resource_id',0);} ?>
<?php if($creatorEditor): echo hidden('price_currency','balance');field('price','Paid content price (CNY)',money((int)($editing['price_amount']??0)),'number',['step'=>'0.01','min'=>'0']);echo '<p class="hint">'.t('Paid submissions remain subject to review. Put the paid material in the protected body.').'</p>';endif ?>
<?php partial('editor_images',['editing'=>$editing,'kind'=>$kind]); ?>
<?php partial('editor_attribution',['editing'=>$editing,'kind'=>$kind]); ?>
<?php if ($staff): ?><div class="field-divider"></div><?php select_field('price_currency','Price asset',options(['balance','points','tokens']),$editing['price_currency']??'balance');field('price','Price (CNY for balance; integer for points or tokens)',($editing['price_currency']??'balance')==='balance'?money((int)($editing['price_amount']??0)):($editing['price_amount']??0),'number',['step'=>'0.01','min'=>'0']);if ($kind==='product') {select_field('product_type','Delivery type',options(['digital','code','physical','invitation']),$editing['product_type']??'digital');field('invite_uses','Uses per generated invitation',$editing['invite_uses']??1,'number',['min'=>'1','max'=>'1000']);field('invite_days','Generated invitation validity (days)',$editing['invite_days']??30,'number',['min'=>'1','max'=>'3650']);echo '<p class="form-help">'.e(t('Generated invitation codes are consumed only when registration mode is invite.')).'</p>';field('inventory','Stock (-1 means unlimited)',$editing['inventory']??-1,'number',['min'=>'-1']);field('delivery_text','Delivery instructions (visible after purchase)',$editing['delivery_text']??'','textarea');}field('publish_at','Scheduled publication (site timezone)',!empty($editing['publish_at'])?date('Y-m-d\TH:i',(int)$editing['publish_at']):'','datetime-local');check_field('creator_pricing','Allow an approved author to manage this price',!empty($editing['creator_pricing']));check_field('featured','Featured selection',!empty($editing['featured']));check_field('pinned','Pin to top',!empty($editing['pinned']));check_field('vip_free','VIP members can read protected content for free',!empty($editing['vip_free']));endif ?>
<?php check_field('comment_enabled','Allow comments',!isset($editing['comment_enabled']) || (bool)$editing['comment_enabled']); ?><div class="form-actions"><?php button($staff?'Save content':'Submit for review','full','check'); ?></div><p class="hint"><?= t('Content dates use Asia/Shanghai. Scheduled items become visible on reads; no background worker is needed.') ?></p></aside></form>

<?php if($staff && !empty($editing['id'])): ?>
<a class="btn secondary" href="<?= e(au('translations',['content_id'=>$editing['id']])) ?>"><?= t('Content translations') ?></a><section class="panel revision-panel"><div class="section-heading"><h2><?= t('Revision history') ?></h2><span class="pill">v<?= (int)$editing['edit_version'] ?></span></div><p class="hint"><?= t('Restore text only. Prices, stock, assets and access rules are not rolled back. The latest 20 versions are retained.') ?></p>
<?php foreach($a->db->all('SELECT id,actor_id,created_at FROM cy_revisions WHERE content_id=? ORDER BY id DESC LIMIT 20',[(int)$editing['id']]) as $revision): ?>
<div class="row revision-row"><span class="grow">#<?= (int)$revision['id'] ?> / <?= dt((int)$revision['created_at']) ?> / UID <?= (int)$revision['actor_id'] ?></span><?= form_start('admin_revision') . hidden('content_id',$editing['id']) . hidden('revision_id',$revision['id']) ?><?php button('Restore text','secondary small','refresh'); ?></form></div>
<?php endforeach ?><a class="btn secondary" href="<?= e(au('resources',['content_id'=>$editing['id']])) ?>"><?= t('Resource releases') ?></a><?php if($kind==='product'): ?><a class="btn secondary" href="<?= e(au('variants',['content_id'=>$editing['id']])) ?>"><?= t('Manage product variants') ?></a><?php endif ?></section><?php endif ?>
