<?php
$curve = implode(',', \Chengyu\Core\Motion::curve($s));
$style = '--radius:' . (int)$s->get('radius') . 'px;--blur:' . (int)$s->get('blur') . 'px;--duration:' . (int)$s->get('motion_duration') . 'ms;--lift:' . (int)$s->get('hover_lift') . 'px;--curve:cubic-bezier(' . $curve . ');';
$style .= '--reveal-distance:'.(int)$s->get('motion_distance').'px;--stagger-step:'.(int)$s->get('motion_stagger').'ms;';
$accent = $s->get('accent');
if (is_string($accent) && preg_match('/^#[a-fA-F0-9]{6}$/D', $accent)) { $rgb = [hexdec(substr($accent,1,2)),hexdec(substr($accent,3,2)),hexdec(substr($accent,5,2))]; $style .= '--accent:' . $accent . ';--accent-rgb:' . implode(',', $rgb) . ';--accent-soft:rgba(' . implode(',', $rgb) . ',.10);'; }
?>
<!doctype html><html lang="<?= e(\Chengyu\Core\Locale::current()) ?>" data-reveal-style="<?= e($s->get('motion_reveal_style')) ?>" data-curve-name="<?= e($s->get('motion_curve')) ?>" data-image-lightbox="<?= $s->get('image_lightbox')?'1':'0' ?>" data-reading-focus="<?= $s->get('reading_focus')?'1':'0' ?>" data-reading-tools="<?= $s->get('reading_tools')?'1':'0' ?>" data-motion-curves="<?= e(json_encode(\Chengyu\Core\Motion::CURVES,JSON_THROW_ON_ERROR)) ?>" data-motion-settings="<?= e(json_encode(array_combine(\Chengyu\Core\Motion::KEYS,array_map(static function($key)use($s){return $s->get($key);},\Chengyu\Core\Motion::KEYS)),JSON_THROW_ON_ERROR)) ?>" data-adaptive="<?= $s->get('motion_adaptive')?'1':'0' ?>" data-hero-art="<?= e($s->get('hero_art')) ?>" data-layout-width="<?= e($s->get('layout_width','balanced')) ?>" data-layout-style="<?= e($s->get('layout_style','island')) ?>" data-density="<?= e($s->get('content_density')) ?>" data-theme="<?= e($s->get('theme')) ?>" data-mode="<?= e($s->get('color_mode')) ?>" data-glass="<?= e($s->get('glass')) ?>" data-base="<?= e($a->basePath) ?>" data-visitor-theme="<?= $s->get('theme_switcher') && empty($isAdminLayout) ? '1' : '0' ?>" style="<?= e($style) ?>"<?php foreach (['motion','ambient','grain','particles','reveal','ripple'] as $flag): ?> data-<?= e($flag) ?>="<?= $s->get($flag) ? '1' : '0' ?>"<?php endforeach ?> data-transition="<?= $s->get('page_transition') ? '1' : '0' ?>">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="csrf-token" content="<?= e(\Chengyu\Core\Security::csrf()) ?>"><meta name="color-scheme" content="light dark"><title><?= e((($title ?? '') === $s->get('site_name') ? $s->get('site_name') : ($title ?? $s->get('site_name')) . ' - ' . $s->get('site_name'))) ?></title><?php if ($s->get('seo_enabled')): ?><meta name="description" content="<?= e(isset($item) ? $item['excerpt'] : $s->get('site_description')) ?>"><meta name="keywords" content="<?= e($s->get('seo_keywords')) ?>">
<?php $seoRoute=$route??'home';$canonical=$a->canonical($seoRoute,array_merge($_GET,isset($item)?['id'=>(int)$item['id']]:[])); ?>
<link rel="canonical" href="<?= e($canonical) ?>"><meta property="og:title" content="<?= e($title??$s->get('site_name')) ?>"><meta property="og:description" content="<?= e(isset($item)?$item['excerpt']:$s->get('site_description')) ?>"><meta property="og:type" content="<?= isset($item)?'article':'website' ?>"><meta property="og:url" content="<?= e($canonical) ?>"><?php endif ?>
<?php if (!empty($isAdminLayout) || $s->get('noindex') || in_array($route ?? '', ['search','support','tracking','learning','learn','checkout','checkout_review','receipt','guest_orders','guest_content','upgrade','connect','security','login','register','profile','wallet','orders','write','messages','notifications','pay','reset','forgot','verify','creator','history','following'], true)): ?><meta name="robots" content="noindex,nofollow"><?php endif ?>
<link rel="icon" type="image/svg+xml" href="<?= e(asset('art/favicon.png')) ?>"><script src="<?= e(asset('boot.js')) ?>"></script><script src="<?= e(asset('media-workbench.js')) ?>" defer></script><link rel="stylesheet" href="<?= e(asset('app.css')) ?>"><script src="<?= e(asset('spring.js')) ?>" defer></script><script src="<?= e(asset('motion.js')) ?>" defer></script><script src="<?= e(asset('app.js')) ?>" defer></script><script src="<?= e(asset('features.js')) ?>" defer></script><link rel="stylesheet" href="<?= e(asset('studio.css')) ?>">
<link rel="stylesheet" href="<?= e(asset('refinement.css')) ?>"><script src="<?= e(asset('refinement.js')) ?>" defer></script><script src="<?= e(asset('studio.js')) ?>" defer></script><link rel="stylesheet" href="<?= e(asset('community.css')) ?>"><link rel="stylesheet" href="<?= e(asset('interactions.css')) ?>"><script src="<?= e(asset('interactions.js')) ?>" defer></script><link rel="stylesheet" href="<?= e(asset('motion.css')) ?>"><link rel="stylesheet" href="<?= e(asset('discovery.css')) ?>"><link rel="stylesheet" href="<?= e(asset('connections.css')) ?>"><link rel="stylesheet" href="<?= e(asset('commerce.css')) ?>"><script src="<?= e(asset('connections.js')) ?>" defer></script><script src="<?= e(asset('discovery.js')) ?>" defer></script><script src="<?= e(asset('feedback.js')) ?>" defer></script><script src="<?= e(asset('motion-studio.js')) ?>" defer></script>
<link rel="stylesheet" href="<?= e(asset('platform.css')) ?>"><script src="<?= e(asset('platform.js')) ?>" defer></script>
<link rel="stylesheet" href="<?= e(asset('workbench.css')) ?>"><script src="<?= e(asset('workbench.js')) ?>" defer></script>
<?php if ($s->get('motion') && $s->get('page_transition')): ?><style>@view-transition{navigation:auto;}@media(prefers-reduced-motion:reduce){@view-transition{navigation:none;}}</style><?php endif ?>
<link rel="stylesheet" href="<?= e(asset('island.css')) ?>"><script src="<?= e(asset('island.js')) ?>" defer></script>
<?php if ($s->get('rss_enabled')): ?><link rel="alternate" type="application/rss+xml" title="RSS" href="<?= e($a->basePath . '/feed.php') ?>"><?php endif ?></head>
