<?php if($s->get('studio_enabled')){partial('composed',['slot'=>'home']);} ?>
<?php if ($s->get('hero_enabled')): ?><section class="hero glass"><div class="hero-copy"><p class="eyebrow"><?= e($s->get('hero_eyebrow')) ?></p><h1><?= nl2br(e(str_replace('\\n',"\n",$s->get('hero_title')))) ?></h1><p class="hero-description"><?= e($s->get('hero_description')) ?></p><?php if ($s->enabled($s->get('hero_route'))): ?><a class="btn" href="<?= e(url($s->get('hero_route'))) ?>"><?= e($s->get('hero_button')) ?><?= icon('arrow') ?></a><?php endif ?><?php if ($s->get('show_stats')): $counts=$a->content->feed('all',$me,['size'=>1]); ?><div class="hero-meta"><span><strong><?= $counts['total'] ?></strong><?= t('Shared discoveries') ?></span><span><strong><?= $a->memberCount() ?></strong><?= t('Curious minds') ?></span></div><?php endif ?></div><div class="hero-art" aria-hidden="true"><?php if($s->get('hero_art')==='anime'): ?><img class="hero-anime" src="<?= e(asset('art/island-anime.webp')) ?>" alt="" width="1536" height="1024" fetchpriority="high"><?php endif ?><div class="art-grid"></div><div class="orbit-ring second"></div><div class="orb"></div><div class="orbit-ring"></div><div class="floating-card one"><div class="row"><?= icon('leaf') ?><div><strong><?= t('A place to grow') ?></strong><small>GOOD IDEAS LIVE HERE</small></div></div></div><div class="floating-card two"><div class="row"><div class="mini-lines"></div><div><strong><?= t('Made of possibilities') ?></strong><small>EXPLORE. CREATE. SHARE.</small></div></div></div><div class="floating-card three"><?= icon('sparkles') ?></div><div class="floating-glyph">&#10033;</div></div><div class="particles" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></div></section><?php endif ?>
<div class="quick-links"><?php foreach (['articles'=>['Stories & ideas','A fresh perspective','book'],'forum'=>['Community','One conversation away','message'],'shop'=>['Resource collection','Make something meaningful','box'],'membership'=>['Membership','A little more to explore','crown']] as $r=>$v): if (!$s->enabled($r)) {continue;} ?><a class="quick-link glass" href="<?= e(url($r)) ?>"><span class="quick-icon"><?= icon($v[2]) ?></span><span><strong><?= t($v[0]) ?></strong><small><?= t($v[1]) ?></small></span><?= icon('chevron') ?></a><?php endforeach ?></div>
<div class="main-grid <?= !$s->get('show_sidebar') ? 'no-sidebar':'' ?>"><div class="main-column"><?php foreach (explode(',',$s->get('home_sections')) as $section):
if ($section === 'featured' && $s->enabled('articles')): $entries=$a->content->feed('article',$me,['featured'=>true,'size'=>2])['items']; if (!$entries) {continue;} ?>
<section class="section"><div class="section-heading"><h2><?= t('The editor\'s shelf') ?><small>SELECTED FOR YOU</small></h2><span class="pill soft"><?= icon('sparkles') ?><?= t('Handpicked') ?></span></div><div class="featured-grid"><?php foreach ($entries as $entry): ?><a class="featured-item panel glass reveal" href="<?= e(item_url($entry)) ?>"><img src="<?= e(cover($entry)) ?>" alt="" loading="lazy"><div><span class="pill soft"><?= e($entry['category_name']) ?></span><h3><?= e($entry['title']) ?></h3><span class="text-link"><?= t('Read the story') ?><?= icon('arrow') ?></span></div></a><?php endforeach ?></div></section>
<?php elseif ($section === 'articles' && $s->enabled('articles')): $entries=$a->content->feed('article',$me,['size'=>6])['items']; ?>
<section class="section layout-<?= e($s->get('card_layout')) ?>"><div class="section-heading"><h2><?= t('A little inspiration') ?><small>LATEST STORIES</small></h2><a class="text-link" href="<?= e(url('articles')) ?>"><?= t('Explore all') ?><?= icon('arrow') ?></a></div><div class="card-grid"><?php foreach ($entries as $entry) {partial('card',['entry'=>$entry]);} ?></div><?php if (!$entries) {empty_state();} ?></section>
<?php elseif ($section === 'community' && $s->enabled('forum')): $entries=$a->content->feed('thread',$me,['size'=>3])['items']; ?>
<section class="section"><div class="section-heading"><h2><?= t('Conversations in bloom') ?><small>FROM THE COMMUNITY</small></h2><a class="text-link" href="<?= e(url('forum')) ?>"><?= t('Join in') ?><?= icon('arrow') ?></a></div><div class="thread-list panel glass"><?php foreach ($entries as $entry) {partial('thread',['entry'=>$entry]);} if (!$entries) {empty_state();} ?></div></section>
<?php elseif ($section === 'products' && $s->enabled('shop')): $entries=$a->content->feed('product',$me,['size'=>3])['items']; ?>
<section class="section"><div class="section-heading"><h2><?= t('Tools for your next idea') ?><small>THE COLLECTION</small></h2><a class="text-link" href="<?= e(url('shop')) ?>"><?= t('Visit the shop') ?><?= icon('arrow') ?></a></div><div class="card-grid"><?php foreach ($entries as $entry) {partial('card',['entry'=>$entry]);} ?></div><?php if (!$entries) {empty_state();} ?></section>
<?php endif; endforeach ?></div><?php if ($s->get('show_sidebar')) {partial('sidebar');} ?></div>
