<?php require __DIR__ . '/head.php'; $nav = $a->navigation(); ?>
<body data-site-route="<?= e($route??'home') ?>"><a class="skip-link" href="#main"><?= t('Skip to content') ?></a><div class="ambient" aria-hidden="true"></div><header class="site-header glass"><div class="container header-inner"><a class="brand" href="<?= e(url()) ?>"><?= brand_mark() ?><span><span class="brand-name"><?= e($s->get('site_name')) ?></span><small class="brand-caption">IDEAS, TOGETHER.</small></span></a><nav class="desktop-nav" aria-label="<?= t('Main navigation') ?>"><?php foreach (array_slice($nav,0,5) as $link): ?><a href="<?= e($link['href']) ?>" class="<?= ($route ?? '') === $link['route'] ? 'active' : '' ?>"<?= $link['route'] === 'external' ? ' rel="noopener" target="_blank"' : '' ?>><?= t($link['label']) ?></a><?php endforeach ?></nav><div class="header-actions"><?php partial('locale_switch'); ?>
<?php if ($s->enabled('search')): ?><button class="header-search" data-dialog="search-dialog" aria-label="<?= t('Search') ?>"><?= icon('search') ?><span><?= t('Explore something') ?></span><kbd class="keycap">K</kbd></button><?php endif ?>
<?php if ($s->get('theme_switcher')): ?><button class="icon-button" data-dialog="appearance-dialog" aria-label="<?= t('Appearance') ?>"><?= icon('palette') ?></button><?php endif ?>
<?php if ($me): ?><a class="icon-button optional" href="<?= e(url('notifications')) ?>" aria-label="<?= t('Notifications') ?>"><?= icon('bell') ?></a><a href="<?= e(url('profile')) ?>" aria-label="<?= t('Your profile') ?>"><?= avatar($me,'small') ?></a><?php else: ?><a class="btn small" href="<?= e(url('login')) ?>"><?= t('Sign in') ?><?= icon('arrow') ?></a><?php endif ?>
<button class="icon-button mobile-menu" data-dialog="menu-dialog" aria-label="<?= t('Open menu') ?>"><?= icon('menu') ?></button></div></div></header>
<?php if ($s->get('reading_progress') && isset($item)): ?><div class="reading-progress" aria-hidden="true"></div><?php endif ?>
<main class="site-main container page-content" id="main"><?php foreach (flashes() as $flash): ?><div class="alert <?= e($flash['type']) ?>" role="status"><?= e($flash['message']) ?></div><?php endforeach ?><?php if($s->enabled('announcements')){partial('announcements');} ?><?php partial('composed',['slot'=>'global_before']); ?><?= $content ?><?php partial('composed',['slot'=>'global_after']); ?></main>
<footer class="site-footer"><div class="container"><div class="footer-top"><div class="footer-brand"><a class="brand" href="<?= e(url()) ?>"><?= brand_mark() ?><strong class="brand-name"><?= e($s->get('site_name')) ?></strong></a><small><?= e($s->get('footer_text')) ?></small></div><nav class="footer-links"><a href="<?= e(url('guest_orders')) ?>"><?= t('Guest orders') ?></a><?php foreach(['collections'=>'Editorial collections','links'=>'Link directory','tasks'=>'Task center'] as $navRoute=>$label): if($s->enabled($navRoute)): ?><a href="<?= e(url($navRoute)) ?>"><?= t($label) ?></a><?php endif; endforeach ?><a href="<?= e(url('terms')) ?>"><?= t('Terms & privacy') ?></a><?php if ($s->get('contact_email') && filter_var($s->get('contact_email'), FILTER_VALIDATE_EMAIL)): ?><a href="mailto:<?= e($s->get('contact_email')) ?>"><?= t('Contact') ?></a><?php endif ?><?php if ($s->get('rss_enabled')): ?><a href="<?= e($a->basePath . '/feed.php') ?>">RSS</a><?php endif ?><?php if ($a->auth->can('admin')): ?><a href="<?= e(au()) ?>"><?= t('Dashboard') ?></a><?php endif ?></nav></div><div class="footer-bottom"><span>&copy; <?= date('Y') ?> <?= e($s->get('site_name')) ?> &middot; <?= t('An independent place for good ideas.') ?></span><span><?php if ($s->get('icp_number')): ?><a href="https://beian.miit.gov.cn/" rel="noopener" target="_blank"><?= e($s->get('icp_number')) ?></a><?php endif ?> <?php if ($s->get('police_number')): ?><a href="<?= e($s->get('police_url') ?: '#') ?>" rel="noopener" target="_blank"><?= e($s->get('police_number')) ?></a><?php endif ?> <?php if ($s->get('host_credit_label')): ?><a href="<?= e($s->get('host_credit_url') ?: '#') ?>" rel="noopener" target="_blank"><?= e($s->get('host_credit_label')) ?></a><?php endif ?></span></div></div></footer>
<nav class="mobile-bottom-nav" aria-label="<?= t('Mobile navigation') ?>"><?php foreach (['home'=>['Home','home'],'articles'=>['Discover','compass'],'forum'=>['Community','message'],'shop'=>['Shop','box'],'profile'=>['Account','user']] as $r=>$v): if (!in_array($r,['home','profile'],true) && !$s->enabled($r)) {continue;} ?><a href="<?= e(url($r)) ?>" class="<?= ($route ?? '') === $r ? 'active':'' ?>"><?= icon($v[1]) ?><span><?= t($v[0]) ?></span></a><?php endforeach ?></nav><button class="back-top icon-button" data-back-top aria-label="<?= t('Back to top') ?>"><?= icon('arrow') ?></button><?php require __DIR__ . '/dialogs.php'; ?></body></html>
