<?php if($s->get('studio_enabled') && in_array($route,['articles','forum','shop'],true)){partial('composed',['slot'=>$route]);} ?>
<section class="page-hero"><div><span class="eyebrow"><?= e(strtoupper($route)) ?> / CHENGYU</span><h1><?= e($title) ?></h1><p><?= e($s->get('site_tagline')) ?></p></div><span class="page-hero-art"><?= icon($route==='forum'?'message':($route==='shop'?'box':'compass')) ?></span></section>
<?php if ($route==='search'): ?><form class="search-form section" action="<?= e($a->basePath.'/index.php') ?>"><input type="hidden" name="r" value="search"><input class="input" name="q" value="<?= e($filters['q']) ?>" placeholder="<?= t('Search keywords') ?>" aria-label="<?= t('Search keywords') ?>" maxlength="100"><select class="input" name="kind" aria-label="<?= t('Content type') ?>"><?php foreach(['all'=>'All','article'=>'Articles','thread'=>'Discussions','product'=>'Products'] as $key=>$label): ?><option value="<?= e($key) ?>" <?= $kind===$key?'selected':'' ?>><?= t($label) ?></option><?php endforeach ?></select><?= button('Search','','search') ?></form><?php endif ?>
<?php if ($route==='forum' && $s->enabled('circles')): ?><a class="circle-discover panel glass" href="<?= e(url('circles')) ?>"><span class="quick-icon"><?= icon('users') ?></span><div class="grow"><strong><?= t('Find your circle') ?></strong><p><?= t('Shared interests. Thoughtful conversations. Your people.') ?></p></div><?= icon('arrow') ?></a><?php endif ?>
<?php if ($route==='forum'): ?><div class="forum-categories"><?php foreach ($a->categories->visible('thread',$me) as $cat):  ?><a class="forum-category panel glass" href="<?= e(url('forum',['category'=>$cat['id'],'q'=>$filters['q'],'kind'=>$kind])) ?>"><span class="quick-icon"><?= icon($cat['icon']) ?></span><div><strong><?= e($cat['name']) ?></strong><small><?= e($cat['description']) ?></small></div></a><?php endforeach ?></div><?php endif ?>
<?php partial('catalog_filters',['filters'=>$filters,'kind'=>$kind,'route'=>$route]); ?>
<div class="main-grid <?= !$s->get('show_sidebar')?'no-sidebar':'' ?>"><div><div class="section-heading"><div class="filters"><a class="filter <?= !$filters['category']?'active':'' ?>" href="<?= e(url($route,array_merge($filters,['category'=>0,'page'=>1,'kind'=>$kind]))) ?>"><?= t('All discoveries') ?></a><?php if ($kind!=='all'): foreach ($a->categories->visible($kind,$me) as $cat):  ?><a class="filter <?= (int)$filters['category']===(int)$cat['id']?'active':'' ?>" href="<?= e(url($route,array_merge($filters,['category'=>$cat['id'],'page'=>1,'kind'=>$kind]))) ?>"><?= e($cat['name']) ?></a><?php endforeach; endif ?></div><?php if ($route==='forum' && $s->enabled('submissions')): ?><a class="btn small" href="<?= e(url('write',['kind'=>'thread'])) ?>"><?= icon('plus') ?><?= t('Start a conversation') ?></a><?php endif ?></div>
<div class="catalog-toolbar"><div class="filters"><span class="muted"><?= $feed['total'] ?> <?= t('results') ?></span><span class="filter-separator"></span><?php foreach (($route==='search'?['relevance'=>'Relevance','latest'=>'Latest','popular'=>'Most viewed']:($route==='shop'?['latest'=>'Latest','sales'=>'Best selling','price'=>'Price low to high','price_desc'=>'Price high to low','updated'=>'Recently updated']:['latest'=>'Latest','popular'=>'Most viewed'])) as $sort=>$label): ?><a class="filter subtle <?= $filters['sort']===$sort?'active':'' ?>" href="<?= e(url($route,array_merge($filters,['sort'=>$sort,'page'=>1,'kind'=>$kind]))) ?>"><?= t($label) ?></a><?php endforeach ?></div><?php if($route!=='forum'): ?><div class="view-switch" role="group" aria-label="<?= t('Result layout') ?>"><button type="button" data-catalog-view="grid" aria-pressed="true" aria-label="<?= t('Grid view') ?>"><?= icon('grid') ?></button><button type="button" data-catalog-view="list" aria-pressed="false" aria-label="<?= t('List view') ?>"><?= icon('menu') ?></button></div><?php endif ?></div>
<?php if (!$feed['items']): empty_state(); elseif ($route==='forum'): ?><div class="thread-list panel glass"><?php foreach ($feed['items'] as $entry) {partial('thread',['entry'=>$entry]);} ?></div><?php else: ?><div data-catalog-results class="layout-<?= e($s->get('card_layout')) ?>"><div class="card-grid"><?php foreach ($feed['items'] as $entry) {partial('card',['entry'=>$entry]);} ?></div></div><?php endif ?><?php partial('pagination',['feed'=>$feed,'route'=>$route]); ?></div><?php if ($s->get('show_sidebar')) {partial('sidebar');} ?></div>
