<?php $meta=json_decode($sale['metadata'],true,32,JSON_THROW_ON_ERROR); ?>
<section class="page-hero commerce-hero"><div><span class="eyebrow">CHENGYU / RECEIPT</span><h1><?= e($title) ?></h1><p class="receipt-number"># <?= e($sale['sale_no']) ?></p></div><span class="commerce-status <?= e($sale['status']) ?>"><?= icon($sale['status']==='paid'?'check':'clock') ?><?= t($sale['status']) ?></span></section>
<?php if(!empty($owner['is_guest'])): ?><div class="commerce-note important"><strong><?= t('Save your guest pass before leaving') ?></strong><p><?= t('Anyone with this pass can access these purchases. Keep it private; it is not sent automatically by email.') ?></p><a class="btn secondary small" href="<?= e(url('guest_orders')) ?>"><?= t('Open guest pass and orders') ?></a></div><?php endif ?>
<div class="commerce-grid"><div><section class="panel glass commerce-panel"><?php partial('checkout_summary',['summary'=>$meta['quote']]); ?><p class="hint"><?= t('Payment method') ?>: <?= e(\Chengyu\Services\DirectPayments::NAMES[$sale['gateway']]??tr('Site wallet')) ?> &middot; <?= dt((int)$sale['created_at'],'Y-m-d H:i') ?></p>
<?php if($sale['status']==='pending'): ?><div class="row wrap"><?php if((int)$sale['expires_at']>time()): ?><?= form_start('checkout_open','','',false).hidden('sale_id',$sale['id']) ?><?php button('Continue payment','','arrow'); ?></form><?php endif ?><?= form_start('checkout_check','','',false).hidden('sale_id',$sale['id']) ?><?php button('Verify payment','secondary','refresh'); ?></form><?php if(!(int)$sale['attempted_at']): ?><?= form_start('checkout_cancel','','',false).hidden('sale_id',$sale['id']) ?><?php button('Cancel unpaid order','ghost','close'); ?></form><?php endif ?></div><p class="hint"><?= t('An expired page is not proof that payment was cancelled. Pending remote orders keep their reservation until verified closed or paid.') ?></p><?php endif ?><?php if($sale['last_error']): ?><p class="alert warning"><?= t($sale['last_error']) ?></p><?php endif ?></section>
<?php foreach($orders as $order): ?><article class="panel glass commerce-panel section"><div class="row between wrap"><h2><?= e($order['title']) ?></h2><span class="pill"><?= t($order['status']) ?></span></div><p class="hint">#<?= e($order['order_no']) ?> &middot; <?= t($order['fulfillment']) ?></p>
<?php if(in_array($order['status'],['paid','refund_requested'],true)): ?>
<?php if($order['address_snapshot']): $addr=json_decode($a->crypto->open($order['address_snapshot']),true,16,JSON_THROW_ON_ERROR); ?><details><summary><?= t('Delivery address') ?></summary><p><?= e($addr['recipient'].' / '.$addr['phone']) ?></p><p><?= nl2br(e($addr['address'])) ?></p></details><?php endif ?>
<?php if($order['delivery_cipher']): ?><div class="delivery-box"><span class="eyebrow"><?= t('Delivery details') ?></span><pre><?= e($a->crypto->open($order['delivery_cipher'])) ?></pre></div><?php endif ?>
<?php if($order['kind']==='content'): ?><a class="btn secondary small" href="<?= e(url('guest_content',['id'=>$order['id']])) ?>"><?= t('Open your content') ?> <?= icon('arrow') ?></a><?php endif ?>
<?php if($order['status']==='paid'&&$order['fulfillment']==='shipped'): ?><?= form_start('checkout_receive','','',false).hidden('order_id',$order['id']) ?><?php button('Confirm receipt','secondary small','check'); ?></form><?php endif ?>
<?php endif ?>
<?php partial('shipment_link',['order'=>$order]); ?><?php if($order['kind']==='content'): partial('service_customer',['order'=>$order]);endif ?></article><?php endforeach ?></div>
<aside class="commerce-aside"><div class="panel glass commerce-panel"><span class="commerce-seal"><?= icon('shield') ?></span><h2><?= t('Your order stays traceable') ?></h2><p><?= t('Stock, access, delivery and refunds use the same order record. Payment retries do not create a second purchase.') ?></p><a class="text-link" href="<?= e(url(!empty($owner['is_guest'])?'guest_orders':'orders')) ?>"><?= t('All your orders') ?> <?= icon('arrow') ?></a></div></aside></div>