<?php
partial('account_nav',['route'=>$route]);$uid=(int)$me['id'];$version=(int)$me['session_version'];
$factor=$a->secondFactor->status($uid);$setup=$a->secondFactor->pending($uid,$version);
$issued=$_SESSION['factor_codes']??null;unset($_SESSION['factor_codes']);
if (!is_array($issued) || $issued['user_id']!==$uid || $issued['version']!==$version || $issued['expires_at']<=time()) {$issued=null;}
?>
<section class="security-hero panel glass section"><div><span class="eyebrow">YOUR ACCOUNT / YOUR CONTROL</span><h1><?= t('Security center') ?></h1><p><?= t('A second key for your island. Private by design, independent of email delivery.') ?></p><span class="pill <?= $factor['enabled']?'success':'soft' ?>"><?= icon($factor['enabled']?'check':'lock') ?><?= t($factor['enabled']?'Two-factor authentication enabled':'Password protection active') ?></span></div><div class="security-emblem" aria-hidden="true"><span></span><span></span><?= icon('shield') ?></div></section>
<?php if($issued): ?><section class="panel recovery-panel section" role="status"><h2><?= t('Save your recovery codes now') ?></h2><p><?= t('Each code works once. This list is shown once only. Keep it offline, separate from your password.') ?></p><div class="recovery-grid"><?php foreach($issued['codes'] as $code): ?><code><?= e($code) ?></code><?php endforeach ?></div></section><?php endif ?>
<div class="two-column security-grid"><section class="panel glass"><div class="section-heading"><div><span class="eyebrow">01 / AUTHENTICATOR</span><h2><?= t('Authenticator app') ?></h2></div><?= icon('shield') ?></div>
<?php if(!$factor['enabled']): ?>
<p class="hint"><?= t('Use an authenticator that supports six-digit TOTP codes. Setup does not send your secret to a third-party QR website.') ?></p>
<?php if($setup): ?><div class="setup-key"><span class="eyebrow"><?= t('Enter this key in your authenticator') ?></span><code><?= e($setup['secret']) ?></code><small><?= t('Time based / SHA1 / 6 digits / 30 seconds') ?></small></div><p class="hint"><?= t('The setup expires in 10 minutes. Complete it with your current password and an authenticator code.') ?></p><?= form_start('factor_activate') ?><?php field('current_password','Current password','','password',['required'=>'required','autocomplete'=>'current-password']);field('factor_code','Authenticator code','','text',['required'=>'required','autocomplete'=>'one-time-code','inputmode'=>'numeric','pattern'=>'[0-9]{6}','maxlength'=>'6']);button('Enable two-factor authentication','full','shield'); ?></form>
<?php elseif($s->enabled('two_factor')): ?><?= form_start('factor_begin') ?><?php field('current_password','Current password','','password',['required'=>'required','autocomplete'=>'current-password']);button('Set up an authenticator','full','plus'); ?></form>
<?php else: ?><div class="alert info"><?= t('New authenticator enrollment is currently disabled. Existing protection remains active.') ?></div><?php endif ?>
<?php else: ?><div class="security-stat"><strong><?= (int)$factor['recovery_remaining'] ?></strong><div><b><?= t('Recovery codes remaining') ?></b><p class="hint"><?= t('Enabled on') ?> <?= dt((int)$factor['enabled_at']) ?></p></div></div><p class="hint"><?= t('A used authenticator code cannot be replayed. Wait for the next code when performing another protected action.') ?></p><details><summary><?= t('Replace recovery codes') ?></summary><?= form_start('factor_rotate') ?><?php partial('factor_proof');button('Generate eight new recovery codes','secondary full','refresh'); ?></form><p class="hint"><?= t('All old recovery codes stop working immediately.') ?></p></details><details><summary><?= t('Disable two-factor authentication') ?></summary><?= form_start('factor_disable') ?><?php partial('factor_proof');button('Disable after verification','ghost full','lock'); ?></form></details><?php endif ?></section>
<section class="panel glass"><span class="eyebrow">02 / SESSIONS</span><h2><?= t('Keep only this session') ?></h2><p><?= t('Sign out other browsers after a lost device or an account change. The current browser stays signed in.') ?></p><?= form_start('session_revoke') ?><?php partial('factor_proof',['factorRequired'=>$factor['enabled']]);button('Sign out other sessions','secondary full','logout'); ?></form><div class="security-note"><strong><?= t('Recovery is not a back door') ?></strong><p class="hint"><?= t('Changing or resetting a password does not disable an enrolled authenticator. Keep your recovery codes before signing out.') ?></p></div><a class="text-link" href="<?= e(url('profile')) ?>"><?= t('Password and email settings') ?><?= icon('arrow') ?></a></section></div>
<section class="panel section"><div class="section-heading"><div><span class="eyebrow">03 / RECENT ACTIVITY</span><h2><?= t('Your account security events') ?></h2></div><span class="hint"><?= t('Latest 20 events') ?></span></div><div class="security-events"><?php foreach($a->db->all("SELECT action,created_at FROM cy_audit WHERE actor_id=? AND action LIKE 'account.%' ORDER BY id DESC LIMIT 20",[$uid]) as $event): ?><div class="security-event"><?= icon('shield') ?><div class="grow"><strong><?= e(tr($event['action'])) ?></strong><time><?= dt((int)$event['created_at']) ?></time></div><span class="event-dot" aria-hidden="true"></span></div><?php endforeach ?></div></section>

<section class="panel glass section"><div class="section-heading"><div><span class="eyebrow">04 / CONNECTED IDENTITIES</span><h2><?= t('Connected accounts') ?></h2></div><?= icon('compass') ?></div><p class="hint"><?= t('Link a provider only from your own account. Unlinking signs out other local sessions. Tokens are not kept after verification.') ?></p>
<div class="identity-grid"><?php foreach($a->oauth->links($uid) as $identity): ?><article class="identity-card"><span class="provider-mark"><?= e(strtoupper(substr($identity['provider'],0,1))) ?></span><h3><?= e($identity['label']) ?></h3><p><?= e(\Chengyu\Services\OAuth::PROVIDERS[$identity['provider']]['name']??$identity['provider']) ?></p><small><?= t('Connected on') ?> <?= dt((int)$identity['created_at']) ?></small><details><summary><?= t('Unlink this account') ?></summary><?= form_start('oauth_unlink').hidden('id',$identity['id']) ?><?php partial('factor_proof',['factorRequired'=>$factor['enabled']]);button('Verify and unlink','secondary full','lock'); ?></form></details></article><?php endforeach ?></div>
<div class="provider-actions"><?php foreach($a->oauth->available() as $provider=>$label): ?><details class="provider-connect"><summary><?= t('Connect') ?> <?= e($label) ?></summary><?= form_start('oauth_begin').hidden('provider',$provider).hidden('purpose','link') ?><?php partial('factor_proof',['factorRequired'=>$factor['enabled']]);button('Verify and continue','secondary full','arrow'); ?></form></details><?php endforeach ?></div></section>
